### ISSUE TITLE
[Bug Report] [Preview] MultiplexingClient hangs if incorrect connection string used to construct device client

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#1009]
Customer reports that providing the incorrect device connection string (has an out of date primary/secondary key) to a device client, and then attempting to register that device client will lead to an infinite loop.

Note that this is a bug in the preview release's ```MultiplexingClient```, not a bug in the normal release's ```TransportClient```

AB#8869925

**Comment by timtay-microsoft** [comment]
Need to add a timeout to these register/unregister calls as, even in normal scenarios, hub may take too long to respond. Make it a configurable option at multiplexing client constructor time, maybe

**Comment by timtay-microsoft** [comment]
Closing this issue as device client 1.29.0-preview-001 has the fix for this issue

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
