### ISSUE TITLE
[Technical Question] Not receiving metadata in 'startDeviceTwin(..., PropertyCallBack genericPropertyCallBack...)

### ISSUE THREAD

**Issue by marc-roedder-gcx** [Azure/azure-iot-sdk-java#1011]
I´m using the Azure IoT SDK for Java DeviceTwin functionality. On calling `startDeviceTwin()`, I receive the reported and desired properties once in the `TwinPropertyCallBack`.

However, inside of the `Property` sent, I can only get the `version` of the 'root node', not for the sub-properties or `TwinCollection`s (they are all `null`). On Azure Portal, I can clearly see that all of them have their own versions in the metadata section of the JSON. Example:

```
...
  "properties": {
    "desired": {
      "Broadcast": {
        "0": {
          "Scene": 2,
          "Brightness": 13
        }
      },
      "$metadata": {
        "$lastUpdated": "2020-12-01T07:53:53.0372127Z",
        "$lastUpdatedVersion": 17,
        "Broadcast": {
          "0": {
            "$lastUpdated": "2020-12-01T07:53:53.0372127Z",
            "$lastUpdatedVersion": 17,
            "Scene": {
              "$lastUpdated": "2020-12-01T07:53:53.0372127Z",
              "$lastUpdatedVersion": 17
            },
            "Brightness": {
              "$lastUpdated": "2020-12-01T07:28:08.5730028Z",
              "$lastUpdatedVersion": 15
            }
          },
          "$lastUpdated": "2020-12-01T07:53:53.0372127Z",
          "$lastUpdatedVersion": 17
        }
      },
      "$version": 17
    },
...
```

How can I receive these versions for the nested `TwinCollection`s? Is it some configuration or is it just not supported currently?

In the above example, I want to prevent re-processing of the Brightness value, as my local state is already at 'Version 15'.

AB#8899171

**Comment by timtay-microsoft** [comment]
The service does not send that metadata to devices by design. It is only available to service clients who request for a device's twin. In general, you will need to rely on the overall version of the document for concurrency protection.

**Comment by az-iot-builder-01** [comment]
@marc-roedder-gcx, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
