### ISSUE TITLE
[Bug Report][Preview] MultiplexingClient devices can't resubscribe to twin after being re-registered

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#1017]
If a device client that is registered to a multiplexing client is subscribed to twin/methods, is then unregistered from its multiplexing client, and then later re-registered to a multiplexing client, that device client can't start device twin again due to an SDK state issue.

AB#8931920

**Comment by timtay-microsoft** [comment]
This will be fixed in the next preview release. The SDK will not preserve subscriptions for you, but it will allow for the device client to re-subscribe to twin and methods as expected

**Comment by timtay-microsoft** [comment]
#1016 for tracking purposes

**Comment by timtay-microsoft** [comment]
Closing this issue as device client 1.29.0-preview-001 has the fix for this issue

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
