### ISSUE TITLE
SSL Context in service Client 

### ISSUE THREAD

**Issue by gianni-di-marco** [Azure/azure-iot-sdk-java#1027]
It will be usefull to change SSL Context in ServiceClient (like the feature in DeviceClient) to connect to iot hub in a private azure stack appliance.

in AmqpConnectionHandler.java it   SSLContext is initialized  with iotHub ca certificates.
As far as I can see there is no way to change it.
 

```java:
private SslDomain makeDomain(SslDomain.Mode mode)
    {
        SslDomain domain = Proton.sslDomain();

        try
        {
            // Need the base trusted certs for IotHub in our ssl context. IotHubSSLContext handles that
            domain.setSslContext(new IotHubSSLContext().getSSLContext());
        }
        catch (Exception e)
        {
            this.savedException = e;
        }

        domain.init(mode);

        return domain;
    }
```
AB#9010062

**Comment by timtay-microsoft** [comment]
I like this idea a lot. I'll try to get this feature added soon.

**Comment by timtay-microsoft** [comment]
Closing this issue because service client version 1.27.0 now has this feature

**Comment by az-iot-builder-01** [comment]
@gianni-di-marco, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by mojitodaiquiri** [comment]
Hi, there,
it does't work for me, I just had a quick look and seems that the sslcontext option does't go deep through to the message sender....
in ServiceClient the variable is initialize like that
       // Codes_SRS_SERVICE_SDK_JAVA_SERVICECLIENT_12_007: [The constructor shall create a new instance of AmqpSend object]
        this.amqpMessageSender = new AmqpSend(hostName, userName, sasToken, this.iotHubServiceClientProtocol, options.getProxyOptions());

with no ssl context.
