### ISSUE TITLE
Device Twin update for cross region is taking time [Technical Question]

### ISSUE THREAD

**Issue by gandhirajan** [Azure/azure-iot-sdk-java#1037]
We have deployed a Spring boot application in the South Central US region that updates device twins connected to IoT Hubs deployed across various regions. We have IoT hubs deployed in South Central US, West US and East Asia region.

The total time taken to update device twin within same region (South central US) is 27 ms which includes the time taken to get the device twin  - 9.17 ms and time taken to update device twin - 17.7 ms. But the total time taken to update device twin across the region (West US or East Asia) is 210 ms which includes the time taken to get the device twin  - 99.99 ms and time taken to update device twin - 110.29 ms. 

The conclusion is that we could see 10 fold increase in the time taken for cross-region update as compared to same region. Is this the expected behavior? Is there any settings available to improve the performance of cross region update? Please find the sample code we used to update the device twin as follows:

`

    public void updateDeviceTwin(EventMessage eventMessage, String iotConnectionString) {
        List < Map < String, Object >> remoteActionCommandList = new ArrayList < > ();
    Set < Pair > desiredProperties = new HashSet < > ();
    DeviceTwinDevice device = new DeviceTwinDevice(eventMessage.getServiceTag());
    try {
        long startTime = System.currentTimeMillis();
        DeviceTwin twinClient = getInitialState(iotConnectionString);
        long endTime = System.currentTimeMillis();
        telemetryClient.trackMetric("IoTHubConnectionTime - ", endTime - startTime);
        long startTime1 = System.currentTimeMillis();
        twinClient.getTwin(device);
        long endTime1 = System.currentTimeMillis();
        telemetryClient.trackMetric("GetDeviceTwinTime - ", endTime1 - startTime1);
        for (CommandList commandList: eventMessage.getCommandList()) {
            Map < String, Object > remoteActionCommandMap = new HashMap < > ();
            remoteActionCommandMap.put(CMD, commandList.getCmd());
            if (!commandList.getPrms().isEmpty()) { //todo change this condition
                remoteActionCommandMap.put(PRMS, commandList.getPrms());
                remoteActionCommandList.add(remoteActionCommandMap);
            }
        }
        desiredProperties.add(new Pair(REMOTE_ACTION, remoteActionCommandList));
        if (!desiredProperties.isEmpty())
            device.setDesiredProperties(desiredProperties);
        long startTime2 = System.currentTimeMillis();
        twinClient.updateTwin(device);
        long endTime2 = System.currentTimeMillis();
        telemetryClient.trackMetric("UpdateDeviceTwinTime - ", endTime2 - startTime2);
        /*twinClient.getTwin(device);
        System.out.println(device.desiredPropertiesToString());*/
    } catch (Exception e) {
        //todo change method level exception
        throw new ServiceException(IOTHUB_FAILED_ERROR_CODE, e.getMessage(), ERROR_UPDATING_DEVICE_TWIN, e);
    }
    }
`
`

    private DeviceTwin getInitialState(String iotConnectionString) {
        try {
            return DeviceTwin.createFromConnectionString(iotConnectionString);
        }catch (Exception e) {
            throw new ServiceException(IOTHUB_FAILED_ERROR_CODE,e.getMessage(),INCORRECT_IOT_HUB_CONNECTION_STRING,e);
        }
    }
`

Any thoughts on improving performance?

AB#9047274

**Comment by timtay-microsoft** [comment]
It is typical that network requests across regions take longer than network requests within a region, yes. I don't see this as a limitation of the SDK or of IoT Hub. 

When optimizing for speed, you should aim to have devices connect to an IoT Hub within the same region when possible. Solutions built using Device Provisioning Service allow you to dynamically allocate your devices to an Iot Hub based on geolatency, which sounds like something you'd be interested in.

**Comment by gandhirajan** [comment]
Hi @timtay-microsoft , Thanks for the response. I do agree with you that cross region operations will have network latency that adds up to the overall operations time. In our use case, the spring boot application deployed in South Central US will update device twins associated with IoT hubs that are spread across various regions. We cannot afford to have one spring boot service per region as per our design. 

All I m trying to understand is that the ten fold increase in the overall operation time for cross region is expected? Is there anything we can improve on device twin update code that can probably bring down the overall operation time for cross region? Could you please confirm that the current operation times are optimum numbers as per azure-iot-java sdk?

**Comment by timtay-microsoft** [comment]
> All I'm trying to understand is that the ten fold increase in the overall operation time for cross region is expected? 

The SDK and service don't maintain expected latency for service requests based on location/distance, so I can't really qualify the 10 fold latency increase as "expected" or "unexpected". That said, if you consistently see roughly the same amount of latency over many requests, then I'd say it is safe to expect those same numbers in the future as well.

>  Is there anything we can improve on device twin update code that can probably bring down the overall operation time for cross region?

There isn't a way to write device twin code that makes it travel faster over the network, no. You can choose to send reported property updates less frequently if it helps to speed up your springboot application, but that won't have any noticeable affect on latency per reported property update.

**Comment by timtay-microsoft** [comment]
While not particular to this SDK or to Iot Hub, and not indicative of a guarantee to meet these standards, you may find these general Azure latency articles/tools useful:

https://docs.microsoft.com/en-us/azure/networking/azure-network-latency
https://docs.microsoft.com/en-us/azure/network-watcher/view-relative-latencies
https://www.azurespeed.com/Azure/Latency

**Comment by timtay-microsoft** [comment]
Do you have any other questions on this topic? Otherwise I'll close this thread

**Comment by gandhirajan** [comment]
Hi @timtay-microsoft , we will test the operation time across various region and get back to you in case we see any discrepancies in the time taken. Closing this thread for now.

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @gandhirajan, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
