### ISSUE TITLE
Message CorrelationId property of DeviceClient differs across SDK's, making Cloud Tenent API not generic.

### ISSUE THREAD

**Issue by AnnapoorniS** [Azure/azure-iot-sdk-java#104]
Hi,
We are having a common Cloud Tenent Api in c# to receive the messages from several device client, which could receive response message from c# device client using the Message's SystemProperties parameter "correlation-id". 

But when we use Azure IoT Device Client for Java, to send the similar response messages to the common cloud Tenent in c# we are facing issues as the message properties differ across SDK.
Especially the **"correlation-id" parameter is not set for the Message through Java SDK** but, is set for the Message object sent through c# SDK to the SystemProperties parameter "correlation-id". 
Which eventually gives back a default guid as response for SystemProperties parameter "correlation-id" while retrieving messages from Java SDK.

When the same response "Message" is framed by us with both the device client, the device SDK inbuilt message framing is different across SDK's and we are facing issues in retrieving back in cloud Tenent. **Why there exist an inconsistent mechanism across all SDK’s to access the correlation-id?**

 **OS and version used:** <VERSION>  Android 7.1 

**Java runtime used:** <VERSION>  JDK "1.8.0_45"

**SDK version used:** <VERSION>  IoT Device Client 1.2.27 for Java

# Description of the issue:
When sending response messages to the cloud using Azure IoT device client SDK for Java, the correlationId which I have set for the Message, I am unable to retrieve it back in the cloud in message.SystemProperties parameter "correlation-id". 
 
# Code sample exhibiting the issue:

Message framed in Java Device Client,
		Message message = new Message(messageInBytes);
		message.setCorrelationId(UUID.randomUUID().toString());
		message.setMessageId(UUID.randomUUID().toString());

Code to retrieve back the response in cloud,
var correlationIdString = GetStringValueOrEmpty(localMessage.SystemProperties, "correlation-id");
 

# Console log of the issue:
SetResponse [00000000-0000-0000-0000-000000000000]>> Got result for command=[Response], version=[1]

**Comment by AnnapoorniS** [comment]
Thanks, Kindly help fixing this at the earliest.

**Comment by jkriba** [comment]
Hi prmathur,
  We are also facing the same issue, basically we were not be able to have a common Cloud Tenent API for all the Microsoft provided Connectors. Kindly provide a fix asap since this is becoming business critical and single point failure for the Microsoft Device SDK for Java. thanks in advance,

Regards
JK

**Comment by prmathur-microsoft** [comment]
We are working on a fix for this issue. We will have update for you soon.

**Comment by prmathur-microsoft** [comment]
Maven packages for this issue has been released. Please try it on your end and let us know if you see any further issues.

**Comment by AnnapoorniS** [comment]
Tried with the latest device client SDK 1.3.30  but still facing the same issue in receiving the data back from cloud for "correlation-id" property. As I was walking through the commits for the fix in SystemProperty I see a difference in naming conventions for the reserved properties variables as "iothub-correlationId", instead of "correlation-id". Will this make any difference?

I want you to reopen this issue and make all the properties generic across the SDK.

The Message object should hold the 'message-id' property and 'correlation-id' property as system property to retrieve it back accordingly. Kindly fix it at the earliest.

Thanks.

**Comment by timtay-microsoft** [comment]
I'm sorry we didn't fix this entirely for you. I'll re-open this.

To help us fix this completely for you, could you tell us some details on your scenario?
- Are you using the java SDK for sending the message, receiving the message, or both?
- What code are you calling to set the correlation ID and message ID on the sender side?
- What code are you calling to retrieve the correlation ID and message ID on the receiver side?

Thanks,
-Tim

**Comment by AnnapoorniS** [comment]
I am using Java SDK for sending the message and C# for receiving the message.

Java Code to set the correlationId and messageId on the sender side:
Message msg = new Message(msgInBytes);
msg.setCorrelationId(UUID.randomUUID().toString());
msg.setMessageId(UUID.randomUUID().toString());

C# code to retrieve the correlationId of message from EventHub on receiverSide: 
var correlationIdString = GetStringValueOrEmpty(EventData.SystemProperties, "correlation-id");

Thanks,
Annapoorni S

**Comment by prmathur-microsoft** [comment]
We identified some more issues related to sending properties and we are working on a fix for that.

**Comment by prmathur-microsoft** [comment]
We have provided fixes for this in the master branch. Please try it out at your end and let us know if it works for you.

**Comment by prmathur-microsoft** [comment]
Maven package for the same is also released. Follow our release from https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-7-14. Please feel free to reopen if this issue still not resolved post our new fix.

**Comment by AnnapoorniS** [comment]
Trying sample with java deviceclient 1.3.31 SDK for **HTTPS** protocol, I couldn't send any data by sendEventAsync() method of device client.

I/System.out: {"deviceId":"Sample","messageId":0,"temperature":20.83712863792431,"humidity"47.23667818960061}
W/art: Unresolved exception class when finding catch block: javax.naming.SizeLimitExceededException
W/art: Unresolved exception class when finding catch block: javax.naming.SizeLimitExceededException

![image](https://user-images.githubusercontent.com/22465018/28248556-086e0c16-6a64-11e7-968a-eacf1a2d3186.png)


While debugging I found the the exception occurring here. 

![image](https://user-images.githubusercontent.com/22465018/28248791-17f2ae86-6a68-11e7-8ecd-df177d6fccbc.png)


![image](https://user-images.githubusercontent.com/22465018/28248699-6c641dc6-6a66-11e7-8150-604611215996.png)



Couldn't send even a single message.

**Comment by prmathur-microsoft** [comment]
Did you change anything in the sample ? At my end I'm unable to repro this behavior running default sample over HTTPS with message ID and correlation ID. I'm successfully able to send messages.
If you changed anything from sample then can you provide details ?

**Comment by AnnapoorniS** [comment]
No, I didn't change anything in the sample, I just downloaded the latest device android-sample with 1.3.31 SDK, updated the connectionString and changed the protocol to **HTTPS**. While running the code I am facing this issue. I tried in few other machines also. Kindly check and let me know.

**Comment by prmathur-microsoft** [comment]
Oh so you are running this on Android. Recently we pushed in a change where we are encoding HTTP message with Base 64 and Base 64 java API's doesn't work on Android. This is the reason why we don't have AMQP_WS and (now) HTTPS working on Android. We have this in our backlog to fix the issue. Until then can you try using any other protocol ? perhaps MQTT ? or AMQP ? They are functional on Android.

**Comment by AnnapoorniS** [comment]
By the way our requirement is with android HTTPS protocol, can you fix this issue with high priority as I just tried java sample with pom file to download the dependency I could get it working, **kindly fix the dependency issue in 1.3.31 SDK for android HTTPS.**  Can you prioritize this? Should I create a new ticket as the fix will be helpful for us only if it works with HTTPS on Android? @prmathur-microsoft 

Thanks for the fix @timtay-microsoft it works great.

Regards,
Annapoorni S

**Comment by jkriba** [comment]
Hi Radha,
  Sorry to say that, this really breaks all the current working products. Which is really not good..
Practically all the client applications which is running our connector in production using HTTPS will stop working if they try to use the latest SDK...Kindly consider this as a major blocker here..thanks

Regards
JK

**Comment by prmathur-microsoft** [comment]
Hi @AnnapoorniS and @jkriba feel free to open another issue for HTTPS on Android and we will prioritize it at our end.

**Comment by AnnapoorniS** [comment]
Created a ticket for the HTTPS support required in android.
[https://github.com/Azure/azure-iot-sdk-java/issues/120](url) 
Kindly fix at the earliest.

Thanks, 
Annapoorni S

**Comment by aloysiustany** [comment]
I found a similar issue when using Microsoft.Azure.EventHubs. Raised a defect in https://github.com/Azure/azure-event-hubs-dotnet/issues/242
