### ISSUE TITLE
azure-iot-sdk-java maven install FAILURE

### ISSUE THREAD

**Issue by Pllvcn83** [Azure/azure-iot-sdk-java#105]
I would like build the azure-iot-sdk-java
I used the following commands:_
```
git clone https://github.com/Azure/azure-iot-sdk-java.git

cd azure-iot-sdk-java/device

mvn install

```

OS and version used: Windows 10
Java runtime used:java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) Client VM (build 25.131-b11, mixed mode)

SDK version used: the last

# Description of the issue:
the maven build is finished with a failure.

here the logs:
[INFO] IoT Hub Java Device Client ......................... FAILURE [  3.758 s]
[INFO] IoT Hub Java Device SDK Samples .................... SKIPPED
[INFO] Send Event Sample .................................. SKIPPED
[INFO] Send Serialized Event Sample ....................... SKIPPED
[INFO] Handle Messages Sample ............................. SKIPPED
[INFO] Sender and Receiver Sample ......................... SKIPPED
[INFO] Device Twin Sample ................................. SKIPPED
[INFO] Device Method Sample ............................... SKIPPED
[INFO] File Upload Sample ................................. SKIPPED
[INFO] IoT Hub Java Device SDK tests ...................... SKIPPED
[INFO] IoT Hub Java Device Client Parent .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.255 s
[INFO] Finished at: 2017-06-16T09:28:00+02:00
[INFO] Final Memory: 16M/174M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project iot-device-client: Compilation failure: Compilation failure:
[ERROR] /C:/Users/vincenzo.pellegrini/iot/azure-iot-sdk-java/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java:[6,51] com.microsoft.azure.sdk.iot.deps.serializer.ParserUtility is not public in com.microsoft.azure.sdk.iot.deps.serializer; cannot be accessed from outside package
[ERROR] /C:/Users/vincenzo.pellegrini/iot/azure-iot-sdk-java/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java:[504,9] cannot find symbol
[ERROR]   symbol:   variable ParserUtility
[ERROR]   location: class com.microsoft.azure.sdk.iot.device.DeviceClient
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by prmathur-microsoft** [comment]
Can you please clean your repo, rebase to master and try again ? At some point in time parser utility was not public and my suspicion is you may be using older package from repo. Please compile from root - mvn clean install.

fyi - https://github.com/Azure/azure-iot-sdk-java/blob/master/deps/serializer/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/ParserUtility.java is now public.

**Comment by prmathur-microsoft** [comment]
Can you please update us if the above comment resolves your issue ?

**Comment by prmathur-microsoft** [comment]
Closing this for now. Feel free to reopen it if you see further issues.
