### ISSUE TITLE
Didn't find class "javax.net.ssl.SNIHostName" in SDK version iot-device-client-1.27.0

### ISSUE THREAD

**Issue by nazmul32** [Azure/azure-iot-sdk-java#1067]
# Context
- Android 6 or below

## Description of the issue
I am facing this crash issue below Android 7 devices. This is already discussed in this thread.

https://github.com/eclipse/paho.mqtt.java/issues/633

Also, here there is a related issue.

https://github.com/Azure/azure-iot-sdk-java/issues/596

Which version of **Paho MQTT** library is used in **iot-device-client-1.27.0**? I am assuming if this is **1.2.2** or not. Which is the Azure IoT device client SDK that gives support for older devices also. I do not want to downgrade library if not mandatory because I have support for **Device Provisioning Service** in Device Client SDK. I am seeking for some help as we have lots of older devices for the service needs to be run on.

## Code sample exhibiting the issue
    implementation ('com.microsoft.azure.sdk.iot:iot-device-client:1.27.0') {
        exclude module: 'azure-storage'
    }
    implementation ('com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.8.4')

## Console log of the issue
01-18 20:35:58.677 32111-32214/com.test.app E/AndroidRuntime: FATAL EXCEPTION: MQTT Con: 8f86b15a-ce8a-26b1-9748-f4dfd8754f72
    Process: com.test.app, PID: 32111
    java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/net/ssl/SNIHostName;
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:139)
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:722)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.net.ssl.SNIHostName" on path: DexPathList[[zip file "/data/app/com.test.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.test.app-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at org.eclipse.paho.client.mqttv3.internal.SSLNetworkModule.start(SSLNetworkModule.java:139) 
        at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:722) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: javax.net.ssl.SNIHostName
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)

AB#9149712

**Comment by timtay-microsoft** [comment]
We don't really support Java 7 anymore, since most of our dependencies have dropped support for it. I have a more detailed write up [here](https://github.com/Azure/azure-iot-sdk-java/issues/747) including a theoretical workaround that allows you to continue using MQTT on the latest versions of this SDK

**Comment by timtay-microsoft** [comment]
Given that there are several open issues about Java 7 compatibility, I'm inclined to close this as a duplicate, but is there anything else around this issue that I can help you understand first, @nazmul32 ?

**Comment by nazmul32** [comment]
Thanks @timtay-microsoft for response. Seems the replacement of 
    
 ```
  implementation ('com.microsoft.azure.sdk.iot:iot-device-client:1.27.0') {
        exclude module: 'azure-storage'
    }
```

with 

```
api ('com.microsoft.azure.sdk.iot:iot-device-client:1.27.0') {
        exclude module: 'slf4j-api'
        exclude module:'azure-storage'
        exclude module: 'bcmail-jdk15on' //fixes 1.17.1 -> 1.17.2 jump
        exclude module: 'bcprov-jdk15on' //fixes 1.17.1 -> 1.17.2 jump
        exclude module: 'proton-j' //fixes 1.17.1 -> 1.17.2 jump, but removes support for AMQPS and AMQPS_WS
        exclude module: 'jnr-unixsocket' // fixes 1.17.4 -> 1.17.5 jump (issue #434 caused us to upgrade unixsocket dependency, but that was for supporting raspberry pis. Android should be unaffected)
        exclude module: 'qpid-proton-j-extensions'
        exclude module: 'org.eclipse.paho.client.mqttv3'
    }
```

this is correct solution. But there is another problem. I have another dependencies that is still causing same crash which is below one.

`implementation ('com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.8.4')`

**Do we need some exclude/modification like previous one for this dependency also? 

**Also another point is here **api** is used to exclude dependencies, if **implementation** is used instead like

```
implementation('com.microsoft.azure.sdk.iot:iot-device-client:1.27.0') {
        exclude module: 'slf4j-api'
        exclude module:'azure-storage'
        exclude module: 'bcmail-jdk15on' //fixes 1.17.1 -> 1.17.2 jump
        exclude module: 'bcprov-jdk15on' //fixes 1.17.1 -> 1.17.2 jump
        exclude module: 'proton-j' //fixes 1.17.1 -> 1.17.2 jump, but removes support for AMQPS and AMQPS_WS
        exclude module: 'jnr-unixsocket' // fixes 1.17.4 -> 1.17.5 jump (issue #434 caused us to upgrade unixsocket dependency, but that was for supporting raspberry pis. Android should be unaffected)
        exclude module: 'qpid-proton-j-extensions'
        exclude module: 'org.eclipse.paho.client.mqttv3'
    }
```

Will this create any issue? I am aware of the difference between **api** and implementation in **gradle**. But for being extra cautious asking this.

**Comment by timtay-microsoft** [comment]
The provisioning device client also uses the same versions of Paho, proton-j, and bouncycastle, so you'll need the same exclusions. This will remove AMQP support from the provisioning device client, but should still allow for MQTT and HTTP support

```
implementation ('com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.8.4') 
{
        exclude module: 'slf4j-api'
        exclude module: 'bcmail-jdk15on' //fixes 1.17.1 -> 1.17.2 jump
        exclude module: 'bcprov-jdk15on' //fixes 1.17.1 -> 1.17.2 jump
        exclude module: 'proton-j' //fixes 1.17.1 -> 1.17.2 jump, but removes support for AMQPS and AMQPS_WS
        exclude module: 'qpid-proton-j-extensions'
        exclude module: 'org.eclipse.paho.client.mqttv3'
}
```

> Will this create any issue? I am aware of the difference between api and implementation in gradle. But for being extra cautious asking this.

No, you should be fine here

**Comment by nazmul32** [comment]
Thanks. I tried it before and it worked. I wanted to be sure which modules need to be excluded. As this worked, I am closing this ticket.

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @nazmul32, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
