### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by Beppux86** [Azure/azure-iot-sdk-java#107]
- **OS and version used:** Windows 7 

- **Java runtime used:** <VERSION> JSE 1.8

- **SDK version used:** <VERSION> iot-device-client-1.3.29-with-deps.jar

# Description of the issue:
I'm using the DeviceClient to send an uploadToBlobAsync request. Every time i call that api, the response is 11 error, and the following log.

I've looked at the code, and I can't understand how can I do like suggested, because in the class FileUploadResponseParser is not exposed the GsonBuilder.

How can I resolve my problem?

# Code sample exhibiting the issue:
                client.uploadToBlobAsync(file.getName(), new FileInputStream(file), file.length(), callback,
                        callbackContext);

# Console log of the issue:
File upload failed to upload the stream to the blob. java.lang.IllegalArgumentException: Malformed json:java.lang.RuntimeException: Unable to invoke no-args constructor for class com.microsoft.azure.sdk.iot.deps.serializer.FileUploadResponseParser. Register an InstanceCreator with Gson for this type may fix this problem.

**Comment by prmathur-microsoft** [comment]
Can you please provide details about values of file.getName() and file.length() ?
Also are you able to run our sample with your values of parameters for fileupload ?

**Comment by mamokarz** [comment]
Hi @Beppux86,
Can you provide the Gson version that you are using too?
Thanks,

**Comment by prmathur-microsoft** [comment]
Also we suspect this fix might resolve your issue. Please give it a try and let us know if you still see issues.

@916138a854e05283280a0fcdd31311534e1c7ab2.

**Comment by prmathur-microsoft** [comment]
Maven package with the fix has been released. Please give it a try and feel free to reopen if you see any further issues.
