### ISSUE TITLE
#1027 does not work

### ISSUE THREAD

**Issue by mojitodaiquiri** [Azure/azure-iot-sdk-java#1089]
Hi, there,
it does't work for me, I just had a quick look and seems that the sslcontext option does't go deep through to the message sender....
in ServiceClient the variable is initialize like that
       // Codes_SRS_SERVICE_SDK_JAVA_SERVICECLIENT_12_007: [The constructor shall create a new instance of AmqpSend object]
        this.amqpMessageSender = new AmqpSend(hostName, userName, sasToken, this.iotHubServiceClientProtocol, options.getProxyOptions());

with no ssl context.

_Originally posted by @mojitodaiquiri in https://github.com/Azure/azure-iot-sdk-java/issues/1027#issuecomment-766747721_

AB#9195461

**Comment by timtay-microsoft** [comment]
Looks like you are right, I'll get a fix in for this soon

**Comment by timtay-microsoft** [comment]
The fix for this issue has been checked in, so we'll try to do a release with it soon

**Comment by timtay-microsoft** [comment]
Closing this issue as Service client version 1.27.1 has the fix for it.
