### ISSUE TITLE
[Azure IoT Service Client] Method for RegistryManager AddDevice With Twin Update 

### ISSUE THREAD

**Issue by sunilpatra1990** [Azure/azure-iot-sdk-java#1095]
Hi Team , 

We are using RegistryManager java sdk to addDevice operation to create Device. 

Do we have api method in RegistryManager to create Device and update DeviceTwin at the same time ? 

language : java 
iot service client: iot-service-client-1.27.0

I checked .NET sdk its there RegistryManager.AddDeviceWithTwinAsync , But do we have same operation available in **java iot-service-client sdk.** 

AB#9214703

**Comment by timtay-microsoft** [comment]
Currently the Java SDK does not have this API, no. Is there a reason why creating the device and then updating the twin isn't working for you?

**Comment by timtay-microsoft** [comment]
@sunilpatra1990 do you need any more help here? Or can I go ahead and close this issue?

**Comment by sunilpatra1990** [comment]
Thank you Tim for your response. Apologies for not replying earlier. 

We can close the issue now. Thanks.

**Comment by timtay-microsoft** [comment]
Closing as per the above
