### ISSUE TITLE
environmental-sensor-sample does not compile, misses Classes AbstractDigitalTwinComponent 

### ISSUE THREAD

**Issue by in-fke** [Azure/azure-iot-sdk-java#1099]
See https://github.com/Azure-Samples/azure-iot-samples-java/tree/master/digital-twin/Samples/device/JdkSample
At least this class does not compile:
https://github.com/Azure-Samples/azure-iot-samples-java/blob/master/digital-twin/Samples/device/JdkSample/environmental-sensor-sample/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/sample/EnvironmentalSensor.java

```
[ERROR] /D:/work/azure-iot-samples-for-java/digital-twin/Samples/device/JdkSample/environmental-sensor-sample/src/main/java/com/microsoft/azure/sdk/iot/digitaltwin/sample/EnvironmentalSensor.java:[6,54] cannot find symbol
  symbol:   class AbstractDigitalTwinComponent
  location: package com.microsoft.azure.sdk.iot.digitaltwin.device
```

Could you provide a working sample?

AB#9245937

**Comment by timtay-microsoft** [comment]
The digital twin samples in that repo are tied to a now defunct implementation of the digital twins service, and we don't support it anymore. Here's a [digital twin sample](https://github.com/Azure/azure-iot-sdk-java/tree/master/device/iot-device-samples/pnp-device-sample) that we do support though.

I plan on removing the defunct digital twin sample from the repo that you linked since we no longer support them.

**Comment by in-fke** [comment]
Are those samples you linked for implementing devices or for IoT Hub Service consumers?
I was looking for the second, along the lines:
https://docs.microsoft.com/de-de/azure/iot-pnp/concepts-developer-guide-service?pivots=programming-language-java#iot-hub-digital-twin-examples

**Comment by timtay-microsoft** [comment]
My apologies, I did link device side samples above. [Here](https://github.com/Azure/azure-iot-sdk-java/tree/master/service/iot-service-samples/digitaltwin-service-samples) are the service side samples that I recommend following

**Comment by timtay-microsoft** [comment]
@in-fke do you need any more help here? Or can I go ahead and close this issue?

**Comment by in-fke** [comment]
Well I was helped, that's OK, but is the ticket solved? It's time consuming if examples are provided that are not up-to-date.

**Comment by timtay-microsoft** [comment]
The old samples that you originally found have been removed, and they have been replaced with links to the latest samples that I shared with you above. Is there somewhere else that you still see out of date samples?

**Comment by in-fke** [comment]
That's fine.
