### ISSUE TITLE
Property removal in Device Twine does not work properly

### ISSUE THREAD

**Issue by gbidsilva** [Azure/azure-iot-sdk-java#110]
HI Team,

Java SDK Device Client : 1.3.29
From Cent OS 6.7

I am using Device Twin explorer available in the Microsoft Azure Portal to view the device twine which I updated/ pushed using Java Device SDK. 

When I tried to remove a property available in 'Reported' section by setting the property value to 'null' it is not removing that property as explained under 'Device Operations' in : https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins 

I have the reported structure as follows,

```
"reported": {
      "alerts": "sample-alerts",      
      "id": "abc",
      "latest": "latest value"
}
```

And I want to remove the "latest" property. Then I mark it as null and saved it as follows - but it did not work. Instead, it gave me following error.

```
"reported": {
      "alerts": "sample-alerts",      
      "id": "abc",
      "latest": null
}
```

Failed to update device twin for '35dd3-d21a-4a02-ba0f-d3a8a0567c': 'Unable to update device twin.'

I also tried the samething with Java device SDK and I did not get any exception and I received 'OK' status as a response but it did not remove that property.

```
homeKit.setReportedProp(new Property("latest", null));
client.sendReportedProperties(homeKit.getReportedProp());
```

Am I doing anything wrong here ?

**Comment by tameraw** [comment]
@gbidsilva - Thanks for filing. We're investigating the issue.

**Comment by mamokarz** [comment]
I'm working to fix it.

**Comment by prmathur-microsoft** [comment]
Fix has been checked in master branch. Maven package for the same is also released. Follow our release from https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-7-14

**Comment by axeowl** [comment]
The bug persists just on "reported" properties.
 "reported": {
       "TelemetryConfig": {
             "value": -1092085696
         },
}
I should be able to delete "TelemetryConfig" prop setting it "TelemetryConfig": null, but when I save the previous situation is restored.

Thanks for your attention
