### ISSUE TITLE
Why the rule not triggered in the IOT central?

### ISSUE THREAD

**Issue by wuwei3** [Azure/azure-iot-sdk-java#1107]
I set the rule trigger in IOT rule central

device template

![template](https://user-images.githubusercontent.com/46955295/107000016-31197380-67c2-11eb-8051-3561b7cfc49a.png)

Rule 

![rule](https://user-images.githubusercontent.com/46955295/107000042-3b3b7200-67c2-11eb-8a55-2446e84c7bff.png)

action:

![action](https://user-images.githubusercontent.com/46955295/107000069-4098bc80-67c2-11eb-9faa-3b3168ba9809.png)

the telemetry data

![data](https://user-images.githubusercontent.com/46955295/107000117-56a67d00-67c2-11eb-935f-7224b800fef5.png)

the data I sent from device is 110, greater than 100, but I didn't received any email.

Did I do the correct configuration?

I am sure the email address is correct.

AB#9282243

**Comment by wuwei3** [comment]
I also tried "component", "interface" with different type like "String", "Double","Integer", "Boolean", none of them was working.

**Comment by wuwei3** [comment]
another question is how to config with Azure Logic Apps workflow?

I tried, the "When rule is fired" it cannot auto-run, I have to click "Run Trigger" every time, it can trigger the rule, how to make it auto-run? and send the telemetry data to one topic?

**Comment by timtay-microsoft** [comment]
This looks like a question about IoT Central, not IoT Hub. This Github issues page is for questions/bugs on the IoT Hub java SDK, not for IoT Central. I'll see if I can find someone to answer this for you though.

**Comment by wuwei3** [comment]
Many thanks

**Comment by timtay-microsoft** [comment]
@yang-hai-feng any thoughts on this issue?

**Comment by yang-hai-feng** [comment]
@wuwei3 , currently IoT Central only allow send email to users added in your IoT Central Application, does your QQ email configured in email notification template is one user of your IoT Central Application?

**Comment by yang-hai-feng** [comment]
for the flow connector, which flow connector version did you used? @peolivei2, would you please have a look? customer's application id is: 110b00bb-4997-4ca5-b584-f527ff17839b.

**Comment by peolivei2** [comment]
@wuwei3 for the Logic Apps, it should run automatically when your IoT Central rule triggers. Make sure you select the "Azure IoT Central V3" connector in Logic Apps, then the "When a rule is fired" trigger. It will ask you to select the application and rule to use. The rule must be enabled in IoT Central.

If the Logic Apps action still doesn't run automatically, please open a support ticket in IoT Central so we can investigate for your specific application.

**Comment by wuwei3** [comment]
> @wuwei3 , currently IoT Central only allow send email to users added in your IoT Central Application, does your QQ email configured in email notification template is one user of your IoT Central Application?

Correct, if I change to the email I register as azure account, it works.

**Comment by wuwei3** [comment]
> @wuwei3 for the Logic Apps, it should run automatically when your IoT Central rule triggers. Make sure you select the "Azure IoT Central V3" connector in Logic Apps, then the "When a rule is fired" trigger. It will ask you to select the application and rule to use. The rule must be enabled in IoT Central.
> 
> If the Logic Apps action still doesn't run automatically, please open a support ticket in IoT Central so we can investigate for your specific application.

The email works for now, but If I want to trigger the rule, make the data goes to the topic, how should I do?

**Comment by wuwei3** [comment]
@peolivei2 

For rule trigger to topic, What I did are:

1. I selected "Azure IoT Central V3", and the "When a rule is fired"

![1](https://user-images.githubusercontent.com/46955295/107455275-84584100-6b89-11eb-8b56-2eac08f7359f.png)

I am confused at this, the "When a rule is fired" should connect to the rule trigger I want to select of IOT central, but it doesn't have any link, like if I click the select box, it could find out all central, and I select one central, it find out all rules under the central, but It needs to input by myself, I tried the input the "application Id" of central, but not works.

2. I select the "Service bus" and "send message" action, I want to send the data which trigger the rule, but how to config in "Send message"?

![2](https://user-images.githubusercontent.com/46955295/107455732-41e33400-6b8a-11eb-8f64-834720c91198.png)

**Comment by yang-hai-feng** [comment]
@wuwei3 would you please try click "Change Connection" on "When a rule is fired" step, use your IoT Central User Account to login?
![image](https://user-images.githubusercontent.com/14871527/107456365-eb7fe200-6b04-11eb-82ec-5b4133b53925.png)

**Comment by wuwei3** [comment]
@yang-hai-feng 

![6](https://user-images.githubusercontent.com/46955295/107457267-b4edaa00-6b8c-11eb-8d02-02eb45af557e.png)

This is the problem I always encounter, the "orange_npit@163.com" is the register and login account I am using, how to do for make it correct?

I create the central with this account, and it is the "Administrator" role

![5](https://user-images.githubusercontent.com/46955295/107457544-347b7900-6b8d-11eb-90e4-b8ccda0de8b8.png)

but I don't know why it always saying not correct.

**Comment by yang-hai-feng** [comment]
Looks like you need to add your account to your Azure Active Directory as well:

![image](https://user-images.githubusercontent.com/14871527/107458666-63e8a200-6b09-11eb-9c0e-04da8dc37d45.png)

Click the new guest user and see if you can add your email account to your directory.

**Comment by wuwei3** [comment]
@yang-hai-feng 

not work

![3](https://user-images.githubusercontent.com/46955295/107459504-4ced9280-6b91-11eb-94f0-01050a30ce16.png)


I tried "Create user" and "invite user", but both not working

**Comment by yang-hai-feng** [comment]
The first user list in your screenshot is the one that you used in Central Application, seems there is no error, not sure why when you login it shows you don't belong to this tenant, maybe try on InPrivate window on browser to login again and see if it works.

**Comment by yang-hai-feng** [comment]
@wuwei3, would you please try to create a new user(not the guest user) on you directory, and add this user to your IoT Central application first, then you can go to your logic app designer choose "Change Connection" and sign in with new created user? one of my engineer told me that currently we don't support on guest user.

**Comment by timtay-microsoft** [comment]
@wuwei3 do you still need any help on this issue?

**Comment by wuwei3** [comment]
> @wuwei3 do you still need any help on this issue?

Sorry for the late replying, I am still on vocation now, I will try @yang-hai-feng said to me after 22nd Feb.

**Comment by wuwei3** [comment]
@timtay-microsoft you could close this issue, I have commit another issue for SDK

**Comment by timtay-microsoft** [comment]
Closing this issue as per the above
