### ISSUE TITLE
[Bug Report] RegistryManager.getDevice throws IotHubNotFoundException, not IotHubDeviceNotFoundException

### ISSUE THREAD

**Issue by niklas-wulf-gcx** [Azure/azure-iot-sdk-java#1108]
# Context

- **OS and version used:** macOS 11.2
- **Java runtime used:** 11
- **SDK version used:** Service Client 1.27.1

## Description of the issue

`RegistryManager.getDevice(String deviceId)` throws `IotHubNotFoundException` instead of `IotHubDeviceNotFoundException` if a device does not exist in the registry of an *existing* IoTHub.

I think this is because `IotHubExceptionManager.httpResponseVerification(response)` does not differentiate between different possible 404 responses. 

## Code sample exhibiting the issue

```kotlin
private fun deviceExists(id: String): Boolean {
        return try {
            registryManager.getDevice(id)
            true
        } catch (ex: IotHubNotFoundException) {  // <- I would expect to add IoTHubDeviceNotFoundException here
             false
        } catch (ex: Exception) {
            false
        }
    }
```

## Console log of the issue

```
com.microsoft.azure.sdk.iot.service.exceptions.IotHubNotFoundException: ErrorCode:DeviceNotFound;<DEVICE_ID> Tracking ID:1bc30319a4294a7d89ba1511f14f0b5b-G:20-TimeStamp:02/05/2021 10:03:38
	at com.microsoft.azure.sdk.iot.service.exceptions.IotHubExceptionManager.httpResponseVerification(IotHubExceptionManager.java:82) ~[iot-service-client-1.27.1.jar:na]
	at com.microsoft.azure.sdk.iot.service.RegistryManager.getDevice(RegistryManager.java:237) ~[iot-service-client-1.27.1.jar:na]
...
```

AB#9282910

**Comment by timtay-microsoft** [comment]
The IotHubDeviceNotFoundException is never thrown by the SDK, and we'd consider it a breaking change to start throwing it at this point, even though it is an apt description of that error case. Instead, we recommend checking the errorCode and errorCodeDescription of the thrown IotHubException in order to get the granularity between 404xxx status codes.

Is there a reason why you'd like to see the IotHubDeviceNotFoundException thrown, or why parsing the substatus codes isn't sufficient?

**Comment by niklas-wulf-gcx** [comment]
It was just our expectation. The behaviour is confusing, you have to admit. I just wanted to let you know.
IntelliJ suggested the `IotHubDeviceNotFoundException` and it looked the most fitting.

That being said: I do not have strong feelings about it ;)

IMO you may decide to say "this is expected and OK behaviour" and close this ticket.

**Comment by timtay-microsoft** [comment]
Yeah, I do find it confusing that we have this IotHubDeviceNotFoundException, and that it isn't thrown in this case. Ideally we wouldn't have created that type in the first place, but it could be a breaking change to delete it at this point, so I'll go ahead and close this issue as "won't fix"
