### ISSUE TITLE
[Technical Question] Why MultiplexingClient has a fixed capacity?

### ISSUE THREAD

**Issue by mikegpl** [Azure/azure-iot-sdk-java#1110]
Hi,

I've recently started implementing multiplexing connections to IoT Hub using MultiplexingClient, however I've noticed that it's capacity is limited to 1000/500 (AMQPS/AMQPS_WS) DeviceClients. Was this decision backed by experiments/benchmarks, if so, are there any plans to publish the results? Is this limit going to become configurable in the future?

Best regards,
Michał

AB#9283722

**Comment by timtay-microsoft** [comment]
The limits that the SDK imposes are based on the limits that the service itself imposes. The service team doesn't have any plans to change these limits at the moment, no.

**Comment by mikegpl** [comment]
Thank you for quick response, since it's a definite answer I'm closing the issue.
