### ISSUE TITLE
Unable to run send-receive-sample

### ISSUE THREAD

**Issue by Miaoxiaoqi** [Azure/azure-iot-sdk-java#112]
Mac OS Sierra 10.12.5 
java version 1.8.0_131

Hi Team,

I meet issue while running  <azure-iot-sdk-java/device/iot-device-samples/send-receive-sample>
I download the log4j zip package, unzip it, set up the $PATH and $CLASSPATH, but the issue still exists. 

# Console log of the issue:

X-MacBook-Pro:Demo x$ cd /***/azure-iot-sdk-java/device/iot-device-samples/send-receive-sample/target/
X-MacBook-Pro:target x$ java -jar ./send-receive-sample-1.3.30-with-deps.jar "HostName=***;DeviceId=***;SharedAccessKey=***" 5 "amqps"
Starting...
Beginning setup.
Successfully read input parameters.
Using communication protocol AMQPS.
Successfully created an IoT Hub client.
Successfully set message callback.
Opened connection to IoT Hub.
Beginning to receive messages...
Sending the following event messages: 
Updated token expiry time to 2400
{"deviceId":"MyJavaDevice","messageId":0,"temperature":27.86869982590742,"humidity":49.132529556961934}
{"deviceId":"MyJavaDevice","messageId":1,"temperature":29.348651823007174,"humidity":37.399819445107234}
{"deviceId":"MyJavaDevice","messageId":2,"temperature":27.260810137647834,"humidity":35.935160066020345}
{"deviceId":"MyJavaDevice","messageId":3,"temperature":23.070198452218715,"humidity":48.308974224182904}
{"deviceId":"MyJavaDevice","messageId":4,"temperature":25.154152136064205,"humidity":38.173676158541156}
Wait for 2 second(s) for response from the IoT Hub...
Lost connection to the server. Reconnection attempt 1...
In receive mode. Waiting for receiving C2D messages. Press ENTER to close
log4j:WARN No appenders could be found for logger (com.microsoft.azure.sdk.iot.device.Message).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
IoT Hub responded to message 51c2a3b2-c99a-49e4-8e8c-13d88f4c3e7c with status MESSAGE_EXPIRED
IoT Hub responded to message 6d617197-2187-455d-8096-34cd708e18a3 with status MESSAGE_EXPIRED
IoT Hub responded to message 0d6779c3-e6a9-49bb-a649-79d12e63b926 with status MESSAGE_EXPIRED
IoT Hub responded to message ae37d3d9-6e18-44ac-bab7-5ccdef0b64e4 with status MESSAGE_EXPIRED
IoT Hub responded to message c360d14d-d52e-492f-bd54-004c38e8cd46 with status MESSAGE_EXPIRED
Lost connection to the server. Reconnection attempt 2...
Lost connection to the server. Reconnection attempt 3...

Closing

Please let me know if any other information was needed.

thanks!
Best Regards

**Comment by prmathur-microsoft** [comment]
Please update this resource appropriately for seeing logs.

https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/send-receive-sample/src/main/resources/log4j.properties

Specifically change the root logger to the appropriate by removing the comment from either example 1 or 2.

# Initialize the root logger with level WARN as a default 
log4j.rootLogger = WARN

# If you want to be more verbose and direct output to the log file or console, follow the below examples
# Example 1: log4j.rootLogger = DEBUG, FILE 
# Example 2: log4j.rootLogger = ALL, CONSOLE

**Comment by prmathur-microsoft** [comment]
Please let us know if the above resolved your issue and if you have any other question on this.

**Comment by prmathur-microsoft** [comment]
I'm closing this for now as the issue looks resolved by my comment above. Feel free to reopen this issue if you have any other concerns.
