### ISSUE TITLE
It seems that the device SDK connection not stable under mutiple thread

### ISSUE THREAD

**Issue by wuwei3** [Azure/azure-iot-sdk-java#1123]
# Context

- **OS and version used:**  Windows 10, and Ubuntu 18.04
- **Java runtime used:** 1.8
- **SDK version used:** iot-device-client-1.29.0.jar

## Description of the issue

  I have 10 simulation device, I want to report data (send temperature, humidity, CO2 data to the devices) every 7 mins, I used the Java thread pool to finish it, but it always throwing connection failed exception after 10 or 15 times later, it was ok maybe before 10 times

## Code sample exhibiting the issue

![7](https://user-images.githubusercontent.com/46955295/108308800-5909cd80-71eb-11eb-8efa-200724a5be82.png)

## Console log of the issue
Caused by: com.microsoft.azure.sdk.iot.provisioning.device.internal.exceptions.ProvisioningDeviceConnectionException: Exception opening connection
at com.microsoft.azure.sdk.iot.provisioning.device.internal.contract.mqtt.ContractAPIMqtt.open(ContractAPIMqtt.java:175)
at com.microsoft.azure.sdk.iot.provisioning.device.internal.contract.mqtt.ContractAPIMqtt.authenticateWithProvisioningService(ContractAPIMqtt.java:228)
at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.authenticateWithSasToken(RegisterTask.java:202)
at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.authenticateWithDPS(RegisterTask.java:319)
at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.call(RegisterTask.java:341)
at com.microsoft.azure.sdk.iot.provisioning.device.internal.task.RegisterTask.call(RegisterTask.java:37)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
... 4 more
Caused by: java.io.IOException: Unable to subscribe on topic : $dps/registrations/res/#
at com.microsoft.azure.sdk.iot.deps.transport.mqtt.MqttConnection.subscribe(MqttConnection.java:236)
at com.microsoft.azure.sdk.iot.provisioning.device.internal.contract.mqtt.ContractAPIMqtt.open(ContractAPIMqtt.java:170)
... 11 more
Caused by: Timed out waiting for a response from the server (32000)
at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:112)
at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
at com.microsoft.azure.sdk.iot.deps.transport.mqtt.MqttConnection.subscribe(MqttConnection.java:232)
... 12 more

I think my network was ok, I tested, if I just only used one device, not this error, but if it was the thread with multiple devices, I met this error frequently.

I remember I tested IOT HUB with 10,000 simulation devices, and I also used the thread pool to connection the hub, I also always met this error frequently.

AB#9354480

**Comment by timtay-microsoft** [comment]
I'm a little confused by this error description. The code snippets and descriptions you provided are for the IoT Hub device client, but the exception stacktrace is for the Device Provisioning Service device client. Can you clarify which device client is in question here?

Also, when you mention that you are using multiple threads, can you clarify if you are using multiple threads per provisioning device client, per IoT Hub device client, or just multiple threads and each thread has a provisioning and/or IoT Hub device client on it?

**Comment by timtay-microsoft** [comment]
If the issues is with the Device Provisioning Service device client, then here are some relevant throughput quotas that you may be hitting:

![image](https://user-images.githubusercontent.com/28789848/108397270-a165c300-71cc-11eb-9941-83fa8d31dd60.png)


> Caused by: Timed out waiting for a response from the server (32000)

This would suggest a throughput issue to me, not a network issue. If the Device Provisioning Service is overloaded with a lot of requests at once, the time to respond per request will likely grow which could cause this timeout. How many devices are registering through Device Provisioning Service at the same time?

**Comment by wuwei3** [comment]
> I'm a little confused by this error description. The code snippets and descriptions you provided are for the IoT Hub device client, but the exception stacktrace is for the Device Provisioning Service device client. Can you clarify which device client is in question here?

    Sorry, it was my fault, I was using the IOT central and the 10 devices are registering in central hub, not the IOT hub.
But based on the sample of the azure provided in github, 

 https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/pnp-device-sample/thermostat-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/Thermostat.java

it needs to use the iot-device-client jar

> Also, when you mention that you are using multiple threads, can you clarify if you are using multiple threads per provisioning device client, per IoT Hub device client, or just multiple threads and each thread has a provisioning and/or IoT Hub device client on it?

   just multiple threads and each thread has a provisioning and/or IoT Hub device client on it.

**Comment by wuwei3** [comment]
> If the issues is with the Device Provisioning Service device client, then here are some relevant throughput quotas that you may be hitting:
> 
> ![image](https://user-images.githubusercontent.com/28789848/108397270-a165c300-71cc-11eb-9941-83fa8d31dd60.png)
> 
> > Caused by: Timed out waiting for a response from the server (32000)
> 
> This would suggest a throughput issue to me, not a network issue. If the Device Provisioning Service is overloaded with a lot of requests at once, the time to respond per request will likely grow which could cause this timeout. How many devices are registering through Device Provisioning Service at the same time?

  Yes,  I saw this, but I just have only 10 devices and connect in every 7 mins, it is lower than the throughput, so I think it should not be appearing this error.

**Comment by timtay-microsoft** [comment]
> Caused by: java.io.IOException: Unable to subscribe on topic : $dps/registrations/res/#

Interestingly, the maximum wait time for the timeout that you are hitting is only [1 second](https://github.com/Azure/azure-iot-sdk-java/blob/da9084a0d2081cad80115599541fc64b9eb313c4/deps/src/main/java/com/microsoft/azure/sdk/iot/deps/transport/mqtt/MqttConnection.java#L33). I'm not sure why the SDK would impose such a short timeout on subscribing to a topic. The load that you are imposing on the service seems reasonable to me too, but it is possible that the service will take longer than 1 second to respond to a subscription request. 

I'll go ahead and make the SDK give more time before throwing this timeout exception to help deal with situations like this. 1 second before timing out was clearly too aggressive.

**Comment by timtay-microsoft** [comment]
The overly short timeout issue has been fixed as of provisioning device client 1.8.7, so I'm closing this issue. If you still see any issues around this workflow, feel free to open a new issue

**Comment by wuwei3** [comment]
@timtay-microsoft , have you pushed the latest to maven repository?

**Comment by timtay-microsoft** [comment]
Yep! https://search.maven.org/artifact/com.microsoft.azure.sdk.iot.provisioning/provisioning-device-client/1.8.7/jar
