### ISSUE TITLE
Device Twin updates cannot be done at a rapid rate

### ISSUE THREAD

**Issue by gbidsilva** [Azure/azure-iot-sdk-java#113]
**Env. Details:**
SDK Used : **Azure Device SDK**
```
<dependency>
	<groupId>com.microsoft.azure.sdk.iot</groupId>
	<artifactId>iot-device-client</artifactId>
	<version>1.3.29</version>
</dependency>
```
		
On
**Java 1.8 + Cent OS (Linux)**

HI Team,

In my application, I am trying to update/ push device twin data.
I was able to get it working properly but, I have encountered some issues.
In this application I have a method called 'updateDeviceTwinInAzure' and inside that method I am updating the device twin using the azure device sdk.

Following is my code,

```
package com.gbids.azuretwin;

import com.microsoft.azure.sdk.iot.device.DeviceClient;
import com.microsoft.azure.sdk.iot.device.DeviceTwin.Device;
import com.microsoft.azure.sdk.iot.device.DeviceTwin.Property;
import com.microsoft.azure.sdk.iot.device.IotHubClientProtocol;
import com.microsoft.azure.sdk.iot.device.IotHubEventCallback;
import com.microsoft.azure.sdk.iot.device.IotHubStatusCode;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AzureTwinUpdate {
    private static final Logger logger = LoggerFactory.getLogger(AzureTwinUpdate.class);

    public void updateDeviceTwinInAzure(final int propertyValue) throws Exception {
        logger.info("Attempting to update device twin...");

        Device homeKit = new Device() {
            @Override
            public void PropertyCall(String propertyKey, Object propertyValue, Object context) {
                System.out.println(propertyKey + " changed to " + propertyValue);
            }
        };

        // Connection String is something like below,
        // final String deviceConnectionString = "HostName=b123.azure-devices.net;DeviceId=" + deviceId + ";SharedAccessKey=***********************";
        DeviceClient client = new DeviceClient(deviceConnectionString, IotHubClientProtocol.MQTT);

        client.open();
        client.startDeviceTwin(new DeviceTwinStatusCallBack(), null, homeKit, null);

        homeKit.setReportedProp(new Property("testProperty", propertyValue));

        client.sendReportedProperties(homeKit.getReportedProp());
        homeKit.clean();
        client.closeNow();
    }

    protected static class DeviceTwinStatusCallBack implements IotHubEventCallback {
        public void execute(IotHubStatusCode status, Object context) {
            logger.info("IoT Hub responded to device twin operation with status " + status.name());
        }
    }
}
```
Following is the unit test methods which I am using to test this functionality.

```
package com.gbids.azuretwin;

import org.junit.Before;
import org.junit.Test;

public class AzureTwinUpdateTest {

    private AzureTwinUpdate azureTwinUpdate = null;

    @Before
    public void init(){
        azureTwinUpdate = new AzureTwinUpdate();
    }

    @Test
    public void updateDeviceTwinInAzureTest() throws Exception {
        azureTwinUpdate.updateDeviceTwinInAzure(10);
    }    
}

```
Above code is working as expected.

But when I invoke above 'updateDeviceTwinInAzure()' method multiple times rapidly within a for loop as follows, then it is not working as expected.

```
@Test
public void updateDeviceTwinInAzureTest() throws Exception {
	for(int i = 0; i < 5; i++){
		azureTwinUpdate.updateDeviceTwinInAzure(i);
	}
}
```

The result I am getting when running this in a for loop is as follows,

```
INFO  com.gbids.azuretwin.AzureTwinUpdate  - Attempting to update device twin...
INFO  com.gbids.azuretwin.AzureTwinUpdate  - IoT Hub responded to device twin operation with status OK_EMPTY
INFO  com.gbids.azuretwin.AzureTwinUpdate  - IoT Hub responded to device twin operation with status OK_EMPTY
INFO  com.gbids.azuretwin.AzureTwinUpdate  - Attempting to update device twin...
INFO  com.gbids.azuretwin.AzureTwinUpdate  - IoT Hub responded to device twin operation with status MESSAGE_CANCELLED_ONCLOSE
INFO  com.gbids.azuretwin.AzureTwinUpdate  - IoT Hub responded to device twin operation with status MESSAGE_CANCELLED_ONCLOSE
INFO  com.gbids.azuretwin.AzureTwinUpdate  - Attempting to update device twin...
INFO  com.gbids.azuretwin.AzureTwinUpdate  - IoT Hub responded to device twin operation with status MESSAGE_CANCELLED_ONCLOSE
INFO  com.gbids.azuretwin.AzureTwinUpdate  - IoT Hub responded to device twin operation with status MESSAGE_CANCELLED_ONCLOSE
INFO  com.gbids.azuretwin.AzureTwinUpdate  - Attempting to update device twin...
INFO  com.gbids.azuretwin.AzureTwinUpdate  - IoT Hub responded to device twin operation with status MESSAGE_CANCELLED_ONCLOSE
INFO  com.gbids.azuretwin.AzureTwinUpdate  - IoT Hub responded to device twin operation with status MESSAGE_CANCELLED_ONCLOSE
```

It is giving me "`MESSAGE_CANCELLED_ONCLOSE`" for update requests after first one.

However If I put 'Thread.sleep(2000);' before closing the client then it works fine - which is not a good practice I think.
I suspect this has something to do with the 'client.closeNow();' statement.
I even tried creating multiple device clients with different connection strings for different devices instead of pushing it for same device but, I am getting the same behaviour.

Am I doing anything wrong here ?
If this is the behavior then what is the recommended way of pushing twin data continuously ?

**Comment by prmathur-microsoft** [comment]
We have deprecated `close` and moved to `closeNow`. `closeNow` is expected to be called only when you are sure to exit. `closeNow` cleans up all the resources and exits the sdk gracefully. Hence you are receiving the message - MESSAGE_CANCELLED_ONCLOSE.  If you are not sure if you want to exit or if you are waiting for confirmation of message then please use any kind of wait (Thread.sleep(2000) as you suggested) until you are sure to exit and use closeNow then.

**Comment by gbidsilva** [comment]
Thank you @prmathur-microsoft for your response.

Well,  Adding wait can be easily done when we are pushing twin data for the same device since it is using one device client.
But, my requirement is quite different.

I want to push twin data for multiple devices one after the other (let's say inside a for loop). Therefore, we need to create dedicated device client for every device in every method call with the different device ID.
In that situation we may need to put device clients created in each call into some sort of a map and close them in a separate thread later on. Otherwise If I close them within the method as soon after it sends the twin data, device twin requests which are coming after that will not be properly updated due to : MESSAGE_CANCELLED_ONCLOSE.

Do I have any better way of doing this ?

Following code sample illustrate above mentioned behavior.

```
public class AzureTwinUpdate {
    private static final Logger logger = LoggerFactory.getLogger(AzureTwinUpdate.class);
   
    public void updateDeviceTwinInAzureWithStringAndValue(final String connectionString, final int propertyValue) throws Exception {
        logger.info("Attempting to update device twin...");

        Device homeKit = new Device() {
            @Override
            public void PropertyCall(String propertyKey, Object propertyValue, Object context) {
                System.out.println(propertyKey + " changed to " + propertyValue);
            }
        };
		
        DeviceClient client = new DeviceClient(connectionString, IotHubClientProtocol.MQTT);
        client.open();
        client.startDeviceTwin(new DeviceTwinStatusCallBack(), null, homeKit, null);
        homeKit.setReportedProp(new Property("testProperty", propertyValue));
        client.sendReportedProperties(homeKit.getReportedProp());
		
        homeKit.clean();
        client.closeNow();
    }

    protected static class DeviceTwinStatusCallBack implements IotHubEventCallback {
        public void execute(IotHubStatusCode status, Object context) {
            logger.info("IoT Hub responded to device twin operation with status " + status.name());
        }
    }
}
```
Following is the unit test case for above scenario,
```
@Test
public void updateDeviceInAzurewithConnectionStringAndValueTest() throws Exception {	
	List<String> connectionStringList = new ArrayList<String>();
	// Note the difference in device IDs
	connectionStringList.add("HostName=abc.azure-devices.net;DeviceId=gbidsTestDevice;SharedAccessKey=*****************");
	connectionStringList.add("HostName=abc.azure-devices.net;DeviceId=gbidsTestDevice2;SharedAccessKey=******************");

	for(int i=0; i<connectionStringList.size(); i++){
		azureTwinUpdate.updateDeviceTwinInAzureWithStringAndValue(connectionStringList.get(i), i);
	}
}
```

The Log result I am getting is as follows,
```
[main] INFO  com.gbids.azuretwin.AzureTwinUpdate  - Attempting to update device twin...
[pool-1-thread-1] INFO  com.gbids.azuretwin.AzureTwinUpdate  - IoT Hub responded to device twin operation with status OK_EMPTY
[pool-1-thread-1] INFO  com.gbids.azuretwin.AzureTwinUpdate  - IoT Hub responded to device twin operation with status OK_EMPTY
[main] INFO  com.gbids.azuretwin.AzureTwinUpdate  - Attempting to update device twin...
[main] INFO  com.gbids.azuretwin.AzureTwinUpdate  - IoT Hub responded to device twin operation with status MESSAGE_CANCELLED_ONCLOSE
[main] INFO  com.gbids.azuretwin.AzureTwinUpdate  - IoT Hub responded to device twin operation with status MESSAGE_CANCELLED_ONCLOSE
```

Appreciate your help on this.

**Comment by ruwan-jayaweera** [comment]
Is there a solution for this issue?

**Comment by prmathur-microsoft** [comment]
Basically you should wait till you receive a response from IotHub that your properties were sent successfully and only then close. And you can get this message from callback.

For eg : 

what you would like to do is pass an object to the callback and once you receive OK_EMPTY for the operation you are interested in, you should save it in that call back. 

class StatusObject
{
  String ConnectionString;
   boolean isSuccess;
}
StatusObject sObj = new StatusObject
for eg : client.startDeviceTwin(new DeviceTwinStatusCallBack(), null, homeKit, sObj);


and In the call back
protected static class DeviceTwinStatusCallBack implements IotHubEventCallback {
        public void execute(IotHubStatusCode status, Object context) {
            logger.info("IoT Hub responded to device twin operation with status " + status.name());
            if (status == OK_EMPTY)
                  StatusObject statusObject = ( StatusObject) context;
                  statusObject.isSuccess = true;
            else 
                  statusObject.isSuccess = false;
        }
    }

Now before closing device client you should wait till sObj.isSuccess is set to true and then close it.

Please let me know if this does not help.

**Comment by prmathur-microsoft** [comment]
We will be closing this for now. Feel free to reopen if the above does not answer your question. Happy to help again!

**Comment by gbidsilva** [comment]
@prmathur-microsoft : Please reopen this issue since we need more clarifications.

I just tried what you suggested for this issue as follows, and I have some concerns regarding it,
The sample I have tried is as follows,

```
class DeviceTwinSample{
	public void updateDeviceTwinInAzure(final int propertyValue) throws Exception {
		Device homeKit = new Device() {
			@Override
			public void PropertyCall(String propertyKey, Object propertyValue, Object context) {
				System.out.println(propertyKey + " changed to " + propertyValue);
			}
		};

		final String deviceConnectionString = "HostName=abc.azure-devices.net;DeviceId=gbidsTestDevice;SharedAccessKey=Key";
		DeviceClient client = new DeviceClient(deviceConnectionString, IotHubClientProtocol.MQTT);
		client.open();

		// Creating object to pass as the callback context..
		TwinOperationStatus twinOperationStatus = new TwinOperationStatus(client);
		client.startDeviceTwin(new DeviceTwinStatusCallBack(), twinOperationStatus, homeKit, null);
		homeKit.setReportedProp(new Property("testProperty", propertyValue));
		client.sendReportedProperties(homeKit.getReportedProp());
	}

	protected static class DeviceTwinStatusCallBack implements IotHubEventCallback {
		public void execute(IotHubStatusCode status, Object context) {
			logger.info("Callback status : " + status.name());
			if(context instanceof  TwinOperationStatus){
				TwinOperationStatus oppStatus = (TwinOperationStatus) context;
				try {
					logger.info("Closing the device client");
					oppStatus.getDeviceClient().closeNow();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}else{
				logger.warn(context.toString());
			}
		}
	}

	class TwinOperationStatus {
		DeviceClient deviceClient = null;
		TwinOperationStatus(DeviceClient client){
			this.deviceClient = client;
		}

		public DeviceClient getDeviceClient() {
			return deviceClient;
		}
	}
}
```
In this way I was trying to close the device client regardless of the status that is return from the cloud - means I am not checking whether the status is OK_EMPTY or not.
If I do it like this then I am getting following output,

```
2017-08-09 18:48:48,228 [main] INFO  com.gbids.azuretwin.AzureTwinUpdate  - Attempting to update device twin...
2017-08-09 18:48:49,553 [pool-1-thread-2] INFO  com.gbids.azuretwin.AzureTwinUpdate  - Callback status : OK_EMPTY
2017-08-09 18:48:49,553 [pool-1-thread-2] INFO  com.gbids.azuretwin.AzureTwinUpdate  - Closing the device client
java.lang.IllegalStateException: Cannot add a message to an MQTT transport that is closed.

	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.addMessage(MqttTransport.java:142)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.sendEventAsync(DeviceIO.java:292)
	at com.microsoft.azure.sdk.iot.device.DeviceTwin.DeviceTwin.updateReportedProperties(DeviceTwin.java:346)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.sendReportedProperties(DeviceClient.java:426)
	at com.gbids.azuretwin.AzureTwinUpdate.updateDeviceTwinInAzure(AzureTwinUpdate.java:37)
	at com.gbids.azuretwin.AzureTwinUpdateTest.updateDeviceTwinInAzureTestOnce(AzureTwinUpdateTest.java:32)
```
If I remove the device closing part (oppStatus.getDeviceClient().closeNow()), then it is working fine for a single update. Then I can get output as follows for successfull scenario as follows,

```
2017-08-09 18:58:35,372 [pool-1-thread-1] INFO  com.gbids.azuretwin.AzureTwinUpdate  - Callback status : OK_EMPTY
2017-08-09 18:58:35,373 [pool-1-thread-1] INFO  com.gbids.azuretwin.AzureTwinUpdate  - Callback status : OK_EMPTY
```
So in this case, eventhough I am updating only one property which is the 'testProperty' - homeKit.setReportedProp(new Property("testProperty", propertyValue)), I am getting two status outputs from the sdk.

Question 1:
Why are we getting more than one output from the SDK for a given property update and what are those ?

Question 2:
If I am to close the device client in the callback, what should be the server output that I need to keep checking ?
Possible status outputs that I am getting is : OK_EMPTY, OK etc.

Question 3:
Do we really have to close the device client at all after the device twin update ?

**Comment by prmathur-microsoft** [comment]
Ans to your question : 
Question 1:
Why are we getting more than one output from the SDK for a given property update and what are those ?
ANS : When you start twin, we internally do gettwin which basically retrieves the entire twin document for the first time. And then following that, we provide status for updated properties. Hence you see two updates. Last one should be yours (only if you closed and opened twin)

Question 2:
If I am to close the device client in the callback, what should be the server output that I need to keep checking ?
Possible status outputs that I am getting is : OK_EMPTY, OK etc.
Ans : Both the cases are good cases. Ok and OK_Empty. So you should be good if your get either.

Question 3:
Do we really have to close the device client at all after the device twin update ?
Ans : Not really. Infact you close the device client only upon exiting your application. For all other instances you should let device client handle the queue of messages it receives. 

Let us know if this does not help.

**Comment by prmathur-microsoft** [comment]
Closing this and I assume it might be working as I have not heard back. Feel free to reopen if you have any further questions.
