### ISSUE TITLE
ExecutorService in RegistryManager is never shutdown

### ISSUE THREAD

**Issue by zelenoto** [Azure/azure-iot-sdk-java#114]
The ExecutorService in com.microsoft.azure.sdk.iot.service.RegistryManager is never shutdown. This prevents applications using any of its async methods to terminate normally due to dangling threads.

I guess RegistryManager.close method will be a good place to shutdown the executor (or just use [ForkJoinPool.commonPool](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html#commonPool--) instead of custom executor service)

**Comment by prmathur-microsoft** [comment]
We have added this to our backlog to address it. In the meantime please feel free to provide a PR and we will take it in.

**Comment by prmathur-microsoft** [comment]
As of this checkin @4d231e74646f60c95f355ce153d9e178fd905bf7  a close API is implemented in registry manager. Packages with these changes will be released soon.
