### ISSUE TITLE
Cannot get JSON or Object structure form getTwin() method in DeviceTwin

### ISSUE THREAD

**Issue by gbidsilva** [Azure/azure-iot-sdk-java#115]
Env. Details:
SDK Used : Azure Service SDK
```
<dependency>
	<groupId>com.microsoft.azure.sdk.iot</groupId>
	<artifactId>iot-service-client</artifactId>
	<version>1.5.22</version>
</dependency>
```
On
Java 1.8 + Cent OS (Linux)

Hi Team,

I am facing some issues in retriving Device Twin through Java Service SDK.
When we use, 
```
DeviceTwin twinClient = DeviceTwin.createFromConnectionString(iotHubConnectionString);
DeviceTwinDevice device = new DeviceTwinDevice(deviceId);
try {
	twinClient.getTwin(device);
} catch (com.microsoft.azure.sdk.iot.service.exceptions.IotHubException e) {
	e.printStackTrace();
}
```
`getTwin()` method is returning values properly but not with a JSON format. It is returning some toString() value.

Consider following device twin JSOS structure which is available in Azure Device Explorer (I have removed some prop. from following structure),

```
{
  "deviceId": "149933hgt335",
  "etag": "AAAA22AAAAE=",
  "properties": {
    "desired": {
      
    },
    "reported": {
	  "sensors": {
          "sensor4": "4",
          "sensor5": "5",
          "sensor2": "2",
          "sensor3": "3",
          "sensor8": "8",
          "sensor9": "9",
          "sensor6": "6",
          "sensor7": "7",
          "sensor0": "0",
          "sensor1": "1"
        }
    },
    "metadata": {
        
    }
  },
  "$version": 2
}
```

For above reported structure I am getting following reported string from the sdk.

```
final Set<Pair> reportedProperties = device.getReportedProperties();
```

The value I am getting is : 

```
{sensors={sensor4=4, sensor5=5, sensor2=2, sensor3=3, sensor8=8, sensor9=9, sensor6=6, sensor7=7, sensor0=0, sensor1=1}}
```

Above is not in JSON Structure. This becomes problematic when we try to deserialize incoming twin values from SDK into the respective internal object structures or even into Maps.
If we are to do so then, we need to do some sort of String Manipulation or Tokenization process to get them deserialized - which I think is not the best practice.

Following is the place where I think the root cause is,

in `com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwin`, in `getTwin()` method, we have following...
```
device.getTwinParser().updateTwin(twin);
device.setTags(device.getTwinParser().getTagsMap());
device.setDesiredProperties(device.getTwinParser().getDesiredPropertyMap());
device.setReportedProperties(device.getTwinParser().getReportedPropertyMap());
```
Inside updateTwin(), somewhere down the line, following line is getting executed.

in `com.microsoft.azure.sdk.iot.deps.serializer.TwinProperty` class, in `getPropertyMap()` method,
```
propertyMap.put(e.getKey(), e.getValue().value.toString());
```
`toString()` is causing the issue.

Is this the intended behavior of getTwin() method ? If that is so, then what is the way to get JSON structure or object hierarchy such as Map from the SDK call ?

**Comment by prmathur-microsoft** [comment]
We will investigate this issue and get back to you soon.

**Comment by mamokarz** [comment]
Hi @gbidsilva, thank you to report this issue. You are correct, and the JSON format shall be the best option, I'll fix it.

**Comment by tmenninger** [comment]
FYI this exact same JSON problem exists in the client side of this SDK. Documented here

https://social.msdn.microsoft.com/Forums/en-US/f3ee4fa6-da22-4b19-aa62-e9e47e8f3873/basic-portal-ui-device-twin-feature-not-working?forum=azureiothub

I validated this is still an issue with:

<dependency>
      <groupId>com.microsoft.azure.sdk.iot</groupId>
      <artifactId>iot-device-client</artifactId>
      <version>1.3.30</version>
 </dependency>

**Comment by prmathur-microsoft** [comment]
Fix is checked in master branch and Maven package for the same is also released. Follow our release from https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-7-14. Feel free to reopen if you see any further issues.
