### ISSUE TITLE
[feature request] Update reported property of a device without starting a device twin

### ISSUE THREAD

**Issue by jonasbark** [Azure/azure-iot-sdk-java#1151]
**Is your feature request related to a problem? Please describe.**
A related issue is this: 

**Describe the solution you'd like**
I'd like to update reported properties without having to start a device twin. 

**Describe alternatives you've considered**
Currently I'm using the alternative to start the device twin, then send the reported properties:
```kotlin

val client = DeviceClient(registryManager.getDeviceConnectionString(device), IotHubClientProtocol.MQTT)
client.open()
client.startDeviceTwin({ status, _ ->
        if (status == IotHubStatusCode.OK_EMPTY) {
           // means that the reported properties are sent
           client.closeNow()
        }
}, null, TwinPropertyCallBack { _, _ -> }, null)

client.sendReportedProperties(thing.toReportedProperties())
```
when using MQTT it will cause this issue:
```
com.microsoft.azure.sdk.iot.device.exceptions.TransportException: Cannot subscribe when mqtt client is disconnected
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:253)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttDeviceTwin.start(MqttDeviceTwin.java:68)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.sendMessageResult(MqttIotHubConnection.java:419)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.acknowledgeReceivedMessage(IotHubTransport.java:873)
```

when using AMQPS it will cause this issue:
https://github.com/Azure/azure-iot-sdk-java/issues/1104
but even worse, it will clash with the Device client from IOT Edge, saying that another AMPQS connection is currently used. I added my use case below.

**Additional context**
My use case is this: 
I have an IOT Edge device that is responsible for finding and connecting to other hardware devices (in my case robots). It's also responsible for managing the children's IOT devices, adding them via the RegistryManager class.
So regularly, e.g. every minute I'd like to update the reported properties of a child IOT Device *from* the IOT Edge device. 

I'd like to do this without having to start a device twin, then having to close it soon after due to the issues mentioned above. 

AB#9507356

**Comment by timtay-microsoft** [comment]
For some context here, the reason that the SDK requires you to start the twin before sending any reported properties is because the service won't fully respond to reported properties sent by a client unless the client is subscribed to desired property updates already. The service will send the basic AMQP ack upon receiving the reported property message, but it won't send the response message that contains the status code and any error information, if there was an error. Because of this, there isn't a great way to send a reported property without starting the twin first.

As I mentioned in the other issue thread, closing the device client during a callback executed by the client itself is not supported behavior. You will need to close the client from a different thread. Something like the below will work:

```java
DeviceClient client = new DeviceClient(connString, protocol);
client.open();

final AtomicBoolean twinOperationFinished = new AtomicBoolean(false);
client.startDeviceTwin(
    new IotHubEventCallback()
    {
        @Override
        public void execute(IotHubStatusCode responseStatus, Object callbackContext)
        {
            if (responseStatus == IotHubStatusCode.OK || responseStatus == IotHubStatusCode.OK_EMPTY)
            {
                System.out.println("A twin operation completed successfully");
                twinOperationFinished.set(true);
            }
        }
    },
    null,
    new TwinPropertyCallBack()
    {
        @Override
        public void TwinPropertyCallBack(Property property, Object context)
        {
            System.out.println(
                "Twin property change " + property.getKey() +
                    " to " + property.getValue() +
                    ", Properties version:" + property.getVersion());
        }
    },
    null);

do
{
    Thread.sleep(100);
}
while(!twinOperationFinished.get());

System.out.println("Finished starting twin, sending reported properties...");

Set<Property> reportProperties = new HashSet<Property>()
{
    {
        add(new Property("SomeReportedPropertyKey", "SomeReportedPropertyValue"));
    }
};

twinOperationFinished.set(false);
client.sendReportedProperties(reportProperties);
do
{
    Thread.sleep(100);
}
while(!twinOperationFinished.get());

System.out.println("Finished sending reported properties, closing client now...");

client.closeNow();
```

Is there some reason why you'd prefer to avoid starting the twin other than how your current implementation isn't working?

**Comment by jonasbark** [comment]
>but it won't send the response message that contains the status code and any error information 
That's good to know - I tried my luck with reflection but now I see why it said it succeeded but the reported properties were never applied.

Thank you for the code example - I'll have a try.

> Is there some reason why you'd prefer to avoid starting the twin other than how your current implementation isn't working?

I'm not entirely sure if I understand the question correctly, so I'll try to explain:
The IOT Edge device part is connected through AMQPS already and stays connected at all times. When I'm trying to start the device twin of a child device with the same protocol I'm regularly getting issues, stating that "another AMPQS connection is currently used" on either the IOT Edge part or the child device connection. Which does make sense I guess.
I tried it with MQTT for the child devices and it caused issues as well - but it might be fixed by the code you mentioned.

Those issues causes the whole setup to fail and that's also the reason why I'm trying to avoid starting the device twin. Another reason would be to save CPU and network requests (one PUT/PATCH request vs one active connection with several back and forth messages). I have to potentially scale those operations to 100 devices.

**Comment by timtay-microsoft** [comment]
> The IOT Edge device part is connected through AMQPS already and stays connected at all times. When I'm trying to start the device twin of a child device with the same protocol I'm regularly getting issues, stating that "another AMPQS connection is currently used"

IoT Hub only allows a single device identity to have 1 open connection at a time. It sounds like you have both the edge device and the child device using the same device identity. Am I understanding that correctly, though? If so, I'd recommend that each physical device has its own distinct identity rather than sharing one device identity across multiple physical devices.

**Comment by jonasbark** [comment]
Each device has its own IOT hub device, so that wouldn't be the issue. I assume that multiple AMPQS concurrent connections to different devices are supposed to work without issues?

My current workaround regarding that issue is to have the IOT Edge device connect via MQTT and the child devices connect via AMPQS - that works okay-ish.

**Comment by timtay-microsoft** [comment]
> I assume that multiple AMPQS concurrent connections to different devices are supposed to work without issues?

A single physical device can open any number of connections to IoT Hub as long as each connection uses a unique device identity that no other physical device currently has a connection open for. Multiple physical devices can have open connections to IoT Hub at the same time under the same restrictions, yes. 

> My current workaround regarding that issue is to have the IOT Edge device connect via MQTT and the child devices connect via AMPQS - that works okay-ish.

I'm curious why you have to do that. What errors are you seeing from the SDK if both the Edge and child devices connect over the same protocol?

**Comment by jonasbark** [comment]
This one:
```
com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.AmqpInternalErrorException at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertFromAmqpException
Another AMQP Client has opened a Receive Link
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertFromAmqpException (50)
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onSessionClosedUnexpectedly (699)
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionHandler.onLinkClosedUnexpectedly (291)
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsReceiverLinkHandler.onLinkRemoteClose (114)
org.apache.qpid.proton.engine.BaseHandler.handle (176)
org.apache.qpid.proton.engine.impl.EventImpl.dispatch (108)
org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch (324)
org.apache.qpid.proton.reactor.impl.ReactorImpl.process (291)
com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run (25)
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call (1115)
java.util.concurrent.FutureTask.run (-1)
java.util.concurrent.ThreadPoolExecutor.runWorker (-1)
java.util.concurrent.ThreadPoolExecutor$Worker.run (-1)
java.lang.Thread.run (-1)
```
Please note that this exception was thrown in the IOT Edge Device connection which ultimately rendered the whole IOT edge device useless. I can understand that this error would be thrown in my use case (connecting multiple child devices) due to not properly closing a connection but it really wasn't. 
That's why I assumed that more than one AMPQS connections (with different device IDs) would cause issues.

**Comment by timtay-microsoft** [comment]
That exception should only be thrown if your Edge device has opened a connection with a device identity when another connection with that identity is already active. I'd double check that each device is only opening the connections you'd expect

**Comment by timtay-microsoft** [comment]
Is there anything else I can help you with on this issue, @jonasbark?

**Comment by jonasbark** [comment]
With the workaround from https://github.com/Azure/azure-iot-sdk-java/issues/1151#issuecomment-797034125 it works okayish.

I'm still seeing internal errors, such as 
```
LoggerName: com.microsoft.azure.sdk.iot.device.transport.IotHubTransport
Logger Message: Updating transport status to new status DISCONNECTED_RETRYING with reason NO_NETWORK
LoggingLevel: WARN
java.lang.NullPointerException at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call
org.apache.qpid.proton.engine.HandlerException: java.lang.NullPointerException
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call (1137)
```
but I see you already closed https://github.com/Azure/azure-iot-sdk-java/issues/1104 due to lack of repo, which I don't quite understand.


Regarding this issue itself: I would still like to update the reported properties with the least bandwidth and workarounds possible.

**Comment by jonasbark** [comment]
Here's a new exception that is happening even with the workaround:
```
java.util.ConcurrentModificationException at java.util.LinkedHashMap$LinkedHashIterator.nextNode
java.util.ConcurrentModificationException
java.util.LinkedHashMap$LinkedHashIterator.nextNode (-1)
java.util.LinkedHashMap$LinkedValueIterator.next (-1)
java.util.AbstractCollection.finishToArray (-1)
java.util.AbstractCollection.toArray (-1)
java.util.ArrayList.<init> (-1)
org.apache.qpid.proton.engine.impl.SessionImpl.doFree (153)
org.apache.qpid.proton.engine.impl.EndpointImpl.free (190)
org.apache.qpid.proton.engine.impl.ConnectionImpl.doFree (210)
org.apache.qpid.proton.engine.impl.EndpointImpl.free (190)
org.apache.qpid.proton.reactor.impl.ReactorImpl.free (137)
com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.close (286)
com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.close (429)
com.microsoft.azure.sdk.iot.device.DeviceIO.close (265)
com.microsoft.azure.sdk.iot.device.InternalClient.closeNow (192)
com.microsoft.azure.sdk.iot.device.DeviceClient.closeNow (519)
```

**Comment by timtay-microsoft** [comment]
This thread has gotten a bit off topic, and I'd like to provide some closure to anyone who saw this open issue and was curious if we planned on adding support for updating reported properties without starting device twin.

My team's stance is that we do not plan to add support for the SDK around this scenario because the service itself does not support this scenario. At its heart, twin is a bi-directional style of communication, not a one-way property updating message system. With that in mind, I'm closing this issue. 

@jonasbark if you are still seeing these MQTT/AMQP issues, please open a new issue with all the required context and repro steps

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
