### ISSUE TITLE
[Technical Question] Why does DeviceTwinDevice doesn't support deviceScope property

### ISSUE THREAD

**Issue by jinyanghuang** [Azure/azure-iot-sdk-java#1157]
I am using iot-service-client. I am trying to fetch the deviceScope of all io-device. However, the DeviceTwinDevice doesn't have that property. My code is as follow

```
String iotHubConnectionString  = "xxx";

DeviceTwin twinClient = DeviceTwin.createFromConnectionString(iotHubConnectionString);

SqlQuery sqlQuery = SqlQuery.createSqlQuery("*",SqlQuery.FromType.DEVICES,"capabilities.iotEdge=false",null);
Query twinQuery = twinClient.queryTwin(sqlQuery.getQuery());
DeviceTwinDevice d = twinClient.getNextDeviceTwin(twinQuery);
```

AB#9552710

**Comment by abhipsaMisra** [comment]
The device scope property is available under the `Device` object that can be retrieved using the `RegistryManager`: https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/Device.java#L192
This would require you to fetch the `Device` instance from either the retrieved twin instance or through a device Id (if you have one saved already).

Would this work for you?

**Comment by jinyanghuang** [comment]
> The device scope property is available under the `Device` object that can be retrieved using the `RegistryManager`: https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/Device.java#L192
> This would require you to fetch the `Device` instance from either the retrieved twin instance or through a device Id (if you have one saved already).
> 
> Would this work for you?

Thanks, can you provide an example? I don't have a device Id. I would like to retrieve all devices' deviceScope?

**Comment by abhipsaMisra** [comment]
You can use the following code:

```java
...
DeviceTwinDevice d = twinClient.getNextDeviceTwin(twinQuery);

RegistryManager registryManager = RegistryManager.createFromConnectionString(iotHubConnectionString);
Device retrievedDevice = registryManager.getDevice(d.getDeviceId());
```

**Comment by jinyanghuang** [comment]
Thanks so much. That worked
