### ISSUE TITLE
Question: list all Twins from DeviceClient

### ISSUE THREAD

**Issue by ApiO** [Azure/azure-iot-sdk-java#116]
Hi,
I'm actualy working with this client sdk version:

```
<dependency>
    <groupId>com.microsoft.azure.sdk.iot</groupId>
    <artifactId>iot-device-client</artifactId>
    <version>1.3.29</version>
</dependency>
```

I try, from a device client, to get all its twins (desired/reported), maybe I miss something but I found nothing in the API documentation. 

Is it possible ? a future feature ? According to this [documentation ](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins)it may be possible.

In my use case, it will allow me to make some dynamic subscritions on the reported properties.

Thanks

**Comment by ApiO** [comment]
I compared with C# API and there is a simple and nice DeviceClient.GetTwinAsync(), it will be perfect in java sdk too.

**Comment by prmathur-microsoft** [comment]
We have added this to our backlog and will consider adding it in future. In the meantime, please feel free to provide a PR and I'll review it for you.

**Comment by ApiO** [comment]
Glad to hear that :)
It would have been a pleasure to do this PR, but unfortunately I'm not currently skilled enough with Java. So I'll just stay here and wait and ... cheer!

**Comment by prmathur-microsoft** [comment]
We have added this API and is currently released as maven package. In master please have a look at https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java#L601
Closing it for now. Let us know if you have any further issues.
