### ISSUE TITLE
Method to get the callback for sendReportedProperties(Set<DeviceTwin.Property> reportedProperties)

### ISSUE THREAD

**Issue by motoxyz** [Azure/azure-iot-sdk-java#1166]
First, we are using sendReportedProperties(Set<DeviceTwin.Property> reportedProperties) function to send reported device twin to iothub. It worked in almost every time except there are a scenario that the reported device twin are not received by iothub. But in client side, we dont know whether the reported device twin are successfully sent out or not.

It mostly happened when LTE or Wifi connection are being cut off while client half ways sending the reported device twin.

For sendReportedProperties(Set<DeviceTwin.Property> reportedProperties), there are no callback function parameter that allow us to define our own callback function. Client is not informed about the status whether reported device twin received by iothub or not.

Is there any function/callback that can inform client when reported device twin are successfully received by iothub? Or return error if it is not received by iothub.

Thanks.

**Comment by jamdavi** [comment]
@motoxyz I believe if there is an issue with the underlying connection call you should get an IOException from the call. Are you saying that IoT Hub is giving back a non ok message and we're not reporting it?

**Comment by motoxyz** [comment]
@jamdavi Able to get the status from below callback function when iothub received the reported device twin.

    protected static class DeviceTwinStatusCallBack implements IotHubEventCallback
    {
        @Override
        public void execute(IotHubStatusCode status, Object context)
        {
            Succeed.set((status == IotHubStatusCode.OK) || (status == IotHubStatusCode.OK_EMPTY));
            System.out.println("IoT Hub responded to device twin operation with status " + status.name());
        }
    }

But, the callback function not only being triggered when iothub received the reported device twin (sendReportedProperties), but it also being triggered when iothub responded to below API.
1. client.startDeviceTwin(new DeviceTwinStatusCallBack(), null, new onProperty(), null);
2. client.getDeviceTwin();

Is there any method that we can trace whether the returned callback is for which event?

**Comment by jamdavi** [comment]
@motoxyz sorry for the delay here, I went on vacation and this wasn't picked up. I'll take a look at this today and see if there is an enhancement or better way to do this.

**Comment by jamdavi** [comment]
@motoxyz You are correct that there is no way to make this work currently. 

I've spent some time looking at how to do this and I think this will result in a feature request and require a fair amount of changes to the SDK so it supports the current way and the requested way.

**Comment by jamdavi** [comment]
@motoxyz The fix has been checked in to master. There is a release started, but it is on hold for review with some other teams. I will work with the group to get this change added to the next release.

**Comment by motoxyz** [comment]
Thanks for the fix. I tried to run the DeviceTwinSample.java and able to print out the callback.
May I know what is the version it will be released for picking up this fix?
com.microsoft.azure.sdk.iot:iot-device-client

**Comment by jamdavi** [comment]
@motoxyz The fix has been released in the latest release. You can find it here:

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2021-5-5

**Comment by timtay-microsoft** [comment]
Closing this issue as the fix has been released as of device client version 1.30.0
