### ISSUE TITLE
Client connection with HTTPs always throw TLS certificate exception

### ISSUE THREAD

**Issue by MickeyMouseS** [Azure/azure-iot-sdk-java#1167]
Every connection using HTTPs to IoT Hub using a intermediate IoT Edge with autogenerated certificates throw an error when validating the certificate. The certificate have been installed in cacerts (all versions of java installed), system and private trust stores (using them with -Djavax.net.ssl.trustStore).

For other protocols (MQTT), setting the path to proper certificate solves the problem, but in HTTPs does not allow to set this parameter.

I have make sure, by means of SSLPoke, that the certificate installed was the proper one and the connection was allowed outside of this library.

# Context

- **OS and version used:** MacOS Big Sur 11.1
- **Java runtime used:** 1.8.0_241
- **SDK version used:** 1.29.4 (iot-device-client-version)

## Console log of the issue
com.microsoft.azure.sdk.iot.device.exceptions.TransportException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

AB#9622225

**Comment by timtay-microsoft** [comment]
Can you share the SDK side code that you are writing so that we can attempt to repro this?

**Comment by bikamani** [comment]
@MickeyMouseS Could you provide some information on how are you validating for MQTT and what your application code looks like using HTTP?

**Comment by timtay-microsoft** [comment]
Closing due to lack of customer response

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
