### ISSUE TITLE
[Technical Question] registryManager.getDevices() is deprecated, replacement does not include symmetric keys

### ISSUE THREAD

**Issue by jonasbark** [Azure/azure-iot-sdk-java#1169]
registryManager.getDevices() is deprecated, naming
```
 com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwin.queryTwin(String sqlQuery, Integer pageSize) to query for all devices.
```
as replacement.

This is the output of registryManager.getDevices() that includes the symmetric key:

```json
[{
   "deviceId":"9",
   ...
   "authentication":{
      "symmetricKey":{
         "primaryKey":"...=",
         "secondaryKey":"...="
      },
      "x509Thumbprint":{
         "primaryThumbprint":null,
         "secondaryThumbprint":null
      },
      "type":"sas"
   },
}]
```

And this is the output of the DeviceTwin.queryTwin:
```json
[{
   "deviceId":"...",
   "x509Thumbprint":{
      
   },
   "modelId":"",
   "version":19294,
   "properties":{
      ...
      },
     ...
}]
```
The latter does not include the symmetric key. What am I to use as a replacement to query multiple devices that include the key in the output?
I don't wish to call registryManager.getDevice(id) for 40+ devices to get these information.

Library used:
com.microsoft.azure.sdk.iot:iot-service-client:1.28.0

**Comment by vinagesh** [comment]
We will investigate and get back to you with the details.

**Comment by vinagesh** [comment]
Hey, after doing some more investigation, your options are to either do a GET on every ID or you could choose to use the registry export job, which would include the symmetric keys for every device. There is no exact replacement for the deprecated GetDevices() API.

**Comment by vinagesh** [comment]
I know this might be a bit inconvenient usage wise, but these are the only options that are available now. We will try to investigate if the experience can be improved in the future.

**Comment by jonasbark** [comment]
Okay, thank you for taking care 👍
