### ISSUE TITLE
Unable to make a single AMQPS connection to the IOTHub for multiple devices 

### ISSUE THREAD

**Issue by bhuvanalakshmi** [Azure/azure-iot-sdk-java#117]
- **OS and version used:** 
Mac El Captain 

- **Java runtime used:** 
Java 1.8.0_60

- **SDK version used:**
iot-device-client - 1.3.29

# Description of the issue:
 Unable to make a single connection to the IOTHub for multiple devices for AMQP. Looks like this is supported in the C SDK but not in the java 

# Code sample exhibiting the issue:
String connectionStr = "----";// IotHub connection string
DeviceClient client = new DeviceClient(connectionStr,  IotHubClientProtocol.AMQPS);

# Console log of the issue:
Exception in thread "main" java.lang.IllegalArgumentException: Device ID cannot be null.
      at com.microsoft.azure.sdk.iot.device.IotHubConnectionString.validateTerms(IotHubConnectionString.java:220)
      at com.microsoft.azure.sdk.iot.device.IotHubConnectionString.<init>(IotHubConnectionString.java:98)
      at com.microsoft.azure.sdk.iot.device.DeviceClient.<init>(DeviceClient.java:147)

**Comment by prmathur-microsoft** [comment]
Can you share how are you trying to connect to Multiple devices ? Are you interested in multiple devices over single connection or are you ok with multiple devices over multiple connections ?

**Comment by bhuvanalakshmi** [comment]
I am interested in multiple devices over single connection - just like this sample supported in the C SDK. 
https://github.com/Azure/azure-iot-sdk-c/blob/1ad2c5355a3d9759493eda9b41647c34b845ec20/iothub_client/samples/iothub_client_sample_amqp_shared/iothub_client_sample_amqp_shared.c

I am using the DeviceClient with IOTHub Connection string for AMQPS protocol. 

 String connectionStr = "----";// IotHub connection string
DeviceClient client = new DeviceClient(connectionStr, IotHubClientProtocol.AMQPS);

Is there an other way to do this ?

**Comment by prmathur-microsoft** [comment]
Currently java SDK does not support multiplexing over AMQP. We have this feature in our backlog and will be adding it in future.

**Comment by bhuvanalakshmi** [comment]
@prmathur-microsoft  - What does it take to connect to IOTHUB using amqps without device id ?  I see there is documentation available on how to use MQTT without SDKs (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support). But, i don't see documentation for AMQP.

**Comment by bhuvanalakshmi** [comment]
Is there a timeline on when this will be supported in the java SDK ?

**Comment by prmathur-microsoft** [comment]
At this point of time it is planned to be worked on in October

**Comment by timtay-microsoft** [comment]
Multiplexing over AMQP will be supported in the next release

**Comment by timtay-microsoft** [comment]
Support for multiplexing has now been released:

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-12-2

I'm closing this issue for now, feel free to re-open if it something else comes up
