### ISSUE TITLE
Its unable to serialize devices correctly for bulk import

### ISSUE THREAD

**Issue by marichka-spin** [Azure/azure-iot-sdk-java#1177]
According to the allowed azure documentation and examples, in order to perform bulk import of devices into azure iot hub each device should be serialized to json. I've tried to perform bulk import couple of times and then I tried to perform export first. What I've got? example of exported devices:
`{"id":"d8494cb9-2271-499d-9bf3-037f9bc7f9ef","eTag":"MTA0NDQxMTE5Nw==","status":"enabled","statusReason":"","authentication":{"symmetricKey":{"primaryKey":"******","secondaryKey":"******"},"x509Thumbprint":{"primaryThumbprint":null,"secondaryThumbprint":null},"type":"sas"},"twinETag":"AAAAAAAAAAE=","tags":{},"properties":{"desired":{},"reported":{}},"capabilities":{"iotEdge":false}}
{"id":"0094808b-2016-4987-84b0-bc8c5cdd3e88","eTag":"MTYzOTc2OTk0","status":"enabled","statusReason":"","authentication":{"symmetricKey":{"primaryKey":"******","secondaryKey":"******"},"x509Thumbprint":{"primaryThumbprint":null,"secondaryThumbprint":null},"type":"sas"},"twinETag":"AAAAAAAAAAE=","tags":{},"properties":{"desired":{},"reported":{}},"capabilities":{"iotEdge":false}}`

And example how object of class com.microsoft.azure.sdk.iot.service.Device is serialized:
`{"deviceId":"673d1f07-9167-4175-bd08-6674375d3bd0","generationId":"","eTag":"","connectionState":"Disconnected","connectionStateUpdatedTime":"0001-01-01T00:00:00","lastActivityTime":"0001-01-01T00:00:00-00:00","cloudToDeviceMessageCount":0,"status":"Enabled","statusReason":"","scope":"","statusUpdatedTime":"0001-01-01T00:00:00","capabilities":null,"primaryThumbprint":null,"primaryKey":"******","secondaryKey":"******","symmetricKey":{"primaryKey":"******","secondaryKey":"******"},"secondaryThumbprint":null,"authenticationType":"SAS"}
{"deviceId":"acac854b-501d-4eb8-9d12-2be535055704","generationId":"","eTag":"","connectionState":"Disconnected","connectionStateUpdatedTime":"0001-01-01T00:00:00","lastActivityTime":"0001-01-01T00:00:00-00:00","cloudToDeviceMessageCount":0,"status":"Enabled","statusReason":"","scope":"","statusUpdatedTime":"0001-01-01T00:00:00","capabilities":null,"primaryThumbprint":null,"primaryKey":"******","secondaryKey":"******","symmetricKey":{"primaryKey":"******","secondaryKey":"******"},"secondaryThumbprint":null,"authenticationType":"SAS"}`

Having looked through the source code of iot sdk (iot-service-client) I came to the conclusion that the most appropriate object for serialization os object of class com.microsoft.azure.sdk.iot.service.ExportImportDevice and its decorator com.microsoft.azure.sdk.iot.deps.serializer.ExportImportDeviceParser, but the issue is that method 'ExportImportDeviceParser toExportImportDeviceParser()'  (with description 'To serialize a ExportImportDevice object, it must first be converted to a ExportImportDeviceParser object.') is package private and can't be used outside.

# Context

- **OS and version used:** MacOS 14.0
- **Java runtime used:** openjdk version "11.0.8" 2020-07-14 LTS
- **SDK version used:**  com.microsoft.azure.sdk.iot:iot-service-client:1.26.0

**Comment by timtay-microsoft** [comment]
We have a pair of samples that should help demonstrate what you are trying to do: 

[For importing devices](https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceManagerImportSample.java)

[For exporting devices](https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceManagerExportSample.java)

**Comment by marichka-spin** [comment]
Thank you a lot - it helps
