### ISSUE TITLE
[Bug Report] Thread leak on authentication failure in TransportClient multiplexed connection

### ISSUE THREAD

**Issue by sanjay-90210** [Azure/azure-iot-sdk-java#1183]
# Context

- **OS and version used:** Ubuntu 16.04.7 LTS
- **Java runtime used:** openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~16.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

- **SDK version used:** iot-device-client 1.29.4

## Description of the issue
When one or more devices that are multiplexed onto a single AMQP transport has authentication issues, a re-connection thread lingers even after the transport is closed. It will later run into operation timeout and exit on its own. Since this thread is not a daemon thread, it will keep the java process running even after main exists.

## Code sample exhibiting the issue

Run the below class with 2 connect strings, one from an enabled device and another from a disabled or deleted device.

```
public class Main
{
    public static void main(String[] args) throws Exception
    {
        TransportClient tc = new TransportClient(IotHubClientProtocol.AMQPS);

        List<DeviceClient> list = new ArrayList<>(10);

        for(String cs : args)
        {
            DeviceClient client = new DeviceClient(cs, tc);
            list.add(client);
        }
        try 
        {
            tc.open();
        }
        catch(Throwable tx)
        {
            tx.printStackTrace();
        }

        System.out.println("Press Enter to close ...");
        Scanner scanner = new Scanner(System.in);
        scanner.nextLine();

        tc.closeNow();

        System.out.println("Press Enter to exit ...");
        scanner.nextLine();
    }
}
```

## Console log of the issue

[main] INFO com.microsoft.azure.sdk.iot.device.transport.ExponentialBackoffWithJitter - NOTE: A new instance of ExponentialBackoffWithJitter has been created with the following properties. Retry Count: 2147483647, Min Backoff Interval: 100, Max Backoff Interval: 10000, Max Time Between Retries: 100, Fast Retry Enabled: true
[main] DEBUG com.microsoft.azure.sdk.iot.device.DeviceClientConfig - Device configured to use software based SAS authentication provider
[main] DEBUG com.microsoft.azure.sdk.iot.device.TransportClient - DeviceClient instance successfully added to the transport client
[main] INFO com.microsoft.azure.sdk.iot.device.transport.ExponentialBackoffWithJitter - NOTE: A new instance of ExponentialBackoffWithJitter has been created with the following properties. Retry Count: 2147483647, Min Backoff Interval: 100, Max Backoff Interval: 10000, Max Time Between Retries: 100, Fast Retry Enabled: true
[main] DEBUG com.microsoft.azure.sdk.iot.device.DeviceClientConfig - Device configured to use software based SAS authentication provider
[main] DEBUG com.microsoft.azure.sdk.iot.device.TransportClient - DeviceClient instance successfully added to the transport client
[main] INFO com.microsoft.azure.sdk.iot.device.transport.ExponentialBackoffWithJitter - NOTE: A new instance of ExponentialBackoffWithJitter has been created with the following properties. Retry Count: 2147483647, Min Backoff Interval: 100, Max Backoff Interval: 10000, Max Time Between Retries: 100, Fast Retry Enabled: true
[main] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Opening amqp layer...
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsCbsSessionHandler - Opening Cbs session handler
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSenderLinkHandler - cbs sender link with link correlation id 3ad66933-6c6d-43fd-b43d-f3c32c3b7560 was successfully opened
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsReceiverLinkHandler - cbs receiver link with link correlation id 1697155a-885e-4b0b-9900-2c4014052a90 was successfully opened
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSasTokenRenewalHandler - Sending authentication message for device m7
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSasTokenRenewalHandler - Sending authentication message for device m9
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSasTokenRenewalHandler - CBS message authentication succeeded for device m7
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSasTokenRenewalHandler - CBS message authentication succeeded for device m9
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsReceiverLinkHandler - telemetry receiver link with link correlation id 9af92f25-f7a1-44e5-8538-55dab363b9c4 was successfully opened
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - The device session in the multiplexed connection to the IoT Hub has been established for device m7
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Updating device m7 status to new status CONNECTED with reason CONNECTION_OK
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Invoking connection status callbacks with new status details
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSenderLinkHandler - telemetry sender link with link correlation id 9af92f25-f7a1-44e5-8538-55dab363b9c4 was successfully opened
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - The device session in the multiplexed connection to the IoT Hub has been established for device m7
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSenderLinkHandler - telemetry sender link with link correlation id 51dc6fdf-5fc2-49dc-86c6-6906d8f90298 was successfully opened
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSenderLinkHandler - telemetry sender link with link correlation id 51dc6fdf-5fc2-49dc-86c6-6906d8f90298 was closed remotely unexpectedly
[azure-iot-sdk-ReactorRunner] ERROR com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Amqp session closed unexpectedly. notifying the transport layer to start reconnection logic...
[azure-iot-sdk-ReactorRunner] WARN com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Amqp session for device m9 was closed, creating a thread to notify transport layer
com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.AmqpNotFoundException: {"errorCode":404001,"trackingId":"0f7b1672945c46a5b7496ad95d74d752-G:0-TimeStamp:04/22/2021 07:28:48-G:0-TimeStamp:04/22/2021 07:28:48","message":"m9","timestampUtc":"2021-04-22T07:28:48.2104677Z"}
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertFromAmqpException(AmqpsExceptionTranslator.java:62)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onSessionClosedUnexpectedly(AmqpsIotHubConnection.java:721)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionHandler.onLinkClosedUnexpectedly(AmqpsSessionHandler.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSenderLinkHandler.onLinkRemoteClose(AmqpsSenderLinkHandler.java:115)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:26)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsReceiverLinkHandler - telemetry receiver link with link correlation id 51dc6fdf-5fc2-49dc-86c6-6906d8f90298 was successfully opened
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - The device session in the multiplexed connection to the IoT Hub has been lost for device m9
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Mapping exception throwable to COMMUNICATION_ERROR because the sdk was unable to classify the thrown exception to anything other category
com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.AmqpNotFoundException: {"errorCode":404001,"trackingId":"0f7b1672945c46a5b7496ad95d74d752-G:0-TimeStamp:04/22/2021 07:28:48-G:0-TimeStamp:04/22/2021 07:28:48","message":"m9","timestampUtc":"2021-04-22T07:28:48.2104677Z"}
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertFromAmqpException(AmqpsExceptionTranslator.java:62)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onSessionClosedUnexpectedly(AmqpsIotHubConnection.java:721)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionHandler.onLinkClosedUnexpectedly(AmqpsSessionHandler.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSenderLinkHandler.onLinkRemoteClose(AmqpsSenderLinkHandler.java:115)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:26)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] WARN com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Updating device m9 status to new status DISCONNECTED_RETRYING with reason COMMUNICATION_ERROR
com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.AmqpNotFoundException: {"errorCode":404001,"trackingId":"0f7b1672945c46a5b7496ad95d74d752-G:0-TimeStamp:04/22/2021 07:28:48-G:0-TimeStamp:04/22/2021 07:28:48","message":"m9","timestampUtc":"2021-04-22T07:28:48.2104677Z"}
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertFromAmqpException(AmqpsExceptionTranslator.java:62)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onSessionClosedUnexpectedly(AmqpsIotHubConnection.java:721)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionHandler.onLinkClosedUnexpectedly(AmqpsSessionHandler.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSenderLinkHandler.onLinkRemoteClose(AmqpsSenderLinkHandler.java:115)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:26)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Invoking connection status callbacks with new status details
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionHandler - Amqp session closed locally for device m9
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsReceiverLinkHandler - Closing telemetry receiver link with link correlation id 51dc6fdf-5fc2-49dc-86c6-6906d8f90298
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 207 milliseconds
[azure-iot-sdk-ReactorRunner] ERROR com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Amqp transport error occurred, closing the amqps connection
com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.ProtonIOException: bytes left unconsumed
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertFromAmqpException(AmqpsExceptionTranslator.java:84)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onTransportError(AmqpsIotHubConnection.java:506)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:26)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Amqp connection closed locally, shutting down all active sessions...
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Shutting down cbs session...
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSessionHandler - Amqp session closed locally for device m7
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSenderLinkHandler - Closing telemetry sender link with link correlation id 9af92f25-f7a1-44e5-8538-55dab363b9c4
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsReceiverLinkHandler - Closing telemetry receiver link with link correlation id 9af92f25-f7a1-44e5-8538-55dab363b9c4
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsSenderLinkHandler - Closing cbs sender link with link correlation id 3ad66933-6c6d-43fd-b43d-f3c32c3b7560
[azure-iot-sdk-ReactorRunner] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsReceiverLinkHandler - Closing cbs receiver link with link correlation id 1697155a-885e-4b0b-9900-2c4014052a90
[azure-iot-sdk-ReactorRunner] WARN com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Amqp connection was closed, creating a thread to notify transport layer
com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.ProtonIOException: bytes left unconsumed
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertFromAmqpException(AmqpsExceptionTranslator.java:84)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onTransportError(AmqpsIotHubConnection.java:506)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:26)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.io.IOException: Could not open the connection
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:162)
	at com.microsoft.azure.sdk.iot.device.TransportClient.open(TransportClient.java:133)
	at com.kalkitech.test.azure.rcvprops.Main.main(Main.java:26)
Caused by: com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions.ProtonIOException: bytes left unconsumed
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsExceptionTranslator.convertFromAmqpException(AmqpsExceptionTranslator.java:84)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onTransportError(AmqpsIotHubConnection.java:506)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:26)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:1142)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Press Enter to close ...
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 364 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 744 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 1555 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 3200 milliseconds

**[main] INFO com.microsoft.azure.sdk.iot.device.TransportClient - Transport client closed successfully
Press Enter to exit ...**
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 5644 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.RetryDecision - NOTE: A new instance of RetryDecision has been created with retry enabled, the client will retry after 10000 milliseconds
**[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Reconnection was abandoned due to the operation timeout
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection - Shutting down amqp layer...
[azure-iot-sdk-DeviceSessionReconnectionTask:58b01b61-7021-4a6c-962a-9860e1266ad3] DEBUG com.microsoft.azure.sdk.iot.device.transport.IotHubTransport - Client connection closed successfully**

**Comment by timtay-microsoft** [comment]
TransportClient is the deprecated multiplexing client for this SDK, so I'd advise you to switch to the [MultiplexingClient](https://github.com/Azure/azure-iot-sdk-java/blob/767389dd24124d825201602f1499da454bf0fddf/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MultiplexingClient.java#L35) which does not have this same issue from my initial testing.

Here is what your code would look like with the MultiplexingClient instead:

```java
MultiplexingClient multiplexingClient = new MultiplexingClient("your-iot-hub-hostname.azure-devices.net", protocol);

List<DeviceClient> list = new ArrayList<>(10);

for(String cs : args)
{
    DeviceClient client = new DeviceClient(cs, protocol);
    list.add(client);
}

multiplexingClient.registerDeviceClients(list);

try
{
    multiplexingClient.open();
}
catch(Throwable tx)
{
    tx.printStackTrace();
}

System.out.println("Press Enter to close ...");
Scanner scanner = new Scanner(System.in);
scanner.nextLine();

multiplexingClient.close();

System.out.println("Press Enter to exit ...");
scanner.nextLine();
```

**Comment by timtay-microsoft** [comment]
The MultiplexingClient has much better retry logic and error handling as well. For additional details, we have a pretty in-depth sample [here](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/multiplexing-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/MultiplexingSample.java) for your reference

**Comment by sanjay-90210** [comment]
@timtay-microsoft - Thank you

Sorry, I was not aware of the multiplexing client at all. This is good to know, I will try out the new mechanism. I wanted to ask about the registration issue with multiplexed transport as it does not allow device addition/deletion once opened. It also does not give any meaningful exception if one or more devices out of the 100s of multiplexed devices run into an authentication issue. I will try out all the uses cases I have with multiplexed connections and report here.

X.509 authenticated devices, self signed or with CA, does not work with multiplexed transport according to this [document](https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.device.deviceclient.deviceclient?view=azure-java-stable#com_microsoft_azure_sdk_iot_device_DeviceClient_DeviceClient_java_lang_String_com_microsoft_azure_sdk_iot_device_TransportClient_). Is this the same case with the MultiplexingClient too ?

**Comment by timtay-microsoft** [comment]
> X.509 authenticated devices, self signed or with CA, does not work with multiplexed transport according to this document. Is this the same case with the MultiplexingClient too?

Yes, the service itself does not support multiplexing for x509 devices, so both the deprecated TransportClient and current MultiplexingClient have the same limitation

**Comment by timtay-microsoft** [comment]
> I wanted to ask about the registration issue with multiplexed transport as it does not allow device addition/deletion once opened. 

The MultiplexingClient does allow for adding/removing devices from the multiplexed connection at all times, unlike the TransportClient

**Comment by sanjay-90210** [comment]
I have added the multiplex client related issues under the issue [1188](https://github.com/Azure/azure-iot-sdk-java/issues/1188)

**Comment by timtay-microsoft** [comment]
> I have added the multiplex client related issues under the issue 1188

With that in mind, would you object to me closing this thread? Considering the TransportClient is deprecated and has a replacement, I don't have any plans to provide bug fixes to it.

**Comment by sanjay-90210** [comment]
Sure, you can close this issue as this mechanism is deprecated. I also do not have a load of issues with this as the thread exits after a while. I am still using this as the multiplexing client has more issues that this at this time.

**Comment by timtay-microsoft** [comment]
Closing this thread per the above. I'll be working through the issues with the MultiplexingClient to unblock you
