### ISSUE TITLE
IoTHub not updating the DeviceTwin when send events through the device client SDK

### ISSUE THREAD

**Issue by ruwan-jayaweera** [Azure/azure-iot-sdk-java#119]
- **OS and version used:** CentOS 7

- **Java runtime used:** jdk1.8.0_121

- **SDK version used:** 

1. Azure Device SDK to send events to IoTHub

```
<dependency>
       <groupId>com.microsoft.azure.iothub-java-client</groupId>
       <artifactId>iothub-java-device-client</artifactId>
       <version>1.0.11</version>
</dependency>
```

2. Azure Service SDK to retrieve the DeviceTwin

```
<dependency>
	<groupId>com.microsoft.azure.sdk.iot</groupId>
	<artifactId>iot-service-client</artifactId>
	<version>1.5.22</version>
</dependency>
```

# Description of the issue:
Hi Team,

We are facing an issue of IoTHub not updating the device twin when send events through the device client SDK.

# Code sample exhibiting the issue:
We are using the following code to send events to the iothub using the device SDK.

```
public void updateDeviceState(String deviceId, String msg, boolean isPeriodic, DeviceClient connectedDeviceClient) {
        try {
            connectedDeviceClient.open();
        } catch (IOException e) {
            logger.error("Error while opening the client ", e);
            throw new RuntimeException("Could not open the client");
        }
        logger.info("Sending data to device {}. Data {}", deviceId, msg);
        connectedDeviceClient
                .sendEventAsync(new Message(msg), (IotHubStatusCode responseStatus, Object callbackContext) -> {
                    if (IotHubStatusCode.OK_EMPTY != responseStatus) {
                        logger.warn("Could not send the message {} for device {}", msg, deviceId);
                    } else {
                        logger.info("Message Delivered Status : {}", responseStatus);
                    }
                }, null);
}
```
But when we retrieve the Twin (using the following code), the values that we send using the device client SDK are not reflected in the Twin.

```
	final String iotHubConnectionString = IotHubUtil.getIotHubConnectionString(azureConfigurationManager);
        final IotHubConnectionString connectionString = IotHubConnectionStringBuilder.createConnectionString(iotHubConnectionString);
		
	URL url = null;
	if(Tools.isNullOrEmpty(deviceId).booleanValue()) {
            throw new IllegalArgumentException("device name cannot be empty or null");
        } else {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.append("https://");
            stringBuilder.append(this.hostName);
            stringBuilder.append("/");
            stringBuilder.append("twins");
            stringBuilder.append("/");
            stringBuilder.append(deviceId);
            stringBuilder.append("?");
            stringBuilder.append("api-version=2016-11-14");
            url = new URL(stringBuilder.toString());
        }	

        HttpResponse response = null;
        try {
            response = DeviceOperations.request(connectionString, url, HttpMethod.GET, new byte[0], String.valueOf(UUID.randomUUID()), USE_DEFAULT_TIMEOUT);
        } catch (com.microsoft.azure.sdk.iot.service.exceptions.IotHubException e) {
            throw new PlatformDelegateException(ErrorCode.PLATFORM_DELEGATE_ERROR_AZURE_TWIN_RETRIEVAL, String.format("Could not retrieve device twin data for device : %S", deviceId));
        }
```

Doesn't the IoTHub update the Device Twin with the latest received event values?

**Comment by prmathur-microsoft** [comment]
Device twin communication works as follows : 
Device client - 
1. Subscribe to Desired properties
2. Send reported properties.
Please follow sample from here to under the API and its usage.
https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java


Service Client : 
1. Get Twin Document
2. Update Desired Properties
3. Update tags
4. Schedule Jobs

Sample explaining these API is located here - 
https://github.com/Azure/azure-iot-sdk-java/tree/master/service/iot-service-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot

Please let me know if the above does not answer your question.

**Comment by ruwan-jayaweera** [comment]
Thank you for your response.

I understand that I can write to DeviceTwin from the device-sdk and read from DeviceTwin through the service-sdk. 

But I want the iot-hub to call-back/push messages & read all devices messages in one stream. So I use the built-in endpoint -"Events" (messages/events) to access the device-to-cloud messages. I access the Event Hub-compatible endpoint of 'messages/events' using the [azure-event-hubs-java](https://github.com/Azure/azure-event-hubs-java/tree/dev/azure-eventhubs-eph) in order to process messages.

Is there a way to read the updates to the DeviceTwin in a stream (without polling)? Is there a way to be notified when the DeviceTwin is updated (in order to read the twin)?

**Comment by olivierbloch** [comment]
Hi @ruwan-jayaweera 
In order to be "notified" of device Twin reported properties changes in the back end is to leverage the routing feature of IoT Hub. This is described in [this article](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#back-end-operations).

**Comment by prmathur-microsoft** [comment]
@ruwan-jayaweera - please let us know if the above resolves your issue.

**Comment by ruwan-jayaweera** [comment]
No this didn't help. This would only notify when a single device twin is updated.

I want to send telemetry using device-to-cloud messages. And retrieve these using the service-facing endpoint (messages/events) with the help of event-hub SDK in my solution back end. I also want the device twin to reflect these latest telemetry so that my solution can display the latest telemetry values.

According to [Device-to-cloud communications guidance](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-d2c-guidance) this does not automatically happen. 

Is my understanding correct?

**Comment by olivierbloch** [comment]
Hi @ruwan-jayaweera , your understanding is correct. D2C messages and Twins properties are 2 different things. Twins is not designed to be used for high throughput telemetry, but rather for state and configuration type of information. There is no notion of history for twins and typically if you don't read a reported property updated by a device before it is updated again, you lose the first update.
Furthermore the throttling limits are different for D2C and Twins (see [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling)).
It seems what you are trying to do is use Twins as your sole reference for both device status/configuration and telemetry info. If your "telemetry" info frequency is low to the point it fits in the throttling limits of Twins udpates, then you can certainly use only Twins. If that's not the case, then you will have to use a combination of Twins and D2C messages and reconcile the data in your back end.

**Comment by prmathur-microsoft** [comment]
@ruwan-jayaweera - please let us know if you have any further questions.

**Comment by prmathur-microsoft** [comment]
Closing this for now. Feel free to reopen if you see any further issues.
