### ISSUE TITLE
HTTPS protocol is not working in Android with Java Device Client SDK

### ISSUE THREAD

**Issue by AnnapoorniS** [Azure/azure-iot-sdk-java#120]
Hi,
Trying with the latest java device client SDK 1.3.31 in android, couldn't send even a single message with HTTPS protocol. Previous SDKs works for HTTPS protocol, this overflows with Exception from the sendEventAsync(). It is a breaking change.

- **OS and version used:** <VERSION> Android 7.1 

- **Java runtime used:** <VERSION>  JDK "1.8.0_45"

- **SDK version used:** <VERSION>  IoT Device Client 1.3.31 for Java 

# Description of the issue:
I/System.out: {"deviceId":"Sample","messageId":0,"temperature":20.83712863792431,"humidity"47.23667818960061}
W/art: Unresolved exception class when finding catch block: javax.naming.SizeLimitExceededException
W/art: Unresolved exception class when finding catch block: javax.naming.SizeLimitExceededException
W/art: Unresolved exception class when finding catch block: javax.naming.SizeLimitExceededException
W/art: Unresolved exception class when finding catch block: javax.naming.SizeLimitExceededException

# Code sample exhibiting the issue:
While debugging I found the the exception occurring here. Kindly fix this with high priority as it breaks the previously working functionality.
![image](https://user-images.githubusercontent.com/22465018/28402161-007612da-6d3c-11e7-94e8-74fe4840c776.png)

# Console log of the issue:
![image](https://user-images.githubusercontent.com/22465018/28402174-10cbeaba-6d3c-11e7-9d96-bcd8885d0bee.png)
![image](https://user-images.githubusercontent.com/22465018/28402196-311eb144-6d3c-11e7-9986-e7ce2d7c0cc7.png)

**Comment by prmathur-microsoft** [comment]
Thanks for filing this issue. We are working to fix this.

**Comment by mamokarz** [comment]
I'll take a look.

**Comment by anhashia** [comment]
https://github.com/Azure/azure-iot-sdk-java/commit/87d2c65c67ae7e1c3e5e2e6efce497853aa20b47

**Comment by anhashia** [comment]
Fix released in device SDK version **1.3.33**. Closing the issue. Please re-open it if you run into any issues.
