### ISSUE TITLE
[BUG Report]Aure IOT Hub throws the SAS Token expired even though the connection String is valid 

### ISSUE THREAD

**Issue by nitikamehta** [Azure/azure-iot-sdk-java#1212]
IOT SDK Version : <groupId>com.microsoft.azure.sdk.iot</groupId>
			<artifactId>iot-device-client</artifactId>
			<version>1.30.1</version>
Repro Steps 
1. Create a device Client with the expired SAS Token connection string .
2. It will throw the SAS token expired exception.
3. Now create a device client with a new connection String which is valid .
Actual : IT still throws the SAS expired Token Exception 
Expected : the Device client should be created as the connectionString is valid and not expired .

**Comment by timtay-microsoft** [comment]
Can you provide some sample code that demonstrates this issue? And can you share the format of what your connection strings look like?

**Comment by nitikamehta** [comment]
This is the exception we are getting 
java.lang.SecurityException: Your SAS Token has expired
and the application runs fine if we provide a valid connection string .
the issue gets resolved once I restart the application and provide a valid connection string .
So the Repro steps is 
once the device client sets up with the expired connection string it does not get created even though after we provide a valid connection string and issue only get resolved once we restart our application
the sample code we are using for the same is below 
public DeviceClient createDeviceClient() throws URISyntaxException {
		return new DeviceClient(connString, protocol);

	}
connString = "HostName=" + endpoint.getConfig().get("Path") + ";DeviceId="
					+ endpoint.getConfig().get("UserName") + ";SharedAccessSignature="
					+ endpoint.getConfig().get("Password");
			protocol = IotHubClientProtocol.AMQPS_WS;

			try {
				if (client == null) {
					setClient(createDeviceClient());
				}
				client.open();

				Map<String, String> hb = new HashMap<>();
				SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
				String time = format.format(Calendar.getInstance().getTime());
				hb.put("SystemTime", time);
				String json = new Gson().toJson(hb);
				message = new Message(json);
				message.setProperty("ObjectType", "HeartbeatRequest");
				message.setProperty("ObjectVersion", "1");
				if (endpoint.getUsername() != null) {
					message.setProperty("SystemGuid", endpoint.getUsername());
					message.setProperty("From", endpoint.getUsername());
				}
				message.setProperty("EventId", UUID.randomUUID().toString());
				message.setProperty("MessageContentType", "application/json");
				message.setMessageId(UUID.randomUUID().toString());
			} catch (Exception e) {
				LOG.error(e.getMessage());
				throw new ThirdPartyIntegrationException("IOT Hub connection Issue:"+e.getMessage());
			}
and the connection string we are using is something like this :
    "Path": "<tenantName>.azure-devices.net",
         "UserName": "<SystemGuid>>",
          "Password": "SharedAccessSignature sr=<<tenantName>>%2fdevices%<<systemGuid>>&sig=<<signature>>d&se=<<expiryDate>>&&skn=iothubowner",

**Comment by timtay-microsoft** [comment]
The above repro code doesn't exactly show how you are encountering this error, so I wrote up what I believe you are doing. 

```java
public static void main(String[] args)
    throws IOException, URISyntaxException
{
    IotHubClientProtocol protocol = IotHubClientProtocol.AMQPS;
    String hostname = "<your hub name>.azure-devices.net";
    String deviceId = "<your device Id>";
    String deviceKey = "<your device key>";

    DeviceClient client = null;

    try
    {
        // Create a client with an expired connection string, it throws immediately as expected
        String expiredConnectionString = createConnectionString(hostname, deviceId, deviceKey, true);
        client = new DeviceClient(expiredConnectionString, protocol);
    }
    catch (SecurityException e)
    {
        System.out.println("SAS token was expired, as expected");
    }

    // Create a new client with a non-expired connection string
    String validConnectionString = createConnectionString(hostname, deviceId, deviceKey, false);
    client = new DeviceClient(deviceKey, protocol); // doesn't throw a SecurityException complaining about SAS token expired
}

public static String createConnectionString(String hostname, String deviceId, String deviceKey, boolean expired)
{
    int timeToLiveSeconds = 120;
    if (expired)
    {
        timeToLiveSeconds *= -1;
    }
    
    //Sample code for SasTokenHelper can be found here, if you are interested
    // https://github.com/Azure/azure-iot-sdk-java/blob/a162b28016c8e7aeddf7df0518c33dbe94f9005a/device/iot-device-samples/custom-sas-token-provider-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/CustomSasTokenProviderSample.java#L36
    String sharedAccessToken = new String(new SasTokenHelper(hostname, deviceId, deviceKey, timeToLiveSeconds).getValue());
    return "HostName=" + hostname + ";DeviceId=" + deviceId + ";SharedAccessSignature=" + sharedAccessToken;
}
```

When I run the above code, I don't see anything wrong with constructing a device client with a valid connection string, even if I previously created a client with an expired connection string. Am I doing something differently from you, though?

**Comment by timtay-microsoft** [comment]
Also, in general, if you want to control which SAS tokens are used by the SDK like it appears you do, the DeviceClient has a constructor that takes in a SasTokenProvider interface which is much more flexible than the constructor you are currently using. I recommend checking out [this sample](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/custom-sas-token-provider-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/CustomSasTokenProviderSample.java) if you are curious

The current constructor that you are using does not allow you to provide another SAS token once your previous SAS token has expired, but the SasTokenProvider constructor does. That allows you to reuse a single device client for a longer period of time

**Comment by timtay-microsoft** [comment]
@nitikamehta are you still running into any issues here?

**Comment by nitikamehta** [comment]
Hi @timtay-microsoft ,
Another observation that i found :
issue is that its not happening on the version 1.29.1 and its there only on version 1.30 and later.
Is it by design and do i need to change the constructor only

**Comment by nitikamehta** [comment]
I am actually not using the SAS Token Helper but i am creating the device client as 
String connString = "HostName=" + endpoint.getConfig().get("Path") + ";DeviceId="
+ endpoint.getConfig().get("UserName") + ";SharedAccessSignature="
+ endpoint.getConfig().get("Password");
protocol = IotHubClientProtocol.AMQPS_WS;
new DeviceClient(connString, protocol);
this Device client throws SAS Token expired Exception

**Comment by nitikamehta** [comment]
The issue is Resolved it was some error on our side . Thanks for your support
