### ISSUE TITLE
Q: How do you "nest" reported properties like you can in the Node SDK?

### ISSUE THREAD

**Issue by rvplauborg** [Azure/azure-iot-sdk-java#122]
- **OS and version used:** Windows 10 

- **Java runtime used:** 1.8 

- **SDK version used:** 1.3.31 

# Description of the issue:
I seem to have a problem with reporting properties. I am using the Azure Remote Monitoring solution, but in that solution, to show i.e. Manufacturer in the Device page correctly, it must be on the form `System.Manufacturer` which then corresponds to some value.

I cannot add a key `System.Manufacturer` to a Property, as the SDK states "Key cannot contain illegal unicode control characters". I have tried nesting the properties, but this does not result in what I want, more like `System.key.value.Manufacturer` or the like. I also tried to send the property with key `System`, with a JSON object as a value which then consisted of a key `Manufacturer` and a value. Not working either.

What am I to do here? How do you "nest" property key names. In the Node.js SDK you simply just fire JSON away, so there I could just have 
```
"System": {
    "Manufacturer": "MIA"
}
```

And it would result in my dashboard getting the `System.Manufacturer` property.

edited: Added actual SDK version number, and grammar.

**Comment by prmathur-microsoft** [comment]
Currently java SDK does not support nested tags and it is in our backlog to address this issue.

**Comment by rvplauborg** [comment]
@prmathur-microsoft Are there news on this? Is it possible to nest somewhat now?

**Comment by prmathur-microsoft** [comment]
We are working to resolve this issue. This should be in master soon eta 10/20

**Comment by prmathur-microsoft** [comment]
This issue has now been resolved and fixed on latest package. Please give it a try and feel free to reopen if you see further issues.

**Comment by rvplauborg** [comment]
@prmathur-microsoft How do you then actually report a nested property? It would of course be the easiest if the SDK supported using "." in Property keys, but I can tell that it doesn't. 

If I want to report "Device.Sensor.Sensor_X" with a given value as a property - how can I?

**Comment by prmathur-microsoft** [comment]
You are right. We currently have this supported on our service client but we need to take care of it on device client as well. I have reopened it and will let you know when it is fixed.

**Comment by mamokarz** [comment]
Hi @rvplauborg,

All properties in the Twin are pairs key value, where the key is a `String` and the value is an `Object`. To access a nested property, you just need to cast the value as another `Map<String, Object>` and use it.

```java
private Map<String, Object> getNestedProperties(Property myProperty)
{
    Map<String, Object> receivedNestedProperty = null;
    if(myProperty.getValue() instanceof Map)
    {
        Map<String, Object> receivedNestedProperty = (Map<String, Object>)myProperty.getValue();
    }
    return receivedNestedProperty;
}
```

On the other hand, you can set a nested property by creating a `Map` and use it as a property value. For example, image that you have a Device called `homeKit` and you want to set a nested property `Manufacturer` with the content `MIA` on the `System` property, you can use the following code:

```java
    Map<String, Object> myNestedProperty = new HashMap<String, Object>()
    {
        {
            put("Manufacturer", "MIA");
        }
    };
    Property myProperty = new Property("System", myNestedProperty);
    homeKit.setReportedProp(myProperty);
```

**Comment by prmathur-microsoft** [comment]
@rvplauborg - Does the above comment from @mamokarz  resolve your issue? Let us know if you have any other concerns.

**Comment by rvplauborg** [comment]
Hi

It is not relevant for the time being, as I do not work with this anymore.
But if I do again I will use the help given. Thanks.

Best regards

Den 23. jan. 2018 20.38 skrev "prmathur" <notifications@github.com>:

**Comment by prmathur-microsoft** [comment]
Good to know. Closing this for now. Feel free to reopen if you see further issues.
