### ISSUE TITLE
Twin metada is inconsistent

### ISSUE THREAD

**Issue by stien-slalom** [Azure/azure-iot-sdk-java#1223]
- OS and version used: macOS 10.15.7

- Java runtime used: Java 11 (Kotlin 1.4)

- SDK version used: 1.30.0

**Steps to reproduce the issue:**

Create properties and delete properties a couple of times caused the twin in an inconsistent state that specifically complaining about $lastUpdatedByDigest and $lastUpdatedVersion.

After couple create and delete properties couple of times, get deviceTwin throw `java.lang.IllegalArgumentException: Twin metadata is inconsistent`.

DeviceTwin.getTwin() --> 
` 
detailMessage = "Twin metadata is inconsistent"
 cause = {IllegalArgumentException@20757} "java.lang.IllegalArgumentException: Twin metadata is inconsistent"
 stackTrace = {StackTraceElement[16]@20761} 
  0 = {StackTraceElement@20766} "com.microsoft.azure.sdk.iot.deps.twin.TwinCollection.addMetadata(TwinCollection.java:404)"
  1 = {StackTraceElement@20767} "com.microsoft.azure.sdk.iot.deps.twin.TwinCollection.addMetadata(TwinCollection.java:415)"
  2 = {StackTraceElement@20768} "com.microsoft.azure.sdk.iot.deps.twin.TwinCollection.createFromRawCollection(TwinCollection.java:377)"
  3 = {StackTraceElement@20769} "com.microsoft.azure.sdk.iot.deps.twin.TwinProperties.<init>(TwinProperties.java:134)"
  4 = {StackTraceElement@20770} "com.microsoft.azure.sdk.iot.deps.twin.TwinState.createFromTwinJson(TwinState.java:326)"
  5 = {StackTraceElement@20771} "com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwin.getTwinOperation(DeviceTwin.java:227)"
  6 = {StackTraceElement@20772} "com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwin.getTwin(DeviceTwin.java:208)"
  7 = {StackTraceElement@20773} "device.client.impl.IotHubClientImpl$getDeviceTwinInformation$2.invokeSuspend(IotHubClientImpl.kt:75)"
  8 = {StackTraceElement@20774} "device.client.impl.IotHubClientImpl$getDeviceTwinInformation$2.invoke(IotHubClientImpl.kt)"
  9 = {StackTraceElement@20775} "device.client.impl.IotHubClientImpl$iotHubOperation$2.invokeSuspend(IotHubClientImpl.kt:311)"
  10 = {StackTraceElement@20776} "kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)"
  11 = {StackTraceElement@20777} "kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)"
  12 = {StackTraceElement@20778} "kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)"
  13 = {StackTraceElement@20779} "kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)"
  14 = {StackTraceElement@20780} "kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)"
  15 = {StackTraceElement@20781} "kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)"
`

**Example device twin:**
`
"properties": {
    "desired": {
        "dataTop": {
            "field1": "",
            "field2": ""
        },
        "$metadata": {
            "dataTop": {
                ...
                "field1": {
                    "$lastUpdatedVersion": 1,
                    "$lastUpdatedByDigest": "123456123456123456"
                }
            }
        }
    }
}
`

The problem is that the desired property was deleted, but desired properties $metadata still exists with $lastUpdatedByDigest and $lastUpdatedVersion.

**Comment by bikamani** [comment]
@stien-slalom Thanks for filing a github issue. 

Could you specify order of operations are you following? Is it a consistent failure?

**Comment by stien-slalom** [comment]
@bikamani  This is the flow to reproduce the `Twin metada is inconsistent`. It is a consistent failure.
- Create the device twin
- Update desired property
- Update desired property
- Get twin for device

**Comment by bikamani** [comment]
@stien-slalom Could you try with upgrading client versions to latest? We recently released some changes which adds support for Twin metadata, link: https://github.com/Azure/azure-iot-sdk-java/releases/tag/2021-05-24.

**Comment by stien-slalom** [comment]
@bikamani I've updated to version `1.31.0` and it addressed the issue. Thanks for the quick response and fix!

**Comment by bikamani** [comment]
@stien-slalom Thanks for letting us know.
