### ISSUE TITLE
Several job (JobResult) dates incorrect

### ISSUE THREAD

**Issue by mwm-twx** [Azure/azure-iot-sdk-java#123]
- **OS and version used:** Linux (Fedora 26)
- **Java runtime used:** Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
- **SDK version used:** (Service SDK) 1.6.23

# Description of the issue:
Querying a job through the JobClient returns a JobResult with dates that are nonsensical (created date is after start and end dates).

`iothub-explorer` view:
```
createdTime:  2017-07-21T15:47:17.8802362Z
startTime:    2017-07-21T15:47:17.0594Z
endTime:      2017-07-21T15:47:25.4144865Z
```

`JobResult` view:
```
createdTime:  Fri Jul 21 18:13:59 GMT 2017
startTime:    Fri Jul 21 15:47:17 GMT 2017
endTime:      Fri Jul 21 16:56:29 GMT 2017
```

As seen in the different views, the start-time is correct and the other two are not.  The other two dates have seven digits of sub-second precision, which is the underlying cause of this issue.

The `JobResponseParser` uses a `SimpleDateFormatter` with format `yyyy-MM-dd'T'HH:mm:ss.SSSS'Z'`.  As detailed in the javadocs, the number of pattern characters used for a numeric type only matters on parsing for consecutive fields.  Since that's not the case here, all seven digits are interpreted as milliseconds and throw the resulting date off by a minutes to hours.

**Comment by mamokarz** [comment]
@mwm-twx thank you to report this issue, I'm investigating it.

**Comment by prmathur-microsoft** [comment]
A maven package with the fix for this is released. Please give it a try and let us know if it does not resolve your issue. Also feel free to reopen in such case
