### ISSUE TITLE
[QUERY] How to get SSLContextBuilder class to construct a DeviceClient using x509 auth

### ISSUE THREAD

**Issue by sesu-bio** [Azure/azure-iot-sdk-java#1234]
**Query/Question**
We are currently using the deprecated DeviceClient constructor with the following signature:
`DeviceClient(String connString, IotHubClientProtocol protocol, String publicKeyCertificate, boolean isCertificatePath, String privateKey, boolean isPrivateKeyPath) throws URISyntaxException`
The deprecation warning references a [sample implementation](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/send-event-x509/src/main/java/samples/com/microsoft/azure/sdk/iot/SendEventX509.java) which uses the [SSLContextBuilder](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/send-event-x509/src/main/java/samples/com/microsoft/azure/sdk/iot/SSLContextBuilder.java) helper class. It seems wrong to just copy the helper class for several reasons:
- it would not be detected by our vulerability and license compliance tools
- no version management via Maven, especially bad because the class contains certificates

What is the intended way to use the non-deprecated constructor? Are the users supposed to copy the helper class?

**Setup (please complete the following information if applicable):**
 - Version of the Library used: iot-device-client 1.26.0
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Query Added
- [x ] Setup information Added

**Comment by timtay-microsoft** [comment]
Hi @sesu-bio, the SSLContextBuilder class is sample code, but it does work fine if you want to copy it as is. There are many ways for you to build and SSLContext, and the SSLContextBuilder sample is just one of the ways. The only important thing to keep in mind is that the SSLContext that you construct will need to trust the IoT Hub service's public certificate. The SSLContextBuilder has that certificate for your reference.

Do you need any other help here?

**Comment by sesu-bio** [comment]
Hi @timtay-microsoft, this answers my question. Thanks!

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
