### ISSUE TITLE
JobClient.cancelJob makes invalid backend request

### ISSUE THREAD

**Issue by mwm-twx** [Azure/azure-iot-sdk-java#124]
- **OS and version used:** Linux (Fedora 26)
- **Java runtime used:** Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
- **SDK version used:** (Service SDK) 1.6.23

# Description of the issue:
Calling `JobClient.cancelJob` causes an `IotHubException` with the following message:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Length Required</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Length Required</h2>
<hr><p>HTTP Error 411. The request must be chunked or have a content length.</p>
</BODY></HTML>
```

Stacktrace:
```
at com.microsoft.azure.sdk.iot.service.exceptions.IotHubExceptionManager.httpResponseVerification(IotHubExceptionManager.java:112)
at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceOperations.request(DeviceOperations.java:137)
at com.microsoft.azure.sdk.iot.service.jobs.JobClient.cancelJob(JobClient.java:273)
...
```

# Code sample exhibiting the issue:
Any `JobClient.cancelJob` call; regardless of whether the job ID is valid.

**Comment by prmathur-microsoft** [comment]
We are aware of this issue and it is fixed on latest master. @789bf2c44a0a62ad8f398f24a3ee4329798b60aa
Please retry with latest master to see if it resolves your issue.

**Comment by mwm-twx** [comment]
I tried on current master (ab9c0507ba386beb9dd39454264385391422c7b2) and I don't see the issue anymore.  Thanks!
