### ISSUE TITLE
Unable to connect multiple devices via MQTT protocol.

### ISSUE THREAD

**Issue by darrickc** [Azure/azure-iot-sdk-java#125]
- **OS and version used:** <Ubuntu 16.04> 

- **Java runtime used:** <1.8> 

- **SDK version used:** <1.3.31> 

# Description of the issue:
When trying to connect multiple devices in the same application every other device fails with a disconnect and an exception. I'm trying to write a multithreaded simulator to simulate thousands of devices connecting and sending data simultaneously. Is this possible?

> java.io.IOException: Unable to subscribe to topic :devices/sim_3/messages/devicebound/# because java.io.EOFExceptionConnection lost
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:140)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.open(MqttTransport.java:83)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:212)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:197)
	at com.company.Main.lambda$main$0(Main.java:49)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.company.Main.main(Main.java:45)

# Code sample exhibiting the issue:

        IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
        List<String> conns = new ArrayList<>();
        conns.add("MY CONNECTION STRING"); //10 TIMES
        conns.forEach((newConnString) -> {
            try {
                DeviceClient client = new DeviceClient(newConnString, protocol);

                client.open();
                System.out.println("connected - "+newConnString);

            } catch (Exception e) {
                e.printStackTrace();
            }
        });

    }

**Comment by darrickc** [comment]
Looking at the code - specifically Mqtt.java it looks like it does not:
`private static MqttConnectionInfo info ;`

Can anyone confirm my hypothesis?

**Comment by anhashia** [comment]
Hi @darrickc 

MQTT protocol **doesn't** support multiplexing. Please use different device connection string  for each connection.
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-protocols (provides information on choice of protocol).

You will be able to multiplex using AMQP protocol on D2C side but on C2D side, the Azure IoT Hub will have issue in identifying the right device for which you planned to send the command. So it should be **avoided**.

For **automation** testing or simulation, please follow following code for reference
https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-tests/src/test/java/tests/integration/com/microsoft/azure/sdk/iot/device/iothubservices/SendMessagesIT.java

**Comment by anhashia** [comment]
Hi @darrickc
I just tested on my local setup. Even with **different** device connection string in the same application, there does seem to be some issue with MQTT protocol. It looks like there is limitation of 1 device connection per application for MQTT. It needs to be further investigated.

**Comment by prmathur-microsoft** [comment]
@darrickc  - you are right about the hypothesis. private static MqttConnectionInfo info ; is the culprit line of code. We will work on resolving this issue.

**Comment by prmathur-microsoft** [comment]
Fix for this issue is checked in. Please feel free to reopen if this does not fix your issue.
