### ISSUE TITLE
null serialization value

### ISSUE THREAD

**Issue by MikalaiSavenka** [Azure/azure-iot-sdk-java#1254]
Issue on line: https://github.com/Azure/azure-iot-sdk-java/blob/1ee51d807da156bf035d048cebd87b84ff6d0fe4/device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/PnpConvention.java#L67

gson.toJson(telemetryPairs) returns null because telemetryPairs is anonymous class created on line https://github.com/Azure/azure-iot-sdk-java/blob/1ee51d807da156bf035d048cebd87b84ff6d0fe4/device/iot-device-samples/pnp-device-sample/temperature-controller-device-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/device/PnpConvention.java#L54 and Gson cannot serialize it correctly

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
