### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by Pllvcn83** [Azure/azure-iot-sdk-java#127]
•OS and version used: Windows 7 

•Java runtime used: JSE 1.8

•SDK version used: iot-device-client-1.3.29-with-deps.jar

# Description of the issue:
This is the copy of defect 107 of Beppuc86

I'm using the DeviceClient to send an uploadToBlobAsync request. Every time i call that api, the response is 11 error, and the following log.

I've looked at the code, and I can't understand how can I do like suggested, because in the class FileUploadResponseParser is not exposed the GsonBuilder.

# Code sample exhibiting the issue:
client.uploadToBlobAsync(file.getName(), new FileInputStream(file), file.length(), callback,
                    callbackContext);

# Console log of the issue:
File upload failed to upload the stream to the blob. java.lang.IllegalArgumentException: Malformed json:java.lang.RuntimeException: Unable to invoke no-args constructor for class com.microsoft.azure.sdk.iot.deps.serializer.FileUploadResponseParser. Register an InstanceCreator with Gson for this type may fix this problem.

**I **resolved the issue adding a costructor into the class: FileUploadResponseParser****

like this

    public FileUploadResponseParser() {
    	this.hostName = "";
        this.containerName = "";
        this.correlationId = "";
        this.blobName = "";
        this.sasToken = "";
   
	}

If you think the fix is valid can you insert this costructor in the next release.

**Comment by prmathur-microsoft** [comment]
@Pllvcn83  - Github does not show any question related to this thread. Do you intend to post one ?

**Comment by prmathur-microsoft** [comment]
@Pllvcn83 Do you wish to provide an PR for this issue ?

**Comment by prmathur-microsoft** [comment]
A fix has been checked in for this issue @195513340d52f3d36fa7b3dd494fe8e1278a95c3
Please try it from our master branch and let us know if this fixes it.

**Comment by prmathur-microsoft** [comment]
Maven package with the fix has been released. Closing this issue. Please feel free to reopen if you have any other concerns.
