### ISSUE TITLE
Will Message 

### ISSUE THREAD

**Issue by willin** [Azure/azure-iot-sdk-java#128]
- **OS and version used:** <VERSION>  Android

- **Java runtime used:** <VERSION>  Android SDK

- **SDK version used:** <VERSION>  latest

# Description of the issue:

how to send mqtt Last Will / Testament message to specific route?

ref: Azure/azure-event-hubs-node#31

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by mastermanu** [comment]
Hi @willin,

We currently do not support a Last Will / Testament for the MQTT Protocol.

May I ask what the scenario / customer requirement here is?

**Comment by prmathur-microsoft** [comment]
@willin - can you please provide your scenario so that we can help you better.

**Comment by prmathur-microsoft** [comment]
Closing this as I have not received any response in a while. Feel free to reopen if you have any further questions.
