### ISSUE TITLE
Device Twins mash-up with concurrent updates

### ISSUE THREAD

**Issue by nzhechev-bosch** [Azure/azure-iot-sdk-java#129]
I'm using iot-device-client:1.3.32, jdk 1.8.0_65. 

When I have two devices, which report properties concurrently, more often than not the properties get mangled - e.g. one twin has no properties and the other has the properties from both devices.

Following is a code snippet illustrating the issue ([full source](https://github.com/Azure/azure-iot-sdk-java/files/1189837/device-twins-test.zip)):

    ExecutorService executor = Executors.newFixedThreadPool(2);

    RegistryManager manager = RegistryManager.createFromConnectionString(CONNECTION_STRING);

    Device deviceA = addDevice(manager, DEVICE_A_ID);
    Device deviceB = addDevice(manager, DEVICE_B_ID);

    CountDownLatch latch = new CountDownLatch(4);
    executor.execute(() -> {
      updateTwin(deviceA, Collections.singleton(new Property("A", 1)), latch);
    });

    executor.execute(() -> {
      updateTwin(deviceB, Collections.singleton(new Property("B", 2)), latch);
    });

    latch.await(5, TimeUnit.SECONDS); // wait for 4 IotHubStatuses

    executor.shutdown();    

After this the expected outcome is for `device-A` twin to have property `A` and `device-B` twin - property `B`, but what happens is that one device twin contains both properties and the other twin is empty.

When device twin updates are done sequentially instead of through executor service, e.g.

  updateTwin(deviceA, Collections.singleton(new Property("A", 1)), latch);
  updateTwin(deviceB, Collections.singleton(new Property("B", 2)), latch);

the behavior is as expected -  `device-A` twin has property `A` and `device-B` - property `B`. The issue manifests itself only with concurrent updates.

**Comment by prmathur-microsoft** [comment]
Very interesting to see such issue.  We have guarded for multi threading support on device twin and have it tested ever now and then and yet we never saw this issue. I'll investigate further to see if I can repro this at my side.

**Comment by nzhechev-bosch** [comment]
I guess this was related to #125, because with iot-device-client:1.4.33 it is now working correctly.
