### ISSUE TITLE
[java] send-receive-sample does not work with amqps

### ISSUE THREAD

**Issue by tameraw** [Azure/azure-iot-sdk-java#13]
_From @gemehendrix on December 22, 2016 16:5_

I've been trying to incorporate the azure iot device client java library into a piece of software I'm writing. It appears HTTPS is working ok but AMQPS and MQTT are not. I have tried the tokens I'm using with a simple C# program and it works fine.

I then tried using the sample applications provided to see if this was something I was doing. It appears the sample applications exhibit the same problem.

I tried running the 'sample-receive-sample' with AMQPS and get the follow errors in my output...

    Starting...
    Beginning setup.
    Successfully read input parameters.
    Using communication protocol AMQPS.
    Successfully created an IoT Hub client.
    Successfully set message callback.
    Opened connection to IoT Hub.
    Beginning to receive messages...
    Sending the following event messages:
    Updated token expiry time to 2400
    Event Message 0
    Press any key to exit...
    Lost connection to the server. Reconnection attempt 1...
    Lost connection to the server. Reconnection attempt 2...
    IoT Hub responded to message 0 with status MESSAGE_EXPIRED
    Lost connection to the server. Reconnection attempt 3...
    Lost connection to the server. Reconnection attempt 4...
    Lost connection to the server. Reconnection attempt 5...
    Lost connection to the server. Reconnection attempt 6...
    Lost connection to the server. Reconnection attempt 7...
    Lost connection to the server. Reconnection attempt 8...
    Lost connection to the server. Reconnection attempt 9...
    Lost connection to the server. Reconnection attempt 10...

Note the reconnection attempts. This is the same message I get in my own application. MQTT is different. I just don't get any responses. As I mentioned before, it's ok with HTTPS.

I have ruled out token and firewall issues by creating a separate C# program with the same parameters.

Please note, I am using a connection string in the following format...

    HostName=<hostName>;DeviceId=<deviceId>;SharedAccessSignature=<SharedAccessSignature>

Update: this works if I use a SASToken created from the device key. This problem only occurs when I use a SAS token created from the server key.

_Copied from original issue: Azure/azure-iot-sdks#1032_

**Comment by tameraw** [comment]
_From @prmathur-microsoft on January 5, 2017 22:47_

Can you please explain what does it mean by creating SAS Token from server key ? 
Azure IOT SDK for java currently only supports the following : 
1. Use device key in the connection string
2. Use SAS token in the connection string
Both of the above can be created using device explorer.
Please let me know more details about how you are creating SAS tokens to help me help you better.

**Comment by tameraw** [comment]
_From @olivierbloch on January 10, 2017 18:11_

Hi @gemehendrix 
If by "Creating SAS Token from server key" you mean using one of the IoT Hub policies shared access keys (such as iothubowner), then you should NOT use this key to provision the device client. You should only use device id/key pair or SASToken generated from these to connect a device client.
This doesn't answer why you are seeing this difference in behavior when switching protocols, but can you please confirm that you are NOT seeing the issue when using a SASToken generated with a DeviceID/Key pair?

**Comment by tameraw** [comment]
_From @anhashia on January 10, 2017 23:50_

Investigating !

**Comment by anhashia** [comment]
Hi @gemehendrix

If you use Azure IoT SDK ( including Send and Receiver Sample), it should abstract all the SAS token generation details, You will just specify connection string in following format in send receive sample provided in the SDK.

``
HostName=<iothub_host_name>;DeviceId=<device_id>;SharedAccessKey=<device_key>
``

For AMQP connection (if using **SASL PLAIN**), you would need username and password.

Security tokens are covered in detail under
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security

For SASL PLAIN, username will change based on scope of the token as mentioned in the above documentation.
*{policyName}@sas.root.{iothubName} will be used for IoT hub-level tokens.
*{deviceId}@sas.{iothubname} if using device-scoped tokens.

For connecting to specific device, you would normally use device specific token which is just scoped for that device. In this case username and password will be as shown below (**example**)
username:MyDevice1@sas.MyTestHub
password: SharedAccessSignature sig={**}&se=1484788914&sr=MyTestHub.azure-devices.net/devices/MyDevice1

Now are you are trying to use token with based on policy name (for example skn=**iothubowner**)
you will have to set username and password accordingly (**example** below).

username: iothubowner@sas.root.MyTestHub
SAS token: SharedAccessSignature sr=mytesthub.azure-devices.net&sig={**}&se=1516341316&skn=iothubowner

**Comment by tameraw** [comment]
@gemehendrix - Please let us know if still having issues. Thanks.

**Comment by IgorGanapolsky** [comment]
@anhashia What about **SharedAccessKeyName** in the connection string?

**Comment by anhashia** [comment]
Hi @IgorGanapolsky 
Connection string should be of following form
`HostName=<iothub_host_name>;DeviceId=<device_id>;SharedAccessKey=<device_key>`

It should be **SharedAccessKey** for device key
