### ISSUE TITLE
MQTT keep alive delay

### ISSUE THREAD

**Issue by cafenroy** [Azure/azure-iot-sdk-java#130]
Is it possible to set the keep alive delay when using the MQTT protocol?

The default seems to be 20 seconds. It will consume between 30-50MB per month. We don't have this amount of bandwidth for our cellular connected devices. 

Thanks

**Comment by prmathur-microsoft** [comment]
Currently we don't have this support in our SDK. We will add this to our backlog and implement it in future. But at the moment I'm happy to review your PR if you wish to provide one.

**Comment by anhashia** [comment]
Increased to 230 seconds https://github.com/Azure/azure-iot-sdk-java/commit/ccdf4b6be0cc2ea28764a3a5cc66d92692748d58

**Comment by prmathur-microsoft** [comment]
Please let us know if this resolves your issue. Closing it for now. Feel free to reopen if you see any further issues.

**Comment by cafenroy** [comment]
Its better like that.

Thanks
