### ISSUE TITLE
No methods to avoid messages lost if they are buffered after connection down and power down

### ISSUE THREAD

**Issue by MirkoBianchetti** [Azure/azure-iot-sdk-java#132]
Hi, i want to report a strange behavior in the java Iot hub sdk.

Maybe it's a bug or a not expected behavior.

I use AMQPS protocol to send messages to hub. The client who manage the connection (DeviceClient.class) has to call an open() to instaurate connection; after that i call every time function sendEventAsync() to provide message on the hub. From what i've seen in the sdk code, the open() function shall generate a IOException() if it can't connect to the hub but, when a first time it has a fully work connection, it does nothing.

Problem  came when i lost connection after a first one went well. Inside the sdk (AmqpsHubConnection.class : onTransportError()) there is a function to manage these kind of problems, but this function try to reconnect and start a mechanism of messages buffering to send after connection restore. What happens if my device lose power alimentation? I think obiouvsly all messages in buffer go lost.  Furthermore in my code (external to sdk) I haven't any evidence of a lost connection, otherwise I could implement a file persist mechanism for messages. DeviceClient.class has a State.OPEN/State.CLOSE flag that isn't updated on this kind of event, while it would be desirable to update it and to implement a simple method isOpen() to fetch it (furthermore it is present in the new incapsulated class DeviceIO though I don't know if it's updated, anyway I can't access this).

I want know if there is a mechanism or a workaround to persist these unsendable messages.

At the moment i'm using this version of sdk
        <dependency>
            <groupId>com.microsoft.azure.sdk.iot</groupId>
            <artifactId>iot-service-client</artifactId>
            <version>1.6.23</version>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure.sdk.iot</groupId>
            <artifactId>iot-device-client</artifactId>
            <version>1.3.31</version>
        </dependency>

Thanks
Mirko Bianchetti

**Comment by prmathur-microsoft** [comment]
Yes you are right about the bug. We have recently introduced https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceClient.java#L819 . This currently only works for AMQP and AMQPS_ws. You can register a call back for status alerts. Currently this API supports connection drop and connection established. In future we may add more states. But for the moment this may resolve your issue. Please let me know if it does not work for you.

**Comment by prmathur-microsoft** [comment]
@MirkoBianchetti - please let us know if you have any further questions. If not we would like to close this issue.

**Comment by MirkoBianchetti** [comment]
Hi, thanks for your answer. Have you fixed this problem? If it done yes, we can close the issue. thanks you.

**Comment by prmathur-microsoft** [comment]
yes, what your asking has already been implemented. Closing this.
