### ISSUE TITLE
Cannot get JSON or Object structure from Device Twin desired property in device SDK

### ISSUE THREAD

**Issue by davesters** [Azure/azure-iot-sdk-java#133]
- **OS and version used:** OSX 10.12.1 

- **Java runtime used:** JDK 1.8.0_131 

- **SDK version used:** 1.3.32 

# Description of the issue:

Issue #115 seems to still be affecting the device SDK. I am not sure if the fix was only done for the service SDK's `getTwin()` method, but I am seeing the same issue when receiving desired properties via the `PropertyCall` callback.

When I have a JSON object set as the value for a desired property. I comes back as a string in the `PropertyCall` callback, but it is some `toString()` version, and not a properly formed JSON string. So I am unable to deserialize it into a POJO. As a workaround, I have to store the desired property as a serialized JSON string.

It would help if it came back as a properly formed JSON string, or if there is another way to deserialize the value to an object that I am not aware of I could use that.

# Code sample exhibiting the issue:

## Partial Device Twin

    {
      "deviceId": "TEST",
      "etag": "AAAAAAAAAC4=",
      "properties": {
        "desired": {
          "sensors": {
            "sensor1": {
              "name": "foo",
              "property": "bar"
            },
            "sensor2": {
              "name": "foo",
              "property": "bar"
            }
          }
        },
        "reported": {}
      }
    }

## Code Sample

    DeviceClient client = new DeviceClient(connectionString, IotHubClientProtocol.MQTT);
    Device device = new Device() {
        @Override
        public void PropertyCall(String propertyKey, Object propertyValue, Object context) {
            // 'propertyValue' is a string, but JSON serialize fails here.
        }
    };

    client.open();
    client.startDeviceTwin(new DeviceTwinStatusCallBack(), null, device, null);
    client.subscribeToDesiredProperties(device.getDesiredProp());

The `propertyValue` looks like this:

    "{sensors={sensor1={name=foo, property=bar}, sensor2={name=foo, property=bar}}"

And I would hope it would look like this:

        "{\"sensors\":{\"sensor1\":{\"name\":\"foo\", \"property\":\"bar\"}, \"sensor2\"{\"name:\"foo\", \"property\":\"bar\"}}"

This is what I end up storing as the desired property as a work around.

As the propertyValue is returning a string, does this need to be fixed to return it as a JSON string, or is there another method I should be using to get the property deserialized to the object I want?

Any help is appreciated!

**Comment by mamokarz** [comment]
Hi @davesters, I was OOF and back today, I'll take a look on it, sorry about the delay.

**Comment by mamokarz** [comment]
I'm fixing it.

**Comment by prmathur-microsoft** [comment]
Maven package with the fix for this issue has been released. Closing this now. feel free to reopen if you see any further issues.

**Comment by davesters** [comment]
This is great! I will test it out as soon as possible and report back.

Thank you!
