### ISSUE TITLE
[Bug Report] Build error on 'mvn install'

### ISSUE THREAD

**Issue by euchungmsft** [Azure/azure-iot-sdk-java#1333]
# Context

![image](https://user-images.githubusercontent.com/20915976/131614017-5443b1f7-2a44-4d15-9a35-1f14cc62b54b.png)

## Description of the issue
Please be as detailed as possible: which feature has a problem, how often does it fail, etc.

Following instructions listed on here, https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509-java
at the step of running mvn 

`mvn install -DskipTests=true`

## Console log of the issue
Consider setting the DEBUG environment variable to '*'. This will produce a much more verbose output that will help debugging
Don't forget to remove any connection string information!

![image](https://user-images.githubusercontent.com/20915976/131614181-df95ef73-0596-48e2-a112-7d78f7072607.png)

and I see it like this on the repo at both path

![image](https://user-images.githubusercontent.com/20915976/131614304-12c3850a-2d7e-4f3d-9824-539a7b02e8e7.png)

no device/package-list

The error was repeating 2-3 times, it seems like they're ignored and however, build was done with no errors in the end

**Comment by timtay-microsoft** [comment]
This shouldn't impact your ```mvn install``` in any meaningful way. Did you need these package-list files for something in particular?

**Comment by euchungmsft** [comment]
Thanks for your feedback @timtay-microsoft  

This shouldn't impact your mvn install in any meaningful way. 
Yes, build was done successfully and it was running properly. The errors impacted nothing to the build and functions in the end

Did you need these package-list files for something in particular?
I don't think so

One suggestion is adding comments on this error in README. This will be closed soon, thanks again for your confirmation
