### ISSUE TITLE
[Bug Report] DeviceTwin's DesiredProperties are not retrieved after deviceClient.getDeviceTwin(); is called

### ISSUE THREAD

**Issue by aleciav** [Azure/azure-iot-sdk-java#1334]
# Context

- **OS and version used:** Ubuntu 20.04
- **Java runtime used:** openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
- **SDK version used:** iot-device-client-1.30.1; iot-deps-0.12.0; provisioning-device-client-1.8.7

## Description of the issue
After correctly opening a DeviceClient I would like to retrieve all the desired properties from the DeviceTwin. I have followed the [DeviceTwinSample.java](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java) where after opening the DeviceClient I start the DeviceTwin via startDeviceTwin(...) API and then subscribe to the interested DesiredProperties via the subscribeToTwinDesiredProperties(...) API. Finally, I call the getDeviceTwin() API in order to make sure I get all the previously registered TwinPropertyCallBacks called.

What happens is that these TwinPropertyCallBacks are never called after the getDeviceTwin() call. But they get called only when I change a DesiredProperty inside the DeviceTwin (from the Azure IoT Explorer Tool). This makes impossible for me to correctly startup my device using the last set DesiredProperties.

I have the entire code inside a Thread only for having a retry mechanism in case the internet connection is lost or not present.

### Deep analysis
In order to try to find the issue I have debugged some internals of the iot-hub-sdk and found out the following:
Inside the method DeviceTwin.deviceTwinResponseMessageCallback (line 92) I have noticed that after I get the first response **DEVICE_OPERATION_TWIN_GET_RESPONSE** the retrieved twinState contains as reported and desired properties null values causing the fact that the twinPropertyCallbacks are never called.

Indeed, It seems that the received DeviceTwin JSON is not parsed correctly. The received JSON is the following: `{"desired":{"prop1":"value4","$version":29},"reported":{"$version":1}}`, which seems okay, but after the Gson lib takes place (in TwinState.createFromPropertiesJson(...)) using the TwinProperties.class as I said the properties field are set as null.

Different behavior happens when changing a single DesiredProperty: the received JSON is parsed correctly and the DisiredProperties are not null but contain valid data. Received JSON: `{"prop1":"value5","$version":30}`

Note: no exceptions have been observed neither from debug nor from logs.

## Code sample exhibiting the issue
```
public class DataProcessorRunnable implements Runnable
{
    private static final Logger LOGGER = LoggerFactory.getLogger(DataProcessorRunnable.class);
	
    private static final long RETRY_INTERVAL = 10000;
	
    private DeviceClient deviceClient;
	
    private boolean isConnectionOk = false;
    private boolean keepRunning = true;
	
    private static final AtomicBoolean Succeed = new AtomicBoolean(false);
	
	
    public DataProcessorRunnable()
    {
    }
	
    public synchronized void stop()
    {
        this.keepRunning = false;
    }

    private synchronized boolean keepRunning()
    {
        return this.keepRunning == true;
    }
	
    private void internalStop()
    {
        try
        {
            deviceClient.closeNow();
        }
        catch (IOException e)
        {
            LOGGER.error("REDGE: Error while closing DeviceClient...");
        }
    }

    public void run()
    {
        // Infinite thread loop
        while (true)
        {
            if (keepRunning() == false)
            {
                internalStop();
                
                LOGGER.info("DataProcessorRunnable has been stopped...");
                return;
            }
            
            if (isConnectionOk == false)
            {
                LOGGER.info("Starting Provisioning process...");
                
                try
                {
                    // Here I do the provisioning via Azure DPS using an X.509 certificate
                    GatewayProvisioning gp = new GatewayProvisioning(DataProcessorContext.getKeyStoreManager());
                    deviceClient = gp.runProvisioning();
                }
                catch (Exception e)
                {
                    LOGGER.error("Provisioning process failed. Will try again in a moment...");
                    
                    try
                    {
                        Thread.sleep(RETRY_INTERVAL);
                    }
                    catch (InterruptedException e1)
                    {
                        internalStop();
                        return;
                    }
                    continue;
                }
                
                LOGGER.info("Provisioning process succesfully completed...");
                               
                deviceClient.registerConnectionStatusChangeCallback(new Callbacks.IotHubConnectionStatusChangeCallbackLogger(), new Object());
                
                LOGGER.info("Opening DeviceClient...");
                
                try
                {
                    deviceClient.open();
                }
                catch (IOException e)
                {
                    LOGGER.error("error while opening DeviceClient", e);
                    internalStop();
                    continue;
                }
                
                try
                {
                    Succeed.set(false);
                    deviceClient.startDeviceTwin(new Callbacks.DeviceTwinStatusCallBack(), Succeed, new Callbacks.onProperty(), null);
                    do
                    {
                        Thread.sleep(1000);
                    }
                    while(!Succeed.get());
                }
                catch (IllegalArgumentException | UnsupportedOperationException | IOException e)
                {
                    LOGGER.error("Error while starting DeviceTwin", e);
                    internalStop();
                    continue;
                }
                catch (InterruptedException e)
                {
                    LOGGER.error("Thread interrupted", e);
                }
                
                LOGGER.info("Subscribe to Desired properties on device Twin...");
                Map<Property, Pair<TwinPropertyCallBack, Object>> desiredProperties = new HashMap<Property, Pair<TwinPropertyCallBack, Object>>()
                {
                    {
                        put(new Property("prop1", null), new Pair<TwinPropertyCallBack, Object>(new Callbacks.onDesiredProperty1Change(), null));
                    }
                };
                
                try
                {
                    deviceClient.subscribeToTwinDesiredProperties(desiredProperties);
                    System.out.println("Get device Twin...");
                    deviceClient.getDeviceTwin(); // For each desired property in the Service, the SDK will call the appropriate callback with the value and version.
                }
                catch (IOException e)
                {
                    LOGGER.error("IOException", e);
                }
                
                LOGGER.info("DeviceClient succesfully open...");
                
                isConnectionOk = true;
            }
            
            try
            {
                Thread.sleep(RETRY_INTERVAL);
            }
            catch (InterruptedException e)
            {
                internalStop();
                return;
            }
        }
    }
}

public class Callbacks
{
        private static final Logger s_logger = LoggerFactory.getLogger(Callbacks.class);
		
	//Device Twin
	public static class DeviceTwinStatusCallBack implements IotHubEventCallback
	{
		@Override
		public void execute(IotHubStatusCode status, Object context)
		{
			if (context instanceof AtomicBoolean)
			{
				AtomicBoolean succeed = (AtomicBoolean)context;
				succeed.set((status == IotHubStatusCode.OK) || (status == IotHubStatusCode.OK_EMPTY));
			}
			
			System.out.println("DEVICETWINCALLBACK IoT Hub responded to device twin operation with status " + status.name());
		}
	}
	
	public static class onProperty implements TwinPropertyCallBack
	{
		@Override
		public void TwinPropertyCallBack(Property property, Object context)
		{
			s_logger.info("onProperty callback for " + (property.getIsReported()?"reported": "desired") +
							" property " + property.getKey() +
							" to " + property.getValue() +
							", Properties version:" + property.getVersion());
		}
	}
	
	public static class IotHubConnectionStatusChangeCallbackLogger implements IotHubConnectionStatusChangeCallback
    {
        @Override
        public void execute(IotHubConnectionStatus status, IotHubConnectionStatusChangeReason statusChangeReason, Throwable throwable, Object callbackContext)
        {
            s_logger.info("\n");
            s_logger.info("CONNECTION STATUS UPDATE: " + status);
            s_logger.info("CONNECTION STATUS REASON: " + statusChangeReason);
            s_logger.info("CONNECTION STATUS THROWABLE: " + (throwable == null ? "null" : throwable.getMessage()));
            s_logger.info("\n");

            if (throwable != null)
            {
                throwable.printStackTrace();
            }

            if (status == IotHubConnectionStatus.DISCONNECTED)
            {
            	s_logger.error("The connection was lost, and is not being re-established." +
                        " Look at provided exception for how to resolve this issue." +
                        " Cannot send messages until this issue is resolved, and you manually re-open the device client");
            }
            else if (status == IotHubConnectionStatus.DISCONNECTED_RETRYING)
            {
            	s_logger.error("The connection was lost, but is being re-established." +
                        " Can still send messages, but they won't be sent until the connection is re-established");
            }
            else if (status == IotHubConnectionStatus.CONNECTED)
            {
            	s_logger.info("The connection was successfully established. Can send messages.");
            }
        }
    }
	
	public static class onDesiredProperty1Change implements TwinPropertyCallBack
    {
        @Override
        public void TwinPropertyCallBack(Property property, Object context)
        {
            System.out.println(
                    "onDesiredProperty1Change change " + property.getKey() +
                            " to " + property.getValue() +
                            ", Properties version:" + property.getVersion());
        }
    }
}
```

## Console log of the issue

13:13:27,224 [Component Resolve Thread] INFO  KeyStoreManager:15  - Opening the KeyStore...
13:13:27,253 [Component Resolve Thread] INFO  KeyStoreManager:15  - KeyStore correctly open.
13:13:27,257 [pool-9-thread-1] INFO  HACLProcessorCore:15  - REDGE: Starting Provisioning process...
13:13:27,264 [pool-9-thread-1] INFO  GatewayProvisioning:15  - Starting provisioning...
13:13:27,264 [pool-9-thread-1] INFO  GatewayProvisioning:24  - Alias gwcertinfo found...
13:13:27,265 [pool-9-thread-1] INFO  GatewayProvisioning:24  - Alias gwcertinfo found...
13:13:27,298 [pool-9-thread-1] DEBUG ProvisioningDeviceClient:104  - Starting provisioning thread...
13:13:27,301 [pool-9-thread-1] INFO  GatewayProvisioning:15  - Waiting for Provisioning Service to register...
13:13:27,303 [azure-iot-sdk-ProvisioningTask] INFO  ProvisioningTask:273  - Opening the connection to device provisioning service...
13:13:28,309 [azure-iot-sdk-ProvisioningTask] INFO  ProvisioningTask:293  - Connection to device provisioning service opened successfully, sending initial device registration message
13:13:28,317 [azure-iot-sdk-RegisterTask] INFO  RegisterTask:297  - Authenticating with device provisioning service using x509 certificates
13:13:28,564 [azure-iot-sdk-ProvisioningTask] INFO  ProvisioningTask:296  - Waiting for device provisioning service to provision this device...
13:13:28,564 [azure-iot-sdk-ProvisioningTask] INFO  ProvisioningTask:178  - Current provisioning status: ASSIGNING
13:13:31,659 [azure-iot-sdk-ProvisioningTask] INFO  ProvisioningTask:230  - Device provisioning service assigned the device successfully
13:13:37,305 [pool-9-thread-1] INFO  GatewayProvisioning:15  - IotHUb Uri : **my-iot-hub-uri**
13:13:37,306 [pool-9-thread-1] INFO  GatewayProvisioning:15  - Device ID : **my-device-id**
13:13:37,316 [pool-9-thread-1] INFO  ExponentialBackoffWithJitter:98  - NOTE: A new instance of ExponentialBackoffWithJitter has been created with the following properties. Retry Count: 2147483647, Min Backoff Interval: 100, Max Backoff Interval: 10000, Max Time Between Retries: 100, Fast Retry Enabled: true
13:13:37,321 [pool-9-thread-1] INFO  ExponentialBackoffWithJitter:98  - NOTE: A new instance of ExponentialBackoffWithJitter has been created with the following properties. Retry Count: 2147483647, Min Backoff Interval: 100, Max Backoff Interval: 10000, Max Time Between Retries: 100, Fast Retry Enabled: true
13:13:37,322 [pool-9-thread-1] INFO  GatewayProvisioning:15  - REDGE: Provisioning process succesfully completed...
13:13:37,326 [pool-9-thread-1] INFO  GatewayProvisioning:15  - REDGE: Opening DeviceClient...
13:13:37,334 [pool-9-thread-1] DEBUG MqttIotHubConnection:260  - Opening MQTT connection...
13:13:37,335 [pool-9-thread-1] DEBUG Mqtt:120  - Sending MQTT CONNECT packet...
13:13:38,039 [pool-9-thread-1] DEBUG Mqtt:123  - Sent MQTT CONNECT packet was acknowledged
13:13:38,039 [pool-9-thread-1] DEBUG Mqtt:253  - Sending MQTT SUBSCRIBE packet for topic devices/**my-device-id**/messages/devicebound/#
13:13:38,121 [pool-9-thread-1] DEBUG Mqtt:258  - Sent MQTT SUBSCRIBE packet for topic devices/**my-device-id**/messages/devicebound/# was acknowledged
13:13:38,122 [pool-9-thread-1] DEBUG MqttIotHubConnection:286  - MQTT connection opened successfully
13:13:38,122 [pool-9-thread-1] DEBUG IotHubTransport:353  - The connection to the IoT Hub has been established
13:13:38,123 [pool-9-thread-1] INFO  IotHubTransport:1560  - Updating transport status to new status CONNECTED with reason CONNECTION_OK
13:13:38,123 [pool-9-thread-1] DEBUG IotHubTransport:1570  - Invoking connection status callbacks with new status details
13:13:38,123 [pool-9-thread-1] INFO  Callbacks:15  - 
13:13:38,123 [pool-9-thread-1] INFO  Callbacks:15  - CONNECTION STATUS UPDATE: CONNECTED
13:13:38,123 [pool-9-thread-1] INFO  Callbacks:15  - CONNECTION STATUS REASON: CONNECTION_OK
13:13:38,123 [pool-9-thread-1] INFO  Callbacks:15  - CONNECTION STATUS THROWABLE: null
13:13:38,124 [pool-9-thread-1] INFO  Callbacks:15  - 
13:13:38,124 [pool-9-thread-1] INFO  Callbacks:15  - The connection was successfully established. Can send messages.
13:13:38,125 [pool-9-thread-1] DEBUG IotHubTransport:445  - Client connection opened successfully
13:13:38,125 [pool-9-thread-1] INFO  DeviceClient:442  - Device client opened successfully
13:13:38,160 [pool-9-thread-1] INFO  IotHubTransport:540  - Message was queued to be sent later ( Message details: Correlation Id [8a0f3bde-d2f5-40c9-b438-148c798fcc88] Message Id [86395daa-a993-48ef-9885-460ca845ebb4] Device Operation Type [DEVICE_OPERATION_TWIN_SUBSCRIBE_DESIRED_PROPERTIES_REQUEST] )
13:13:38,161 [pool-9-thread-1] INFO  IotHubTransport:540  - Message was queued to be sent later ( Message details: Correlation Id [fe16f334-d03e-45ba-84cc-8214b216d569] Message Id [6fa33a47-5879-4707-aed7-b8332e0d35c9] Request Id [fe16f334-d03e-45ba-84cc-8214b216d569] Device Operation Type [DEVICE_OPERATION_TWIN_GET_REQUEST] )
13:13:38,163 [azure-iot-sdk-IotHubSendTask] INFO  IotHubTransport:1473  - Sending message ( Message details: Correlation Id [8a0f3bde-d2f5-40c9-b438-148c798fcc88] Message Id [86395daa-a993-48ef-9885-460ca845ebb4] Device Operation Type [DEVICE_OPERATION_TWIN_SUBSCRIBE_DESIRED_PROPERTIES_REQUEST] )
13:13:38,166 [azure-iot-sdk-IotHubSendTask] DEBUG Mqtt:253  - Sending MQTT SUBSCRIBE packet for topic $iothub/twin/res/#
13:13:38,244 [azure-iot-sdk-IotHubSendTask] DEBUG Mqtt:258  - Sent MQTT SUBSCRIBE packet for topic $iothub/twin/res/# was acknowledged
13:13:38,245 [azure-iot-sdk-IotHubSendTask] DEBUG Mqtt:253  - Sending MQTT SUBSCRIBE packet for topic $iothub/twin/PATCH/properties/desired/#
13:13:38,325 [azure-iot-sdk-IotHubSendTask] DEBUG Mqtt:258  - Sent MQTT SUBSCRIBE packet for topic $iothub/twin/PATCH/properties/desired/# was acknowledged
13:13:38,326 [azure-iot-sdk-IotHubSendTask] INFO  IotHubTransport:1473  - Sending message ( Message details: Correlation Id [fe16f334-d03e-45ba-84cc-8214b216d569] Message Id [6fa33a47-5879-4707-aed7-b8332e0d35c9] Request Id [fe16f334-d03e-45ba-84cc-8214b216d569] Device Operation Type [DEVICE_OPERATION_TWIN_GET_REQUEST] )
13:13:38,329 [azure-iot-sdk-IotHubSendTask] DEBUG IotHubTransport:657  - Invoking the callback function for sent message, IoT Hub responded to message ( Message details: Correlation Id [8a0f3bde-d2f5-40c9-b438-148c798fcc88] Message Id [86395daa-a993-48ef-9885-460ca845ebb4] Device Operation Type [DEVICE_OPERATION_TWIN_SUBSCRIBE_DESIRED_PROPERTIES_REQUEST] ) with status OK_EMPTY
13:13:38,395 [MQTT Call: **my-device-id**] DEBUG IotHubTransport:198  - IotHub message was acknowledged. Checking if there is record of sending this message ( Message details: Correlation Id [fe16f334-d03e-45ba-84cc-8214b216d569] Message Id [6fa33a47-5879-4707-aed7-b8332e0d35c9] Request Id [fe16f334-d03e-45ba-84cc-8214b216d569] Device Operation Type [DEVICE_OPERATION_TWIN_GET_REQUEST] )
13:13:38,396 [azure-iot-sdk-IotHubSendTask] DEBUG IotHubTransport:657  - Invoking the callback function for sent message, IoT Hub responded to message ( Message details: Correlation Id [fe16f334-d03e-45ba-84cc-8214b216d569] Message Id [6fa33a47-5879-4707-aed7-b8332e0d35c9] Request Id [fe16f334-d03e-45ba-84cc-8214b216d569] Device Operation Type [DEVICE_OPERATION_TWIN_GET_REQUEST] ) with status OK_EMPTY
13:13:38,398 [MQTT Call: **my-device-id**] INFO  IotHubTransport:285  - Message was received from IotHub ( Message details: Correlation Id [fe16f334-d03e-45ba-84cc-8214b216d569] Message Id [a6539ceb-f6fa-43eb-a528-e425fee728de] Request Id [fe16f334-d03e-45ba-84cc-8214b216d569] Device Operation Type [DEVICE_OPERATION_TWIN_GET_RESPONSE] )
13:13:38,399 [azure-iot-sdk-IotHubReceiveTask] DEBUG IotHubTransport:932  - Executing callback for received message ( Message details: Correlation Id [fe16f334-d03e-45ba-84cc-8214b216d569] Message Id [a6539ceb-f6fa-43eb-a528-e425fee728de] Request Id [fe16f334-d03e-45ba-84cc-8214b216d569] Device Operation Type [DEVICE_OPERATION_TWIN_GET_RESPONSE] )
DEVICETWINCALLBACK IoT Hub responded to device twin operation with status OK
13:13:39,162 [pool-9-thread-1] INFO  Callbacks:15  - Subscribe to Desired properties on device Twin...
13:13:39,177 [pool-9-thread-1] INFO  IotHubTransport:540  - Message was queued to be sent later ( Message details: Correlation Id [1ca2aa16-9b9c-4096-b841-d315ed235d73] Message Id [3f069c63-2789-450f-a016-b94f3bbc40f4] Device Operation Type [DEVICE_OPERATION_TWIN_SUBSCRIBE_DESIRED_PROPERTIES_REQUEST] )
Get device Twin...
13:13:39,177 [azure-iot-sdk-IotHubSendTask] INFO  IotHubTransport:1473  - Sending message ( Message details: Correlation Id [1ca2aa16-9b9c-4096-b841-d315ed235d73] Message Id [3f069c63-2789-450f-a016-b94f3bbc40f4] Device Operation Type [DEVICE_OPERATION_TWIN_SUBSCRIBE_DESIRED_PROPERTIES_REQUEST] )
13:13:39,177 [pool-9-thread-1] INFO  IotHubTransport:540  - Message was queued to be sent later ( Message details: Correlation Id [7ccf6f7d-211b-43d2-bc8a-0bb6504756dc] Message Id [0e6089d1-f57c-4cea-b97f-36815209a227] Device Operation Type [DEVICE_OPERATION_TWIN_SUBSCRIBE_DESIRED_PROPERTIES_REQUEST] )
13:13:39,177 [azure-iot-sdk-IotHubSendTask] DEBUG Mqtt:253  - Sending MQTT SUBSCRIBE packet for topic $iothub/twin/PATCH/properties/desired/#
13:13:39,177 [pool-9-thread-1] INFO  IotHubTransport:540  - Message was queued to be sent later ( Message details: Correlation Id [91413f30-cc88-4a9f-b3d4-906817d0adf7] Message Id [ce8a438c-f3f1-43ad-b60d-b19eaf27d87e] Request Id [91413f30-cc88-4a9f-b3d4-906817d0adf7] Device Operation Type [DEVICE_OPERATION_TWIN_GET_REQUEST] )
13:13:39,177 [pool-9-thread-1] INFO  Callbacks:15  - REDGE: DeviceClient succesfully open...
13:13:39,177 [pool-9-thread-1] INFO  Callbacks:15  - DataProcessor status connection of cloud:Connected
13:13:39,272 [azure-iot-sdk-IotHubSendTask] DEBUG Mqtt:258  - Sent MQTT SUBSCRIBE packet for topic $iothub/twin/PATCH/properties/desired/# was acknowledged
13:13:39,273 [azure-iot-sdk-IotHubSendTask] INFO  IotHubTransport:1473  - Sending message ( Message details: Correlation Id [7ccf6f7d-211b-43d2-bc8a-0bb6504756dc] Message Id [0e6089d1-f57c-4cea-b97f-36815209a227] Device Operation Type [DEVICE_OPERATION_TWIN_SUBSCRIBE_DESIRED_PROPERTIES_REQUEST] )
13:13:39,273 [azure-iot-sdk-IotHubSendTask] DEBUG Mqtt:253  - Sending MQTT SUBSCRIBE packet for topic $iothub/twin/PATCH/properties/desired/#
13:13:39,352 [azure-iot-sdk-IotHubSendTask] DEBUG Mqtt:258  - Sent MQTT SUBSCRIBE packet for topic $iothub/twin/PATCH/properties/desired/# was acknowledged
13:13:39,353 [azure-iot-sdk-IotHubSendTask] INFO  IotHubTransport:1473  - Sending message ( Message details: Correlation Id [91413f30-cc88-4a9f-b3d4-906817d0adf7] Message Id [ce8a438c-f3f1-43ad-b60d-b19eaf27d87e] Request Id [91413f30-cc88-4a9f-b3d4-906817d0adf7] Device Operation Type [DEVICE_OPERATION_TWIN_GET_REQUEST] )
13:13:39,353 [azure-iot-sdk-IotHubSendTask] DEBUG IotHubTransport:657  - Invoking the callback function for sent message, IoT Hub responded to message ( Message details: Correlation Id [1ca2aa16-9b9c-4096-b841-d315ed235d73] Message Id [3f069c63-2789-450f-a016-b94f3bbc40f4] Device Operation Type [DEVICE_OPERATION_TWIN_SUBSCRIBE_DESIRED_PROPERTIES_REQUEST] ) with status OK_EMPTY
13:13:39,420 [MQTT Call: **my-device-id**] DEBUG IotHubTransport:198  - IotHub message was acknowledged. Checking if there is record of sending this message ( Message details: Correlation Id [91413f30-cc88-4a9f-b3d4-906817d0adf7] Message Id [ce8a438c-f3f1-43ad-b60d-b19eaf27d87e] Request Id [91413f30-cc88-4a9f-b3d4-906817d0adf7] Device Operation Type [DEVICE_OPERATION_TWIN_GET_REQUEST] )
13:13:39,423 [MQTT Call: **my-device-id**] INFO  IotHubTransport:285  - Message was received from IotHub ( Message details: Correlation Id [91413f30-cc88-4a9f-b3d4-906817d0adf7] Message Id [f9712d1b-7a93-4e06-8644-fea3bb21f343] Request Id [91413f30-cc88-4a9f-b3d4-906817d0adf7] Device Operation Type [DEVICE_OPERATION_TWIN_GET_RESPONSE] )

**Comment by aleciav** [comment]
Issue resolved on our side. No changes were needed.

Root cause: issue with Gson library dependencies.

**Comment by payalgaikwad42** [comment]
@aleciav Hi, I am facing similar issue at my end. Could you please tell me how did you created device client for this application? 
did you hardcoded cert and key while creating SecurityProviderX509Cert  or is it possible to give cert path?

**Comment by aleciav** [comment]
Hi @payalgaikwad42, for security reason I would not suggest to hard-code the Private key and Certificate in the code. Maybe better to use a Keystore.
