### ISSUE TITLE
Cannot get properties at 4th nested level in DeviceTwin

### ISSUE THREAD

**Issue by gbidsilva** [Azure/azure-iot-sdk-java#134]
Env. Details:
SDK Used : Azure Service SDK

```
<dependency>
	<groupId>com.microsoft.azure.sdk.iot</groupId>
	<artifactId>iot-service-client</artifactId>
	<version>1.6.23</version>
</dependency>
```
On
Java 1.8 + Cent OS (Linux)

Hi Team,

I am facing some issues in retrieving Device Twin through Java Service SDK.
According to the Device Twin documentation available at : https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins , we can have a Twin JSON structures up to 5 nested levels in Desired and Reported properties in DeviceTwin JSON.
The line which explains this is as follows,
"All JSON objects in tags, desired, and reported properties can have a maximum depth of 5".

I have following JSON structure in my Device Twin which is having 4 nested levels in Device Twins' reported section (I have also marked the respective levels in it too).

```
{
  "deviceId": "5253b83b4333",
  "etag": "AAAAAAAE=",  
  "properties": { 
    "desired": { 
      "$version": 1
    },
    "reported": { -> Level 1
      "alerts": { -> Level 2
        "alert_1": { -> Level 3
          "alertCode": "alert_1",
          "secondaryCode": "",
          "variables": { -> Level 4
            "Summary": "alert summary"
          },
          "alertStatus": "WARN"          
        }
      },     
      "$version": 2
    }
  }
}
```

But, this cannot be retrieved by using `com.microsoft.azure.sdk.iot.service.devicetwin.getTwin()` method.
I am getting the following exception when execute above method to retrieve above device twin.
```
Malformed Json: exceed 5 levels
```

This should be a valid Twin JSON and it should also be retrievable because, I can see it in the device twin explore in Azure therefore, if this is not a valid one then I should not be able to push it to the device twin anyway.

Appreciate your help on this.
Thanks.

**Comment by prmathur-microsoft** [comment]
Currently nesting is not supported in java SDK. We added that feature to our backlog and will address it soon.

**Comment by prmathur-microsoft** [comment]
#122

**Comment by gbidsilva** [comment]
@prmathur-microsoft : I was able to get properties upto the 4th nested level through SDK. So it is supported but not matched with the documentation.

**Comment by prmathur-microsoft** [comment]
@gbidsilva you are right about that. We have it partially implemented. We have it in our backlog to implement it fully.

**Comment by nielsvn92** [comment]
@prmathur-microsoft can you tell me when (approximately) you expect nesting will be supported in the Java SDK?

**Comment by timtay-microsoft** [comment]
The fix for this issue is now released. See the release below for versions:

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-10-23 

I will close this issue for now. Feel free to re-open if it did not fix your issues.
