### ISSUE TITLE
ProvisioningServiceClient::getEnrollmentGroup raises an exception if the group only contains CAreferences.

### ISSUE THREAD

**Issue by ccifuentesfer** [Azure/azure-iot-sdk-java#1340]
How to reproduce:
- Upload a root or intermediate certificate to Azure DPS.
- Create an enrollment group that uses the uploaded certificate.
- Call the function.

This call raises the exception:
"X509 attestation for EnrollmentGroup does not contains a valid certificate."

The issue seems to be here:
```
if (((X509Attestation)attestation).getRootCertificatesFinal() == null)
{
    throw new IllegalArgumentException("X509 attestation for EnrollmentGroup does not contains a valid certificate.");
}
```

https://github.com/Azure/azure-iot-sdk-java/blob/05a7e0daa03e2f01ffb16598539535b429e7f97f/provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/configs/EnrollmentGroup.java#L428

Same file from the csharp SDK:
```
if ((((X509Attestation)value).RootCertificates == null) && (((X509Attestation)value).CAReferences == null))
{
    throw new ArgumentException("Attestation mechanism does not contain a valid certificate");
}
```
https://github.com/Azure/azure-iot-sdk-csharp/blob/9e782d28f244f8e62e414dd867c9e242155f17d1/provisioning/service/src/Config/EnrollmentGroup.cs#L260

**Comment by timtay-microsoft** [comment]
Yep, this appears to be a bug in the SDK. #1342 will fix this issue for you.

**Comment by timtay-microsoft** [comment]
Provisioning service client 1.9.1 has now been released with this fix, so I'm closing this issue
