### ISSUE TITLE
[Bug Report] TransportException error message wrong after MAX_IN_FLIGHT_COUNT change

### ISSUE THREAD

**Issue by DBY047** [Azure/azure-iot-sdk-java#1350]
# Context
MAX_IN_FLIGHT_COUNT have been change from 10 to 65000

## Description of the issue
If the number of pending delivery tokens becomes >= to MAX_IN_FLIGHT_COUNT. The error message in the TransportException still  refers to the hold limits

## Code sample exhibiting the issue
```java
TransportException transportException = new TransportException("Cannot publish when mqtt client is holding 10 tokens and is disconnected");
```

**Comment by timtay-microsoft** [comment]
Device client version 1.31.3 has been released and has the fix for this issue, so this issue was closed
