### ISSUE TITLE
Incorrect IoTHub.ConnectionDeviceId in events  

### ISSUE THREAD

**Issue by nzhechev-bosch** [Azure/azure-iot-sdk-java#136]
- **OS and version used:** Windows 7

- **Java runtime used:** Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

- **SDK version used:** iot-device-client:1.3.32, iot-service-client:1.7.23

# Description of the issue:
It seems that when there are more than one `DeviceClient` objects sending events concurrently through  `sendEventAsync` method all received messages  on the cloud have the same `IoTHub.ConnectionDeviceId` property, regardless of which device actually sent the message.

Attached is a sample application ([events-test.zip](https://github.com/Azure/azure-iot-sdk-java/files/1221608/events-test.zip)) that creates two devices and starts sending events from two threads (one for each  `DeviceClient`) at 2 second intervals until `enter`is pressed. The messages are in JSON format with two properties - `deviceId` and `timestamp`.

In Azure Cloud there is a Stream Analytics job with input from IoT Hub from which I sample for 1 minute. 
The attached [samples.zip](https://github.com/Azure/azure-iot-sdk-java/files/1221648/samples.zip) contains the outputs from two queries - `select *` and (for easier reading)  `select deviceid, iothub.ConnectionDeviceId` - from which is visible that, no matter which `DeviceClient` sends the messages the `ConnectionDeviceId` property is `device-A`.

# Code sample exhibiting the issue:
[events-test.zip](https://github.com/Azure/azure-iot-sdk-java/files/1221608/events-test.zip)

# Console log of the issue:
[app-log.TXT](https://github.com/Azure/azure-iot-sdk-java/files/1221653/app-log.TXT)

**Comment by prmathur-microsoft** [comment]
We are aware of this issue and we are working on resolving it. #125

**Comment by prmathur-microsoft** [comment]
Fix for this issue is checked in. Please let us know if this fixes your issue

**Comment by nzhechev-bosch** [comment]
Yes, it works as expected with iot-device-client:1.4.33. Thanks!
