### ISSUE TITLE
WaitingList growing indefinitely when we send messages with network disabled.

### ISSUE THREAD

**Issue by sergaz-msft** [Azure/azure-iot-sdk-java#137]
Error: java.lang.OutOfMemoryError: Java heap space

Please change the following:
1. Set a maximum limit on the queue which can be configurable via set option.
2. Once the queue gets filled beyond maximum limit, discard the newest message and inform user 
3. To inform the user, add a new enum to the status say DISCARD_MAX_QUEUE_LIMIT_REACHED. And inform the user that message had been discarded via callback.

**Comment by prmathur-microsoft** [comment]
#148

**Comment by prmathur-microsoft** [comment]
As per workaround in #148 we will close this issue now. Feel free to reopen if the solution offered does not meet you needs.
