### ISSUE TITLE
[feature request] Identifiable threads

### ISSUE THREAD

**Issue by niklas-sparfeld-gcx** [Azure/azure-iot-sdk-java#1382]
**Is your feature request related to a problem? Please describe.**

In our system we open many DeviceClients, either simple-plexed or multiplexed.
Since we were running into some issues with the IoT SDK, we debugged it quite a lot.

The problem is that the executors and reactors of *different* clients all share the same thread names (e.g. `private static final String THREAD_NAME = "azure-iot-sdk-ReactorRunner";`).

This makes it harder to filter for threads in our logs or in IntelliJ or decide which things happen in parallel.

**Describe the solution you'd like**

#### Solution A): Unique Thread Names

I would like all the threads to have unique names, just like the ReactorRunner `this.threadName = THREAD_NAME_PREFIX + threadNamePostfix;`.

I would *prefer* them all to have the same postfix for the same connection, if possible.

I think this is a simple improvement and it would help in these situations quite a lot. For example I could provide much better logs to you people :)

#### Solution B): Mapped Diagnostic Context

We're implementing Mapped Diagnostic Context. When Azure SDK spawns a thread the context is lost and we can no longer correlate the log messages via this technique.

I currently see no good way to integrate Azure SDK threads with this, but maybe you know better.

I think solution A) would already help a lot, is simple and could be implemented fast.

Thanks you all :-)

**Comment by azabbasi** [comment]
@niklas-sparfeld-gcx 
Hi Niklas,
We are investigating the potential approaches we can take in naming our threads and I would like to ask some clarifying questions
Different connections will be opened within the lifetime of a DeviceClient, Does it make sense for you to have the thread identified by the connection GUID or a singular Device Client GUID? We have multiple options and they each vary in cost of implementation, I will list them here from cheapest to most expensive.
* Provide a unique Identifier postfix per connection  -> azure-iot-sdk-ReactorRunner-purpose-ConnectionGUID
* Associate each Device client with a random GUID and add it as a prefix to the thread name  -> `RandomGUID-azure-iot-sdk-ReactorRunner-purpose`
* Associate each Device client with a random GUID and add it as a prefix to the thread name and suffix it with a random GUID per connection -> `RandomGUID-azure-iot-sdk-ReactorRunner-purpose-ConnectionGUID`
* Associate each Device client with a user-specified prefix (via client options) and use it in naming threads -> `UserProvidedPrefix-azure-iot-sdk-ReactorRunner-purpose`
* Associate each Device client with a user-specified prefix (via client options) and use it in naming threads and suffix it with connection GUID -> `UserProvidedPrefix-azure-iot-sdk-ReactorRunner-purpose-ConnectionGUID`

It would be great if you can let us which approach meets your requirements and give us a little bit of insight as to why that is the case.

Thank you
Azad

**Comment by niklas-sparfeld-gcx** [comment]
Yes, that works for us, thanks 👍

**Comment by azabbasi** [comment]
@niklas-sparfeld-gcx 
We have checked in a fix for this and it will be published with our next release. It may be worth mentioning that the device Id or connection Id is not always present when we are opening up a thread. 
For example in case of multiplexing in AMQP, there is no device Id present for opening connections, sending and receiving messages, etc.
Another example is for provisioning device client, when the thread is being spun up, there is no connection established, so we set the thread name to include `ConnectionPending` and when we have a connection established, we will change the thread name to include the connection guide.

I hope this helps and addresses the issue.

Thanks

**Comment by jamdavi** [comment]
We have added improvements in the latest release that should help with this issue and others. Please feel free to reopen if the upgraded library does not solve this problem.

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2021-12-15
