### ISSUE TITLE
Is MQTT over WebSockets possible with the Java SDK?

### ISSUE THREAD

**Issue by Brideau** [Azure/azure-iot-sdk-java#139]
I'm looking to use MQTT over WebSockets to communicate from a device within our corporate firewall to the Azure IoT Hub, as mentioned on the [choose a communication protocol](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-protocols) page.

I currently have this working using just MQTT using the following with the Java SDK v1.3.33:
```java
private static DeviceClient client;
private static IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
String connString = "some connection string"
client = new DeviceClient(connString, protocol);

```
While there seems to be an `IotHubClientProtocol.AMQPS_WS` enum for doing AMQPS over WebSockets, there doesn't seem to be an equivalent `MQTT_WS` listed [in the docs](https://azure.github.io/azure-iot-sdk-java/device/com/microsoft/azure/sdk/iot/device/IotHubClientProtocol.html). I also cannot find an example of an implementation over MQTT over WebSockets or any documentation on how it is done.

Am I overlooking something, or is this not currently possible in the Java SDK?

**Comment by prmathur-microsoft** [comment]
This feature has been checked in recently and maven package for the same is also release. Please try it on the latest version - 1.4.33 and you will find the support.

**Comment by Brideau** [comment]
Perfect, I'll give this a try today to confirm that everything works.

**Comment by Brideau** [comment]
Works perfectly - thanks for the help.

**Comment by prmathur-microsoft** [comment]
Closing this as it works
