### ISSUE TITLE
High data usage with MQTT?

### ISSUE THREAD

**Issue by MattHoneycutt** [Azure/azure-iot-sdk-java#140]
- **OS and version used:** Linux (embedded)

- **Java runtime used:** 1.8

- **SDK version used:** 1.8

# Description of the issue:
Using the MQTT protocol, we're seeing about 4MB of data usage per day.  That's with no cloud-to-device nor device-to-cloud messages being sent.  That's *just* with the client idly connected to the hub.  

That seems high.  Interestingly, even though AMQP should be a heavier protocol, changing our client to AMQP instead MQTT reduced the usage from 4MB per day to just 2MB per day.

Is this normal behavior?  Is there some setting we've overlooked that will reduce the amount of data used? 

# Code sample exhibiting the issue:
this.client = new DeviceClient("hub-connections-string-here", IotHubClientProtocol.MQTT);
//..snip...
this.client.open();

# Console log of the issue:
n/a

**Comment by prmathur-microsoft** [comment]
We will investigate this and let you know soon

**Comment by ApiO** [comment]
Could it be a difference in the heartbeat setups ? (see also #130)

**Comment by MattHoneycutt** [comment]
Yeah, I think that could definitely be it, especially if it's set to 20 seconds.

**Comment by anhashia** [comment]
Ping request interval from the MQTT client has been increased to **230** seconds as default from 20 seconds
https://github.com/Azure/azure-iot-sdk-java/commit/ccdf4b6be0cc2ea28764a3a5cc66d92692748d58
That should reduce the ping traffic.

There are also plans to make this user configurable in future.

**Comment by prmathur-microsoft** [comment]
Please let us know if this resolves your issue with the latest package. Closing it for now. Feel free to reopen if you see further issues.
