### ISSUE TITLE
[Bug Report] Azure IoT Hub via MQTT receiving very little data

### ISSUE THREAD

**Issue by jouniaro** [Azure/azure-iot-sdk-java#1403]
# Context

- Azure MQTT Broker & .NET Core event handler

## Description of the issue
We are submitting data to the Azure IoT Hub via MQTT from our Java application and handling it there with the .NET Core handler as described in https://www.prosysopc.com/blog/azure-mqtt-demo/

However, looking at the data in the Power BI graph https://uademo.prosysopc.com/ does not correspond to the expected - there should be a triangle wave updated every 4 seconds.

## Code sample exhibiting the issue
Sample application available on request with the Prosys OPC UA SDK for Java: https://www.prosysopc.com/products/opc-ua-java-sdk/

**Comment by timtay-microsoft** [comment]
For issues with the service, you'll need to file a support ticket [here](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview). This issues page is just for tracking issues with the Azure IoT Hub Java SDK. After you've filed a support ticket on the link above, a service-side engineer will be able to take a look at your IoT Hub instance and shed some light on the traffic patterns you're seeing.

**Comment by timtay-microsoft** [comment]
@jouniaro do you mind if I close this issue?

**Comment by jouniaro** [comment]
Oh, sorry. I hadn't noticed your advice (the emails were classified as Spam by MS Exchange...), but I have now created a new ticket over there. Thanks, that's what I was looking for since I just got an instruction to report the issue here first.
