### ISSUE TITLE
Release of iot service client(1.9.24) and deps(0.1.2) is not synced on maven repo

### ISSUE THREAD

**Issue by zhang-hua** [Azure/azure-iot-sdk-java#142]
- **OS and version used:** <VERSION> 
Windows 10
- **Java runtime used:** <VERSION> 
JDK 1.8.0_141
- **SDK version used:** <VERSION> 
Java SDK Dependency (com.microsoft.azure.sdk.iot:iot-deps:0.1.2)
- ** IDE:**: 
IntelliJ IDEA

# Description of the issue:

The getDevicesAsync call against RegistryManager did not return and hang due to the iot-deps-0.1.2.jar  on maven is not updated with latest release. 

How to reproduce:
* Download iot-deps-0.1.2.jar from http://repo1.maven.org/maven2/com/microsoft/azure/sdk/iot/iot-deps/0.1.2/iot-deps-0.1.2.jar
* Decompress the jar archive 
* Check DeviceParse.class under com/microsoft/azure/sdk/iot/deps/serializer/
* It is missing but should be expected there  because: https://github.com/Azure/azure-iot-sdk-java/blob/master/deps/src/main/java/com/microsoft/azure/sdk/iot/deps/serializer/DeviceParser.java

Same problem exists for iot service client 1.9.24.
http://repo1.maven.org/maven2/com/microsoft/azure/sdk/iot/iot-service-client/1.9.24/iot-service-client-1.9.24.jar

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by prmathur-microsoft** [comment]
Maven package with newer version has been released. Closing this now. Feel free to reopen if you see any further issues.
