### ISSUE TITLE
Enforcing TLS 1.2

### ISSUE THREAD

**Issue by DeveloperBeginner** [Azure/azure-iot-sdk-java#1427]
OS and version used: Android 6.0.1

Java runtime used: 1.8.0

SDK version used: 1.19.0

I create a device client object using the following code
DeviceClient deviceClient = DeviceClient.createFromSecurityProvider(iotHubUri, deviceId, securityProviderX509, IotHubClientProtocol.AMQPS );

And then I open the device client connection.
deviceClient.open();

I want to enforce TLS 1.2 for all communication between Android app and the IoT platform. How can we do this?

**Comment by timtay-microsoft** [comment]
To add onto the above, the Java SDK itself enforces TLS 1.2 by default. This behavior can only be changed by providing your own SSLContext instance to the SDK when initializing your clients. 

https://github.com/Azure/azure-iot-sdk-java/blob/ef780172c96a323b1ea0d96e4409b01ee14682f3/deps/src/main/java/com/microsoft/azure/sdk/iot/deps/auth/IotHubSSLContext.java#L36

**Comment by azabbasi** [comment]
Please feel free to re-open the issue if you have any other questions/concerns. 
Thank you
