### ISSUE TITLE
[Bug Report] Java iot sdk Custom module (using Module client) automatic reconnection not happening untill restart of module

### ISSUE THREAD

**Issue by prashantg077** [Azure/azure-iot-sdk-java#1428]
# Context

- **OS and version used:**  (Windows 10, Ubuntu 18.04, etc. )
- **Java runtime used:** jdk11
- **SDK version used:** 1.21.1

## Description of the issue
USE CASE
Reli run of sending C2D messages with 75messages/min 
ModuleA ---> uses device client to recieve C2D message and then redirects to ModuleB using configured routes and TTL
ModuleB ----> uses module client to recieve messages.

ISSUE
custom module (ModuleB ) that uses module client to recieve messages gets disconnected and stops recieving any messages although the module was up and running but connectivity was lost and no reconnection happened.

## Code sample exhibiting the issue
moduleRecieverClient = ModuleClient.createFromEnvironment(IotHubClientProtocol.AMQPS);
moduleRecieverClient.open();

## Console log of the issue
EdgeHub logs added , 

<4> 2021-12-02 04:37:06.146 +00:00 [WRN] - Module devedh/ReceiverModuleB is not connected
<4> 2021-12-02 04:38:06.147 +00:00 [WRN] - Module devedh/ReceiverModuleB is not connected
<6> 2021-12-02 04:39:01.848 +00:00 [INF] - New token received on the Cbs link
<6> 2021-12-02 04:39:01.848 +00:00 [INF] - Token updated for devedh/ReceiverModule
<4> 2021-12-02 04:39:06.148 +00:00 [WRN] - Module devedh/ReceiverModuleB is not connected
<6> 2021-12-02 04:39:08.636 +00:00 [INF] - Entering periodic task to reauthenticate connected clients
<6> 2021-12-02 04:39:14.667 +00:00 [INF] - New token received on the Cbs link
<6> 2021-12-02 04:39:14.667 +00:00 [INF] - Token updated for devedh/ReceiverModuleA
<6> 2021-12-02 04:39:22.200 +00:00 [INF] - New token received on the Cbs link
<6> 2021-12-02 04:39:22.200 +00:00 [INF] - Token updated for devedh/ReceiverModuleE
<6> 2021-12-02 04:39:42.311 +00:00 [INF] - New token received on the Cbs link
<6> 2021-12-02 04:39:42.311 +00:00 [INF] - Token updated for devedh/ReceiverModuleC
<6> 2021-12-02 04:39:57.655 +00:00 [INF] - New token received on the Cbs link
<6> 2021-12-02 04:39:57.655 +00:00 [INF] - Token updated for devedh/ReceiverModuleD
<4> 2021-12-02 04:40:06.149 +00:00 [WRN] - Module devedh/ReceiverModuleB is not connected
<6> 2021-12-02 04:40:15.004 +00:00 [INF] - New token received on the Cbs link
<6> 2021-12-02 04:40:15.004 +00:00 [INF] - Token updated for devedh/ReceiverModuleG
<6> 2021-12-02 04:40:16.621 +00:00 [INF] - New token received on the Cbs link
<6> 2021-12-02 04:40:16.621 +00:00 [INF] - Token updated for devedh/ReceiverModuleH
<6> 2021-12-02 04:40:29.571 +00:00 [INF] - New token received on the Cbs link
<6> 2021-12-02 04:40:29.571 +00:00 [INF] - Token updated for devedh/ReceiverModuleF
<6> 2021-12-02 04:40:41.809 +00:00 [INF] - Request starting HTTP/1.1 GET http://edgehub:9600/metrics  
<6> 2021-12-02 04:40:41.810 +00:00 [INF] - Request finished in 1.6879ms 200 text/plain; version=0.0.4; charset=utf-8
<6> 2021-12-02 04:41:02.734 +00:00 [INF] - New token received on the Cbs link
<6> 2021-12-02 04:41:02.734 +00:00 [INF] - Token updated for devedh/gatewaymodule
<4> 2021-12-02 04:41:06.149 +00:00 [WRN] - Module devedh/ReceiverModuleB is not connected
<4> 2021-12-02 04:42:06.149 +00:00 [WRN] - Module devedh/ReceiverModuleB is not connected
<4> 2021-12-02 04:43:06.149 +00:00 [WRN] - Module devedh/ReceiverModuleB is not connected

**Comment by timtay-microsoft** [comment]
Can you share the module client logs for Module B in this scenario?

**Comment by jamdavi** [comment]
We have added more improvements in the latest release that should help with this issue and others.

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2021-12-15
