### ISSUE TITLE
[Bug Report] Azure IOT( iot-device-client ) sdk java (1.33.1) Device client gets stuck not receiving messages anymore.

### ISSUE THREAD

**Issue by prashantg077** [Azure/azure-iot-sdk-java#1429]
# Context

- **OS and version used:** (Windows 10, Ubuntu 18.04, etc. )
- **Java runtime used:** jdk 11
- **SDK version used:** 1.33.1
## Description of the issue
Scenario ---> Reli run of application (edge module ) with C2D messages . 
                      Standard S1 Tier
                      75 messages/min sent from an application deployed on Azure cloud.
                      runs for 3-4 hrs without any issues , all messages are received and processed. 
Issue -----> After a while say 4 hrs on run  , Device client gets stuck and stops processing any messages from IOT Hub. Although connection is still established with IoT hub but messages are not handled by device client. 

## Code sample exhibiting the issue
Device Client created using X509 cert based authentication
Device client is opened
Device client has a message callback where it receives and acknowledges the messages.

NOTE --- Upon restart also the messages are not received for an hour untill the messages in the IOT Hub queue are expired with default 1 hr TTL.

## Console log of the issue

Does not show any thing in the logs only the messages last processed is shown. No exceptions are shown.

**Comment by jamdavi** [comment]
We have added more improvements in the latest release that should help with this issue and others.

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2021-12-15
