### ISSUE TITLE
Null device id should be allowed for DeviceTwinDevice object when scheduling twin job

### ISSUE THREAD

**Issue by zhang-hua** [Azure/azure-iot-sdk-java#143]
- **OS and version used:** <VERSION> Windows 10

- **Java runtime used:** <VERSION> JDK 1.8.0_141

- **SDK version used:** <VERSION>  Java Service Client (com.microsoft.azure.sdk.iot:iot-service-client:1.9.24)

- **IDE**:  IntelliJ IDEA

# Description of the issue:

It make sense to allow schedule a twin update job without specifying Device Id in DeviceTwinDevice object because query condition will filter the target devices. But current it is not allowed and will fail with IllegalArgumentException thrown in DeviceTwinDevice  constructor.

see the code below:

 public DeviceTwinDevice(String deviceId) throws IllegalArgumentException
    {
        if (deviceId == null || deviceId.length() == 0)
        {
            /*
            **Codes_SRS_DEVICETWINDEVICE_25_002: [** The constructor shall throw IllegalArgumentException if the input string is empty or null.**]**
             */
            throw new IllegalArgumentException("Device ID cannot be null or empty");
        }
...
}

Error message:
java.lang.IllegalArgumentException: Device ID cannot be null or empty
                at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwinDevice.<init>(DeviceTwinDevice.java:41)

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by prmathur-microsoft** [comment]
This issue has been resolved and maven packages are on maven central. Please feel free to reopen if you see any further issues.
