### ISSUE TITLE
Unknown job type is returned by IotHub response but not supported in JobType enumeration

### ISSUE THREAD

**Issue by zhang-hua** [Azure/azure-iot-sdk-java#144]
- **OS and version used:** <VERSION> Windows 10
- **Java runtime used:** <VERSION> JDK 1.8.0_141
- **SDK version used:** <VERSION> Java SDK Dependency (com.microsoft.azure.sdk.iot:iot-deps:0.1.2)
- **IDE:**: IntelliJ IDEA

# Description of the issue:

When the jobs are retrieved from IoTHub, some jobs have ‘unknown’ job type which always fails JobClient.getJob and getNextJob method.
com.microsoft.azure.sdk.iot.service.jobs.JobType
public enum JobType
{
    // missing unknown value will fail JobClient to get jobs
    //unknown,  
    scheduleDeviceMethod,
    scheduleUpdateTwin
}

Error Message:
java.lang.IllegalArgumentException: No enum constant com.microsoft.azure.sdk.iot.service.jobs.JobType.unknown
                at java.lang.Enum.valueOf(Enum.java:238)
                at com.microsoft.azure.sdk.iot.service.jobs.JobType.valueOf(JobType.java:8)
                at com.microsoft.azure.sdk.iot.service.jobs.JobResult.<init>(JobResult.java:125)
                at com.microsoft.azure.sdk.iot.service.jobs.JobClient.getJob(JobClient.java:240)
              

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by prmathur-microsoft** [comment]
This issue has been resolved and maven packages are on maven central. Please feel free to reopen if you see any further issues.
