### ISSUE TITLE
[Bug Report] C2D messages from IoT Hub throw ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by careliot** [Azure/azure-iot-sdk-java#1444]
# Context

- **OS and version used:** Windows 10 or Linux 4.4.227-gentoo x86_64 (same on both)
- **Java runtime used:** 1.8u202
- **SDK version used:** 1.33.1, tried 1.33.0 too
- **Paho library version used:** 1.2.6

## Description of the issue
When receiving C2D messages from IoT Hub, SDK crashes with the attached error (ArrayIndexOutOfBoundsException) before any callback is called. This is happening both on our implementation and with the standard examples provided by Microsoft on GitHub. We're using MQTT or MQTT_WS protocol.

IoT Hub side, we're sending valid JSON content, and we tried both with or without properties appended to the message, but the result is the same.

We need some guidance on understanding what could be the issue here.

## Console log of the issue
[stacktrace.txt](https://github.com/Azure/azure-iot-sdk-java/files/7720956/stacktrace.txt)

**Comment by jamdavi** [comment]
@careliot I will try to reproduce this with the standard samples. Does this happen right away or does it take time to get into this situation?

What it looks like is a property is getting sent with no value, so something like mqtt://host/topic?proprerty1=&property2=value

Here is the affected code

https://github.com/Azure/azure-iot-sdk-java/blob/af8ebfb36c8ae9e607ffbc0f6a57346eb59c3923/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/Mqtt.java#L476-L480

**Comment by careliot** [comment]
@jamdavi thank you for your fast response. It happens right away, just some moments after we sent the message from the Hub.

**Comment by jamdavi** [comment]
@careliot I ran a test sending a message every second for a few minutes and didn't run into the issue.

Are you using the Service Client or are you using the Azure Portal?

**Comment by careliot** [comment]
@jamdavi we are using the portal. As mentioned, we tried various (valid) JSON bodies and a combination of 0 or more properties attached to the message

**Comment by jamdavi** [comment]
Ok I see, this is a problem with Preview version of the IoT Hub. When I do the same against the non-preview version the tests pass. Let me get the service team involved.

**Comment by jamdavi** [comment]
@careliot The service team has acknowledged the regression in the preview version of the hub. With the holidays coming up I am not sure when they will correct this behavior to match the current non-preview hub.

I am going to work on a code fix this week to work around this issue in case it comes up again somehow.

**Comment by careliot** [comment]
@jamdavi thank you. We recreated the Hub without the preview option to work around this, and it's working now (this fixed another issue with AMQPS too). So it's not a top priority for us, in case you need a more relaxed schedule.
