### ISSUE TITLE
ContinuationToken exposure for DeviceTwin 

### ISSUE THREAD

**Issue by timlaverty** [Azure/azure-iot-sdk-java#145]
Preconfigured solutions work, Java version of the IoTHubManager.

# Description of the issue:
IotHub Java SDK 1.5.22 doesn't expose continuationToken functions of device twin query to the client. You can only use DeviceTwin methods hasNextDeviceTwin and getNextDeviceTwin to query device twins. The request and response continuationToken are private members encapsulated in Query. This is not  equivalent to IotHub dotnet SDK. We need the Java SDK to expose this functionality to the client.

# Code sample exhibiting the issue:
com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwin
-          public synchronized DeviceTwinDevice getNextDeviceTwin(Query deviceTwinQuery) throws IOException, IotHubException, NoSuchElementException
-          public synchronized boolean hasNextDeviceTwin(Query deviceTwinQuery) throws IotHubException, IOException
-          …
 
com.microsoft.azure.sdk.iot.service.devicetwin.Query
-          continueQuery
-          getContinuationToken
-          …

**Comment by timtay-microsoft** [comment]
The fix for this issue is now released. See the release below for versions:

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-10-23 

I will close this issue for now. Feel free to re-open if it did not fix your issues.
