### ISSUE TITLE
[feature request] Reduce the amount of log messages

### ISSUE THREAD

**Issue by gabrielandrade2** [Azure/azure-iot-sdk-java#1457]
I think that the SDK is too verbose on the execution of some simple actions, especially `device.transport.IotHubTransport`.
This class generates a ton of INFO log message whenever there is message sent or an update to device twins, for example:
```
14:22:00.353 INFO device.transport.IotHubTransport Message was queued to be sent later ( Message details: Correlation Id [366df651-4d31-4619-ac2b-3a81a4254677] Message Id [13] )
14:22:00.353 INFO device.transport.IotHubTransport Sending message ( Message details: Correlation Id [366df651-4d31-4619-ac2b-3a81a4254677] Message Id [13] )
14:22:00.353 INFO device.transport.IotHubTransport Message was queued to be sent later ( Message details: Correlation Id [c2aea8e7-014a-4fde-acf4-ff93e9d030e7] Message Id [d2e0ea87-d612-4b7e-af5f-0cd4fc97dc8c] Request Id [c2aea8e7-014a-4fde-acf4-ff93e9d030e7] Device Operation Type [DEVICE_OPERATION_TWIN_UPDATE_REPORTED_PROPERTIES_REQUEST] )
14:22:00.354 INFO device.transport.IotHubTransport Sending message ( Message details: Correlation Id [c2aea8e7-014a-4fde-acf4-ff93e9d030e7] Message Id [d2e0ea87-d612-4b7e-af5f-0cd4fc97dc8c] Request Id [c2aea8e7-014a-4fde-acf4-ff93e9d030e7] Device Operation Type [DEVICE_OPERATION_TWIN_UPDATE_REPORTED_PROPERTIES_REQUEST] )
14:22:00.834 INFO device.transport.IotHubTransport Message was received from IotHub ( Message details: Correlation Id [c2aea8e7-014a-4fde-acf4-ff93e9d030e7] Message Id [1d1da470-0ede-413b-b25c-ff809cf04d0b] Request Id [c2aea8e7-014a-4fde-acf4-ff93e9d030e7] Device Operation Type [DEVICE_OPERATION_TWIN_UPDATE_REPORTED_PROPERTIES_RESPONSE] )
```
This type of message flood my log files, as the INFO level is set by default to all the libraries on my project.
I could make an exception for the IoT Hub SDK, but I believe that those message could be more suitable for a DEBUG level.

Could a review on the log levels be made throughout the code? Or could we have a way to configure the level for this kind of messages.

Thank you.

**Comment by brycewang-microsoft** [comment]
Hi @gabrielandrade2,

Thanks for submitting this FR and helping us improve the quality of our SDK repo! To address this, I open this [PR ](https://github.com/Azure/azure-iot-sdk-java/pull/1459)to modify the logging level for some statements so the executions won't be too verbose. Feel free to review the changes and meanwhile let us know what statements in particular are annoying you as well.

**Comment by gabrielandrade2** [comment]
Hello @brycewang-microsoft,

Thanks for your prompt reply!

The messages that are most annoying to me are, in addition to the ones you already changed on the PR, the following:

- `Message was received from IotHub ({})`, on line 285; 
- `Sending message ({})`, on line 1491.

If those could also be changed to "debug" level, it would be great for me!


As one last request, I think that the log of the exception on the line 130 of `transport.mqtt.Mqtt.java` is rather unnecessary. 
It prints the following stack trace at every failure to connect / reconnect to the cloud, which clogs up the log file.
Also, the exception is thrown and the user gets it from calling `DeviceClient.open()`, so he can chooses to print it if he wants at that point.
```
13:21:41.002 WARN transport.mqtt.Mqtt Exception encountered while sending MQTT CONNECT packet
org.eclipse.paho.client.mqttv3.MqttSecurityException: Not authorized to connect
        at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:28) ~[?:?]
        at org.eclipse.paho.client.mqttv3.internal.ClientState.notifyReceivedAck(ClientState.java:1053) ~[?:?]
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:151) ~[?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

Once again, thank you for your support.

**Comment by brycewang-microsoft** [comment]
@gabrielandrade2, thanks for reaching back to us! We aligned these further so that the log statements on INFO level won't be overwhelming for regular use. 

Hope this could help!

**Comment by gabrielandrade2** [comment]
@brycewang-microsoft, thank you very much for your quick support.
I am sure this change will help.
