### ISSUE TITLE
Missing eTag property when getting device twin

### ISSUE THREAD

**Issue by zhang-hua** [Azure/azure-iot-sdk-java#146]
- **OS and version used:** <VERSION> 

- **Java runtime used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

ETag property should be parsed and set for DeviceTwinDevice at:
com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwin:
    public void getTwin(DeviceTwinDevice device) throws IotHubException, IOException{}

https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java#L103

adding this line: 
device.setETag(device.getTwinParser().getETag());

**Comment by prmathur-microsoft** [comment]
Thanks for reporting this issue. We will work on fixing it.

**Comment by mamokarz** [comment]
I'm fixing it.

**Comment by prmathur-microsoft** [comment]
A maven package with the fix has been released. Closing this. Feel free to reopen if you see any further issues
