### ISSUE TITLE
[Technical Question] Sending events during network outage 

### ISSUE THREAD

**Issue by bouff** [Azure/azure-iot-sdk-java#1466]
Hello,

We have a question on how events are handled during a network outage.

Our application encountered an OOM exception in the following scenario:

- Due to the network outage, the transport state is `IotHubConnectionStatus.DISCONNECTED_RETRYING` (expected).
- During the outage, method `sendEventAsync` is called on class `DeviceClient`. The application happens to be generating a lot of telemetry in this scenario.
- After some time, the java process runs out of memory: `Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "azure-iot-sdk-ConnectionReconnectionTask:some-id-1"`

Looking at the code in class `IoTHubTransport`,  events continue to accumulate. For instance, member `waitingPacketsQueue` is a `ConcurrentLinkedQueue` - which is by definition [unbounded](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentLinkedQueue.html).

Figure we'd raise a technical question since addressing this scenario could be either an enhancement or a bug (depending on the design). Or perhaps this responsibility falls on the caller?

The only related mention in the javadoc I could locate is:
```
 The client buffers messages while the network is down, and re-sends them when
 the network comes back online. It also batches messages to improve
 communication efficiency (HTTPS only).
```

Thanks for your time!

**Comment by timtay-microsoft** [comment]
Hi there @bouff, thanks for the question. This SDK doesn't attempt to protect users from OutOfMemory exceptions like these. In general, it is on the user to not keep queueing messages to the point where such exceptions can happen. 

That said, if you are seeing memory usage grow over prolonged reconnection periods in spite of not queueing any new messages, then that may be an SDK memory leak bug. Are you seeing these OutOfMemory exceptions regardless of number of messages queued?

**Comment by bouff** [comment]
Thanks @timtay-microsoft for the clarification.

We'll need to re-adjust how we handle events during a (prolonged) network outage.  After that change is place, we'll monitor memory use and ensure there isn't a leak.
