### ISSUE TITLE
[Technical Question] Upgrade Path from lts_06_2021

### ISSUE THREAD

**Issue by sesu-bio** [Azure/azure-iot-sdk-java#1469]
Hi,
we are currently on the lts_06_2021 branch and we plan to upgrade to the next LTS branch one it's released. To minimize the time we are stuck on a version that is out of support, we consider starting the work to upgrade to a newer release soon (in a branch). But this only makes sense if there already is a release with APIs that are close to the next LTS one.
Do you think this is a sensible approach to start work soon or will there too many breaking changes until the next LTS release?
Will the next LTS release still be based on the 1.x version or the 2.x preview?

Thanks in advance.

**Comment by timtay-microsoft** [comment]
We plan on doing one final LTS release on the 1.x version clients before we release the 2.x version clients, so you shouldn't expect any breaking changes from our next LTS.

**Comment by sesu-bio** [comment]
That is great news. Thank you for your quick reply!
