### ISSUE TITLE
[Bug Report] Memory Leak on client unregistration with MultiplexingClient

### ISSUE THREAD

**Issue by gmousset** [Azure/azure-iot-sdk-java#1478]
# Context

- **OS and version used:** Docker container based on alpine 3.15 (eclipse-temurin:17-alpine)
- **Java runtime used:** openjdk version "17.0.1" 2021-10-19
- **SDK version used:** iot-device-client:1.34.2

## Description of the issue
I work on a gateway for iot devices. Devices are connected to my server application and the application is connected to the IoT Hub through a multiplexed AMQP connection (MultiplexingClient).
Each time a device connects to the gateway, a DeviceClient is created and registered to the MultiplexingClient.
Each time a device disconnects, the DeviceClient is unregisters from the MultiplexingClient.
To send command to the devices through the IoT Hub I subscribe to deviceMethod.

Connections, disconnection, device-to-cloud and cloud-to-device messages, everything seems ok but, during stress test with a lot of connections/disconnections the application crash after some hours because of excessive memory consumption (the application container is managed by k8s and we set limits).

We also noticed than the more the application run, the more the response time to cloud-to-device request is bad: about 90 ms after the beginning more than 10s after few hours.

I profiled the application and it seems there is a memory leak. All objects are not released after device disconnection, and specifically objects on DeviceMethod.

I supposed there's a link with my increasingly bad response times.

Below the capture of the profiler after few hours:
- 749 living DeviceClient objects is more or less the actual devices count connected at this moment
- 15347 living objects for DeviceClientConfig and DeviceMethod callbacks seems the origin of my issues.

![image](https://user-images.githubusercontent.com/766129/156567355-a59221f8-00b3-4ced-8638-4f4998b7a41d.png)

Thanks for your support!

## Code sample exhibiting the issue

Here, a extract of my kotlin code where I register/unregister devices

```
    val deviceConnections = mutableMapOf<String, DeviceClient>()
    private val multiplexingClient = MultiplexingClient(hubProperties.hostName, IotHubClientProtocol.AMQPS)

    init {
        this.multiplexingClient.open()
    }
    
    /**
     * Open connection tu IoT Hub and reference it.
     */
    fun openConnection(
        deviceId: String,
        key: String,
        onConnectionClose: () -> Unit
    ) {
        // check if there's already a connection
        if (this.deviceConnections[deviceId] == null) {
            try {
                val deviceConnectionString = this.connectionStringUtils.deviceConnectionString(deviceId, key)
                val client = DeviceClient(deviceConnectionString, IotHubClientProtocol.AMQPS)

                client.registerConnectionStatusChangeCallback(
                    { status, reason, throwable, _ ->
                        this.logger.info(
                            "connection status has changed to '{}', reason: {}, throwable: {}",
                            status,
                            reason,
                            throwable
                        )

                        if (status == IotHubConnectionStatus.CONNECTED) {
                            this.deviceConnections[deviceId] = client
                            this.listen(deviceId)
                        }

                        if (status == IotHubConnectionStatus.DISCONNECTED) {
                            this.deviceConnections.remove(deviceId)
                            onConnectionClose()
                        }
                    },
                    null
                )

                this.multiplexingClient.registerDeviceClient(client)
            } catch (e: Exception) {
                this.logger.warn("cannot connect device '$deviceId' to iot hub: ${e.message}")
            }
        } else {
            this.logger.warn("connection already opened for {}", deviceId)
        }
    }

    /**
     * Close connection to IoT Hub and remove reference.
     */
    fun closeConnection(
        deviceId: String
    ) {
        val client = this.deviceConnections[deviceId]
        if (client != null) {
            this.multiplexingClient.unregisterDeviceClient(client)
            this.logger.info("close iot hub connection for device '$deviceId'")
        } else {
            this.logger.warn("device '$deviceId' was not connected to iot hub")
        }
    }
    
    /**
     *
     */
	fun listen(
        deviceId: String
    ) {
        this.getClientForDeviceAndApply(
            deviceId,
            { deviceClient ->
                try {
                    deviceClient.subscribeToDeviceMethod(
                        { methodName, methodData, _ ->
                            this.logger.debug("$deviceId - direct method call received for method $methodName")
                            when (methodName) {
                                "meth0" -> doSomething0()
                                "meth1" -> doSomething1()
                                else -> this.logger.warn("$deviceId - unexpected direct method name $methodName")
                            }
                            this.logger.debug("$deviceId - send direct method response")
                            return@subscribeToDeviceMethod DeviceMethodData(200, "OK")
                        },
                        null,
                        { responseStatus, _ ->
                            this.logger.debug("$deviceId - iot hub device method callback status: $responseStatus")
                        },
                        null,
                    )
                } catch (e: Exception) {
                    this.logger.error("$deviceId - direct method handling error: ${e.message}")
                }
            },
            {
                this.logger.warn("no iot hub device client found for id $deviceId")
            },
        )
    }

```

**Comment by timtay-microsoft** [comment]
Thanks for the thorough write up on this. It does appear to be a bug in the SDK, so we'll try to get this fixed soon.

We're just about to release our v2 SDK, so our v1 SDK (which is what you are using) won't get this bug fix though. Fortunately, the MultiplexingClient didn't change much in this major version revision, and the device client code just had it's methods renamed a bit as well, so it shouldn't be a hard transition to make if you are willing to upgrade to it. I'll be putting out a more thorough migration guide in the next few work days, so keep an eye out for that as well.

**Comment by timtay-microsoft** [comment]
On small question on the repro code, though. Does your map ```deviceConnections``` ever "dispose" of an unused device client by removing it from the map? Or would this map contain 15347 entries at the time when you are seeing 15347 instances of DeviceClientConfig/DeviceMethod in memory?

**Comment by gmousset** [comment]
Thanks for your answer.
The map only contains connected client, clients are removed on disconnect.
Do you know when the v2 will be released ?

**Comment by timtay-microsoft** [comment]
We're aiming to get the v2 released next week

**Comment by timtay-microsoft** [comment]
I'm taking a look into this issue now. Out of curiosity, what profiler are you using here?

**Comment by gmousset** [comment]
I use VisualVM. Thx.

**Comment by timtay-microsoft** [comment]
#1487 should fix this issue for you. From my local testing, I was able to repro the behavior you described above, and with the fix, there are no more leaked instances of config/methodsCallback/etc.

**Comment by timtay-microsoft** [comment]
We're aiming to do a release once we get #1486 checked in, FYI.

**Comment by gmousset** [comment]
Thank you @timtay-microsoft! Now there's no more latency on cloud-to-device messages.
The service is more stable, however I notice an unusual memory consomption. I have to investigate more, but it seems to be about org.apache.qpid.proton.engine.impl.LinkNode and org.apache.qpid.proton.amqp.transport.ErrorCondition.
Instances are indirectly created by AmqpsIotHubConnection and objects persists after device disconnection.
Have a nice week end

**Comment by gmousset** [comment]
Hi, I profiled my application and as previously said I can confirm you some objects are not released after devices disconnection.

I have 486 devices connected and that is correct if I look for DeviceClient instances.
![ok](https://user-images.githubusercontent.com/766129/158985114-4adf31a7-116f-4dc9-b0bb-700277c1c112.png)

But after few hours, the amount of theses objects grow up until the application crash:
![ko_nodes](https://user-images.githubusercontent.com/766129/158985042-53900cec-fed0-48e2-8e49-076daff3a5f9.png)
![ko_error](https://user-images.githubusercontent.com/766129/158985061-b2671a0a-c0cb-429f-88b4-6aa7329f1e37.png)

Thanks for your help!

**Comment by timtay-microsoft** [comment]
I'll take a look at these additional leaked class instances, too, sure

**Comment by timtay-microsoft** [comment]
#1501 should fix those resources (ErrorCondition, LinkNode, and a few others) leaking

**Comment by gmousset** [comment]
Hi @timtay-microsoft, first of all I want to thank you very much for your efficient support.
I integrated your latest commits and my application runs since Saturday without interruption.
The memory consumption management is very much better, nevertheless there are some issues left.

The first is about Message/MessageProperty/IotHubTranposrtPacket.
![002](https://user-images.githubusercontent.com/766129/160368312-0d29222a-72d1-4efd-9398-0aa0f7bbc1e4.png)
I think I have understand the cause of this: if you unregister a device before all the messages are polled from the waiting queue, the objects are not released.
I wrote a work around in my code: juste add a 5 seconds temporisation before unregister to let the time to send the last messages. May be this could be improved at SDK level?

The other point concerns proton objects:
![003](https://user-images.githubusercontent.com/766129/160369860-41affef0-2502-4bdb-82ee-fefd140ab362.png)
The cause seems to be the device unregistration, objects are also not released.

Thanks

**Comment by timtay-microsoft** [comment]
> I think I have understand the cause of this: if you unregister a device before all the messages are polled from the waiting queue, the objects are not released.
I wrote a work around in my code: juste add a 5 seconds temporisation before unregister to let the time to send the last messages. May be this could be improved at SDK level?

I agree, the SDK should be cancelling these packets as soon as a user unregisters the client that they belong to. I can get this fixed for you.

For the remaining proton-j objects, they appear to stick around because a given proton-j reactor object never clears its symbol cache. That cache can be seen [here](https://github.com/apache/qpid-proton-j/blob/b51cac846a2f8f72f8dbb838bcd1d755de8110ad/proton-j/src/main/java/org/apache/qpid/proton/codec/SymbolType.java#L37). As far as I can tell, there is no way to make a given reactor clear this cache, but I'll need to explore this a bit further.

**Comment by gmousset** [comment]
Thanks @timtay-microsoft,
I think I'm going to implement a solution based on a multiplexed clients pool. It allows me to close client after some hours and may be avoid too expensive objects cache.

**Comment by timtay-microsoft** [comment]
#1503 will fix the IoT SDK objects leaking

**Comment by timtay-microsoft** [comment]
2.0.1 has been released that fixes the last memory leak issue that lays within the scope of this SDK, so the only remaining bug is the proton-j level cache that isn't being cleared.

**Comment by gmousset** [comment]
Hi @timtay-microsoft,
After some modifications, tests and profiling, I noted that iot hub clients deletion didn't release Symbol objects.
The Symbol class has an internal **static** map that keep reference to all symbol objects...
Symbol objects seem to be "constants" strings like "amqp:open:list", "amqp:sasl-init:list", etc
So after a while, the object maps should not growth indefinitely, so it's ok, but there's also very specifics strings like deviceId and especially strings with correlation id. 
Each time a message is sent a Symbol object is instantiated and referenced and never released.

From what I could see, the "constant" Symbols are instantiated by proton-j lib but the other are instantiated directly by the IoT SDK:

```
AmqpsMethodsSenderLinkHandler(Sender sender, AmqpsLinkStateCallback amqpsLinkStateCallback, ClientConfiguration clientConfiguration, String linkCorrelationId)
    {
        super(sender, amqpsLinkStateCallback, linkCorrelationId, clientConfiguration.getModelId());

        this.senderLinkAddress = getAddress(clientConfiguration);

        //Note that this correlation id value must be equivalent to the correlation id in the method receiver link that it is paired with
        this.amqpProperties.put(Symbol.getSymbol(CORRELATION_ID_KEY), Symbol.getSymbol(CORRELATION_ID_KEY_PREFIX + this.linkCorrelationId));
        this.amqpProperties.put(Symbol.getSymbol(VERSION_IDENTIFIER_KEY), clientConfiguration.getProductInfo().getUserAgentString());
    }
```

May be ```Symbol.getSymbol(CORRELATION_ID_KEY_PREFIX + this.linkCorrelationId)``` could be replaced by ```CORRELATION_ID_KEY_PREFIX + this.linkCorrelationId``` and avoid the Symbol instantiation ?

Thanks!

**Comment by gmousset** [comment]
Thanks for your support.
I patched the sdk by replacing variable string Symbols with String instances and I see no side effects.
It seems to work correctly without thousands Symbol instances.

**Comment by timtay-microsoft** [comment]
Device client package 2.0.3 has been released with the fix for this issue, so I'm closing this thread
