### ISSUE TITLE
BufferOverflowException and Java Heap Space full

### ISSUE THREAD

**Issue by MirkoBianchetti** [Azure/azure-iot-sdk-java#148]
Hi, i want to segnalate this.
I have an app using IoTHub Java SDK and using AMQPS protocol.
I'm sending many messages, I can't quantify how many exactly because i don't know the size of the payload, however i send one message/sec with a variable one from few bytes up to 100kb (I understand that internally the sdk split it in many messages).
Looking at logs I have the java.nio.BufferoverflowException that is risen I suppose from AmqpsIotHubConnection.sendMessage because internally the function the proton engine has a limited bufferSize, that is doubled every BufferoverflowException rised. So if I understand, it isn't a problem, cause after N cycles the buffer will have the right size to accept my big message (it is better if that log doesn't appear cause fill all my logfile).
The second exception is blocking:
IotHubSendTask - java.lang.OutOfMemoryError: Java heap space: Java heap space
I think I had same problem when i tried to manage messages in my local db to bypass problems of internet down and/or power loss. I think the problem is when there is a period of down for IoT Hub connection and messages are collected in not limited queues (waitingMessages, inProgressMessages, receivedMessages, callbackList in AmqpsTransport class) and they can become very large. After that, you play move elements from a queue to another but, on big numbers, these operations keep much more busy the Garbage Collector until it explode with a Java Heap Space exception. 
I think it is the problem, can you investigate? Thanks

Bianchetti Mirko

Here the logs

> ERROR 14/09/2017 - 10:22:22.561 c.m.a.s.i.d.t.a.AmqpsIotHubConnection - java.nio.BufferOverflowException
ERROR 14/09/2017 - 10:22:22.561 c.m.a.s.i.d.t.a.AmqpsIotHubConnection - java.nio.BufferOverflowException
ERROR 14/09/2017 - 10:22:22.561 c.m.a.s.i.d.t.a.AmqpsIotHubConnection - java.nio.BufferOverflowException
ERROR 14/09/2017 - 10:22:22.561 c.m.a.s.i.d.t.a.AmqpsIotHubConnection - java.nio.BufferOverflowException
ERROR 14/09/2017 - 10:22:22.770 c.m.a.s.i.d.t.a.AmqpsIotHubConnection - java.nio.BufferOverflowException
ERROR 14/09/2017 - 10:22:25.049 c.m.a.s.i.d.t.a.AmqpsIotHubConnection - java.nio.BufferOverflowException
ERROR 14/09/2017 - 10:22:25.050 c.m.a.s.i.d.t.a.AmqpsIotHubConnection - java.nio.BufferOverflowException
ERROR 14/09/2017 - 10:22:25.050 c.m.a.s.i.d.t.a.AmqpsIotHubConnection - java.nio.BufferOverflowException
ERROR 14/09/2017 - 10:22:25.784 c.m.a.s.i.d.t.a.AmqpsIotHubConnection - java.nio.BufferOverflowException
ERROR 14/09/2017 - 10:22:25.958 c.m.a.s.i.d.t.a.AmqpsIotHubConnection - java.nio.BufferOverflowException
ERROR 14/09/2017 - 10:22:25.958 c.m.a.s.i.d.t.a.AmqpsIotHubConnection - java.nio.BufferOverflowException
ERROR 14/09/2017 - 10:22:26.162 c.m.a.s.i.d.t.a.AmqpsIotHubConnection - java.nio.BufferOverflowException
ERROR 14/09/2017 - 10:22:26.566 c.m.a.s.i.d.t.IotHubSendTask - java.lang.OutOfMemoryError: Java heap space: Java heap space
ERROR 14/09/2017 - 10:22:38.966 c.m.a.s.i.d.t.IotHubSendTask - java.lang.OutOfMemoryError: Java heap space: Java heap space
WARN  14/09/2017 - 10:22:40.532 c.m.a.s.i.d.Message - The message with messageid 1a700186-6d85-4955-9442-13873da16a49 expired on Thu Sep 14 10:22:39 CEST 2017, method name is isExpired 
WARN  14/09/2017 - 10:22:40.956 c.m.a.s.i.d.Message - The message with messageid d43fbe72-e7f8-46db-95a3-9cdc3181ec64 expired on Thu Sep 14 10:22:40 CEST 2017, method name is isExpired 
WARN  14/09/2017 - 10:22:41.166 c.m.a.s.i.d.Message - The message with messageid 346d58e0-2884-4c14-a5b3-3a9ae75f639b expired on Thu Sep 14 10:22:41 CEST 2017, method name is isExpired 
WARN  14/09/2017 - 10:22:41.166 c.m.a.s.i.d.Message - The message with messageid d5fdccc1-963b-4ab8-8643-88c39bae50a9 expired on Thu Sep 14 10:22:41 CEST 2017, method name is isExpired 
WARN  14/09/2017 - 10:22:41.369 c.m.a.s.i.d.Message - The message with messageid a597e4f1-12b3-47db-bb4e-1c1145e84453 expired on Thu Sep 14 10:22:41 CEST 2017, method name is isExpired 
WARN  14/09/2017 - 10:22:41.369 c.m.a.s.i.d.Message - The message with messageid 1d1c7955-23a3-4ddd-8f62-02da46a99199 expired on Thu Sep 14 10:22:41 CEST 2017, method name is isExpired 
WARN  14/09/2017 - 10:22:41.369 c.m.a.s.i.d.Message - The message with messageid b0042822-c176-48c2-adc8-2c4ffa4092c4 expired on Thu Sep 14 10:22:41 CEST 2017, method name is isExpired 
WARN  14/09/2017 - 10:22:41.582 c.m.a.s.i.d.Message - The message with messageid 3edb1aef-881a-4435-88ec-19500add51b6 expired on Thu Sep 14 10:22:41 CEST 2017, method name is isExpired 
WARN  14/09/2017 - 10:22:41.583 c.m.a.s.i.d.Message - The message with messageid 5f4fd5de-b549-4650-bee4-f3d7aa243b48 expired on Thu Sep 14 10:22:41 CEST 2017, method name is isExpired 
WARN  14/09/2017 - 10:22:41.583 c.m.a.s.i.d.Message - The message with messageid 2a49fcc7-580b-47c9-96b9-ec1299121c8a expired on Thu Sep 14 10:22:41 CEST 2017, method name is isExpired 
WARN  14/09/2017 - 10:22:41.583 c.m.a.s.i.d.Message - The message with messageid f5807041-4549-4f32-a152-d6c2ba6df499 expired on Thu Sep 14 10:22:41 CEST 2017, method name is isExpired 
WARN  14/09/2017 - 10:22:41.583 c.m.a.s.i.d.Message - The message with messageid 2437b772-e4b6-4669-9135-c7e5e1e97a73 expired on Thu Sep 14 10:22:41 CEST 2017, method name is isExpired 
ERROR 14/09/2017 - 10:22:45.642 c.m.a.s.i.d.t.IotHubSendTask - java.lang.OutOfMemoryError: Java heap space: Java heap space
ERROR 14/09/2017 - 10:22:46.896 c.m.a.s.i.d.t.IotHubSendTask - java.lang.OutOfMemoryError: Java heap space: Java heap space
WARN  14/09/2017 - 10:22:48.520 c.m.a.s.i.d.Message - The message with messageid 9c5be491-ae46-400d-a26b-2a8cce143959 expired on Thu Sep 14 10:22:46 CEST 2017, method name is isExpired 
ERROR 14/09/2017 - 10:26:57.370 c.m.a.s.i.d.t.IotHubReceiveTask - java.lang.OutOfMemoryError: Java heap space: Java heap space
ERROR 14/09/2017 - 10:28:19.572 c.m.a.s.i.d.t.IotHubReceiveTask - java.lang.OutOfMemoryError: Java heap space: Java heap space

**Comment by prmathur-microsoft** [comment]
Thanks for the detailed explanation of the error you are seeing. I too suspect that unlimited queueing is the source of the problem as well. Also I do think it makes sense to remove java.nio.BufferOverflowException from the logs. We will work on fixing this issue.

**Comment by MirkoBianchetti** [comment]
Is actually possible to exclude sdk buffering mechanism? I do it on my app, so i only need actual sendMessage and callback function. If I can exclude your buffer maybe i can have a workaround for this problem

**Comment by prmathur-microsoft** [comment]
Actually queuing is inherent to our solution and it may not be possible to exclude using buffer.

**Comment by prmathur-microsoft** [comment]
After discussion we have concluded that we don't have to provide a new API. To resolve this issue what you can do is monitor for status messages from the callback and wait sending any further messages until you get confirmation for the messages that your restrained device can tolerate. 

For example -

Lets say you only want to queue 5 messages.

You would start sending 5 messages and wait for confirmation. You only send 6th message when you received confirmation of atleast 1 of the already sent 5 messages.
This is essentially what new API would have done too. So it is redundant to provide it when you can handle it on your own.

Let me know if this solution does not work for you.

**Comment by prmathur-microsoft** [comment]
@MirkoBianchetti please let us know if you have any further questions on the above mentioned approach.

**Comment by prmathur-microsoft** [comment]
Closing on this as I have not heard back for a while. Feel free to reopen if you see further issues.
