### ISSUE TITLE
Thread starvation in Android mobile application

### ISSUE THREAD

**Issue by mmacagno** [Azure/azure-iot-sdk-java#1492]
# Context

- **OS and version used:** Android 9 / API 28
- **SDK version used:** implementation 'com.microsoft.azure.sdk.iot:iot-device-client:1.30.1'

## Description of the issue
We have several Android applications in production posting iothub messages using the library above.
One one of these we are experiencing several crashes a day per user due to the exception below:

Fatal Exception: java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:733)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:975)
       at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1616)
       at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:342)
       at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleWithFixedDelay(ScheduledThreadPoolExecutor.java:629)
       at com.microsoft.azure.sdk.iot.device.DeviceIO.startWorkerThreads(DeviceIO.java:234)
       at com.microsoft.azure.sdk.iot.device.DeviceIO.execute(DeviceIO.java:514)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.updateStatus(IotHubTransport.java:1573)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionEstablished(IotHubTransport.java:355)
       at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:288)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:1114)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.singleReconnectAttempt(IotHubTransport.java:1328)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.reconnect(IotHubTransport.java:1254)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.handleDisconnection(IotHubTransport.java:1150)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionLost(IotHubTransport.java:336)
       at com.microsoft.azure.sdk.iot.device.transport.ReconnectionNotifier$1.run(ReconnectionNotifier.java:22)
       at java.lang.Thread.run(Thread.java:764)

**There are close to 300 threads azure-iot-sdk-IotHubReceiveTask waiting:**
azure-iot-sdk-IotHubReceiveTask
       at java.lang.Object.wait(Object.java)
       at com.microsoft.azure.sdk.iot.device.transport.IotHubReceiveTask.run(IotHubReceiveTask.java:53)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

## Code sample exhibiting the issue

`
import com.microsoft.azure.sdk.iot.device.DeviceClient;
import com.microsoft.azure.sdk.iot.device.DeviceTwin.DeviceMethodData;
import com.microsoft.azure.sdk.iot.device.DeviceTwin.Property;
import com.microsoft.azure.sdk.iot.device.DeviceTwin.TwinPropertyCallBack;
import com.microsoft.azure.sdk.iot.device.IotHubClientProtocol;
import com.microsoft.azure.sdk.iot.device.IotHubEventCallback;
import com.microsoft.azure.sdk.iot.device.IotHubMessageResult;
import com.microsoft.azure.sdk.iot.device.IotHubStatusCode;

import org.threeten.bp.LocalDateTime;
import org.threeten.bp.format.DateTimeFormatter;

import java.util.Locale;
import java.util.Observable;
import java.util.concurrent.atomic.AtomicBoolean;

public class IoTClient extends Observable implements IotHubEventCallback {
    private static IoTClient instance;

    private static final AtomicBoolean Succeed = new AtomicBoolean(false);

    private DeviceClient client;
    private boolean initialized;
    private final IotHubClientProtocol protocol;

    public static IoTClient getInstance() {
        if (instance == null) {
            synchronized (IoTClient.class) {
                if (instance == null) {
                    instance = new IoTClient();
                }
            }
        }
        return instance;
    }

    private IoTClient() {
        initialized = false;
        client = null;
        protocol = IotHubClientProtocol.MQTT;
    }

    public boolean sendEventAsync(String messageId, String payload, LocalDateTime timestamp, Object context) {
        if (!initialized) {
            showLog(Log.E, "IoTClient::sendToCloud() invoked without valid client initialized", IoTClient.class);
            return false;
        }

        if ((payload == null) || (payload.length() == 0)) {
            showLog(Log.E, "IoTClient::sendToCloud() invoked with empty payload", IoTClient.class);
            return false;
        }

        try {
            String id = messageId == null ? java.util.UUID.randomUUID().toString() : messageId;

            com.microsoft.azure.sdk.iot.device.Message msg = new com.microsoft.azure.sdk.iot.device.Message(payload);

            msg.setMessageId(id);

            DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSS");
            String creationTime = timestamp.format(dateFormat);
            msg.setProperty("iothub-creation-time-utc", creationTime);
      
            showLog(Log.W, String.format(Locale.ROOT, "IoT Hub post(message: %d, id: %s, payload: %s, timestamp: %s)", context, messageId, payload, timestamp), IoTClient.class);
            client.sendEventAsync(msg, this, context);

            return true;
        } catch (Exception e) {
            showLog(Log.E, String.format("IoT Hub post: " + "exception while sending message: %s, closing connection", e.getMessage()), IoTClient.class);
            close();
            return false;
        }
    
}
    public boolean isInitialized() {
        return initialized;
    }

    public Exception init(String connectionString) {
        try {
            showLog(Log.D, "IoTClient::init()", IoTClient.class);

            initialized = false;
            client = null;

            client = new DeviceClient(connectionString, protocol);
            client.setOperationTimeout(60 * 1000); // 1 minute timeout
            client.open();

            if (protocol == IotHubClientProtocol.MQTT) {
                MessageCallbackMqtt callback = new MessageCallbackMqtt();
                Counter counter = new Counter(0);
                client.setMessageCallback(callback, counter);
            } else {
                MessageCallback callback = new MessageCallback();
                Counter counter = new Counter(0);
                client.setMessageCallback(callback, counter);
            }
            client.subscribeToDeviceMethod(new SampleDeviceMethodCallback(), null, new DeviceMethodStatusCallBack(), null);
            Succeed.set(false);
            client.startDeviceTwin(new DeviceTwinStatusCallBack(), null, new onProperty(), null);

            do {
                Thread.sleep(100);
            }
            while (!Succeed.get());
            initialized = true;
        } catch (Exception exception) {
            showLog(Log.E, "Exception while opening IoTHub connection: " + exception.getMessage(), IoTClient.class);
            client = null;
            initialized = false;
            showLog(Log.E, "Shutting down...", IoTClient.class);
            return exception;
        }

        return null;
    }

    public void close() {
        showLog(Log.D, "IoTClient::close()", IoTClient.class);
        if (client != null) {
            try {
                // Is there a way to know if there are messages waiting to be flushed?
                client.closeNow();
                client = null;
                initialized = false;
            } catch (Exception e) {
                showLog(Log.E, "client shutdown failure: " + e.getStackTrace(), IoTClient.class);
            }
        } else {
            showLog(Log.D, "Connection was already closed.", IoTClient.class);
        }

    }

    public void execute(IotHubStatusCode status, Object context) {
        Integer i = (Integer) context;
        showLog(Log.I, "IoT Hub responded to message " + i.toString() + " with status " + status.name(), IoTClient.class);

        try {
            this.setChanged();
            this.notifyObservers(new EventCallbackObservation(status, context));
        } catch (Exception exception) {
            showLog(Log.E, "An observer did not gracefully fail, exception: " + exception.getMessage(), IoTClient.class);
        }

    }

    protected static class DeviceMethodStatusCallBack implements IotHubEventCallback {
        public void execute(IotHubStatusCode status, Object context) {
            showLog(Log.D, "IoT Hub responded to device method operation with status " + status.name(), IoTClient.class);
        }
    }

    protected static class SampleDeviceMethodCallback implements com.microsoft.azure.sdk.iot.device.DeviceTwin.DeviceMethodCallback {
        @Override
        public DeviceMethodData call(String methodName, Object methodData, Object context) {
            DeviceMethodData deviceMethodData;
            switch (methodName) {
                case "command": {
                    int status = method_command(methodData);

                    deviceMethodData = new DeviceMethodData(status, "executed " + methodName);
                    break;
                }
                default: {
                    int status = method_default(methodData);
                    deviceMethodData = new DeviceMethodData(status, "executed " + methodName);
                }
            }

            return deviceMethodData;
        }
    }

    protected static class DeviceTwinStatusCallBack implements IotHubEventCallback {
        @Override
        public void execute(IotHubStatusCode status, Object context) {
            Succeed.set((status == IotHubStatusCode.OK) || (status == IotHubStatusCode.OK_EMPTY));
            showLog(Log.D, "IoT Hub responded to device twin operation with status " + status.name(), IoTClient.class);
        }
    }

    protected static class onProperty implements TwinPropertyCallBack {
        @Override
        public void TwinPropertyCallBack(Property property, Object context) {
            showLog(Log.D, "onProperty callback for " + (property.getIsReported() ? "reported" : "desired") +
                    " property " + property.getKey() +
                    " to " + property.getValue() +
                    ", Properties version:" + property.getVersion(), IoTClient.class);

        }
    }

    // Our MQTT doesn't support abandon/reject, so we will only display the messaged received
    // from IoTHub and return COMPLETE
    static class MessageCallbackMqtt implements com.microsoft.azure.sdk.iot.device.MessageCallback {
        public IotHubMessageResult execute(com.microsoft.azure.sdk.iot.device.Message msg, Object context) {
            Counter counter = (Counter) context;
            showLog(Log.D, "Received message " + counter.toString()
                    + " with content: " + new String(msg.getBytes(), com.microsoft.azure.sdk.iot.device.Message.DEFAULT_IOTHUB_MESSAGE_CHARSET), IoTClient.class);

            counter.increment();

            return IotHubMessageResult.COMPLETE;
        }
    }

    static class MessageCallback implements com.microsoft.azure.sdk.iot.device.MessageCallback {
        public IotHubMessageResult execute(com.microsoft.azure.sdk.iot.device.Message msg, Object context) {
            Counter counter = (Counter) context;
            showLog(Log.D, "Received message " + counter.toString()
                    + " with content: " + new String(msg.getBytes(), com.microsoft.azure.sdk.iot.device.Message.DEFAULT_IOTHUB_MESSAGE_CHARSET), IoTClient.class);

            int switchVal = counter.get() % 3;
            IotHubMessageResult res;
            switch (switchVal) {
                case 0:
                    res = IotHubMessageResult.COMPLETE;
                    break;
                case 1:
                    res = IotHubMessageResult.ABANDON;
                    break;
                case 2:
                    res = IotHubMessageResult.REJECT;
                    break;
                default:
                    // should never happen.
                    throw new IllegalStateException("Invalid message result specified.");
            }

            showLog(Log.D, "Responding to message " + counter.toString() + " with " + res.name(), IoTClient.class);

            counter.increment();

            return res;
        }
    }

    // Used as a counter in the message callback.
    static class Counter {
        int num;

        Counter(int num) {
            this.num = num;
        }

        int get() {
            return this.num;
        }

        void increment() {
            this.num++;
        }

        @Override
        public String toString() {
            return Integer.toString(this.num);
        }
    }

    public class EventCallbackObservation {
        private final IotHubStatusCode status;
        private final Object context;

        public EventCallbackObservation(IotHubStatusCode status, Object context) {
            this.status = status;
            this.context = context;
        }

        public IotHubStatusCode getStatus() {
            return status;
        }

        public Object getContext() {
            return context;
        }
    }

}
`

## Console log of the issue
Have not been able to repro in debug yet.

**Comment by timtay-microsoft** [comment]
There were some known issues around threads not closing correctly upon reconnection events up until [Device Client version 1.34.0](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2021-12-15) so I'd suggest upgrading at least up to that point. Doing so should resolve this issue for you

**Comment by mmacagno** [comment]
Thanks for the prompt response. We had some issues in migrating to .34, but will try again and report back.

**Comment by mmacagno** [comment]
Did you guys change JDK min version requirements by any chance?

**Comment by mmacagno** [comment]
Actually I got a bit more info on the build failure after moving to .34:

`
FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkWatchDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:watchDebugRuntimeClasspath'.
   > Failed to transform bcprov-jdk15on-1.70.jar (org.bouncycastle:bcprov-jdk15on:1.70) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/mac/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.70/4636a0d01f74acaf28082fb62b317f1080118371/bcprov-jdk15on-1.70.jar.
         > Failed to transform '/Users/mac/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.70/4636a0d01f74acaf28082fb62b317f1080118371/bcprov-jdk15on-1.70.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeWatchDebugNativeLibs'.
> Could not resolve all files for configuration ':app:watchDebugRuntimeClasspath'.
   > Failed to transform bcprov-jdk15on-1.70.jar (org.bouncycastle:bcprov-jdk15on:1.70) to match attributes {artifactType=android-java-res, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/mac/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.70/4636a0d01f74acaf28082fb62b317f1080118371/bcprov-jdk15on-1.70.jar.
         > Failed to transform '/Users/mac/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.70/4636a0d01f74acaf28082fb62b317f1080118371/bcprov-jdk15on-1.70.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileWatchDebugJavaWithJavac'.
> Could not resolve all files for configuration ':app:watchDebugCompileClasspath'.
   > Failed to transform bcprov-jdk15on-1.70.jar (org.bouncycastle:bcprov-jdk15on:1.70) to match attributes {artifactType=android-classes-jar, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Execution failed for JetifyTransform: /Users/mac/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.70/4636a0d01f74acaf28082fb62b317f1080118371/bcprov-jdk15on-1.70.jar.
         > Failed to transform '/Users/mac/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.70/4636a0d01f74acaf28082fb62b317f1080118371/bcprov-jdk15on-1.70.jar' using Jetifier. Reason: IllegalArgumentException, message: Unsupported class file major version 59. (Run with --stacktrace for more details.)
           Suggestions:
            - Check out existing issues at https://issuetracker.google.com/issues?q=componentid:460323&s=modified_time:desc, it's possible that this issue has already been filed there.
            - If this issue has not been filed, please report it at https://issuetracker.google.com/issues/new?component=460323 (run with --stacktrace and provide a stack trace if possible).

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

`

**Comment by mmacagno** [comment]
Update: I upgraded Gradle and was able to build.
We will sanity check and report back if we are still seeing thread starvation crashes.
Closing this for now.

**Comment by mmacagno** [comment]
Thanks for the prompt reply.

We had some build issues with .34 but we’ll try again and report back.

Thanks
Mac

Sent with fat fingrs. Excuse the typos.
________________________________
