### ISSUE TITLE
Migrate to Log4j 2.x.x or better

### ISSUE THREAD

**Issue by jemackayoe** [Azure/azure-iot-sdk-java#150]
Why is this using an out dated Log4J library?! Migrate to version 2 or better library.

**Comment by prmathur-microsoft** [comment]
Thanks for raising this issue. We have it in our backlog to make the move and will address it soon. 
#51

**Comment by JMayrbaeurl** [comment]
Any update on this? Log4j 1.2.17 that's currently used by the SDK is legacy since 2015 and modern Java frameworks like Spring Boot don't support Log4j Version 1.x any more!!!

**Comment by JMayrbaeurl** [comment]
Just tested the upgrade to Log4j Version 2.11 for the Device SDK. It took me 5 minutes and I had to change 3 files (see attached).
What's the reason this wasn't done since nearly one year? Priority? Bandwidth?
[log4j2UpgradeDeviceSDK.zip](https://github.com/Azure/azure-iot-sdk-java/files/2224276/log4j2UpgradeDeviceSDK.zip)

**Comment by JMayrbaeurl** [comment]
PR is available. And I agree. Mid-term to Long-term we should use Logback and Logging facades.

**Comment by timtay-microsoft** [comment]
Much appreciated! I'll get this merged in shortly.

**Comment by timtay-microsoft** [comment]
The fix for this issue has been checked in via @JMayrbaeurl's pull request and should be released within a few days.

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released as of Device Client 1.14.0, so I'm closing this issue now.

**Comment by az-iot-builder-01** [comment]
@jemackayoe, @prmathur-microsoft, @JMayrbaeurl, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
