### ISSUE TITLE
Query job with empty jobType or jobStatus should return result

### ISSUE THREAD

**Issue by zhang-hua** [Azure/azure-iot-sdk-java#152]
- **OS and version used:** <VERSION> Windows 10
- **Java runtime used:** <VERSION> JDK 1.8.0_141
- **SDK version used:** <VERSION> Java SDK Dependency (com.microsoft.azure.sdk.iot:iot-deps:0.1.2)
- **IDE:**: IntelliJ IDEA

# Description of the issue:

Query job with empty jobType or jobStatus should return result, not just throw InvalidInputException.
Current Java SDK only support non-null jobType and jobStatus parameters in Job client query. We can not retrieve all jobs without specify them.

# Code sample exhibiting the issue:

public synchronized Query queryJobResponse(JobType jobType, JobStatus jobStatus, Integer pageSize) throws IOException, IotHubException {
if (jobType == null || jobStatus == null)
{
//Codes_SRS_JOBCLIENT_25_041: [If the input parameters are null, the queryJobResponse shall throw IllegalArgumentException.]
throw new IllegalArgumentException("jobType and jobStatus cannot be null");
}
...
# Console log of the issue:

**Comment by joyhui** [comment]
Please prioritize this issue and we use this feature in new PCS2.0 which will be release very soon.

**Comment by mamokarz** [comment]
I'm working on it.

**Comment by prmathur-microsoft** [comment]
A maven package with the fix has been released. Closing this. Feel free to reopen if you see any further issues
