### ISSUE TITLE
[Bug Report] iot-device-client defines SLF4J binding as dependency

### ISSUE THREAD

**Issue by g0rill4z** [Azure/azure-iot-sdk-java#1523]
# Context

- **OS and version used:** macOS 12.3.1
- **Java runtime used:** OpenJDK 11.0.11
- **SDK version used:** 2.0.0 / 2.0.1

## Description of the issue
`iot-device-client` 2.0.0 and 2.0.1 define a SLF4J binding as dependency in its parent POM (`iot-device-client-parent`). I assume this is not intended as it can mess up the logging of applications using the dependency. Also `iot-sdk-java` includes the `log4j-slf4j-impl` twice in its dependency management.

**Comment by brycewang-microsoft** [comment]
Hi @g0rill4z , thanks for bring this to us! I have a small [fix ](https://github.com/Azure/azure-iot-sdk-java/pull/1524) for it.

**Comment by timtay-microsoft** [comment]
Fixed by 2.0.2 which has just been released, so closing this thread
