### ISSUE TITLE
onMethodInvoked not called when it connects back from a disconnecting state on AMQPS Protocol

### ISSUE THREAD

**Issue by vullnetlimani** [Azure/azure-iot-sdk-java#1544]
# Context

- **OS and version used:** <VERSION> (Android)
- **Java runtime used:** <VERSION> (18.0.1)
- **SDK version used:** <VERSION> (iot-device-client:2.0.2)

## Description of the issue
When subscribeToMethodsAsync is called on protocol AMQPS it works fine but if a disconnection happens, and then it connects back the MethodCallback is not triggered at all.

Just for testing purposes, If cloned the repo and unwrapped the if statement on line 885 on InternalClient.java, and then when the same scenario happens everything is working fine.

But if you close the client and then open a new connection, that works as well since the Direct Method is initialized...

I hope you can look into this and make a proper solution that my self using this temporary option

On MQTT it's working without that change

**Comment by timtay-microsoft** [comment]
Can you be a bit more specific about the scenario here? Are you saying that a device client that loses connection and regains its connection via the SDK's internal retry policy stops receiving methods? Or that a device client that loses connection, fails to regain its connection via the SDK's internal retry policy, and then you manually call deviceClient.open() to stops receiving methods?

**Comment by timtay-microsoft** [comment]
Actually, I think I see what you mean here. #1545 should address this issue for you

**Comment by vullnetlimani** [comment]
Hello, yes exactly, so I've just checked the bug you addressed there as well, that's what I did after I unwrapped the if statement on line: 794 InternalClient.java class then everything started to work wonderful, but I see that you have done that on the device twin object as well, on line: 608

So basically the bug was that when you have a fresh new connection it's working but when you get a disconnection and the SDK reconnects back automatically then the direct methods were not working, the only way to make them work was to force close the connection and then open a new one.

**Comment by timtay-microsoft** [comment]
Device client package 2.0.3 has been released with the fix for this issue, so I'm closing this thread
