### ISSUE TITLE
Unable to send messages through AMPQS protocol

### ISSUE THREAD

**Issue by BanupriyaVenkatasen** [Azure/azure-iot-sdk-java#156]
Hi Team,

While sending **C2D messages(SendEvent.java) via AMPQS protocol**,it tries to connect to DeviceClient. But connection isn't getting success.Please find the log and connectionString Format below:

**Log:**

Starting...
Beginning setup.
Successfully read input parameters.
Using communication protocol AMQPS.
log4j:WARN No appenders could be found for logger (com.microsoft.azure.sdk.iot.device.IotHubConnectionString).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Successfully created an IoT Hub client.
Updated token expiry time to 2400
Lost connection to the server. Reconnection attempt 1...
Lost connection to the server. Reconnection attempt 2...
Lost connection to the server. Reconnection attempt 3...
Lost connection to the server. Reconnection attempt 4...
Lost connection to the server. Reconnection attempt 5...
Opened connection to IoT Hub.
Sending the following event messages:
{"deviceId":{deviceId},"messageId":0,"temperature":26.971887105898155,"humidity":46.544163203587686}
Wait for 2 second(s) for response from the IoT Hub...
IoT Hub responded to message {messageId} with status MESSAGE_EXPIRED
Closing
Shutting down...

**Connection String Format:**
HostName={hostname};DeviceId={deviceId};SharedAccessKey={deviceAccessKey}

**Note:**
We are able to connect to  **HTTPS, AMQPS_WS ,MQTT_WS** protocols without any issue

Kindly look into it and let me know if any additional details are required to investigate on this issue

**Comment by prmathur-microsoft** [comment]
1. Can you confirm network connectivity was not an issue when you tried this scenario ?
2. Also could you give us details of SDK version you are trying to use ?
3. You mentioned you are trying to send C2D messages "C2D messages(SendEvent.java) via AMPQS  protocol" Was it a typo ? Because send event is used to send D2C messages.

**Comment by BanupriyaVenkatasen** [comment]
Apologies for the confusion caused here.Please ignore the previous comment,below are the detailed information about the issue:

I'm following the tutorial https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-java-java-c2d.

While executing the C2D messages ,it throws below error:

Exception in thread "main" **java.io.IOException: Connection failed to be established**
	at com.microsoft.azure.sdk.iot.service.transport.amqps.AmqpSendHandler.sendComplete(AmqpSendHandler.java:341)
	at com.microsoft.azure.sdk.iot.service.transport.amqps.AmqpSend.send(AmqpSend.java:127)
	at com.microsoft.azure.sdk.iot.service.ServiceClient.send(ServiceClient.java:128)
	at com.walmart.sumo.iot.hub.App.main(App.java:32)

**ConnectionStringFormat:** HostName={hostName};SharedAccessKeyName=iothubowner;SharedAccessKey={AccessKey};

**iot-service-client version:** 1.9.26

Please let me know that am i missing any settings here and guide me to proceed further

**Comment by prmathur-microsoft** [comment]
Can you verify if your connection string for HUB works from any of the samples located here ? https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-samples/service-client-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ServiceClientSample.java#L29

**Comment by prmathur-microsoft** [comment]
@BanupriyaVenkatasen - please let us know if you have any other questions and if this scenario still doesn't work.

**Comment by prmathur-microsoft** [comment]
Closing this as I have not heard back for a while now. Feel free to reopen if the issue still exist.
