### ISSUE TITLE
[Bug Report] MQTT layer encounters NullPointerException

### ISSUE THREAD

**Issue by mahendradabiaplite** [Azure/azure-iot-sdk-java#1575]
My application reported the highest crashing issue with following bug could you please tell me the exact cause of the issue
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean zk.f.b()' on a null object reference
O
com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe Mqtt.java
com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start MqttMessaging.java
com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open MqttIotHubConnection.java
com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection IotHubTransport.java
com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.singleReconnectAttempt IotHubTransport.java
com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.reconnect IotHubTransport.java
com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.handleDisconnection IotHubTransport.java
com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.onConnectionLost IotHubTransport.java:45
com.microsoft.azure.sdk.iot.device.transport.ReconnectionNotifier$1.run ReconnectionNotifier.java:8
java.lang.Thread.run Thread.java:920

**Comment by tmahmood-microsoft** [comment]
Hi @mahendradabiaplite could you please share more details about what you are trying to achieve and also share the code snippet you are working with that would help us reproduce the issue. Thanks

**Comment by mahendradabiaplite** [comment]
Hello @tmahmood-microsoft  I have only this description in my app center logs. No other description to trace it which component of my app is causing the issue.

**Comment by mahendradabiaplite** [comment]
import android.app.* 
 import android.content.Context 
 import android.content.DialogInterface 
 import android.content.Intent 
 import android.net.ConnectivityManager 
 import android.os.Build 
 import android.os.Handler 
 import android.text.Html 
 import android.text.format.DateFormat 
 import android.util.Log 
 import androidx.appcompat.app.AppCompatActivity 
 import androidx.core.app.NotificationCompat 
 import androidx.core.app.NotificationManagerCompat 
 import androidx.core.content.ContextCompat 
 import com.github.mustachejava.DefaultMustacheFactory 
 import com.google.gson.Gson 
 import com.google.gson.GsonBuilder 
 import com.hypertrack.hyperlog.HyperLog 
  
 import com.microsoft.azure.sdk.iot.device.* 
 import com.microsoft.azure.sdk.iot.device.DeviceTwin.DeviceMethodData 
 import com.microsoft.azure.sdk.iot.device.transport.IotHubConnectionStatus 
 import kotlinx.coroutines.GlobalScope 
 import kotlinx.coroutines.launch 
 import org.greenrobot.eventbus.EventBus 
 import org.json.JSONArray 
 import org.json.JSONException 
 import org.json.JSONObject 
 import java.io.IOException 
 import java.io.StringReader 
 import java.io.StringWriter 
 import java.io.UnsupportedEncodingException 
 import java.net.URISyntaxException 
 import java.text.SimpleDateFormat 
 import java.util.* 
  
  
 class Singleton_IotHubShareInstance private constructor(){ 
  
     companion object { 
  
         /** The only instance  */ 
         private var sInstanceIotHub: Singleton_IotHubShareInstance? = null 
  
         private var client: DeviceClient? = null 
  
         fun getIotHubInstance(): Singleton_IotHubShareInstance? { 
             if (sInstanceIotHub == null) { 
                 synchronized(Singleton_IotHubShareInstance::class) { 
                     sInstanceIotHub = Singleton_IotHubShareInstance() 
                 } 
             } 
             return sInstanceIotHub 
         } 
  
         fun destroy_IotHubInstance() { 
             sInstanceIotHub = null 
         } 
  
         const val notificationIdForShipmentAssigned = 1 
         const val notificationIdForTeamInvite = 2 
         const val notificationIdForUnassignedStopOffer = 3 
         const val notificationIdForUnassignedShipmentOffer = 4 
         const val notificationIdForBulkUpdate = 5 
         const val notificationIdForStopStatusChange = 6 
         const val notificationIdForShipmentStatusChange = 7 
     } 
  
     var context: Context? = null 
  
     private var sendMessage: Message? = null 
     private var lastException: String? = null 
     internal var protocol = IotHubClientProtocol.MQTT 
     private val handler = Handler() 
     private var sendThread: Thread? = null 
     private val METHOD_SUCCESS = 200 
     private val METHOD_THROWS = 403 
     private val METHOD_NOT_DEFINED = 404 
  
     private var msgSentCount = 0 
  
     fun initilizeIotHubDeviceClient(context: Context) { 
         this.context = context 
         callInitClient() 
     } 
  
     private fun callInitClient() { 
         Thread(Runnable { 
             try { 
                 initClient() 
             } catch (e: Exception) { 
                 lastException = "Exception while opening IoTHub connection: $e" 
                 handler.post(exceptionRunnable) 
             } 
         }).start() 
     } 
  
     private fun initClient() 
     { 
         try { 
             client = DeviceClient(AppAuth_Login_Activity.user_ioTHubConnectionString, protocol) 
  
             client?.registerConnectionStatusChangeCallback(IotHubConnectionStatusChangeCallbackLogger (), Object ()) 
             client?.open() 
             val callback = MessageCallback() 
             client?.setMessageCallback(callback, context) 
             client?.subscribeToDeviceMethod(SampleDeviceMethodCallback (), context, DeviceMethodStatusCallBack (), null) 
             Log.e("Locate2u", "Iot hub connected successfully") 
         } catch (e: Exception) { 
             System.err.println("Exception while opening IoTHub connection: $e") 
             Log.e("Locate2u", "Iot hub connection failed") 
             System.out.println("Shutting down...") 
         } 
     } 
  
     fun stop() { 
         Log.i("Locate2u", "Closed iot  hub") 
         Thread(Runnable { 
             try { 
                 sendThread?.interrupt() 
                 client?.closeNow() 
                 println("Shutting down...") 
             } catch (e: Exception) { 
                 lastException = "Exception while closing IoTHub connection: $e" 
                 handler.post(exceptionRunnable) 
             } 
         }).start() 
     } 
  
  
     inner class MessageCallback : com.microsoft.azure.sdk.iot.device.MessageCallback { 
         override fun execute(msg: Message, contextMessageCallback: Any): IotHubMessageResult { 
             Log.e("mTagLocation", "Message with content: " + String(msg.bytes, Message.DEFAULT_IOTHUB_MESSAGE_CHARSET)) 
  
                             } 
                                         
  
     
  
          private fun shutDownIotHubConnection() { 
         Thread(Runnable { 
             try { 
                 sendThread?.interrupt() 
                 client?.closeNow() 
         //        HyperLog.i("mTagLocation", "@@@@@@@@@@  Shutting down...") 
                 println("Shutting down...") 
             } catch (e: Exception) { 
         //        HyperLog.i("mTagLocation", "^^^^^^^  Exception when Shutting down...") 
             } 
         }).start() 
     } 
  
     class EventCallback : IotHubEventCallback { 
         override fun execute(status: IotHubStatusCode, context: Any) { 
             val i = if (context is Int) context else 0 
         //    HyperLog.i("mTagLocation", "Message sent acknowledgement: " + i.toString() + " with status: " + status.name) 
             println("IoT Hub responded to message " + i.toString() + " with status " + status.name) 
  
             if((status == IotHubStatusCode.OK) || (status == IotHubStatusCode.OK_EMPTY)) 
             { 
         //        HyperLog.i("mTagLocation", "IotHub message sent status:  OK") 
             } 
             else 
             { 
         //        HyperLog.i("mTagLocation", "IotHub message sent status:  Fail") 
             } 
         } 
     } 
  
     protected class IotHubConnectionStatusChangeCallbackLogger : IotHubConnectionStatusChangeCallback { 
         override fun execute(status: IotHubConnectionStatus, statusChangeReason: IotHubConnectionStatusChangeReason, throwable: Throwable?, callbackContext: Any) { 
             println() 
             println("CONNECTION STATUS UPDATE: $status") 
             println("CONNECTION STATUS REASON: $statusChangeReason") 
             println("CONNECTION STATUS THROWABLE: " + if (throwable == null) "null" else throwable.message) 
             println() 
  
             throwable?.printStackTrace() 
  
             if (status == IotHubConnectionStatus.DISCONNECTED) { 
                 //connection was lost, and is not being re-established. Look at provided exception for 
                 // how to resolve this issue. Cannot send messages until this issue is resolved, and you manually 
                 // re-open the device client 
             } else if (status == IotHubConnectionStatus.DISCONNECTED_RETRYING) { 
                 //connection was lost, but is being re-established. Can still send messages, but they won't 
                 // be sent until the connection is re-established 
             } else if (status == IotHubConnectionStatus.CONNECTED) { 
                 //Connection was successfully re-established. Can send messages. 
             } 
         } 
     } 
  
     val exceptionRunnable: Runnable = Runnable { 
         try { 
             initClient() 
         } catch (e: URISyntaxException) { 
             e.printStackTrace() 
         } catch (e: IOException) { 
             e.printStackTrace() 
         } 
  
         println(lastException) 
     } 
  
     @Throws(UnsupportedEncodingException::class, JSONException::class) 
     private fun method_setSendMessagesInterval(methodData: Any): Int { 
         //        String payload = new String((byte[])methodData, "UTF-8").replace("\"", ""); 
         //        JSONObject obj = new JSONObject(payload); 
         //        sendMessagesInterval = obj.getInt("sendInterval"); 
         //        handler.post(methodNotificationRunnable); 
         return METHOD_SUCCESS 
     } 
  
     private fun method_default(data: Any): Int { 
         println("invoking default method for this device") 
         // Insert device specific code here 
         return METHOD_NOT_DEFINED 
     } 
  
     inner class DeviceMethodStatusCallBack : IotHubEventCallback { 
         override fun execute(status: IotHubStatusCode, context: Any) { 
             println("IoT Hub responded to device method operation with status " + status.name) 
         } 
     } 
  
     inner class SampleDeviceMethodCallback : com.microsoft.azure.sdk.iot.device.DeviceTwin.DeviceMethodCallback { 
         override fun call(methodName: String, methodData: Any, context: Any): DeviceMethodData { 
             var deviceMethodData: DeviceMethodData 
             try { 
                 when (methodName) { 
                     "setSendMessagesInterval" -> { 
                         val status = method_setSendMessagesInterval(methodData) 
                         deviceMethodData = DeviceMethodData(status, "executed $methodName") 
                     } 
                     else -> { 
                         val status = method_default(methodData) 
                         deviceMethodData = DeviceMethodData(status, "executed $methodName") 
                     } 
                 } 
             } catch (e: Exception) { 
                 val status = METHOD_THROWS 
                 deviceMethodData = DeviceMethodData(status, "Method Throws $methodName") 
             } 
  
             return deviceMethodData 
         } 
     } 
  
 }

**Comment by tmahmood-microsoft** [comment]
@mahendradabiaplite  can you also share what SDK version you are using?

**Comment by mahendradabiaplite** [comment]
Hello @tmahmood-microsoft 

    api('com.microsoft.azure.sdk.iot:iot-device-client:1.24.0') { 
         exclude module: 'slf4j-api' 
         exclude module: 'azure-storage' 
     } 
     
  
     implementation('com.microsoft.azure.android:azure-storage-android:2.0.0@aar')

**Comment by brycewang-microsoft** [comment]
Hi @mahendradabiaplite, I think the NPE issue here has been fixed by [this](https://github.com/Azure/azure-iot-sdk-java/pull/1125) which was included since the device client version 1.29.2 (release note [reference](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2021-02-24)). Can you upgrade the device client version accordingly and give it a try again?

**Comment by mahendradabiaplite** [comment]
> e the device client version accordingly and give it a try again?

will try it. thank you @brycewang-microsoft @tmahmood-microsoft

**Comment by tmahmood-microsoft** [comment]
@mahendradabiaplite did the device client version 1.29.2 help fix the issue for you?

**Comment by mahendradabiaplite** [comment]
I have updated the version as mentioned and have submitted the app to the play store will let you know soon after release of my app. Thank you !!

**Comment by timtay-microsoft** [comment]
@mahendradabiaplite any updates here? Is it okay for us to close this issue?

**Comment by mahendradabiaplite** [comment]
Hello, you can, it seems to be okay now Thank you !
