### ISSUE TITLE
[Bug Report] Cannot enable IoT Edge device capabilities via TwinClient

### ISSUE THREAD

**Issue by chris-pinola-rf** [Azure/azure-iot-sdk-java#1578]
# Context

- **OS and version used:** Ubuntu 20.04 LTS
- **Java runtime used:** openjdk version "15.0.2" 2021-01-19
- **SDK version used:** 2.1.0 (latest as of writing)

## Description of the issue
It is currently not possible to use the `com.microsoft.azure.sdk.iot.service.twin.TwinClient` to grant an existing device the IoT Edge "capability" via this SDK. Calling `capabilities.setIoTEdge(true)` and then attempting to `.patch()` or `.replace()` the twin **does not** result in the capability being enabled within IoT Hub.

## Code sample exhibiting the issue
```kotlin
import com.microsoft.azure.sdk.iot.service.auth.IotHubConnectionStringBuilder
import com.microsoft.azure.sdk.iot.service.twin.TwinClient
import com.microsoft.azure.sdk.iot.service.twin.TwinClientOptions

val iotHubConnectionString = "..."
val deviceId = "..." // Any device created without Edge capabilities will suffice

val client = TwinClient(iotHubConnectionString, TwinClientOptions.builder().build())
  
// Fetch the current twin
val twin = client.get(deviceId)

// Mark this device as eligible for Edge capabilities
twin.capabilities.isIotEdge = true

// Save the edited twin back to IoT Hub
client.patch(twin)

// Observe that the edge capabilities flag is still `false` in the twin!
```

## Console log of the issue
Running with `DEBUG=*` did not yield any logs.

**Comment by timtay-microsoft** [comment]
The service currently only allows you to update this field in the [device update API in RegistryClient](https://github.com/Azure/azure-iot-sdk-java/blob/1501682544813aa28f0ae58e096d8e903a952a50/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/registry/RegistryClient.java#L224) after setting the [edge capabilities flag](https://github.com/Azure/azure-iot-sdk-java/blob/1501682544813aa28f0ae58e096d8e903a952a50/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/registry/Device.java#L50) for your particular device.

**Comment by chris-pinola-rf** [comment]
Thanks @timtay-microsoft, `RegistryClient` does exactly what I'm looking for. 👍
