### ISSUE TITLE
请问安卓如何集成微软物联网sdk

### ISSUE THREAD

**Issue by turkey1993** [Azure/azure-iot-sdk-java#1587]
你好，公司将传感器设备的数据上传到微软物联网，然后我这边的安卓app端想从物联网将数据拉取过来，请问有没有详细的文档说明，非常感谢

**Comment by brycewang-microsoft** [comment]
@turkey1993 您好，请问您是否可以进一步说明“传感器设备的数据”是怎样存储在Azure IoT Hub中的吗？比如是通过Hub中注册的设备的Twin的属性值，亦或是其他形式？

另外，有关使用安卓APP进行设备端和IoT Hub端交互的示例，可以先参考[这里](https://github.com/Azure/azure-iot-sdk-java/tree/main/device/iot-device-samples/android-sample)。

**Comment by brycewang-microsoft** [comment]
@turkey1993 因为一段时间没收到回复，目前我将此问题关闭。如果有后续相关问题，欢迎您随时重开此问题。
