### ISSUE TITLE
JobResult did not use non-parameter constructor of DeviceTwinDevice when device id is null

### ISSUE THREAD

**Issue by zhang-hua** [Azure/azure-iot-sdk-java#159]
- **OS and version used:** <VERSION> Windows 10
- **Java runtime used:** <VERSION> JDK 1.8.0_141
- **SDK version used:** <VERSION>  Java Service Client (com.microsoft.azure.sdk.iot:iot-service-client:1.9.24)
- **IDE**:  IntelliJ IDEA

# Description of the issue:

There is non-parameter constructor DeviceTwinDevice() which should be used when device id is null. It happened at:
https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/jobs/JobResult.java#L158
Need to check twinParser.getDeviceId(). If null, DeviceTwinDevice() should be used here.

related issue: https://github.com/Azure/azure-iot-sdk-java/issues/143

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by timtay-microsoft** [comment]
The fix for this issue is now released. See the release below for versions:

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-10-23

I will close this issue for now. Feel free to re-open if the release did not fix your issues.
