### ISSUE TITLE
Expose $version for desired properties

### ISSUE THREAD

**Issue by sandeeppujar** [Azure/azure-iot-sdk-java#161]
Need to be able to Get version number in desired properties, and also be able to Set the version number for reported properties. 

- **OS and version used:** <VERSION>  Windows 10

- **Java runtime used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

Ability to get the desired version will enable in sequencing updates coming from the hub.

# Code sample exhibiting the issue:
C# SDK provides this functionality  in its class TwinCollection
        /// Gets the version of the <see cref="TwinCollection"/>
        /// </summary>
        public long Version

        {

# Console log of the issue:

**Comment by prmathur-microsoft** [comment]
@mamokarz  is working on making this available in java SDK. He will let you know when it is ready.

**Comment by prmathur-microsoft** [comment]
This issue is now fixed and available in latest release of the SDK. I'm closing this for now. Feel free to reopen if you see any further issues.
