### ISSUE TITLE
NullPointerException with TwinState when queryTwins is used with partial twin

### ISSUE THREAD

**Issue by ranjith-t** [Azure/azure-iot-sdk-java#1611]
SDK throws NullPointerException when QueryClient() is used to get twin details from Hub.

SDK Version: 
group: 'com.microsoft.azure.sdk.iot', name: 'iot-service-client', version:'2.1.3'

API used:
        var twinQueryResponse: TwinQueryResponse = queryClient.queryTwins(sqlQuery)
SQL Query:
**select deviceId from devices**
        **val filter: String = "deviceId"** 
        var sqlQuery: String  = **SqlQueryBuilder.createSqlQuery(filter, SqlQueryBuilder.FromType.DEVICES, null, null)**

Trace:

java.lang.NullPointerException
        at com.microsoft.azure.sdk.iot.service.twin.TwinState.getConnectionState(TwinState.java:538)
        at com.microsoft.azure.sdk.iot.service.twin.Twin.fromJson(Twin.java:99)
        at com.microsoft.azure.sdk.iot.service.query.TwinQueryResponse.<init>(TwinQueryResponse.java:50)
        at com.microsoft.azure.sdk.iot.service.query.QueryClient.queryTwins(QueryClient.java:202)
        at com.microsoft.azure.sdk.iot.service.query.QueryClient.queryTwins(QueryClient.java:160)

# Context

- **OS and version used:** <VERSION> Ubuntu
- **Java runtime used:** <VERSION> openjdk version "1.8.0_342"
- **SDK version used:** <VERSION> version:'2.1.3'

## Description of the issue
When the query is tried with "*"(i.e without filter) things work and list of twins are returned.

## Code sample exhibiting the issue
        val filter: String = "deviceId"
        var sqlQuery: String  = SqlQueryBuilder.createSqlQuery(filter, SqlQueryBuilder.FromType.DEVICES, null, null)
        var twinQueryResponse: TwinQueryResponse = queryClient.queryTwins(sqlQuery)

**Comment by timtay-microsoft** [comment]
Sorry for the delay on this issue. #1639 will fix this bug, and we are planning to get it released within a day or two.

**Comment by ngastelum-ms** [comment]
The fix for this issue has been released as of IoT hub service client version 2.1.5, marking this issue as closed
