### ISSUE TITLE
How to gracefully close DeviceClient?

### ISSUE THREAD

**Issue by ulkeba** [Azure/azure-iot-sdk-java#163]
- **OS and version used:** Windows 10
- **Java runtime used:** 1.8.0_144
- **SDK version used:** 1.4.34

# Description of the issue:
Invoking method `closeNow()` on an instance of `com.microsoft.azure.sdk.iot.device.DeviceClient` immediatly closes the client. If a message had been queued before, but has not yet been sent at the time of the `closeNow()` invocation, the IoT Hub responds with status code `MESSAGE_CANCELLED_ONCLOSE`. 

Is there a way to gracefully close the client, waiting for all messages to be sent before tearing down the connection? 

The JavaDoc of the deprecated `close()` method says "Completes all current outstanding requests and closes the IoT Hub client." -- something like that (or some workaround) would be fine! :)

Any help is very much appreciated!

**Comment by prmathur-microsoft** [comment]
We have deprecated close and replaced it with closeNow. The idea behind closeNow is that we let the users handle when to close the connection. We can only give a best attempt try to send a message and cannot  guarantee of delivery of message. This scenario becomes complicated especially in low network/bandwidth constrained devices. If the user calls close and network goes down, we will have to wait indefinitely until network recovers (for which there is no guarantee). Hence we deprecated it and replaced it with closeNow. Now as a user you know your network scenario very well and should call closeNow only after receiving confirmation of all the messages that you had sent. Please let me know if this explanation does not help.

**Comment by ulkeba** [comment]
Thank you very much for your detailed response and apologize my late reply. 

Your design decision makes perfectly sense, thanks for clarifying. 

I was wondering, however, if there is a way to check if there are still messages pending without tracking the message sending state using callbacks myself...?!

**Comment by prmathur-microsoft** [comment]
The way you can track the status of the message at the moment is by providing message callback. You can look through our samples to get detailed information about how to configure callbacks. 

Our samples are located here - https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/send-receive-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/SendReceive.java#L50

**Comment by ulkeba** [comment]
OK, thanks!
