### ISSUE TITLE
[Bug Report] ServiceClient's send() method got hung for more than 30 mins before it throws exception (java.io.IOException: Encountered exception during amqp connection: proton:io with description Connection timed out)

### ISSUE THREAD

**Issue by PremSahooESL** [Azure/azure-iot-sdk-java#1633]
**[Related Bug]**
[https://github.com/Azure/azure-iot-sdk-java/issues/912](https://github.com/Azure/azure-iot-sdk-java/issues/912)

Based on above earlier reported issue, we were told to use a new ServiceClient instance everytime while sending cloud to device.
But still in Kuberenetes env,  Micro services keep getting (java.io.IOException: Encountered exception during amqp connection: proton:io with description Connection timed out)

**[ENV]**
Java 1.8, Sprint Boot 2.6.6, AKS 1.23.5

**[IoT Hub SDK Version Used ]**
<dependency>
            <groupId>com.microsoft.azure.sdk.iot</groupId>
            <artifactId>iot-service-client</artifactId>
            <version>1.25.0</version>
</dependency>

**[Code block]**
`@Bean
    @Scope(value = ConfigurableBeanFactory.SCOPE_PROTOTYPE, proxyMode = ScopedProxyMode.TARGET_CLASS)
    public ServiceClient createServiceClient(IotHubProperties iotHubProperties) {
        ServiceClient serviceClient = null;
        try {
            serviceClient = ServiceClient.createFromConnectionString(iotHubProperties.getIotHub().getConnectionString(), IotHubServiceClientProtocol.AMQPS);
            serviceClient.open();
            log.info("IoTHub service client connection created");
        } catch (IOException e) {
            log.error("Error while creating service connection for IotHub ", e);
        }
        return serviceClient;
    }

------------------------------------------
 Message msgToGway = new Message(contractAsString);    
 msgToGway.setMessageId(messageId);
 serviceClient.send(deviceId, msgToGway);
 serviceClient.close();
--------------------------------------------`

**Comment by timtay-microsoft** [comment]
Can you try upgrading to the latest SDK version? We have a [migration guide](https://github.com/Azure/azure-iot-sdk-java/blob/main/SDK%20v2%20migration%20guide.md) that will help you make the jump from v1 to v2 here.

**Comment by PremSahooESL** [comment]
Surely we will upgrade to V2.

I have a quick question. The issue which we faced, does Microsoft has any evidence of having the similar issue with V1 Lib before?
If so, What are the areas we must focus for this random continuous timeout exception. Is it a max connection limitation on Azure Kubernetes VM or IoT Hub service client issue. or it could be due to timeout scenario is not handled in V1 Lib?

**Comment by PremSahooESL** [comment]
We tried testing on V2 lib.
Still we get the same error.

Below exception keeps coming......
########################################
catch (TimeoutException ex)
{
    log.info("**Failed to open messaging client due to service taking too long to respond**.");
}
########################################

**Comment by timtay-microsoft** [comment]
This may be a case where the service is not as responsive as it should be. The error indicates that the SDK sent the message successfully, but the service never responded to it with an acknowledgement. You may need to open a support request on your hub through the Azure Portal to get a service engineer to take a look at your hub's logs here.

Some important practices to keep in mind though:
 - In the v2 SDK, you can send multiple messages on a single connection, so you shouldn't open/close the messaging client each time you want to send something.
 - The 5 second timeout you provided to the sendMessage operation is a bit aggressive. If you have a hub with not many units, then you may just be running into the throttling limit. See [here](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/iot-hub/iot-hub-devguide-quotas-throttling.md) for the throttling limits for IoT hub for more details
 
<img width="776" alt="image" src="https://user-images.githubusercontent.com/28789848/201402461-f20f8ca8-3942-4f5e-b06b-ac243a96e478.png">

<img width="773" alt="image" src="https://user-images.githubusercontent.com/28789848/201402339-71414c08-7051-41b3-bf64-cbb099571d40.png">

**Comment by PremSahooESL** [comment]
Thanks for your comments and suggestions.

**Few things to be noted as per our Env**
1. Our Env has more than 10 units of Hub running. It must be enough to handle ingress and egress. 
2. As this exception occurs, when multiple MicroServices using MessagingClient run together on a specific kubernetes Node. If the Microservices are distributed among various Nodes, then this exception never occurs. As MessagingClient has timeout added in all methods (open, send, close), even if it does not receive any ack in the specific duration, it should return, but it gets stuck when above exception occurs. **Why does not it come out as the timeout expires?**

Is it something related to multiple connection opened from MessagingClient in a specific time duration and in addition to this kubernetes Node OS's limitations (do not know exactly what parameter either),combining together making this issue?

**Todo**
By the way, we will try reusing MessagingClient connection as you mentioned in V2 Lib. Will check and if it helps or not.

**Comment by PremSahooESL** [comment]
We never tried with **AMQPS_WS**
Currently we are using **AMQPS**.

Does **AMQPS_WS** perform well over **AMQPS**?

**Comment by timtay-microsoft** [comment]
AMQP_WS should perform the same as AMQPS

**Comment by PremSahooESL** [comment]
ok. Got it, thanks

**Comment by timtay-microsoft** [comment]
1) When using the v2 MessagingClient, you must subscribe to the error processor in order to be notified when the AMQP connection is lost. [This sample](https://github.com/Azure/azure-iot-sdk-java/blob/517d9a3713e2d236885f7a9ef15038af1044a2d1/service/iot-service-samples/messaging-client-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/MessagingClientSample.java#L50) demonstrates the best practice here. If you follow this pattern, your client will reconnect after it loses its connection.

2) This behavior is a possibility and your code should include some retry logic to handle it. The service may be slow to respond at times, or your message may have been lost due to network issues. In either case, you will need to re-send the message.

**Comment by PremSahooESL** [comment]
got it. Thanks.

**Comment by timtay-microsoft** [comment]
Do you need any further help on this, @PremSahooESL?

**Comment by PremSahooESL** [comment]
With retry logic, MessagingClient works well as of now. In fact we are doing a long run test, to see if there is any other corner cases while using V2 Lib. In case we need any further assistance, we will report here.

Thanks a lot for your quick support.

**Comment by timtay-microsoft** [comment]
Okay, I'll go ahead and close this thread for now. If you encounter any new problems, feel free to open a new thread here.

**Comment by PremSahooESL** [comment]
Sure. Thank you.
