### ISSUE TITLE
[Bug Report] Constrained device AMQP sending message rate

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#1654]
The Edgehub team has a [customer issue](https://github.com/Azure/iotedge/issues/6845) that suggests this SDK has the same bug as the C# SDK used to have as detailed [here](https://github.com/Azure/azure-iot-sdk-csharp/issues/2434). 

The problematic behavior is that there is a 50 ms delay between a message being sent to Edgehub and receiving feedback for that message on the service client side. 

As with the [C# SDK fix](https://github.com/Azure/azure-iot-sdk-csharp/pull/2439), this SDK should not batch ack's for feedback messages. The service only sends feedback messages one at a time, and always waits for the previous message to be ack'd before the next message is sent, so there is no scenario where batching makes sense.

**Comment by timtay-microsoft** [comment]
After some initial digging, we don't seem to even be able to choose to batch these acknowledgements with proton-j, so the issue may lay somewhere else.

**Comment by timtay-microsoft** [comment]
Quick update based on a comment on the other thread: The user switching to MQTT lowered the latency down to 10 ms, so there likely isn't an issue here on the feedback receiver. However, the AMQP protocol on the device side may only be polling once every 50 ms. If so, we should investigate making this configurable.

**Comment by alexbaltman** [comment]
Any update on this?

**Comment by timtay-microsoft** [comment]
Our AMQP library does not appear to make this interval configurable, so it is propagating these messages as fast as it can for now. From the other thread, the MQTT library appears to be faster at this, so users looking for speed here should probably use MQTT instead. Since we are limited by the AMQP library here, I'll tag this as "Underlaying Library Issue"

As for the customer's scenario in particular, it sounds like the user may be sending these messages serially (send message, wait for ack, send message, wait for ack, etc.). In general, for higher throughput scenarios, the user is encouraged to send messages in parallel (send X messages, wait for X acks) instead. Doing that should make this delay less impactful.

**Comment by timtay-microsoft** [comment]
#1673 should help the SDK at least match what the AMQP library can do for sending message throughput, though

**Comment by maciej-kepa** [comment]
> Our AMQP library does not appear to make this interval configurable, so it is propagating these messages as fast as it can for now. From the other thread, the MQTT library appears to be faster at this, so users looking for speed here should probably use MQTT instead. Since we are limited by the AMQP library here, I'll tag this as "Underlaying Library Issue"
> 
> As for the customer's scenario in particular, it sounds like the user may be sending these messages serially (send message, wait for ack, send message, wait for ack, etc.). In general, for higher throughput scenarios, the user is encouraged to send messages in parallel (send X messages, wait for X acks) instead. Doing that should make this delay less impactful.

@timtay-microsoft Yes, the messages are send in serial using `MessageCallback` and `onCloudToDeviceMessageReceived` method. As far as I understand this is default behaviour of ModuleClient. 

Could you provide any documentation or sample how to implement the parallel messages sending (waiting for multiple acks) using Java SDK? I couldn't find any option other than implementing it from scratch.

**Comment by timtay-microsoft** [comment]
I want to make a clear distinction between devices/modules _sending_ messages vs devices/modules _receiving_ messages here.

A given device/module _receiving_ cloud-to-device messages or module-to-module messages will always be in serial because of how the service is designed. There is no way to parallelize this.

A given device/module _sending_ messages to the service or to another module can be parallelized, though.

```java
CountDownLatch messagesSentLatch = new CountDownLatch(10);
MessageSentCallback callback = (sentMessage, clientException, callbackContext) ->
{
    if (clientException == null)
    {
        messagesSentLatch.countDown();
    }
};

DeviceClient client = new DeviceClient(connString, protocol);
client.open(true);

for (int i = 0; i < 10; i++)
{
    client.sendEventAsync(new Message("some message"), callback, null);
}

// Waits for all 10 messages to be sent and acknowledged.
messagesSentLatch.await();
```

This is as opposed to sending them in serial like the below snippet:
```java
DeviceClient client = new DeviceClient(connString, protocol);
client.open(true);

for (int i = 0; i < 10; i++)
{
    client.sendEvent(new Message("some message"));
}

```

**Comment by pwarecki** [comment]
If the message consumption from edgeHub by a module is serial what is the maximal throughput of message delivery to the module that can be achieved, of course excluding message processing time on the module side? Currently,  in our tests, we only achieved 100 rec/s and it's too low for our requirements. During the testing, we haven't experienced cpu, disk, or memory resources being overutilized. Where is the bottleneck?  Have you addressed also this issue?

**Comment by timtay-microsoft** [comment]
The bottleneck at this point is likely the edgeHub. In general, both IoT hub and edgeHub are designed with the understanding of many modules/devices connecting each with moderate throughput on operations like these. By contrast, it sounds like you may be aiming for few modules/devices but higher throughput.

**Comment by timtay-microsoft** [comment]
For additional context, [here](https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#basic-and-standard-tier-operations) are the expected limits for c2d messages:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/28789848/226481224-77fa3dec-a9b3-484e-bb38-e0981665a29d.png">

It looks like 120 c2d messages per second is the expectation here from the service side (depending on how many units your hub has).
