### ISSUE TITLE
[Bug Report] TwinClient replace method does not work with AzureSasCredential

### ISSUE THREAD

**Issue by ranjith-t** [Azure/azure-iot-sdk-java#1657]
# Context

- **OS Used:** Ubuntu 20.04.2 LTS
- **Java runtime used:** openjdk version "1.8.0_342"
- **SDK version used:** 2.1.3

## Description of the issue
When device twin replace was requested through TwinClient class, it does not update the twin when AzureSasCredential is used for connection. At the IotHub, neither update of device twin nor there is any exception from TwinClient.

## Code sample exhibiting the issue
TwinClient method replace() does not work when the TwinClient uses AzureSasCredential. It looks like the reason being that the iotHubConnectionString is not able to get proper URL for http request. All other classes tries to use 'hostname'(which is set), but in this particular case it tries to use deviceId to derive the url while the iotHubConnectionString is not initialized.

`URL url;
        if (twin.getModuleId() == null || twin.getModuleId().length() == 0)
        {
            url = this.iotHubConnectionString.getUrlTwin(twin.getDeviceId());
        }
        else
        {
            url = this.iotHubConnectionString.getUrlModuleTwin(twin.getDeviceId(), twin.getModuleId());
        }`

**Comment by brycewang-microsoft** [comment]
Hi @ranjith-t, thanks for bringing this to our attention! The [fix ](https://github.com/Azure/azure-iot-sdk-java/pull/1658)has been merged in and I will update here again once we release a newer version including it.

**Comment by brycewang-microsoft** [comment]
The hub service client package [2.1.6](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2023-01-23) has been released with the fix included, so I am closing this thread.

**Comment by ranjith-t** [comment]
Just confirming that this issue has been fixed.
