### ISSUE TITLE
DeviceClient.closeNow() blocks forever

### ISSUE THREAD

**Issue by a18250** [Azure/azure-iot-sdk-java#167]
- **OS and version used:** <Android 7.1.1> 

- **Java runtime used:** <Java 8> 

- **SDK version used:** <1.5.36> 

# Description of the issue:

My code on mobile device calls SDK in following order:

0. network is available
1. DeviceClient.open()
2. DeviceClient.setMessageCallback()
3. subscribeToDeviceMethod()
4. device is now listening for incoming IoT message/method
5. network connection lost
6. DeviceClient.closeNow()

Problem is that at step 6, the closeNow() never returns and the calling thread is blocked forever (at least I waited for minutes).

If I remove step 3, then there is no block at step 6. This seems indicate the issue is related with direct method handling.

Step into SDK code with Android Studio, it appears the code is blocked on a wait object at:

```
void unsubscribe(String topic) throws IOException {
    synchronized(this.mqttLock) { <<<< lock here
        try {
            if(!this.mqttConnection.getMqttAsyncClient().isConnected()) {
                throw new IOException("Cannot unsubscribe when mqtt client is disconnected");
            }

            if(this.userSpecifiedSASTokenExpiredOnRetry) {
                throw new IOException("Cannot unsubscribe when user supplied SAS token has expired");
            }

            IMqttToken e = this.mqttConnection.getMqttAsyncClient().unsubscribe(topic);
            e.waitForCompletion();
        } catch (MqttException var5) {
            throw new IOException("Unable to unsubscribe to topic :" + topic + "because " + var5.getCause() + var5.getMessage());
        }

    }
}
```

# Code sample exhibiting the issue:

Just the 6 steps above
# Console log of the issue:

**Comment by prmathur-microsoft** [comment]
Thanks for filing this issue. We will investigate and get back toy you soon.

**Comment by timtay-microsoft** [comment]
The fix for this bug has been checked in and will be a part of the next SDK release

**Comment by a18250** [comment]
Just tried master, closeNow() returns instantly. Thanks for the fix !

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released:

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-12-2

I'm closing this issue for now, feel free to re-open if it something else comes up incorrectly
