### ISSUE TITLE
BouncyCastle dependency is out of date

### ISSUE THREAD

**Issue by sirianni** [Azure/azure-iot-sdk-java#168]
The SDK lists `bcprov-jdk16` as a dependency, which is significantly out of date.

http://bouncy-castle.1462172.n4.nabble.com/Bouncycaslte-bcprov-jdk15-vs-bcprov-jdk16-td4656252.html

This causes conflicts with apps that are using a more modern version of bouncycastle.  Please upgrade the SDK to use `bcprov-jdk15on`.

**Comment by timtay-microsoft** [comment]
We are looking into this now, I'll keep you updated.

**Comment by timtay-microsoft** [comment]
Sorry for the delay on this issue, a lot of things got in the way. The fix for your issue is now checked in as of 165bec47dc8384ef2868e056180db723752dc584

These changes will be in the next release. I'll notify you when that happens.

**Comment by timtay-microsoft** [comment]
It will take a day or two to propagate up to Maven central, but the latest release contains the fix for this issue:

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2018-1-23

I'm closing this issue for now, but feel free to re-open if this did not fix your issue
