### ISSUE TITLE
ProvisioningDeviceClient.registerDeviceSync(AdditionalData additionalData) - AdditionalData is not getting passed.

### ISSUE THREAD

**Issue by abhiramk139** [Azure/azure-iot-sdk-java#1731]
Description: In ProvisioningDeviceClient class the additional data attribute that we are passing is not getting set in ProvisioningDeviceClientConfig object. Since the additional data payload is not getting send to the custom allocation function/ policy.

This issue is there only for synchronous registration of devices. Asynchronous calls are working fine.

**Comment by timtay-microsoft** [comment]
Looks like you are correct. #1732 will fix this

**Comment by timtay-microsoft** [comment]
This issue has been fixed as of version 2.1.1, so I'm closing this thread.

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2023-07-25
