### ISSUE TITLE
Can't find or access default constructor for {}, make sure corresponding package is open to azure-core

### ISSUE THREAD

**Issue by Danijal98** [Azure/azure-iot-sdk-java#1738]
# Context

- **OS and version used:** macOS
- **Java runtime used:** Java 17
- **SDK version used:** iotHubDeviceClientVersion=2.2.0, azureStorageBlobVersion=12.22.3, azureCore=1.40.0
- **Project** Working on a KMP project inside an android module

## Description of the issue

While migrating from version 1.29.4 to 2.2.0, following the guide at [FileUploadSimpleSample](https://github.com/Azure/azure-iot-sdk-java/blob/main/iothub/device/iot-device-samples/file-upload-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/FileUploadSimpleSample.java#L79), an exception arises during the `endpoint()` method call of creating a `BlobClient`. The failure point is identified within the `HttpHeaderName` class in the `fromString()` function, particularly when the `ExpandableStringEnum::getDefaultConstructor` is invoked. The function seems to be unable to find or access the default constructor for a given class and suggests ensuring the relevant package is open to azure-core.

## Code sample exhibiting the issue

```kotlin
val blobClient = BlobClientBuilder()
                .endpoint(sasUriResponse.blobUri.toString())
                .buildClient()
```

The exception occurs within:

```java
private static <T> MethodHandle getDefaultConstructor(Class<T> clazz) {
    try {
        MethodHandles.Lookup lookup = ReflectionUtils.getLookupToUse(clazz);
        return lookup.findConstructor(clazz, methodType(void.class));
    } catch (NoSuchMethodException | IllegalAccessException e) {
        LOGGER.verbose("Can't find or access default constructor for {}, make sure corresponding package is open to azure-core", clazz.getName(), e);
    } catch (Exception e) {
        LOGGER.verbose("Failed to get lookup for {}", clazz.getName(), e);
    }

    return null;
}
```

## Console log of the issue

```
LOGGER.verbose("Can't find or access default constructor for {}, make sure corresponding package is open to azure-core", clazz.getName(), e);
```

**Comment by timtay-microsoft** [comment]
This question may be more appropriate to ask in the repo that owns the Azure Storage SDK. You can file an issue for it [here](https://github.com/Azure/azure-sdk-for-java/issues). As far as this repo is concerned, we can update the sample code's dependency on the Azure Storage SDK if there is a version that fixes this issue for you.

**Comment by timtay-microsoft** [comment]
Since this is more an issue with Azure Storage SDK than this SDK, I'll go ahead and close this thread.
