### ISSUE TITLE
QueryCollectionResponse throw IllegalArgumentException: Provided Collection must not be null and cannot be empty

### ISSUE THREAD

**Issue by zhang-hua** [Azure/azure-iot-sdk-java#176]
- **OS and version used:** <VERSION> Windows 10
- **Java runtime used:** <VERSION> JDK 1.8.0_141
- **SDK version used:** <VERSION>  Java Service Client (com.microsoft.azure.sdk.iot:iot-service-client:1.9.24)
- **IDE**:  IntelliJ IDEA

# Description of the issue:

QueryCollectionResponse throw "IllegalArgumentException: Provided Collection must not be null and cannot be empty" when the twin query result is empty. It should not throw this exception and just return an empty result.

# Code sample exhibiting the issue:

https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwin.java#L566

https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/QueryCollectionResponse.java#L52

Test Code:
```
@Test(timeout = 100000)
public void queryWithContinuationTokenTest() {
        try {
            String fullQuery = "select * from devices where deviceId='nonexistdevice'";
            DeviceTwin twinClient = DeviceTwin.createFromConnectionString("HostName=...");
            QueryCollection twinQuery = twinClient.queryTwinCollection(fullQuery);
            QueryOptions options = new QueryOptions();
            while (twinClient.hasNext(twinQuery)) {
                QueryCollectionResponse<DeviceTwinDevice> response = twinClient.next(twinQuery, options);
                for (DeviceTwinDevice twin : response.getCollection()) {
                    System.out.println(twin.getDeviceId() + ":" + response.getContinuationToken());
                }
            }
        } catch (IllegalArgumentException e) {
            Assert.fail(e.getMessage());
        } catch (Exception e){
            Assert.fail(e.getMessage());
        }
}
```
# Console log of the issue:

**Comment by timtay-microsoft** [comment]
The fix for this has been checked in as of af9c41f81f26d07afeccb56d44e1b5d3f8816f2a

It will be in the next release

**Comment by zhang-hua** [comment]
@timtay-microsoft thanks!

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released:

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-12-2

I'm closing this issue for now, feel free to re-open if it something else comes up incorrectly

**Comment by zhang-hua** [comment]
@timtay-microsoft , thanks for fixing this! I'll bump to the new release.
