### ISSUE TITLE
[Technical Question]  One link in https://github.com/Azure/azure-iot-sdk-java/blob/main/logging.md returns 404 now

### ISSUE THREAD

**Issue by zh0903** [Azure/azure-iot-sdk-java#1765]
This link is invalid now:
![image](https://github.com/Azure/azure-iot-sdk-java/assets/49020965/d9f18978-f2b0-4eb0-bf36-2fbe5f41198a)

https://github.com/Azure/azure-iot-sdk-java/blob/main/logging.md

**Comment by timtay-microsoft** [comment]
#1766 should address this and some other out-of-date documentation for you. Thanks for catching this!

**Comment by timtay-microsoft** [comment]
The file has been updated with the fix, so I'll close this thread
