### ISSUE TITLE
[feature request] DeviceTwinStatusCallBack method is not available from the version 2.2.0 of iot-device-client

### ISSUE THREAD

**Issue by soloxio** [Azure/azure-iot-sdk-java#1768]
Hello everyone,

I am facing an issue with the DeviceTwinStatusCallBack method after upgrading the library iot-device-client to verion 2.2.0.

In the past, when I used the version 1.x of iot-device-client, there was a method DeviceTwinStatusCallBack , but now it's no any such kind of this method in version 2.2.0.

Who can help me the same method to use?

Thanks in advance!

**Comment by timtay-microsoft** [comment]
I'd suggest checking out the [device twin sample](https://github.com/Azure/azure-iot-sdk-java/blob/main/iothub/device/iot-device-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java) which shows how we recommend doing twin operations in the v2 SDK now.

For other v1 -> v2 upgrade changes, we also have a [migration guide](https://github.com/Azure/azure-iot-sdk-java/blob/main/SDK%20v2%20migration%20guide.md) you can reference. 

I hope that helps!
