### ISSUE TITLE
[Bug Report] Provisioning Device Client throws "Open called on an already open connection" with wrong logic?

### ISSUE THREAD

**Issue by in-fke** [Azure/azure-iot-sdk-java#1772]
# Context
- **OS and version used:** Windows 10
- **Java runtime used:** Java 11
- **SDK version used:** 2.1.2

## Description of the issue
Implementing reconnect mechanism when network was offline, invoking ProvisioningDeviceClient.registerDevice() throws ProvisioningDeviceConnectionException with message "Open called on an already open connection".

## Code sample exhibiting the issue
see https://github.com/Azure/azure-iot-sdk-java/blob/main/provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/mqtt/ContractAPIMqtt.java#L161
Code states:
```
        if (this.mqttConnection != null && !this.mqttConnection.isMqttConnected())
        {
            throw new ProvisioningDeviceConnectionException("Open called on an already open connection");
        }
```
should it not state instead?
```
        if (this.mqttConnection != null && this.mqttConnection.isMqttConnected())
        {
            throw new ProvisioningDeviceConnectionException("Open called on an already open connection");
        }
```

Also, closing the client does not null the field mqttConnection (which would help with the above logic), so apparently, the only solution is to throw away the client when we know that there was a disconnect?

https://github.com/Azure/azure-iot-sdk-java/blob/main/provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/contract/mqtt/ContractAPIMqtt.java#L208

So apparently, ProvisioningDeviceClient is not intended to be re-used for multiple invocations of `registerDevice` at all, if it seems?

## Console log of the issue
n/a

**Comment by timtay-microsoft** [comment]
This does look a bit off. We'll take a deeper look when we get a chance. Thanks for catching this!

**Comment by timtay-microsoft** [comment]
This has been fixed as of provisioning device client version 2.1.3, so I'll close this thread
