### ISSUE TITLE
 How to use iot-hub in golang

### ISSUE THREAD

**Issue by PurpleScorpion** [Azure/azure-iot-sdk-java#1773]
I did not find "azure-iot-sdk-go" in the github repository. 
Does golang support iot-hub?
If I must use golang to connect to iot-hub, is there a solution?

Looking forward to your answers

**Comment by timtay-microsoft** [comment]
We don't currently offer an IoT hub SDK in golang and don't have any immediate plans to create one. You will need to use an MQTT/HTTP/AMQP client directly to communicate with IoT hub in golang.

For MQTT specific scenarios, I recommend referencing [this doc](https://learn.microsoft.com/azure/iot/iot-mqtt-connect-to-iot-hub)
