### ISSUE TITLE
[Bug Report] Version 2.x of iot-device-client, requires version of reported properties to be sent, while 1.x not require that

### ISSUE THREAD

**Issue by dzakub** [Azure/azure-iot-sdk-java#1776]
# Context

- **OS and version used:** any 
- **Java runtime used:** openjdk version "17.0.10" 2024-01-16
- **SDK version used:** 2.3.0 

## Description of the issue

This issue is about compatibility between version 1.x and 2.x.

Behavior in version 1.x:
Sending message to `$iothub/twin/PATCH/properties/reported/#` mqtt topic (sendReportedProperties method) without version resulted in no error and client was getting a 200 (OK) response on topic `$iothub/twin/res/200/`
Behavior in version 2.x:
Sending message to `$iothub/twin/PATCH/properties/reported/#` mqtt topic (sendReportedProperties method) without version results in error and client was getting a 412 (PRECONDITION_FAILED) response on topic `$iothub/twin/res/412/`

So upgrade to version 2.x causes unnecessary changes for users of client library. Forcing them to manage reported properties version, which can be problematic due to asynchronous and distributed nature of system.

This is a request for reverting behavior to the one present in 1.x version of client.

**Comment by dzakub** [comment]
PR with a fix:
https://github.com/Azure/azure-iot-sdk-java/pull/1777

**Comment by timtay-microsoft** [comment]
Fixed as of 2.5.0, so I'll close this thread
