### ISSUE TITLE
[Technical Question] How can we update a deployment using createOrUpdateDeploymentWithResponse API?

### ISSUE THREAD

**Issue by ranjith-t** [Azure/azure-iot-sdk-java#1785]
For updating a deployment, how we can update the deployment using createOrUpdateDeploymentWithResponse() ? 

I could not get any example, nor the document specify what part of the deployment can be updated? is this API allows user to retry or cancel a deployment? If yes, then what is the format of the request needed? does setting the flags to true in the request is enough?
     *     isCanceled: Boolean (Optional)
     *     isRetried: Boolean (Optional)

**Comment by timtay-microsoft** [comment]
You may have filed this issue in the wrong repo. We don't have a ```createOrUpdateDeploymentWithResponse``` API in the IoT hub or DPS clients that live in this repo.

**Comment by ranjith-t** [comment]
ok, my bad, wrong repo. supposed to be in azure-sdk-for-java
