### ISSUE TITLE
Whole DeviceTwin package is missing in 2.5.0 just updated my Library from 1.34.3

### ISSUE THREAD

**Issue by SidLtimindtree** [Azure/azure-iot-sdk-java#1788]
I was using 1.34.3 just updated to 2.5.0.

Getting an error as :
com.microsoft.azure.sdk.iot.device.DeviceTwin.DeviceMethodCallback
com.microsoft.azure.sdk.iot.device.DeviceTwin.DeviceMethodData

These 2 packages are missing.

Then I compared with old repository so DeviceTwin package is removed in new Version.
What I need to use to work same as earlier?

Thank you

**Comment by timtay-microsoft** [comment]
That package was one of many that got renamed/re-organized when this library moved to v2. You can read a bit about the migration process [here](https://github.com/Azure/azure-iot-sdk-java/blob/main/SDK%20v2%20migration%20guide.md) if you'd like or you can review the [sample code in this repo](https://github.com/Azure/azure-iot-sdk-java/tree/main/iothub/device/iot-device-samples). Either approach should help you figure out the analogous classes in v2
