### ISSUE TITLE
MessageId not added with the MQTT protocol

### ISSUE THREAD

**Issue by robrechtdelanghe** [Azure/azure-iot-sdk-java#179]
- **OS and version used:** Windows 7

- **Java runtime used:** 1.8.0_111-b14

- **SDK version used:** 1.5.37

# Description of the issue:
Issue: The MessageId is not added to the MQTT message if there are no custom properties set.
When sending with the AMQP protocol the MessageID is set even without properties added.

# Code sample exhibiting the issue:
## Code sample that DOES NOT send the MessageId:
```
IotHubClientProtocol protocol= IotHubClientProtocol.MQTT;
DeviceClient client = new DeviceClient("<connection-string>", protocol);
Message msg = new Message("{}");
msg.setMessageId("<UUID>");
client.sendEventAsync(msg, <callback>, <callbackContext>);
```

## Code sample that DOES send the MessageId:
```
IotHubClientProtocol protocol= IotHubClientProtocol.MQTT;
DeviceClient client = new DeviceClient("<connection-string>", protocol);
Message msg = new Message("{}");
msg.setMessageId("<UUID>");
msg.setProperty("this", "fixes it"); // This line fixes it
client.sendEventAsync(msg, <callback>, <callbackContext>);
```

## Code and class that is the problem:
Class: com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging
Method: send(Message message) throws IOException
Code:
```
        if(messageProperties.length > 0)
        {
            /* SOME CODE */

            /*
             **Tests_SRS_MqttMessaging_21_027: [**send method shall append the messageid to publishTopic before publishing using the key name `$.mid`.**]**
             */
            if (message.getMessageId() != null)
            {
                stringBuilder.append(MESSAGE_ID);
                stringBuilder.append(MESSAGE_PROPERTY_KEY_VALUE_SEPARATOR);
                stringBuilder.append(message.getMessageId());

                separatorNeeded = true;
            }

            /* SOME MORE CODE */
        }
```

# Expected result:
Is it possible to send the MessageId idependently of the presence of custom properties?

**Comment by prmathur-microsoft** [comment]
Thanks for filing this issue. You are right message id should be sent irrespective of custom properties and this is a bug. We will work on fixing it. In the meantime if you wish to provide a PR I'll be happy to review it.

**Comment by timtay-microsoft** [comment]
I'm looking into fixing this now. I'll keep you posted @robrechtdelanghe

**Comment by timtay-microsoft** [comment]
The fix for this bug has been checked in and will be a part of the next release. Thanks for bringing it to our attention.

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released:

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-12-2

I'm closing this issue for now, feel free to re-open if it something else comes up incorrectly
