### ISSUE TITLE
[Bug Report] The Direct method on a Azure IoT device timeouts after 24 seconds even after passing higher responseTimeoutInSeconds and connectTimeoutInSeconds to invoke method from DeviceMethod class

### ISSUE THREAD

**Issue by dudheprajwal** [Azure/azure-iot-sdk-java#1791]
# Context

- **OS and version used:** Windows 11
- **Java runtime used:** JDK 11
- **SDK version used:**  IoT service client 1.34.2

## Description of the issue
The Direct method on a Azure IoT device timeouts after 24 seconds with passing higher responseTimeoutInSeconds and connectTimeoutInSeconds to invoke method from DeviceMethod class. The reason for the issue is the below code:

`DeviceOperations.request(var10000, url, var10002, var10003, String.valueOf(var11), this.options.getHttpConnectTimeout(), this.options.getHttpReadTimeout(), proxy);

The above part of code is executed from invokeMethod method from DeviceMethod class. This method is called in the hierarchy of invoke method from DeviceMethod class. The invoke method accepts the responseTimeoutInSeconds and connectTimeoutInSeconds bit, they are of no significance because of getHttpConnectTimeout() and getHttpReadTimeout() used with the DeviceOperations.request method. The default values for this parameters is 24 seconds. Hence, even if we pass 30 sec as  responseTimeoutInSeconds and connectTimeoutInSeconds for invoke method, the Direct method gets timed out after 24 seconds. So, there is no meaning to provide responseTimeoutInSeconds and connectTimeoutInSeconds.

## Console log of the issue
Read timed out

**Comment by timtay-microsoft** [comment]
I believe versions 2.x.x got rid of this odd 24 second timeout, so I'd recommend upgrading to that version. As it stands, we don't plan on making any changes to the 1.X.X SDK versions.
