### ISSUE TITLE
[Java] C2D Feedback receiver doesn't time out

### ISSUE THREAD

**Issue by tameraw** [Azure/azure-iot-sdk-java#18]
_From @dluc on November 26, 2016 3:31_

A request for feedback doesn't timeout, even if a timeout setting is passed to `receive()`/`receiveAsync()` methods.

Example code:
1. Sync: https://gist.github.com/dluc/7e02947720a1b86d03ab42c5801bd208
2. Async: https://gist.github.com/dluc/a4b7f27c586b2ccadffd422c8dfd0d70
 

_Copied from original issue: Azure/azure-iot-sdks#989_

**Comment by tameraw** [comment]
_From @zolvarga on November 28, 2016 20:53_

Hi Devis,

Thanks for reporting this.
We are going to take a look at it.

Thanks,
Zoltan

**Comment by tameraw** [comment]
Possibly related to #968 . We'll be investigating.

**Comment by tameraw** [comment]
_From @anhashia on January 11, 2017 20:30_

Being tracked with Product Backlog Item (PBI)

**Comment by anhashia** [comment]
Fix https://github.com/Azure/azure-iot-sdk-java/commit/3fb12fc895c5a9913a9ccef75ad2667774ed8eaa checked in
