### ISSUE TITLE
C2D -Feedback inconsistency

### ISSUE THREAD

**Issue by BanupriyaVenkatasen** [Azure/azure-iot-sdk-java#186]
Hi Team,

When sending C2D messages,it reaches the cloud successfully but it's not acknowledging the messages.

We are passing correct connectionString and DeviceId. Below is code snippet which is trying to send and receive the feedback:

  Message messageToSend = new Message("message.");
	    messageToSend.setDeliveryAcknowledgement(DeliveryAcknowledgement.Full);
	  
	    serviceClient.send(deviceId, messageToSend);
	    
	   FeedbackBatch feedbackBatch = feedbackReceiver.receive(10000);
	 
	    if (feedbackBatch != null) {
	      System.out.println("Message feedback received, feedback time: "
	        + feedbackBatch.getEnqueuedTimeUtc().toString());
	    }

This issue seems to be intermittent and we are experiencing at random times.It happens ,even though the deliveryAcknowledgement is Full. So, we suspect the message feedback are getting expired ,before the service processing it.

Please let us know the possible causes of this problem and further actions to be taken to handle this issue.

Your help is really appreciated!!

**Comment by BanupriyaVenkatasen** [comment]
Hi Team,

Have you got the chance to look into issue,please let me know if any additional details are required

**Comment by prmathur-microsoft** [comment]
Thanks @BanupriyaVenkatasen  for logging this issue. We will investigate further and get back to you soon.

**Comment by BanupriyaVenkatasen** [comment]
Hi Team,

Please keep us posted on the update

**Comment by timtay-microsoft** [comment]
Could you please tell us what version of the Java IoT Service SDK you are using?

**Comment by BanupriyaVenkatasen** [comment]
It's 1.10.28.Please find the details below:

<dependency>
  <groupId>com.microsoft.azure.sdk.iot</groupId>
  <artifactId>iot-service-client</artifactId>
  <version>1.10.28</version>
</dependency>

**Comment by BanupriyaVenkatasen** [comment]
Hi Team,

Is there any luck on this issue analysis

**Comment by BanupriyaVenkatasen** [comment]
Hi Team,

Kindly keep us posted on the update

**Comment by BanupriyaVenkatasen** [comment]
Hi Team,

Do we have any update

**Comment by prmathur-microsoft** [comment]
Because of holidays, we haven't had much luck in investigating this issue. We will try to prioritize it.

**Comment by prmathur-microsoft** [comment]
Hi @BanupriyaVenkatasen  ... I'm working on reproing this issue. However I can't seem to see the repro. For eg can you run our sample from here - https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-samples/service-client-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ServiceClientSample.java  and provide me your console logs pointing to what you see ?

**Comment by prmathur-microsoft** [comment]
Can you please provide us logs as requested above to help repro this issue ?

**Comment by prmathur-microsoft** [comment]
@BanupriyaVenkatasen  - As I have not heard back from you in a while, I'm closing this issue for now. Feel free to reopen this issue and provide logs for us when you have a chance with repro.
