### ISSUE TITLE
EncryptDecrypt is depricated

### ISSUE THREAD

**Issue by mathias-nickl** [Azure/azure-iot-sdk-java#196]
https://github.com/Azure/azure-iot-sdk-java/blob/2b2eed39e1b2893462a1eb87818897e71879442c/provisioning/security/tpm-provider/src/main/java/com/microsoft/azure/sdk/iot/provisioning/security/hsm/SecurityProviderTPMHsm.java#L337

Dear Provisioning team, 

TPM command EncryptDecrypt (0x164) is depricated and not supported on newer hardware. It is recommended to use EncryptDecrypt2 instead. 

Best 

MN

**Comment by prmathur-microsoft** [comment]
We will work on fixing this issue.

**Comment by prmathur-microsoft** [comment]
This issue is now fixed and in master. We will be releasing a package for the same on 2/9.

**Comment by prmathur-microsoft** [comment]
New maven packages with a fix for this issue are released. Feel free to reopen this issue if you still see any problems. Closing this issue for now.
