### ISSUE TITLE
Logging does not match problem in MessageProperty

### ISSUE THREAD

**Issue by letsfindaway** [Azure/azure-iot-sdk-java#201]
https://github.com/Azure/azure-iot-sdk-java/blob/f2de6124070b4bd9dc142fa2a20ae45fcb002010/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/MessageProperty.java#L87

The log message emit on this line does not match the problem detected.

**Comment by prmathur-microsoft** [comment]
You are right. Do you want to submit a PR for this change ? I'll be happy to review it.

**Comment by prmathur-microsoft** [comment]
New maven packages with a fix for this issue are released. Feel free to reopen this issue if you still see any problems. Closing this issue for now.
