### ISSUE TITLE
Cannot suppress output of "Lost connection to the server...."

### ISSUE THREAD

**Issue by Ken1S** [Azure/azure-iot-sdk-java#205]
- **OS and version used:** Windows 10 

- **Java runtime used:** <VERSION> Java 8

- **SDK version used:** <VERSION> 1.7.0

# Description of the issue:
Printout of "Lost connection to the server." is printed both to System.out and to log.
This makes it harder/impossible to suppres that output that would go to log with info level.

I found the message in 
https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsIotHubConnection.java#L769

---
System.out.println("Lost connection to the server. Reconnection attempt " + currentReconnectionAttempt++ + "...");
        logger.LogInfo("Lost connection to the server. Reconnection attempt %s, method name is %s ", currentReconnectionAttempt, logger.getMethodName());
---

My suggestion is to remove the System.out line

**Comment by timtay-microsoft** [comment]
We are working to get this fix squeezed in for our planned 2/9 release. I will keep you posted

**Comment by timtay-microsoft** [comment]
The fix for this issue has been checked in and will be in the next release today.

**Comment by timtay-microsoft** [comment]
This bug is now fixed as of Device Client version 1.8.0

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2018-2-9

**Comment by yzhong94** [comment]
@Ken1S  thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute customer satisfaction survey.
