### ISSUE TITLE
Typo in the service API : IotHubUnathorizedException

### ISSUE THREAD

**Issue by zoe-mcelderry** [Azure/azure-iot-sdk-java#208]
I guess that this will become a feature now so that other people's code doesn't break, but just wanted to report that I noticed a typo in your service API.  It can throw an IotHubUnathorizedException.

**Comment by prmathur-microsoft** [comment]
Thanks for letting us know of the typo. We will try to fix it by next LTS release so that it doesn't cause breaking changes.

**Comment by timtay-microsoft** [comment]
We have opted to not fix this typo in order to avoid making any breaking changes, so I'm closing this issue.

**Comment by az-iot-builder-01** [comment]
@zoe-mcelderry, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
