### ISSUE TITLE
Android Java SDK  - IotHubEventCallback not called after sendEventAsync

### ISSUE THREAD

**Issue by tameraw** [Azure/azure-iot-sdk-java#21]
_From @kevin-ledinh on November 23, 2016 10:56_

Hi Azure team,

Please advise the following problem when I run the IoT Hub Java SDK to send msg iva AMQP on an Android dev board.

In my first set up, I've been using IoT Hub SDK 1.0.11 and proton-j-azure-iot-0.12.2 (downloaded from Maven repo: https://mvnrepository.com/artifact/com.microsoft.azure.iot/proton-j-azure-iot/0.12.2). With this set up, I am able to send messages to the Could (via sendEventAsync) and receive acknowledgement (via IotHubEventCallback).

In the second set up, a compiled version of the IoT Hub SDK 1.0.15 is used. It is pulled from Maven Repo. I've also checked that the connection string is valid. However, the behaviour is quite different as follows:

- It takes three minutes for the DeviceClient.open() to return. Looking in AmqpIotHubConnection.java, openLock.waitLock(maxWaitTimeForOpeningClosingConnection) is where the wait is. Is this necessary?

- Acknowledgement are not received on the device any more. The implementation of IotHubEventCallback is not called. I used both break points and printing out messages to ADB to confirm this and neither happen. Could you advise on how to investigate and fix this?

Any help appreciated. Best wishes,

Kevin

_Copied from original issue: Azure/azure-iot-sdks#986_

**Comment by tameraw** [comment]
_From @anhashia on November 28, 2016 19:10_

Investigating !

**Comment by tameraw** [comment]
_From @anhashia on December 7, 2016 0:5_

Looking into the issue.

**Comment by tameraw** [comment]
_From @anhashia on December 8, 2016 1:21_

Hi @kevin-ledinh 
I was able to locally **reproduce** the issue using ``iothub-java-device-client:1.0.16``  in Android emulator using **AMQPS** protocol.

This issue looks specific to Android and seems to be coming when accessing **certificate** and needs further investigation. The issue doesn't happen on Windows PC using the same the client library version where client has access to local file system. Below is the thread activity log for reference.

Also, issue seems to be **regression** and doesn't happen if using older version of ``iothub-java-device-client:1.0.9`` with AMQPS protocol in Android application. The issue also doesn't happen with MQTT protocol in Android application using latest ``iothub-java-device-client:1.0.16`` 

**Thread activity log**
````````
<12> pool-1-thread-1@831889970704" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.BlockGuardOs.open(BlockGuardOs.java:106)
	  at java.io.File.createNewFile(File.java:939)
	  at com.microsoft.azure.iothub.DefaultCertificate.getDefaultCertificate(DefaultCertificate.java:47)
	  at com.microsoft.azure.iothub.DeviceClientConfig.getPathToCertificate(DeviceClientConfig.java:245)
	  at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.makeDomain(AmqpsIotHubConnection.java:709)
	  at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.onConnectionBound(AmqpsIotHubConnection.java:453)

````````

``````
<1> main@831887019176" prio=5 sleeping
  java.lang.Thread.State: TIMED_WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:401)
	  at com.microsoft.azure.iothub.ObjectLock.waitLock(ObjectLock.java:9)
	  at com.microsoft.azure.iothub.transport.amqps.AmqpsIotHubConnection.open(AmqpsIotHubConnection.java:210)
	  at com.microsoft.azure.iothub.transport.amqps.AmqpsTransport.open(AmqpsTransport.java:100)
	  at com.microsoft.azure.iothub.DeviceClient.open(DeviceClient.java:175)
	  at com.iothub.azure.microsoft.com.androidsample.MainActivity.SendMessage(MainActivity.java:51)
``````

**Comment by tameraw** [comment]
_From @anhashia on December 8, 2016 1:23_

Similar to https://github.com/Azure/azure-iot-sdks/issues/814

**Comment by tameraw** [comment]
_From @kevin-ledinh on December 15, 2016 10:6_

Hi @anhashia,

Would you be able to update me on this issue?

Best wishes,
Kevin

**Comment by tameraw** [comment]
_From @anhashia on December 15, 2016 19:8_

Hi @kevin-ledinh 
This is coming from the way the certificate is being handled. Product Backlog Item (PBI) has been created  to investigate this further. More details on the root cause is in my **previous** comment above provided 8 days ago .

**Comment by tameraw** [comment]
_From @anhashia on January 9, 2017 18:41_

Hi @kevin-ledinh 

**Root cause**
For AMPQ, Java client library has **dependence** on third party **qpid-proton** library for AMQP protocol. It doesn't seem to be Android aware and doesn't look for ROOT CA store for Android (if no Root CA is passed) for VERIFY_PEER  authentication option. Below links cover passing ROOT CA file in more detail.

1.) https://qpid.apache.org/releases/qpid-proton-0.9/proton/java/api/org/apache/qpid/proton/engine/SslDomain.html#setTrustedCaDb-java.lang.String-

2.) https://qpid.apache.org/releases/qpid-proton-0.9/proton/java/api/org/apache/qpid/proton/engine/SslDomain.VerifyMode.html#VERIFY_PEER_NAME 

If you create a **local copy** of Root CA on Android filesystem for VERIFY_PEER option (which current client library code does) so that you can pass it to qpid-proton library it throws an error and doesn't create local copy of Root CA resulting in the error you are seeing.

**Workaround**
For now, one possible **workaround** would be to use **MQTT** protocol. Client library uses third party  **Paho**  https://eclipse.org/paho/clients/java/ MQTT library which doesn't have this issue as it is supported on Android.

Android sample https://github.com/Azure/azure-iot-sdk-java/tree/master/device/samples/android-sample uses MQTT as default on both send and receive side.

Android sample has been updated to use  latest available `iothub-java-device-client:1.0.16`  client library.
https://github.com/Azure/azure-iot-sdk-java/blob/develop/device/samples/android-sample/app/build.gradle

**Comment by kevin-ledinh** [comment]
Hi @tameraw ,

Using MQTT is going to be disruptive at the current state of the project I'm working on. Can you advise a fix for AMQP protocol?

Thanks, Kev

**Comment by jkriba** [comment]
Hi,
  We are also facing same kind of issue while using AMQPS with Java deviceclient in Android env. And because of business reasons we cannot preffer MQTT as a workaround.

  Kindly let us know if there was any timeline planned for the fix to support AMQPS for Android environment, thanks

Regards
JK

**Comment by prmathur-microsoft** [comment]
Thank jkriba  for raising this. This issue is primarily because we use proton library for AMQP and it is not compatible with Android. We have raised this issue with proton and will work with them for a fix. This is a priority for us too. We will keep you updated as and when we get any information.

**Comment by prmathur-microsoft** [comment]
As of 1.1.25, AMQP and MQTT both work on Android. Please give it a try

**Comment by prmathur-microsoft** [comment]
Closing this the following is resolved now 
1. Close immediately closes without looping
2. SDK works on Android for AMQP and MQTT

Feel free to reopen if you have any further issues.
