### ISSUE TITLE
DeviceNotFoundException: Not registered when device is working and registered

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdk-java#216]
- **OS, version, SKU and CPU architecture used:** Windows 10 Desktop and Server x64
- **Application's .NET Target Framework :** net451 and Java 1.8
- **Device:** Desktop computer / Azure Server
- **SDK version used:** Microsoft.Azure.Devices 1.6.0, Microsoft.Azure.AMQP 2.2.0, Microsoft.Azure.Devices.Shared 1.5.0, Java iot-device-client 1.9.0

# Description of the issue:
As I'm not sure which end is responsible for the issue I've also opened it here: 

[.NET issue 431](https://github.com/Azure/azure-iot-sdk-csharp/issues/431)

Often receiving "Microsoft.Azure.Devices.Common.Exceptions.DeviceNotFoundException -> Not registered" when trying to invoke a method on a device that's running Java iot-device-client using MQTT protocol. The device is online, registered and not blocked, that's been checked on Azure portal directly while reproducing the issue. 

The error happens randomly but very often, some of the method calls work perfectly and some throw the exception (but we can see more exceptions than successful calls), when it fails it's not waiting the connection / response time before it returns the exception and most of the time the device is receiving the message and executing the method properly (even if we see the exception, which prevents us from receiving the method invocation result).

# Code sample exhibiting the issue:

.NET
```
CloudToDeviceMethod method = new CloudToDeviceMethod(METHOD_NAME, TimeSpan.FromSeconds(20), TimeSpan.FromSeconds(20));
method.SetPayloadJson(JsonConvert.SerializeObject(message));

var result = await serviceClient.InvokeDeviceMethodAsync(DEVICE_ID, method);
```

Java

```
client.subscribeToDeviceMethod(new DeviceMethodCallback() {
	@Override
	public DeviceMethodData call(String methodName, Object methodData, Object context) {
		try{
			// ....
		        // Some operations with methodData which generates methodResponseStr
		        // ....
		        return new DeviceMethodData(200, methodResponseStr);
		} catch (Exception e){
			log.debug("Method exception", e);
		}
		return new DeviceMethodData(500, null);
	}
	}, null, new IotHubEventCallback() {
		@Override
		public void execute(IotHubStatusCode responseStatus, Object callbackContext) {
			log.debug("Method status: {}", responseStatus);
		}
	}, null);
```

# Console log of the issue:

> Device {"Message":"{\"errorCode\":404001,\"trackingId\":\"TRACKING_ID:18-TimeStamp:03/27/2018 09:47:35\",\"message\":\"Device not found\",\"timestampUtc\":\"2018-03-27T09:47:35.503359Z\"}","ExceptionMessage":""} not registered

**Comment by timtay-microsoft** [comment]
We're sorry that you are running into issues with this. We'll investigate this issue with the C# SDK as soon as we can. I'll keep you posted.

**Comment by pizerg** [comment]
The issue has been worked around by creating a new hub and migrating all devices to the new one (see csharp sdk issue thread).

**Comment by timtay-microsoft** [comment]
Okay, since it seems to be more a problem with the service than this sdk, I'll go ahead and close this issue.

@pizerg  thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
