### ISSUE TITLE
Android service app, Proton-J AMQPS

### ISSUE THREAD

**Issue by VitSolcik** [Azure/azure-iot-sdk-java#224]
Hi,
I am trying to deploy an Android service app, but I have some issue with connecting to IoT HUB.

As I know client library already work with AMQPS protocol on android using Proton-J library.

But I am afraid that service library doesn't works with Proton-J library on Android (desktop meaven sample works).

Please could You let me know, if someone was trying to make a service Android app or any suggestions are welcome.

I am thinking that this may be certificate problem.

Best regards,
Vit Solcik.

**Comment by timtay-microsoft** [comment]
What king of issues are you running into? Are there any particular exceptions (with stack traces) that you could provide? Do you have a code sample that demonstrates this issue?

**Comment by VitSolcik** [comment]
Hi,

while trying to send cloud to device message I got exception saying **Exception : java.io.IOException: Connection failed to be established**

Here is part of ServiceClient.class which throws exception:
```
    public CompletableFuture<Void> sendAsync(String deviceId, Message message) {
        CompletableFuture<Void> future = new CompletableFuture();
        this.executor.submit(() -> {
            try {
                this.send(deviceId, message);
                future.complete((Object)null);
            } catch (Exception var5) {
                future.completeExceptionally(var5);
            }

        });
        return future;
    }
```

Here is calling of send, it's modified desktop service example:
```
protected static void sendMessage(String commandMessage) throws ExecutionException, InterruptedException, UnsupportedEncodingException
{
    List<CompletableFuture<Void>> futureList = new ArrayList<CompletableFuture<Void>>();
    Map<String, String> propertiesToSend = new HashMap<String, String>();

    // Message messageToSend = new Message(commandMessage + Integer.toString(i));
    Message messageToSend = new Message(commandMessage);

    messageToSend.setDeliveryAcknowledgement(DeliveryAcknowledgement.Full);

    // Setting standard properties
    messageToSend.setMessageId(java.util.UUID.randomUUID().toString());
    System.out.println("Message id set: " + messageToSend.getMessageId());

    // Setting user properties
    propertiesToSend.clear();
    propertiesToSend.put("key_" + Integer.toString(0), "value_" + Integer.toString(0));
    messageToSend.setProperties(propertiesToSend);

    // send the message
    CompletableFuture<Void> future = serviceClient.sendAsync(deviceId, messageToSend);
    futureList.add(future);

    System.out.println("Waiting for all sends to be completed...");
    for (CompletableFuture<Void> future_loop : futureList)
    {
        try
        {
            future_loop.get();
        }
        catch (ExecutionException e)
        {
            if (e.getCause() instanceof  IotHubDeviceMaximumQueueDepthExceededException)
            {
                System.out.println("Maximum queue depth reached");
            }
            else
            {
                System.out.println("Exception : " + e.getMessage());
            }
        }
    }
    System.out.println("All sends completed !");

    System.out.println("Waiting for the feedback...");
    CompletableFuture<FeedbackBatch> future_recv = feedbackReceiver.receiveAsync(); // Default timeout is 60 seconds. [DEFAULT_TIMEOUT_MS = 60000]
    FeedbackBatch feedbackBatch = future_recv.get();

    if (feedbackBatch != null) // check if any feedback was received
    {
        System.out.println(" Feedback received, feedback time: " + feedbackBatch.getEnqueuedTimeUtc());
        System.out.println(" Record size: " + feedbackBatch.getRecords().size());

        for (int i=0; i < feedbackBatch.getRecords().size(); i++)
        {
            System.out.println(" Messsage id : " + feedbackBatch.getRecords().get(i).getOriginalMessageId());
            System.out.println(" Device id : " + feedbackBatch.getRecords().get(i).getDeviceId());
            System.out.println(" Status description : " + feedbackBatch.getRecords().get(i).getDescription());
        }
    }
    else
    {
        System.out.println("No feedback received");
    }
}
```

Any suggestions or advice are welcome, thanks.

**Comment by VitSolcik** [comment]
Hi,

I found that similar issue was discussed with the client library a year ago,
It could help to understand the current issue:
[https://github.com/Azure/azure-iot-sdk-java/issues/21](url)

Regards,
Vit.

**Comment by timtay-microsoft** [comment]
As of now, this SDK does not guarantee Android support. Some aspects of this SDK may work on Android, but we are not currently verifying/developing with Android support in mind. It's likely that we will start supporting it within a few months. For now though, we won't be actively looking into Android bugs. I'll keep this thread posted as we get closer to Android support.

**Comment by jasmineymlo** [comment]
@VitSolcik, Sorry for the delayed response. I can repro the issue and currently looking into it. I will update this thread with findings later.  Which API level are you running the service client on?

**Comment by jasmineymlo** [comment]
@VitSolcik .  We have fix a few bugs along way getting full e2e test suite running on android.  Samples for both device client and service client are updated in https://github.com/Azure-Samples/azure-iot-samples-java/tree/master/iot-hub/Samples/.  Take a look and let us know if you are still running into any issue.  Thanks.

**Comment by jasmineymlo** [comment]
Please let us know or reopen this bug if you are still seeing issue.  Thanks.

**Comment by az-iot-builder-01** [comment]
@VitSolcik, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
