### ISSUE TITLE
Android app crashes when trying to run service client SDK

### ISSUE THREAD

**Issue by GamalMohamed** [Azure/azure-iot-sdk-java#229]
I'm trying to use this Service SDK "'com.microsoft.azure.sdk.iot:iot-service-client:1.9.25'" on an android application extending the "android-sample" project here, but it immediately crashes once I run it..
I'm using a real device running Android Oreo 8.0 (API 26)..
The code is barely the same as the sample except I added the Service SDK dependency in the build.gradle, after which the app crashes upon startup directly..
Worth mentioning that it crashes too on any emulator running API 26, but surprisingly works normally on emulator running API 27 and without any code changes!!)..

So any idea why is this happening and how to make it run on API 26 physical device ??

**Here's my build.gradle:**

    apply plugin: 'com.android.application'
    
    android {
         compileSdkVersion 26
         defaultConfig {
         applicationId "com.example.jimmy.android_iothub"
         minSdkVersion 26
         targetSdkVersion 26
         versionCode 1
         versionName "1.0"
         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
     }
         buildTypes {
             release {
               minifyEnabled false
               proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude "META-INF/MSFTSIG.SF"
        exclude "META-INF/MSFTSIG.RSA"
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'thirdpartynotice.txt'
        }
    }

    dependencies {
        implementation fileTree(dir: 'libs', include: ['*.jar'])
        implementation 'com.android.support:appcompat-v7:26.1.0'
        implementation 'com.android.support.constraint:constraint-layout:1.1.0'
        implementation 'com.android.support:design:26.1.0'
        testImplementation 'junit:junit:4.12'
        androidTestImplementation 'com.android.support.test:runner:1.0.1'
        androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        // Remote binary dependency
        compile 'com.microsoft.azure.sdk.iot:iot-device-client:1.5.37'
        compile 'com.microsoft.azure.sdk.iot:iot-service-client:1.9.25'
    }

**Comment by VitSolcik** [comment]
Hi,

I am trying to make an Android App with service library as well.
I don't have same problem as you, but I have some issue with connection via Proton-J AMQPS library.

I would like to ask you if you established connection once the app run without crashes.

My issue: [link](https://github.com/Azure/azure-iot-sdk-java/issues/224)

Thanks for reply.

**Comment by timtay-microsoft** [comment]
As of now, this SDK does not guarantee Android support. Some aspects of this SDK may work on Android, but we are not currently verifying/developing with Android support in mind. It's likely that we will start supporting it within a few months. For now though, we won't be actively looking into Android bugs. I'll keep this thread posted as we get closer to Android support.

**Comment by jasmineymlo** [comment]
@GamalMohamed @VitSolcik Sorry for the delayed response.  I can repro the issue and currently looking into it.  I will update this thread with findings later.  Did you happen to find a fix/workaround for it?

**Comment by GamalMohamed** [comment]
@jasmineymlo Actually No. 
I just restricted my app to work under Oreo 8.1 (API 27) for the time being.

**Comment by jasmineymlo** [comment]
Please let us know if you still see the same issue.  Feel free to reopen this if needed.  Thanks

**Comment by az-iot-builder-01** [comment]
@VitSolcik, @GamalMohamed, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
