### ISSUE TITLE
Consider refactoring package names

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-iot-sdk-java#232]
It seems the standard convention in Java SDKs for Azure is to have non-public API in an 'internal' package (with subpackages as appropriate). This makes it clearer to developers what API they should and shouldn't use.

My understanding is that the following packages represent all public API - all other packages would then ideally be relocated under `com.microsoft.azure.sdk.iot.internal`:

```
com.microsoft.azure.sdk.iot.device
com.microsoft.azure.sdk.iot.device.DeviceTwin
com.microsoft.azure.sdk.iot.device.exceptions
com.microsoft.azure.sdk.iot.device.transport.amqps.exceptions
com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions
com.microsoft.azure.sdk.iot.provisioning.device
com.microsoft.azure.sdk.iot.provisioning.security
com.microsoft.azure.sdk.iot.provisioning.security.exceptions
com.microsoft.azure.sdk.iot.provisioning.service
com.microsoft.azure.sdk.iot.provisioning.service.exceptions
com.microsoft.azure.sdk.iot.service
com.microsoft.azure.sdk.iot.service.devicetwin
com.microsoft.azure.sdk.iot.service.exceptions
com.microsoft.azure.sdk.iot.service.jobs
```

**Comment by timtay-microsoft** [comment]
We aren't likely to make this change as it would be a breaking change, but we will keep this feedback in mind for any new packages we create.
