### ISSUE TITLE
The Java corresponding SDK for Azure IotHub has the JobType in uppercase, and the job API does not support uppercase.

### ISSUE THREAD

**Issue by chenzheng1988** [Azure/azure-iot-sdk-java#235]
Operating environment:Windows Server 2016 Datacenter
Use language:JAVA
SDK：Iot Hub SDK 
Accomplish the aim：In Azure, the Java SDK corresponding to IotHub is used to implement bulk registration devices.
Error：Internal server error
After a local test, create the job API (hostname /jobs/create for https://iothub) when the call is created.API -version=2016-11-14 times error, finally found that JobType in the SDK is in capital format, the call to create job API does not recognize capital error, change to lowercase format can be successful.
SDK Address：https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/JobProperties.java

**Comment by jasmineymlo** [comment]
@chenzheng1988, would you provide us more details on the issue?  The best would be a snippet from your code.  Thanks.

**Comment by chenzheng1988** [comment]
Hi,

After testing, the API that created the job did not recognize the uppercase JobType, and the Java SDK had the JobType in uppercase format, resulting in the inability to register the device in bulk, and the SDK of C# was in lower case to register the device in bulk. The code is as follows:

Java

C#

public enum JobType
{
       UNKNOWN,
       EXPORT,
       IMPORT
}

                    /// <summary>


    /// Used to delineate job actions.


    /// </summary>


    [JsonConverter(typeof(StringEnumConverter))]


    public enum JobType


    {


        /// <summary>


        /// Unknown


        /// </summary>


        [EnumMember(Value = "unknown")]


        Unknown = 0,





        /// <summary>


        /// Indicates an ExportDevices job


        /// </summary>


        [EnumMember(Value = "export")]


        ExportDevices,





        /// <summary>


        /// Indicates an ImportDevices job


        /// </summary>


        [EnumMember(Value = "import")]


        ImportDevices,





        /// <summary>


        /// Indicates a Device method job


        /// </summary>


        [EnumMember(Value = "scheduleDeviceMethod")]


        ScheduleDeviceMethod,





        /// <summary>


        /// Indicates a Twin update job


        /// </summary>


        [EnumMember(Value = "scheduleUpdateTwin")]


        ScheduleUpdateTwin


    }




[cid:image002.jpg@01D11C9F.4972C090]


Jonny Chen (陈政) | CIE Support Engineer | Microsoft Azure Technical Support, Blue Cloud, 21ViaNet Group, Inc.
Support direct line: 010-56060255   Customer support hot line: 400-089-0365
Case submission & history: https://support.azure.cn/support/support-azure
Cloud solution consulting: 400-085-0139   Website: http://www.21vbluecloud.com<http://www.21vbluecloud.com/>
If you have any feedback about my work, please contact me or my manager Lin Zhongsheng at lin.zhongsheng@oe.21vianet.com<mailto:lin.zhongsheng@oe.21vianet.com>

**Comment by chenzheng1988** [comment]
In the Java SDK, the JobType is capitalized, and the job creation API does not support capitalization.
Code:https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/JobProperties.java

public enum JobType
{
       UNKNOWN,
       EXPORT,
       IMPORT
}

**Comment by jasmineymlo** [comment]
@chenzheng1988, please send me your application code, not the SDK code snippet.  I would like to see how you are using the JobType and which job creation API you are referring to.  Moreover, are you using the JobClient?  Thanks

**Comment by chenzheng1988** [comment]
Do you know the problem?

**Comment by jasmineymlo** [comment]
@chenzheng1988, Which version of SDK are you using?

**Comment by chenzheng1988** [comment]
<groupId>com.microsoft.azure.sdk.iot</groupId>
    <artifactId>iot-service-client</artifactId>
    <name>Iot Hub Java Service SDK</name>
    <version>1.13.2</version>

**Comment by chenzheng1988** [comment]
Hello, is there any progress?

**Comment by timtay-microsoft** [comment]
Since you opened another issue with the same problem, but with a more clear discussion of the issue, I'm closing this issue and directing all further discussion towards [Github Issue #258](https://github.com/Azure/azure-iot-sdk-java/issues/258)
