### ISSUE TITLE
removeDesiredProperties doesn't work

### ISSUE THREAD

**Issue by taroyutao** [Azure/azure-iot-sdk-java#236]
when I use the method:

            desiredProperties.add(new Pair("hum", "yutaotest123"));

            device.setDesiredProperties(desiredProperties);
            System.out.println("Updating Device twin (remove hum)");
            twinClient.updateTwin(device);

            System.out.println("Getting the updated Device twin");
            twinClient.getTwin(device);
            System.out.println(device);

It works ok and can add one tag to device twin, the result is:

Updating Device twin (remove hum)
Getting the updated Device twin
Device ID: myDeviceId
ETag: AAAAAAAAAUw=
Tags:{"plant":"Redmond43","region":"China Suth"}
Reported Properties{"telemetryConfig":{"configId":"0","sendFrequency":"24h"},"newState":"standBy","$version":8,"$metadata":{"$lastUpdated":"2018-01-15T15:34:08.299Z","$lastUpdatedVersion":null,"telemetryConfig":{"$lastUpdated":"2018-01-15T15:34:08.299Z","$lastUpdatedVersion":null,"configId":{"$lastUpdated":"2018-01-15T15:34:08.299Z"},"sendFrequency":{"$lastUpdated":"2018-01-15T15:34:08.299Z"}},"newState":{"$lastUpdated":"2018-01-15T07:50:00.2Z"}}}
Desired Properties: {"**hum":"yutaotest123**","configUpdateTime":"2018-01-12T02:20:57.1234567Z","telemetryConfig1":"{test1}","telemetryConfig":"null","$version":329,"$metadata":{"$lastUpdated":"2018-05-15T08:59:54.708Z","$lastUpdatedVersion":329,"hum":{"$lastUpdated":"2018-05-15T08:59:54.708Z","$lastUpdatedVersion":329},"configUpdateTime":{"$lastUpdated":"2018-01-15T07:24:17.86Z","$lastUpdatedVersion":305},"telemetryConfig1":{"$lastUpdated":"2018-05-15T07:43:22.499Z","$lastUpdatedVersion":318},"telemetryConfig":{"$lastUpdated":"2018-05-15T08:33:50.878Z","$lastUpdatedVersion":327}}}

but when i used remove method:

            **desiredProperties.add(new Pair("hum", null));**

            device.setDesiredProperties(desiredProperties);
            System.out.println("Updating Device twin (remove hum)");
            twinClient.updateTwin(device);

            System.out.println("Getting the updated Device twin");
            twinClient.getTwin(device);
            System.out.println(device);

Updating Device twin (remove hum)
Getting the updated Device twin
Device ID: myDeviceId
ETag: AAAAAAAAAUw=
Tags:{"plant":"Redmond43","region":"China Suth"}
Reported Properties{"telemetryConfig":{"configId":"0","sendFrequency":"24h"},"newState":"standBy","$version":8,"$metadata":{"$lastUpdated":"2018-01-15T15:34:08.299Z","$lastUpdatedVersion":null,"telemetryConfig":{"$lastUpdated":"2018-01-15T15:34:08.299Z","$lastUpdatedVersion":null,"configId":{"$lastUpdated":"2018-01-15T15:34:08.299Z"},"sendFrequency":{"$lastUpdated":"2018-01-15T15:34:08.299Z"}},"newState":{"$lastUpdated":"2018-01-15T07:50:00.2Z"}}}
Desired Properties: {**"hum":"yutaotest123",**"configUpdateTime":"2018-01-12T02:20:57.1234567Z","telemetryConfig1":"{test1}","telemetryConfig":"null","$version":329,"$metadata":{"$lastUpdated":"2018-05-15T08:59:54.708Z","$lastUpdatedVersion":329,"hum":{"$lastUpdated":"2018-05-15T08:59:54.708Z","$lastUpdatedVersion":329},"configUpdateTime":{"$lastUpdated":"2018-01-15T07:24:17.86Z","$lastUpdatedVersion":305},"telemetryConfig1":{"$lastUpdated":"2018-05-15T07:43:22.499Z","$lastUpdatedVersion":318},"telemetryConfig":{"$lastUpdated":"2018-05-15T08:33:50.878Z","$lastUpdatedVersion":327}}}

**the tags doesn't removed.**

pom.xml:

        
        <dependency>
            <groupId>com.microsoft.azure.sdk.iot</groupId>
            <artifactId>iot-service-client</artifactId>
            <version>1.13.1</version>
        </dependency>

DeviceTwinSample.java:https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java

**Comment by taroyutao** [comment]
the same method works in C# SDK

**Comment by taroyutao** [comment]
json method lose the request data, I think it's maybe the reason about this issue.
[image]()

**Comment by karlchen7** [comment]
The Bug was already fixed (#221 old Issue)

Update to version 1.13.2  and it works, but another Bug will come later :) 
I am going to open an new Issue for this bug in a few minutes!

**Comment by timtay-microsoft** [comment]
@karlchen7 is correct. This bug was resolved in the latest version. I'm going to close this issue. If you still see this issue with the latest version, feel free to re-open this bug.

@taroyutao thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).

**Comment by taroyutao** [comment]
I works well now, thank you very much.
