### ISSUE TITLE
The batch removal device attribute failed

### ISSUE THREAD

**Issue by chenzheng1988** [Azure/azure-iot-sdk-java#238]
The device attribute failed to be removed in batch, the device property was set to null, the batch update was performed, and the final device attribute was still present and was not removed.

        // new set of desired properties
        Set<Pair> desiredProperties = new HashSet<Pair>();
        //desiredProperties.add(new Pair("temp", new Random().nextInt(TEMPERATURE_RANGE)));
        desiredProperties.add(new Pair("Name", "wo"));
        device.setDesiredProperties(desiredProperties);

        // date when the update shall be executed
        Date updateDateInFuture = new Date(new Date().getTime() + ADD_10_SECONDS_IN_MILLISECONDS); // 10 seconds in the future.

        // query condition that defines the list of device to be updated
        String queryCondition = "DeviceId IN " + deviceIds + "";

        System.out.println("Schedule updating Device twin (new temp, hum) in 10 seconds");
        Job job = twinClient.scheduleUpdateTwin(queryCondition, device, updateDateInFuture, MAX_EXECUTION_TIME_IN_SECONDS);

        System.out.println("Wait for job completed..."+job.getJobId());
        JobResult jobResult = job.get();
        while (jobResult.getJobStatus() != JobStatus.completed)
        {
            Thread.sleep(GIVE_100_MILLISECONDS_TO_IOTHUB);
            jobResult = job.get();
        }
        System.out.println("job completed");

        System.out.println("Getting the updated Device twin");
        twinClient.getTwin(device);
        System.out.println(device);

pom.xml:
       <dependency>
            <groupId>com.microsoft.azure.sdk.iot</groupId>
            <artifactId>iot-service-client</artifactId>
            <version>1.13.2</version>
        </dependency>

**Comment by chenzheng1988** [comment]
Set the name property to null, and the name attribute still exists after executing the code, without removing it.

     desiredProperties.add(new Pair("Name", null));

Result:

     Desired Properties: {"hum":"asf","temp":64.0,"Address":"China","testproper":"","ID":1.0,"Name":"wo","$version":15,

**Comment by chenzheng1988** [comment]
So I can only delete the property of one device. What do I do if I want to delete the attributes of multiple devices in batches?

**Comment by timtay-microsoft** [comment]
Currently, the IotHub service does not support batch updates for twin, so you can only updateTwin on a device-by-device basis.

**Comment by timtay-microsoft** [comment]
I'm having trouble understanding your previous comment. Are you saying that setting a property to null still does not result in the property being removed in the sample code I gave you?

**Comment by chenzheng1988** [comment]
I want to delete the device attributes in bulk. The example you gave earlier can only delete the attributes of a single device and not delete multiple devices.

**Comment by chenzheng1988** [comment]
Here is the code I used：

       public static final String deviceId = "mydevice1";
       public static final String deviceIds="['mydevice0','mydevice1','mydevice2']";
        public static void main(String[] args) throws Exception
    {

        System.out.println("Starting sample...");
        DeviceTwin twinClient = DeviceTwin.createFromConnectionString(SampleUtils.iotHubConnectionString);
        DeviceTwinDevice device = new DeviceTwinDevice(deviceId);
        try
        {           
            // ============================ schedule update desired property ==========================
            scheduleUpdateDesiredProperties(twinClient, device);
        }
    }
     private static void scheduleUpdateDesiredProperties(DeviceTwin twinClient, DeviceTwinDevice device) throws IOException, IotHubException, InterruptedException
    {
        // new set of desired properties
        Set<Pair> desiredProperties = new HashSet<Pair>();
        desiredProperties.add(new Pair("hum", null));

        device.setDesiredProperties(desiredProperties);
        // date when the update shall be executed
        Date updateDateInFuture = new Date(new Date().getTime() + ADD_10_SECONDS_IN_MILLISECONDS); // 10 seconds in the future.
        // query condition that defines the list of device to be updated
        String queryCondition = "DeviceId IN " + deviceIds + "";
        System.out.println("Schedule updating Device twin (new temp, hum) in 10 seconds");
        Job job = twinClient.scheduleUpdateTwin(queryCondition, device, updateDateInFuture, MAX_EXECUTION_TIME_IN_SECONDS);   
        System.out.println("Wait for job completed..."+job.getJobId());   
        String start=Instant.now().toString();
        System.out.println("Wait for job completed...starttime "+start);
        
        JobResult jobResult = job.get();
        while (jobResult.getJobStatus() != JobStatus.completed)
        {
            Thread.sleep(GIVE_100_MILLISECONDS_TO_IOTHUB);
            jobResult = job.get();
        }
        String start1=Instant.now().toString();
        System.out.println("Wait for job completed...endtime "+start1); 
        System.out.println("job completed");

        System.out.println("Getting the updated Device twin");
        twinClient.getTwin(device);
        System.out.println(device);
        
        desiredProperties.clear();
        desiredProperties.add(new Pair("Name", null));
        device.setDesiredProperties(desiredProperties);
        twinClient.updateTwin(device);
        twinClient.getTwin(device);
        System.out.println(device);
    }

the result is: the hum attribute of the mydevice1 device has been deleted, but the hum properties of the two devices of mydevice0 and mydevice2 still exist. 
So I want to delete the hum property of all three devices.What should I do?

**Comment by timtay-microsoft** [comment]
Okay, I understand your problem now, then. You currently cannot do batch removal of an attribute on devices, but only due to a bug with our Service Client. I'll try to get the fix for that in before our release on 5/25. When I release the fix for this bug, I will update this thread with a sample code for doing what you want.

**Comment by timtay-microsoft** [comment]
The fix for this issue has been checked in. Feel free to build from source to check that the bug is resolved for you. Our next package release will be tomorrow.

For doing batch updates that remove an attribute from multiple devices, you will use the same API that you are using to add those properties in your sample code. You just need to set the desired property to null to delete it.

**Comment by timtay-microsoft** [comment]
The fix for this bug has been released in Service Client 1.13.3.

Since the fix has been released, I'm closing this issue. Feel free to re-open if you still see this issue.

@chenzheng1988 thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).

**Comment by chenzheng1988** [comment]
This problem has been solved. Thank you very much!
