### ISSUE TITLE
PropertyCallBack interface Function name 'PropertyCall' should start with a lowercase letter

### ISSUE THREAD

**Issue by Ernest-su** [Azure/azure-iot-sdk-java#242]
`com.microsoft.azure.sdk.iot.device.DeviceTwin.PropertyCallBack`
 interface Function name 'PropertyCall' should start with a lowercase letter

**Comment by timtay-microsoft** [comment]
This would be a breaking change at this point, but we will be able to fix this later when we are allowed to make breaking changes.

**Comment by timtay-microsoft** [comment]
We have opted to leave this mistake alone in order to avoid any breaking changes, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@Ernest-su, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
