### ISSUE TITLE
DeviceClient.open() in Android devices without internet make leak one thread

### ISSUE THREAD

**Issue by FranAlterados** [Azure/azure-iot-sdk-java#247]
- **OS and version used:** Android 7.0

- **Java runtime used:** 1.8

- **SDK version used:** 
iot-device-client:1.11.0
iot-service-client:1.13.2
iot-deps:0.5.2
azure-storage-android:2.0.0
org.apache.commons:commons-lang3:3.6

# Description of the issue:
When I do open() in a DeviceClient and my android device doesn't have internet one thread called "MQTT Con: XXXXX" is created and never destroyed

# Code sample exhibiting the issue:
```java
public class MainActivity extends AppCompatActivity {

    Button btOpenConnection;
    Button btCloseConnection;

    DeviceClient client;

    private final String connString = "[device connection string]";
    private final String deviceId = "MyAndroidDevice";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        btOpenConnection = findViewById(R.id.bt_open_connection);
        btOpenConnection.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
                try {
                    client = new DeviceClient(connString, protocol);
                    try {
                        client.open();
                    } catch (Exception e2) {
                        System.err.println("Exception while opening IoTHub connection: " + e2.toString());
                    }
                } catch (URISyntaxException e) {
                    e.printStackTrace();
                    System.err.println("Exception while creating device client: " + e.toString());
                }
            }
        });

        btCloseConnection = findViewById(R.id.bt_close_connection);
        btCloseConnection.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                try {
                    client.closeNow();
                } catch (IOException e) {
                    e.printStackTrace();
                    System.err.println("Exception while close device client: " + e.toString());
                }
            }
        });
    }
}
```

**Comment by timtay-microsoft** [comment]
As of now, this SDK does not guarantee Android support. Some aspects of this SDK may work on Android, but we are not currently verifying/developing with Android support in mind. It's likely that we will start supporting it within a few months. For now though, we won't be actively looking into Android bugs. I'll keep this thread posted as we get closer to Android support.

**Comment by timtay-microsoft** [comment]
The threads that spawn when using AMQPS are tied to the reconnection process. They should end shortly after reconnection succeeds.

HTTPS is long term supported, so you are safe to build around it.

**Comment by FranAlterados** [comment]
I just discovered a problem using HTTPS protocol, it doesn't support Direct Methods, Twin Devices, etc.

If the others protocols have issues with threads leaks, how I can solve this?

**Comment by timtay-microsoft** [comment]
Correct, HTTPS does not currently support twin/methods, and we don't have a timeline on when that functionality will be added.

If you want to use MQTT, you can take a look at the Paho issues that have already been filed that I listed above. You could provide them a PR to fix the issue.

If you want to use AMQPS, there shouldn't be any leaked threads. There are some additional threads that are spawned, but those are necessary to create an AMQPS connection. They should close properly when you close your device client instance. Is that not happening for you?

**Comment by timtay-microsoft** [comment]
What are the actual names of the threads that AMQP is leaking for you during a disconnect? azure-iot-sdk-<what?>

**Comment by FranAlterados** [comment]
The leaking threads while I loose and regain connectivity are not called azure-iot-sdk, those threads seems to work fine.

The leaking threads are named "pool-XX-thread-X" where "X" are diferent numbers

**Comment by timtay-microsoft** [comment]
Some headway has been made in identifying and resolving the AMQP issue here. See issue #273 for further discussion.

**Comment by FranAlterados** [comment]
Thanks!! Now I'm suscribed to the issue waiting the fix :)

**Comment by jasmineymlo** [comment]
Closing this one as AMQP thread leaks are tracked in #273.

**Comment by az-iot-builder-01** [comment]
@FranAlterados, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
