### ISSUE TITLE
HTTP Proxy - not working?

### ISSUE THREAD

**Issue by vpopescu** [Azure/azure-iot-sdk-java#25]
I am using the sample in the SDK, for a java service client. I've changed the protocol from AMQP to AMQP.WS, 

I've not had any luck in getting this to work over a proxy. I've tried settings the proxy at JVM level with:

-DproxySet=true -Dhttp.proxyHost=proxy.company.com -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxy.company.com -Dhttps.proxyPort=8080

The SDK insists on trying to connect to azure directly. It doesn't throw any errors, but looking at the trace it should've at least thrown a certficate error because it is retrieving our firewall's ceritificate which is not matching the hostname)

When switching to a network that is not behind the proxy, everything works well.
Am I missing something, or is this a bug / known limitation?

I'm running on Linux, OpenJDK 1.8. We have an unauthenticated proxy.

**Comment by markrad** [comment]
Hi @vpopescu,

I agree with your assertion. Unfortunately this does not appear to be in our code but in the Proton library. I provided both a valid proxy (saw no traffic from my test application) and an invalid proxy (expected it to blow up but it didn't) and the sample still used a direct connection. Since our SDK doesn't mange the actual socket communications, at this time I am assuming this is a limitation of the Proton library.

_Mark Radbourne MSFT_

**Comment by tameraw** [comment]
@vpopescu - This is currently not supported in Java. If you're interested in providing a pull request for this, we'd happily review it.

**Comment by msdevanms** [comment]
Since many companies are working behind proxy, it will be good if azure IoT client supports this feature. Any other library other than Java currently supporting this feature ?

**Comment by Brideau** [comment]
@markrad @msdevanms Any update on this problem? This is a deal killer for us if we can't go through our proxy.

**Comment by prmathur-microsoft** [comment]
Sorry about the delay on this. It is in our backlog and we will work on prioritizing this.

**Comment by jasmineymlo** [comment]
Stay tune, this is still in our backlog.

**Comment by rahul-pharande** [comment]
@jasmineymlo Do you have any updates here? I'm also facing connection issue using azure iot-device-provisoining service client.

**Comment by timtay-microsoft** [comment]
This feature is being actively worked on now

**Comment by timtay-microsoft** [comment]
Finally closing this issue as proxy support has been added as of [this release](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2019-09-30_2)

**Comment by az-iot-builder-01** [comment]
@vpopescu, @msdevanms, @Brideau, @prmathur-microsoft, @gabiSRC, @rahul-pharande, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
