### ISSUE TITLE
Cannot import the device in bulk

### ISSUE THREAD

**Issue by chenzheng1988** [Azure/azure-iot-sdk-java#258]
SDK Version:iot-service-client 1.13.3
The code for batch importing devices is as follows:
    
        System.out.println("Starting import sample...");
        // Creating Azure storage container and getting its URI
        CloudStorageAccount storageAccount = CloudStorageAccount.parse(SampleUtils.storageConnectionString);
        CloudBlobClient blobClient = storageAccount.createCloudBlobClient();
        CloudBlobContainer container = blobClient.getContainerReference(importContainerName);
        container.createIfNotExists();
        String containerSasUri = SampleUtils.getContainerSasUri(container);

       
        // Creating the list of devices to be submitted for import
        StringBuilder devicesToImport = new StringBuilder();
        for (int i = 0; i < 5; i++)
        {
            String deviceId = UUID.randomUUID().toString();
            Device device = Device.createFromId(deviceId, null, null);
            AuthenticationMechanism authentication = new AuthenticationMechanism(device.getSymmetricKey());

            ExportImportDevice deviceToAdd = new ExportImportDevice();
            deviceToAdd.setId(deviceId);
            deviceToAdd.setAuthentication(authentication);
            deviceToAdd.setStatus(DeviceStatus.Enabled);
            deviceToAdd.setImportMode(ImportMode.CreateOrUpdate);

            devicesToImport.append(gson.toJson(deviceToAdd));

            if (i < numberOfDevice - 1)
            {
                devicesToImport.append("\r\n");
            }
        }

        byte[] blobToImport = devicesToImport.toString().getBytes(StandardCharsets.UTF_8);

        // Creating the Azure storage blob and uploading the serialized string of devices
        System.out.println("Uploading " + blobToImport.length + " bytes into Azure storage.");
        InputStream stream = new ByteArrayInputStream(blobToImport);
        CloudBlockBlob importBlob = container.getBlockBlobReference(importBlobName);
        importBlob.deleteIfExists();
        importBlob.upload(stream, blobToImport.length);

        // Starting the import job
        RegistryManager registryManager = RegistryManager.createFromConnectionString(SampleUtils.iotHubConnectionString);
        JobProperties importJob = registryManager.importDevices(containerSasUri, containerSasUri);

        // Waiting for the import job to complete
        while(true)
        {
            importJob = registryManager.getJob(importJob.getJobId());
            if (importJob.getStatus() == JobProperties.JobStatus.COMPLETED
                    || importJob.getStatus() == JobProperties.JobStatus.FAILED)
            {
                break;
            }
            Thread.sleep(500);
        }

        // Checking the result of the import job
        if (importJob.getStatus() == JobProperties.JobStatus.COMPLETED)
        {
            System.out.println("Import job completed. The new devices are now added to the hub.");
        }
        else
        {
            System.out.println("Import job failed. Failure reason: " + importJob.getFailureReason());
        }

        //Cleaning up the blob
        for(ListBlobItem blobItem : container.listBlobs())
        {
            if (blobItem instanceof CloudBlob)
            {
                CloudBlob blob = (CloudBlockBlob) blobItem;
                blob.deleteIfExists();
            }
        }

        registryManager.close();
result of enforcement:
     
     Starting import sample...
     Uploading 1260 bytes into Azure storage.
     Import job failed. Failure reason: Internal server error.
     End Batch Add Properties.....

**Comment by chenzheng1988** [comment]
I found that the reason is that the JobType in the SDK is uppercase. When calling the API that created the job, the uppercase JobType is not recognized, and changing the JobType to lowercase is successful.
https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/JobProperties.java

    public enum JobType
    {
       UNKNOWN,
       EXPORT,
       IMPORT
    }

**Comment by timtay-microsoft** [comment]
You are right, this is a bug on our side. I'll take a look into this.

**Comment by timtay-microsoft** [comment]
The fix for this issue has been checked into the master branch. Feel free to build from source to verify that it works for you. We plan on doing our next release on 6/14

**Comment by timtay-microsoft** [comment]
The fix for the SDK side of this issue has been released as of Service Client 1.13.4

Because of that, I'm closing this issue. Feel free to re-open if you still face this issue.

@chenzheng1988  thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
