### ISSUE TITLE
IoT Hub responded to device twin operation with status ERROR

### ISSUE THREAD

**Issue by vikramtamboli** [Azure/azure-iot-sdk-java#260]
Azure Device Simulation using Java
Once the DeviceTwin is created we are trying to set Reported Properties which gives me error.
**IoT Hub responded to device twin operation with status ERROR**
OS - Windows 7
Programming Language - JAVA

IotHubClientProtocol protocol = IotHubClientProtocol.MQTT;
DeviceClient client = new DeviceClient(con, protocol);
client.subscribeToDeviceMethod(new DirectMethodCallback(), null, new DirectMethodStatusCallback(), null);
client.startDeviceTwin(new DeviceTwinStatusCallback(), null, new PropertyCallback(), null);

DeviceTwin twinClient = DeviceTwin.createFromConnectionString(iotHubConnectionString);
DeviceTwinDevice device = new DeviceTwinDevice(deviceId.getValue());
twinClient.getTwin(device);

HashMap initialUpdate = new HashMap();
Property sentProperty = new Property("firmwareUpdate", initialUpdate);
Set<Property> sentPackage = new HashSet<>();

initialUpdate.put("status", "success");
initialUpdate.put("fwPackageUri", "https://xxxx/DryRun.zip");
initialUpdate.put("startedWaitingTime", LocalDateTime.now().toString());
sentPackage.add(sentProperty);
client.sendReportedProperties(sentPackage);

No exception is thrown. 
any help would be appreciated.

**Comment by timtay-microsoft** [comment]
I'm not seeing the same behavior when I run your code snippet. I'm just getting the expected OK or OK_EMPTY

Are there any special characters in that "https://xxxx/DryRun.zip" String you are using?

Are you getting that ERROR consistently?

Are you seeing the same behavior when using AMQPS?

**Comment by timtay-microsoft** [comment]
@vikramtamboli are you able to provide more information on this behavior?

**Comment by vikramtamboli** [comment]
Hi

If I change protocol to AMQP client is unable to do connection to IoT hub.
Currently we are using MQTT.
Could you point me to right URL where we have working sample code for the reading desired properties & write to reported properties.

**Comment by timtay-microsoft** [comment]
Can you please provide the stacktrace for the error that prevents you from using AMQP?

We have a sample you can use for listening on desired properties and sending reported properties:
https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java

**Comment by timtay-microsoft** [comment]
And what do you mean the behavior is "weird"? Are the properties reported incorrectly? Do you encounter an exception?

**Comment by vikramtamboli** [comment]
**Entire Code**
package com.cognizant.iotworkbench.Controller;

import com.microsoft.azure.sdk.iot.device.DeviceClient;
import com.microsoft.azure.sdk.iot.device.DeviceTwin.Property;
import com.microsoft.azure.sdk.iot.device.DeviceTwin.PropertyCallBack;
import com.microsoft.azure.sdk.iot.device.IotHubClientProtocol;
import com.microsoft.azure.sdk.iot.device.IotHubEventCallback;
import com.microsoft.azure.sdk.iot.device.IotHubStatusCode;
import java.io.IOException;
import java.net.URISyntaxException;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Set;
import org.apache.log4j.Level;
import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

public class ThreeMTestClass {

    static Logger logger = LogManager.getLogger(ThreeMTestClass.class);

    public static void main(String[] args) {
        //BasicConfigurator.configure();
        //logger.info("Hello, World!");
        m3test obj = new m3test();
        obj.test();
    }
}

class m3test {

    static Logger logger = LogManager.getLogger(m3test.class);

    public void test() {
        try {
            String connString = "";
            DeviceClient client = new DeviceClient(connString, IotHubClientProtocol.HTTPS);
            logger.info("Device Object Created.");
            client.open();
            logger.info("Connection Open.");
            client.startDeviceTwin(new DeviceTwinStatusCallback(), null, new PropertyCallback(), null);
            while (true) {
                HashMap initialUpdate = new HashMap();
                Property sentProperty = new Property("softwareConfig", initialUpdate);
                Set<Property> sentPackage = new HashSet<>();

                initialUpdate.put("softwareName", new Date());
                initialUpdate.put("version", "previousVersion");
                initialUpdate.put("softwareURL", "previousSoftwareURL");
                initialUpdate.put("softwarePackageId", "previousSoftwarePackageId");
                initialUpdate.put("fileName", "previousFilename");
                initialUpdate.put("serialNumber", "previousSoftwareName");
                initialUpdate.put("checkSum", "previousChecksum");
                initialUpdate.put("status", "success");

                sentPackage.add(sentProperty);
                client.sendReportedProperties(sentPackage);
                Thread.sleep(5000);
            }
        } catch (InterruptedException | URISyntaxException | IOException ex) {
            Logger.getLogger(m3test.class.getName()).log(Level.ERROR, null, ex);
        }
    }

    protected class DeviceTwinStatusCallback implements IotHubEventCallback {

        @Override
        public void execute(IotHubStatusCode status, Object context) {
            System.out.println("IoT Hub responded to device twin operation with status " + status.name());
        }
    }

    protected class PropertyCallback implements PropertyCallBack<String, String> {

        @Override
        public void PropertyCall(String propertyKey, String propertyValue, Object context) {
            System.out.println("PropertyKey:     " + propertyKey);
            System.out.println("PropertyKvalue:  " + propertyKey);
        }
    }
}
**Logs:**
IotHubConnectionString object is created successfully for cnn-e1-iot-dev-01.azure-devices.net, method name is <init> 
DeviceClientConfig object is created successfully with XXXX, deviceID=YYYY, method name is <init> 
DeviceIO object is created successfully, method name is <init> 
DeviceClient object is created successfully, method name is commonConstructorSetup 
Device Object Created.
Connection opened with success, method name is open 
Connection Open.
Message with messageid d36b87ab-968e-4817-b3e6-3592b77c25cd along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
Message with messageid e074e577-71d3-4a5e-baa5-41c7bc7474c8 along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
**IoT Hub responded to device twin operation with status ERROR**
Message with messageid c2b61911-f14c-492e-818d-753877bce2bc along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
Message with messageid ed0ce5f2-4fc5-4121-92af-4e99c2882f5c along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
Message with messageid ae85fc57-bab0-4922-9d12-2acd70fe9e3b along with callback and callbackcontext is added to the queue, method name is sendEventAsync 

Please let me know if i am missing anything?

**Comment by timtay-microsoft** [comment]
Looks like the problem here is that you are trying to use HTTP to do twin updates. Currently, the service does not sending reported properties over HTTP. 

In your opening post of this issue, your code snippet was using MQTT. Can you double check to see if you are getting this ERROR behavior even with MQTT?

**Comment by vikramtamboli** [comment]
Even for MQTT its not working.
Please find logs for MQTT
IotHubConnectionString object is created successfully for XXXXX, method name is <init> 
DeviceClientConfig object is created successfully with IotHubName=cnn-e1-iot-dev-01.azure-devices.net, deviceID=BlueLink-0000@1 , method name is <init> 
DeviceIO object is created successfully, method name is <init> 
DeviceClient object is created successfully, method name is commonConstructorSetup 
Device Object Created.
Connection opened with success, method name is open 
Connection Open.
Message with messageid a661117c-4eaa-4fae-ad6f-8908221794a2 along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
**Lost connection to the server. Reconnecting 0 time.**

**Comment by timtay-microsoft** [comment]
And are you getting the same "Lost connection to the server" consistently? Or only once in a while?

**Comment by vikramtamboli** [comment]
**With iot-device-client-1.11.2.jar below are log**
Connection opened with success, method name is open 
Message with messageid 2503c637-0ab0-43da-8924-8fd045cb4495 along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
Invoking the callback function for sent message, IoT Hub responded to message with status OK_EMPTY, method name is invokeCallbacks 
The messages in progress are buffered to be sent again due to a connection loss, method name is handleDisconnection 
Pending 1 responses from IotHub yet unsubscribed stop

**getting "Lost connection to the server" consistently**

**Comment by timtay-microsoft** [comment]
I'll need a bit more information from your logs to understand this problem. Can you add the following line of code before you open your device client instance?

```java
client.registerConnectionStatusChangeCallback(new IotHubConnectionStatusChangeCallback()
{
    @Override
    public void execute(IotHubConnectionStatus status, IotHubConnectionStatusChangeReason statusChangeReason, Throwable throwable, Object callbackContext) {
        System.out.println("Status: " + status != null ? status : "null");
        System.out.println("Reason: " + statusChangeReason != null ? statusChangeReason : "null");
        System.out.println("throwable: " + throwable != null ? throwable.getMessage() : "null");
        if (throwable != null)
        {
            throwable.printStackTrace();
        }
    }
},
new Object());
```

This will surface the exception that explains why you are losing connection.

**Comment by timtay-microsoft** [comment]
@vikramtamboli can you please add the above code to your sample and tell me what exception is being encountered during your connection losses?

**Comment by vikramtamboli** [comment]
Hi 

By adding above code exception details were shown in console logs.
I was using old version of apache.commons jar
now able to write to reported properties 

thanks for your help

**Comment by timtay-microsoft** [comment]
I'm glad to hear that your issue was resolved.

@vikramtamboli thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
