### ISSUE TITLE
Please support AMQPS multiplexing for X.509 authenticated Devices

### ISSUE THREAD

**Issue by iitsoftware** [Azure/azure-iot-sdk-java#270]
- **OS and version used:** <VERSION> 

MacOS 10.13.3

- **Java runtime used:** <VERSION> 

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

- **SDK version used:** <VERSION> 

1.11.1

# Description of the issue:

I have auto provisioned a bunch of IoT devices via Azure IoT DPS. The devices are registered at my IoT hub. All devices have an X.509 certificate authentication.

What I now want to do is to send messages to the devices. All certificates are available and I can connect with the DeviceClient to the device at the hub. This is the method of the Azure IoT Java SDK I am using:

`public static DeviceClient createFromSecurityProvider(String uri, String deviceId, SecurityProvider securityProvider, IotHubClientProtocol protocol) throws URISyntaxException, IOException
`

It takes SecurityProviderX509Cert as parameter.

However, each DeviceClient has its own physical connection. What I want is to use AMQP multiplexing by using this constructor:

`public DeviceClient(String connString, TransportClient transportClient) throws URISyntaxException
`

This doesn't work with X.509 devices. Please add a method to multiplex X.509 devices over AMQPS.

**Comment by timtay-microsoft** [comment]
We are interested in implementing this feature in the near future. I'll keep this thread posted with any updates. 

If you'd like to provide a PR for enabling this, I'd be happy to review it for you.

**Comment by iitsoftware** [comment]
I tried to change that but there are some design issues in the SDK that would require some major changes.

I seems that the SDK was initially designed in a way to have a 1:1 relation between device and connection; 1 device = 1 connection. That is, the connection authenticates through the device.

- Even when using multiplexing, each device needs to be registered with a connection string.
- The Transport uses the first registered device' connection string to establish the connection.
- The connection strings of the other devices are obsolet; they are  just riding on the first one.
- I was not able to figure out how the other devices authenticate.
- It is not possible to add/remove devices to/from an established connection.

I would suggest a design like this:

- A device independent Transport with its own credentials and a link to the $cbs node.
- A Device class that can be added/removed to/from the Transport no matter if it is connected or not.
- Device authentication (no matter which kind of) via a dedicated link over the Transport.

I would be glad to help here but I'm a bit lost figuring out how it works with authentication. To figure out how a device authenticates turned into a deep diving into the class hierarchy.

**Comment by timtay-microsoft** [comment]
Closing this feature due to lack of attention, and lack of hub support

**Comment by az-iot-builder-01** [comment]
@iitsoftware, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
