### ISSUE TITLE
X.509 cert authentication support for MQTT_WS 

### ISSUE THREAD

**Issue by JuliusNguyen** [Azure/azure-iot-sdk-java#278]
Is X.509 certificate authentication support for MQTT_WS going to be added anytime soon?

**Comment by timtay-microsoft** [comment]
There is an issue on the Iot Hub service side that is preventing us from implementing that. If you need this feature soon, I suggest filing a ticket against the IotHub service team to expidite the process. Currently, I don't have an ETA and I don't think anyone on the service team is currently working on it

**Comment by JuliusNguyen** [comment]
Thanks for your quick response. I submitted a question on MSDN Forums: 

https://social.msdn.microsoft.com/Forums/en-US/0d89aeaf-dfb1-41e6-aa6d-237483a4fe18/x509-certificate-authentication-support-for-mqtt-over-websocket?forum=azureiothub

I wonder where the problem lies. The feature is implemented in the C# SDK, so to me it seems that there must be some support on the service side already. If anyone knows more on this, I would greatly appreciate any additional information on this.

**Comment by timtay-microsoft** [comment]
The limitation is with the HTTP client that this SDK uses. C# doesn't share that limitation, so they have this feature. The IotHub service folks are aware of how to fix this issue, so don't worry about supplying them with all the details.

**Comment by JuliusNguyen** [comment]
Ah, got it! 

Sooo.. what to do now? On the side of the IoT Hub folks, is there anything I can do to increase the priority of this issue?

Alternatively, would it be possible for me to swap out the HTTP client to somehow solve this?

**Comment by timtay-microsoft** [comment]
I'm campaigning to get this issue fixed on the service side, but this could take a while. If you need a more immediate fix, I'd recommend using a different protocol. CA signed certs are supported over MQTT and AMQPS, or if you want to continue using MQTT_WS, you could switch to using sas tokens/shared access keys for authentication.

**Comment by MoiMoiDG** [comment]
I vote it up. Having full WS support is **crucial** for a lot of infrastructures (e.g. hospitals) where IoT devices are or will be in use. Thank you in advance!

**Comment by timtay-microsoft** [comment]
If you want a good way to have your voice heard on this issue, I recommend you post something to our [User Voice](https://feedback.azure.com/forums/321918-azure-iot) channel for IoT.

**Comment by timtay-microsoft** [comment]
It's been a while, but we did finally get the service side changes needed to light up this feature. The next release of the device client library will contain this feature

**Comment by timtay-microsoft** [comment]
Support for CA signed x509 certs has been added for MQTT_WS (and HTTPS) in the latest release of device client (1.20.3), so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@JuliusNguyen, @MoiMoiDG, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
