### ISSUE TITLE
Upload files to blob

### ISSUE THREAD

**Issue by PanzerHabba** [Azure/azure-iot-sdk-java#28]
Hi,

I wrote a device-client application in node.js, which among others uploaded files to blob-storage associated with iot-hub at given interval.

I now have to convert this application to java for another enviroment and I can`t find this functionality in java-sdk.

Why isn\`t this functionality yet implemented in java-sdk ?
When will you implement this ?
By browsing the different sdk`s in github I get a feeling that java is not prioritized. I hope my assumptions are not correct..

**Comment by tameraw** [comment]
@PanzerHabba - Thanks for your feedback.

Currently the file upload functionality is not available in the Java SDK. 
While Java SDK has lagged in features in the past, it has recently become a priority to bring all missing  features to the SDK.  FileUpload is one of them.

You can see the list of features that are currently on our priority list for java at the following project link:
https://github.com/Azure/azure-iot-sdk-java/projects/1

At present, we're working on adding the DeviceTwin and DeviceMethods to the SDK, and FileUpload is next on the list and you'll see it "In Progress" immediately after the release of those two features.

**Comment by gmousset** [comment]
Hi @tameraw
Does the "FileUpload" task include the implementation of the method "GetFileNotificationReceiver()" for serviceClient ?

**Comment by prmathur-microsoft** [comment]
Yes. This feature is work in progress for both device and service client and it shall be released soon.

**Comment by prmathur-microsoft** [comment]
This feature is now released. Fileupload from device client and receive notifications from service client are both on master and latest maven package. Feel free to reopen if you see further issues.
