### ISSUE TITLE
Azure IotHub- SAS token does not expire

### ISSUE THREAD

**Issue by PoonkuzhaliVasudevan** [Azure/azure-iot-sdk-java#282]
Package version: **Microsoft.Azure.Devices.Client 1.17.0**

I have created a device client in the following way

**_deviceClient = DeviceClient.Create(s_iotHubUri, new DeviceAuthenticationWithToken(deviceId, sasToken), Microsoft.Azure.Devices.Client.TransportType.Amqp);_**

I use the deviceClient to send messages using deviceClient.SendEventAsync(message). The SAS expiry is set to be 5 mins(for example) but the SAS is not expiring at all and the messages are being sent using the device client. I expect an exception like 'SAS has expired'. But messages are being sent normally. But if i stop the communication and try to create a client using the same SAS, i get SAS expired exception but why does this not happen while sending messages to device?

Please help with this issue.

**Comment by PoonkuzhaliVasudevan** [comment]
I tried this using Mqtt and Http also. But issue has not resolved

**Comment by timtay-microsoft** [comment]
Is it possible that you meant to post this issue to the [C# iot SDK](https://github.com/Azure/azure-iot-sdk-csharp)? The Java SDK does not have that API and has no Device Client package version 1.17.0

**Comment by PoonkuzhaliVasudevan** [comment]
Oh yes, by mistake i posted it here.. I will post this issue to the c# iot SDK.
