### ISSUE TITLE
[Android] Azure iot sdk, Can't run sample for android

### ISSUE THREAD

**Issue by alexeyosminin** [Azure/azure-iot-sdk-java#29]
Hi, I've tried to run sample https://github.com/Azure/azure-iot-sdk-java/tree/master/device/iot-device-samples/android-sample. Build completes successfully, but when I'm trying to run it, packaging always fails with the following error:
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK thirdpartynotice.txt
	File1: ...\Users\...\.gradle\caches\modules-2\files-2.1\com.microsoft.azure.sdk.iot\iot-device-client\1.0.17\5400e262163a15494376dcaeab7db18656768c95\iot-device-client-1.0.17.jar
	File2: ...\Users\...\.gradle\caches\modules-2\files-2.1\com.microsoft.azure.sdk.iot.deps\websocket-transport-layer\0.1.2\3f35a8f3a5786a2c22b99b3db29e2550d86f1c2c\websocket-transport-layer-0.1.2.jar 

 I'm using com.android.tools.build:gradle:2.3.0-beta3 gradle.

Only the way I was able to run sample is replacing "compile ('com.microsoft.azure.sdk.iot:iot-device-client:1.0.17')" line to "compile ('com.microsoft.azure.sdk.iot:iot-device-client:1.0.17') {
        exclude group: 'com.microsoft.azure.sdk.iot.deps', module: 'websocket-transport-layer'
    }"

P.S. original 1.0.16 version can't be resolved on my side and I had to replace it to 17

**Comment by anhashia** [comment]
Hi @alexeyosminin 
Please use the latest available version **1.0.17** for all available fixes and improvements. Android sample in Azure IoT SDK will also be updated to use that version.

As far was you build issue is concerned, looks like you are hitting a packaging error.  Based on the error it looks like **duplicate** copies of thirdpartynotice.txt is creating a package error.

You can try to exclude this file by adding this file in the exclusion list as shown below
https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/android-sample/app/build.gradle#L21

**Example** below

```
 packagingOptions {
        exclude "META-INF/MSFTSIG.SF"
        exclude "META-INF/MSFTSIG.RSA"
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'thirdpartynotice.txt'
        exclude 'META-INF/NOTICE.txt'
    }
```

**Comment by anhashia** [comment]
Updated build.grade in Android sample to use **1.0.17** https://github.com/Azure/azure-iot-sdk-java/commit/bdf20dd2e3210574e868362f40431f1f65df63c6

**Comment by alexeyosminin** [comment]
Thx, now it's fine! Let's close this issue?

**Comment by anhashia** [comment]
Closing this. Please re-activate if you have any further questions on this. Thanks !
