### ISSUE TITLE
Java SDK - SendAsync is not thread safe

### ISSUE THREAD

**Issue by varunpuranik** [Azure/azure-iot-sdk-java#30]
If I use ServiceClient.SendAsync to send multiple messages at one time and then wait for all of them to complete, I don't get the right set of messages on the device. Instead, I get one message sent multiple times. 
Here is what my code was doing - 

- Call serviceClient.sendAsync for a batch of messages (say 20). 
- Collect all the CompletableFutures returned in an array.
- Wait for all the futures to complete

Expected behavior - 
- I get all the messages (in any order) on the device

Actual behavior - 
- I get one message sent multiple times on the device (for. e.g., instead of "msg1, msg3, msg2, msg4...", I was getting "msg1, msg3, msg2, msg5, msg5, msg5, msg5...." on the device).

If I add a sleep between the sends, then I get the messages properly. So it seems to be because of some internal data structures being shared across threads.

**Comment by anhashia** [comment]
Hi @varunpuranik 
For local reproduction of the issue, can you please provide code snippet of how you are sending batch of 20 messages and waiting for all futures to complete. Thanks for your help!

**Comment by varunpuranik** [comment]
Here is the code I am using (note, it is scala code) - 
```scala
import java.util.concurrent.CompletableFuture
import com.microsoft.azure.sdk.iot.service.sdk.{DeliveryAcknowledgement, IotHubServiceClientProtocol, Message, ServiceClient}
import scala.collection.mutable.ArrayBuffer

object C2DMessageSender extends App {

  private val connectionString = ""
  private val deviceId = ""

  private val serviceClient = ServiceClient.createFromConnectionString(connectionString,
    IotHubServiceClientProtocol.AMQPS)
  this.serviceClient.open()

  def sendMessages(deviceId: String): ArrayBuffer[CompletableFuture[Void]] = {
    val futures = ArrayBuffer.empty[CompletableFuture[Void]]
    for(i ← 1 to 20) {
      futures += this.sendMessage(deviceId, i)
      // If you uncomment the line below, the issue doesn't repro anymore.
      // Thread.sleep(5000)
    }
    futures
  }

  def sendMessage(deviceId: String, i: Int): CompletableFuture[Void] = {
    val msgId = "msg" + i
    val msgText = "C2D Message " + i
    val message = new Message(msgText)
    message.setDeliveryAcknowledgement(DeliveryAcknowledgement.None)
    message.setMessageId(msgId)
    this.serviceClient.sendAsync(deviceId, message)
  }

  val sendMessageFutures = sendMessages(deviceId)
  CompletableFuture.allOf(sendMessageFutures:_*).join()
  println("Sent all messages")
}
```

**Comment by anhashia** [comment]
Fix checked in https://github.com/Azure/azure-iot-sdk-java/commit/a831c5ff094615ed43130b2e3c92a6ec33d8d872

**Comment by tameraw** [comment]
Closing as this has been released in the latest package.

**Comment by anhashia** [comment]
https://github.com/Azure/azure-iot-sdk-java/commit/ea197dd51be12c3f0e9d7cfd9b6037e44c4052d0 covers E2E test related to the change
