### ISSUE TITLE
[moduleClient] Cannot subscribe to input channel

### ISSUE THREAD

**Issue by adashen** [Azure/azure-iot-sdk-java#303]
- **OS and version used:**  Ubuntu 18.04

- **Java runtime used:** open-jdk 8

- **SDK version used:** 1.13.2

# Description of the issue:
Cannot subscribe to the input channel.

# Code sample exhibiting the issue:
        ModuleClient client = ModuleClient.createFromEnvironment(protocol);
        client.setMessageCallback("input1", msgCallback, client);

Found detail at: https://github.com/adashen/testjavasdk/blob/master/src/main/java/com/microsoft/App.java

# Console log of the issue:
From edgeHub log:
2018-08-13 08:00:22.722 +00:00 [WRN] - No subscription for receiving messages found for deviceId/moduleId

**Comment by timtay-microsoft** [comment]
This is a bug on our end, and we'll try to get the fix out soon. Thanks for filing the issue

**Comment by timtay-microsoft** [comment]
This issue has been released as of DeviceClient 1.13.3, so I'm closing this issue now. Feel free to re-open it if you still face this issue after upgrading.

**Comment by az-iot-builder-01** [comment]
@adashen, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
