### ISSUE TITLE
[Android] MQTT auto closed after a connection resets

### ISSUE THREAD

**Issue by kevin-ledinh** [Azure/azure-iot-sdk-java#31]
[201702010851_MQTT_Azure_SDK_1.0.16_no_stack.txt](https://github.com/Azure/azure-iot-sdk-java/files/745827/201702010851_MQTT_Azure_SDK_1.0.16_no_stack.txt)

Hi Azure team, 

I'm running  IoT Hub Device SDK 1.0.16 with MQTT protocol on an Android board to send sensors data to back end. The sensor data is collected every 30 seconds.

After running happily for 5 days without interruption, my Android board got a new IP address from the router and Android initiated a connection reset call

`D/ConnectivityService( 1976): resetConnections(wlan0, 1)`

Immediately after this, the Azure Device threw this exception and refused to work:

````
02-01 15:27:26.965 I/System.out(14971): java.lang.IllegalStateException: The MQTT connection is currently closed. Call open() before attempting to receive a message.: The MQTT connection is currently closed. Call open() before attempting to receive a message.

02-01 15:27:26.965 I/System.out(14971): com.microsoft.azure.iothub.transport.mqtt.MqttIotHubConnection.receiveMessage(MqttIotHubConnection.java:245)

02-01 15:27:26.965 I/System.out(14971): com.microsoft.azure.iothub.transport.mqtt.MqttTransport.handleMessage(MqttTransport.java:256)

02-01 15:27:26.965 I/System.out(14971): com.microsoft.azure.iothub.transport.IotHubReceiveTask.run(IotHubReceiveTask.java:25)

02-01 15:27:26.965 I/System.out(14971): java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)

02-01 15:27:26.965 I/System.out(14971): java.util.concurrent.FutureTask.runAndReset(FutureTask.java:279)

02-01 15:27:26.965 I/System.out(14971): java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:152)

02-01 15:27:26.975 I/System.out(14971): java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:266)

02-01 15:27:26.975 I/System.out(14971): java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)

02-01 15:27:26.975 I/System.out(14971): java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)

02-01 15:27:26.975 I/System.out(14971): java.lang.Thread.run(Thread.java:841)
````

This exception is caused when the receiveTask continue to run while the connection has closed.  Please see the attached log file for more debug traces.

Could you suggest a way to handle this case? 

Best wishes,

Kevin

**Comment by kevin-ledinh** [comment]
This issue is the same as #12 . The exception is printed every 100ms to stdout.

**Comment by anhashia** [comment]
Investigating !

**Comment by anhashia** [comment]
Hi @kevin-ledinh 

This issue is coming because of **synchronization** not happening properly. MQTT connection state is not fully closed at application level and receive thread is trying to poll for the packets resulting in an error that you are seeing.

I looked at the latest MQTT Java client SDK changes (in **1.0.19**) around this area and looks like those changes should address the issue you are seeing. Quick check would be for you to **re-test** with latest version of available client SDK.

Unfortunately,  there  is issue in Java client SDK version 1.0.19 that will prevent you from using it in Android. It uses Log4j for logging which doesn’t look like is Android compatible.

Work item has been created to address this so that you are able to use latest version of available client SDK to re-test the scenario on Android.

**Comment by anhashia** [comment]
Hi @kevin-ledinh 

Code change https://github.com/Azure/azure-iot-sdk-java/commit/87d77b20df3031c95268ec4e355eca5beaf40f1d has been submitted so that you can use newer version of available client SDK on Android.

Once it gets published in Maven, you can reference newer version in your application and **retest** the scenario.  Newer version would be **1.0.20**

You can also build the client SDK locally with the **latest** available master for testing purpose if you don't want to wait for **milestone** release.

**Comment by tameraw** [comment]
@kevin-ledinh - Please reopen if still seeing issue after testing against the latest SDK release per @anhashia 
Thanks.

**Comment by kevinledinh** [comment]
Hi @tameraw, 

Would you mind sharing your build.gradle file?

I have the following error while trying to build the APK file:

```
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.log4j.xml.DOMConfigurator$5) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
Error:...while parsing com/beust/jcommander/converters/BaseConverter.class
Error:1 error; aborting
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_11\bin\java.exe'' finished with non-zero exit value 1
```

I tried adding the following but still not work:
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    sourceCompatibility = 1.7
    targetCompatibility = 1.7
}
```

**Comment by anhashia** [comment]
Hi @kevin-ledinh 
Please use Android sample for **reference**  https://github.com/Azure/azure-iot-sdk-java/tree/master/device/iot-device-samples/android-sample
You should be able to build the sample with latest client SDK


https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/android-sample/app/build.gradle

Set dependency to latest available version **1.0.20**

`
dependencies {
    // Remote binary dependency
    compile 'com.microsoft.azure.sdk.iot:iot-device-client:1.0.20'
}
`

**Comment by anhashia** [comment]
Hi @kevin-ledinh 
Fix https://github.com/Azure/azure-iot-sdk-java/commit/5815d563952c4fe0d49cf4b3f0d59f4c3c2d1ead

Use **latest** available Android sample for reference
https://github.com/Azure/azure-iot-sdk-java/tree/master/device/iot-device-samples/android-sample

**Comment by kevinledinh** [comment]
Hi 

I still have problem with by gradle sync after mimicking what's in the example project. Here is my gradle file


```
apply plugin: 'com.android.application'
apply plugin: "com.google.protobuf"

android {
    compileSdkVersion 23
    buildToolsVersion '25.0.0'
    defaultConfig {
        applicationId 'com.myApp'
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"

//        jackOptions {
//            enabled true
//        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    productFlavors {
    }

    packagingOptions {
        exclude 'META-INF/BCKEY.SF'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/BCKEY.DSA'
        exclude 'META-INF/MSFTSIG.RSA'
        exclude 'META-INF/MSFTSIG.SF'
        exclude 'thirdpartynotice.txt'
        exclude 'AUTHORS'
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
//    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.google.protobuf:protobuf-java:2.6.1'
}
repositories {
    mavenCentral()
}

dependencies {
    compile 'com.microsoft.azure.sdk.iot:iot-device-client:1.0.20'
}
```

When I enabled 'jack option', gradle cannot sync. When I commented out jack option, the app does not build and returned this error:

```
Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.apache.log4j.xml.DOMConfigurator$5) that doesn't come with an
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
Error:indicate that it is *not* an inner class.
Error:PARSE ERROR:
Error:unsupported class file version 52.0
Error:...while parsing com/beust/jcommander/DynamicParameter.class
Error:1 error; aborting
:app:transformClassesWithDexForDebug FAILED
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe'' finished with non-zero exit value 1
```

Could it be that some plug-ins is not compatible with jack?

Many thanks,

**Comment by anhashia** [comment]
Hi @kevin-ledinh 
One of the **dependent** libraries from IoT SDK has Java 8 language features. So that is why you were seeing error previously. So Jack option was added to fix that. You will need Jack option. See below link for reference
https://developer.android.com/guide/platform/j8-jack.html

Android sample is tested with build tools **25.0** and gradle **3.3**
What error are you getting when you try to build Android sample that is IoT SDK ?
https://github.com/Azure/azure-iot-sdk-java/tree/master/device/iot-device-samples/android-sample

**Comment by kevinledinh** [comment]
Hi @anhashia ,

The sample is built ok with no errors. So I guess it must be a project config difference. 

My project uses gradle 2.10 though. I'll try upgrading gradle and give it a try. 

Thanks for the suggestion. Best wishes.
