### ISSUE TITLE
Use logging facade

### ISSUE THREAD

**Issue by jemackayoe** [Azure/azure-iot-sdk-java#310]
I am having issues with logging using this SDK in a security restricted environment, specifically Log4J2. This SDK should make things simpler and consistent with Azure Storage and switch to using a logging facade such as SLF4J. Please. Thanks.

**Comment by JMayrbaeurl** [comment]
+1

I've asked for this already one year ago. See #50 . But it was closed due to low priority!

**Comment by timtay-microsoft** [comment]
If you would like to provide a PR for this feature, I would be happy to review, and merge it in for you.

**Comment by JMayrbaeurl** [comment]
@timtay-microsoft Do you know why the unit tests for CustomLogger (class CustomLoggerTest) are turned off with the Ignore attribute at class level?

**Comment by timtay-microsoft** [comment]
Those tests are disabled due to being unstable. We were seeing random failures throughout that test suite once every 10 runs or so.

**Comment by JMayrbaeurl** [comment]
PR is available. Unit tests are still disabled

**Comment by timtay-microsoft** [comment]
The addition of this feature has been merged into master thanks to @JMayrbaeurl's PR. When we do our next release, I'll go ahead and close this issue. Feel free to try building from source and letting us know if this fix was satisfactory for you  @jemackayoe

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released as of Device Client 1.14.0, so I'm closing this issue now.

**Comment by az-iot-builder-01** [comment]
@jemackayoe, @JMayrbaeurl, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
