### ISSUE TITLE
AMQP connections with Basic SKU

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#314]
Basic SKUs do not support twin or methods operations, but the amqp connections in this SDK will attempt to open twin and method links even when you don't send anything over them. As a result, users cannot use an amqp connection to a Basic SKU iot hub. This either needs proper documentation, or the amqp connection should not establish links that aren't needed.

**Comment by timtay-microsoft** [comment]
Thanks for filing this issue. We'll look into it soon.

**Comment by timtay-microsoft** [comment]
The fix for this issue has now been checked in, sorry for the delay. Now the SDK only opens telemetry links by default, so the next release will work with basic tier iot hubs.

**Comment by jasmineymlo** [comment]
fixed in https://github.com/Azure/azure-iot-sdk-java/releases/tag/2019-4-19

**Comment by az-iot-builder-01** [comment]
@chaosmail, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
