### ISSUE TITLE
DeviceTwin lastUpdatedVersion on Property object

### ISSUE THREAD

**Issue by FranAlterados** [Azure/azure-iot-sdk-java#315]
Property object doesn't have lastUpdatedVersion and I need it to know if an isolated property has changed.

I found the trouble in this piece of code. Variables lastUpdate and lastUpdatedVersion are setted but never used.

https://github.com/Azure/azure-iot-sdk-java/blob/bab29cedfaad0cfd923d6ad81624ce6060584997/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/DeviceTwin/DeviceTwin.java#L196-L212

**Comment by timtay-microsoft** [comment]
Thanks for filing this issue. This looks like a bug on our side, so we'll look into getting a fix out for this soon.

**Comment by timtay-microsoft** [comment]
I have published a [working branch](https://github.com/Azure/azure-iot-sdk-java/tree/deviceTwinFix) for this issue. This is what you are looking for, right? For those two fields to be exposed via the Property class?

**Comment by timtay-microsoft** [comment]
The fix for this issue has been checked into master now, and is slated to be released on 8/30.

**Comment by FranAlterados** [comment]
Thanks for the quick response 😄

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released as of Device Client 1.14.0, so I'm closing this issue now.

**Comment by az-iot-builder-01** [comment]
@FranAlterados, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by FranAlterados** [comment]
I tried to get lastUpdated and lastUpdatedVersion fields after new release and I always get null. Is there anything missing?

Thanks :)

**Comment by timtay-microsoft** [comment]
After digging into these two pieces of metadata a bit, it seems like they are only sent to the service, never received from the service. That means there is no way this SDK could expose these values for you. This may change in the future, but it would require a change on the service side to have them sent to the device. For now, they will always be null. 

Feel free to leave the suggestion in the [user voice](https://feedback.azure.com/forums/321918-azure-iot) for Iot Hub, and we might get it enable for you.

**Comment by timtay-microsoft** [comment]
The lastUpdated and lastUpdatedVersion metadata are only used to track the last time a device sent or received an update, so those values alone wouldn't tell you when a single property has changed anyways. You may need to implement that feature in your code manually.

**Comment by FranAlterados** [comment]
I have an internal control versioning of these properties, but I still need lastUpdatedVersion to get my expected behaviour

Thank you very much for the response, I posted a suggestion in the platform as you recommend me.

https://feedback.azure.com/forums/321918-azure-iot/suggestions/35395108-add-lastupdatedversion-on-property-object-in-devic

**Comment by yzhong94** [comment]
cc @simonporter @rezasherafat for service feature request

**Comment by rezasherafat** [comment]
@fduranortega can you share more details what your "control versioning" use case entails (perhaps via private messages to me directly if you prefer)?
