### ISSUE TITLE
Twin support

### ISSUE THREAD

**Issue by DavidFBakker** [Azure/azure-iot-sdk-java#32]
Most of the other language SDKs have twin support. Is this coming soon to the java base?

**Comment by tameraw** [comment]
@DavidFBakker - Yes. We're actively working on this and should be released fairly soon.
Please see the link to the project for the latest status:
https://github.com/Azure/azure-iot-sdk-java/projects/1

**Comment by Draczech** [comment]
Is the twin support going to be complete as:
- Twin properties accessible from device client? (R desired + W reported)
- Twin properties accessible from service client? (R reported + W desired, read + update Twin from RegistryManager)
- Twin used in bulk import/export scripts?

It is kind of problematic to develop complex solution on platform providing only partial support for Twins. Currently I'm able to read and update twins from my implementation of HttpRegistryManager, but the rest of listed functions is a bit harder to handle on my own...

**Comment by DavidFBakker** [comment]
Great TY!

**Comment by tameraw** [comment]
@DavidFBakker - FYI as of today we have DeviceTwin support on the Device SDK. For the service SDK we are currently missing the UpdateTwin which is a work in progress.

**Comment by DavidFBakker** [comment]
TY do you know when the service SDK is going to be updated?

David F. Bakker | Arraya Solutions<http://www.ArrayaSolutions.com/>
CTO
523 Plymouth Road, Suite 212, Plymouth Meeting, PA 19462
Phone: +1-610-684-8604 | Fax: +1-484-362-6240 | Mobile: +1 6107649580

[cid:arraya_eec0dceb-1149-40e9-b907-a68f6afbc293.png]<http://www.arrayasolutions.com/>    [cid:fb_a3f92e51-0aa0-48f4-a1e2-7043023633ea.jpg] <https://www.facebook.com/ArrayaSolutions>     [cid:ln_cd9d2a21-548a-460e-84cc-e3fe6130d02c.png] <http://www.linkedin.com/company/Arraya-Solutions>     [cid:tw_eda55cf1-5d71-412c-bedb-9b8a74f62895.jpg] <http://twitter.com/arrayasolutions>     [cid:yt_2ade93aa-237e-4bb0-aa30-539b50db3104.jpg] <http://www.youtube.com/arrayasolutions>

 [cid:CompanySignature_ManagedServices_v3_0c4eabf8-7a5d-4b68-8241-f8b55fca19d1.jpg] <http://www.arrayasolutions.com/service/managed-services/>

________________________________

This email and any files transmitted with it are confidential and is intended only for the individual named. If you are not the named addressee or if this email is to a user no longer associated with the named address you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version. Please note that any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company. Finally, the recipient should check this email and any attachments for the presence of viruses. The company accepts no liability for any damage caused by any virus transmitted by this email. Arraya Solutions Inc, 523 Plymouth Rd, Suite 212, Plymouth Meeting PA 19462 .

**Comment by prmathur-microsoft** [comment]
We are targeting it by either end of this month or early next month.  We will update you soon.

**Comment by Draczech** [comment]
I haven't had enough time for testing the latest version of libraries. So I've only checked the sources and the import/export [How to article](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-bulk-identity-mgmt).  It is not clear to me if bulk operations support Device Twins at the moment. (The how to article doesn't mention that at all).

Is such feature supported or at least planned?

**Comment by prmathur-microsoft** [comment]
Bulk management is not yet supported for Device twin on java SDK.

**Comment by Draczech** [comment]
Do you have at least some preliminary plan for migrating this feature to Java? As there is **UpdateTwins2Async** method available in the [C# SDK](https://github.com/Azure/azure-iot-sdk-csharp/blob/master/service/Microsoft.Azure.Devices/HttpRegistryManager.cs) (which I presume provides the desired feature).

**Comment by prmathur-microsoft** [comment]
Yes we have it in our backlog to implement this. We will most likely address this in 2 months.

**Comment by prmathur-microsoft** [comment]
Job client is now available for java SDK. It is checked in master. Maven package for the same shall be released soon as well.

**Comment by prmathur-microsoft** [comment]
Maven package for the same is also released. Follow our release from https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-7-14
