### ISSUE TITLE
After a direct method invocation I get sometimes IoTHubNotFoundException (with error codes 404001, 404103)

### ISSUE THREAD

**Issue by datoga** [Azure/azure-iot-sdk-java#329]
- **OS and version used:** Alpine 3.8 (via Docker): openjdk:8-jre-alpine

- **Java runtime used:** JDK 8 (8u171).

- **SDK version used:** Azure IoT Service Client: 1.14

# Description of the issue:
We have a connected device, ready to listen some commands.

Sometimes (that's important, we cannot found any pattern to make it fail, sorry!), a direct method invocation to the IoT Hub API returns IoT Hub not found (IotHubNotFoundException) with error codes 404001 or 404003 (the error code depends but the error is the same). The rest of requests work properly.

Looking for the error code I haven't found any reference to IoT Hub not found with that error code, only 
https://github.com/Azure/azure-iot-sdk-csharp/issues/431, but it refers to a not registered device, it seems not related to our error.

Some clues:
- It seems that, after failing one time, the probability to fail raises (burst errors?).
- If the invocation fails, after retrying the next invocation may be ok (or not!).

# Code sample exhibiting the issue:

```
Map<String, Object> payload = new HashMap<>();
payload.put("method", "pairingcode");
payload.put("code", "CODE");

DeviceMethod methodClient = DeviceMethod.
    createFromConnectionString(iotHubConnectionString); // X.509 connection
MethodResult result = methodClient.
    invoke("qacarlos32dev", "runcommand", responseTimeout, connectTimeout, payload);

//connectTimeout = 5 responseTimeout = 200
```

# Console log of the issue:
```
IoT Hub not found! {"errorCode":404001,"trackingId":"a9ded5c59eda49e1adbe8e1eacc78c9a-G:1-TimeStamp:09/03/2018 10:45:52","message":"qacarlos32dev","timestampUtc":"2018-09-03T10:45:52.88087Z"} 
com.microsoft.azure.sdk.iot.service.exceptions.IotHubNotFoundException: IoT Hub not found! {"errorCode":404001,"trackingId":"a9ded5c59eda49e1adbe8e1eacc78c9a-G:1-TimeStamp:09/03/2018 10:45:52","message":"qacarlos32dev","timestampUtc":"2018-09-03T10:45:52.88087Z"} 
	at com.microsoft.azure.sdk.iot.service.exceptions.IotHubExceptionManager.httpResponseVerification(IotHubExceptionManager.java:71) ~[iot-service-client-1.14.0.jar!/:na]
	at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceOperations.request(DeviceOperations.java:137) ~[iot-service-client-1.14.0.jar!/:na]
	at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceMethod.invokeMethod(DeviceMethod.java:175) ~[iot-service-client-1.14.0.jar!/:na]
	at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceMethod.invoke(DeviceMethod.java:81) ~[iot-service-client-1.14.0.jar!/:na]

IoT Hub not found! {"errorCode":404103,"trackingId":"871115953cfb48dea4d28a980c170be7-G:19-TimeStamp:09/03/2018 12:08:48","message":"NotFound","timestampUtc":"2018-09-03T12:08:48.382931Z"} 
com.microsoft.azure.sdk.iot.service.exceptions.IotHubNotFoundException: IoT Hub not found! {"errorCode":404103,"trackingId":"871115953cfb48dea4d28a980c170be7-G:19-TimeStamp:09/03/2018 12:08:48","message":"NotFound","timestampUtc":"2018-09-03T12:08:48.382931Z"} 
	at com.microsoft.azure.sdk.iot.service.exceptions.IotHubExceptionManager.httpResponseVerification(IotHubExceptionManager.java:71) ~[iot-service-client-1.14.0.jar!/:na]
	at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceOperations.request(DeviceOperations.java:137) ~[iot-service-client-1.14.0.jar!/:na]
	at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceMethod.invokeMethod(DeviceMethod.java:175) ~[iot-service-client-1.14.0.jar!/:na]
	at com.microsoft.azure.sdk.iot.service.devicetwin.DeviceMethod.invoke(DeviceMethod.java:81) ~[iot-service-client-1.14.0.jar!/:na]
```

**Comment by timtay-microsoft** [comment]
Are you invoking a lot of methods on a single device at once? Or even invoking a lot of methods on any device at once? This error suggests that the service may have trouble finishing your request in time

**Comment by timtay-microsoft** [comment]
Have you tried increasing the connectTimeout? If you are making a lot of requests at a time, and only have a 5 second timeout, the service is likely to give up on some of those requests and return with the error codes that you are seeing.

**Comment by datoga** [comment]
After some investigation we realized the problem. First, this problem occurs in a specific situation: after an unexpected disconnection of a device, the twin state for the device is still connected (due to the delay to update that field) and I'm able to send commands to it. Nevertheless, this command never arrives, all reports an error, ok then.

Maybe I was been puzzled because of the message. "IoT Hub not found!" seems to say that Azure IoT Hub is gone, not the device! So, the error is expected but the message seems confusing.

**Comment by timtay-microsoft** [comment]
Ah okay, that makes sense. If the device is disconnected, then yes, this is the expected behavior.

As for the error message, I'll look into fixing that up a bit. The 404's aren't all supposed to mean IotHub not found. There is some granularity between 404001 and 404103 that we could do a better job of bubbling up.

**Comment by az-iot-builder-01** [comment]
@datoga, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
