### ISSUE TITLE
get device twin object in java

### ISSUE THREAD

**Issue by vikramtamboli** [Azure/azure-iot-sdk-java#330]
In c# we can get devicetwin object using below code 
Twin twin = await deviceClient.GetTwinAsync();

but in java deviceClient.getDeviceTwin() have return type as void

can some one please let us know which how can we get deviceTwin from deviceClient object in java?

**Comment by jasmineymlo** [comment]
@vikramtamboli, take a look at the [sample](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java).  Unlike the C# sdk returning the Twin object, the Java SDK will call the appropriate callback with the value and version for each desired property in the Service.  Hopes this help.

**Comment by timtay-microsoft** [comment]
@vikramtamboli Are you satisfied with the sample that @jasmineymlo provided? Or do you need extra help?

**Comment by timtay-microsoft** [comment]
I'm going to close this issue now due to inactivity. Feel free to re-open if you have any other questions on how twin works in this SDK.

**Comment by az-iot-builder-01** [comment]
@vikramtamboli, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by williamwilliamwilliam** [comment]
@jasmineymlo what is the appropriate callback? DeviceClient.getDeviceTwin() ultimately uses 

`private final class deviceTwinRequestMessageCallback`

which is a IotHubEventCallback that only carries the response code. I see status "OK" when I call getDeviceTwin, but that's it.

I'm registering a message callback and subscribing to desired properties using the following before calling getDeviceTwin: 
`DeviceClient.setMessageCallback()`
`DeviceClient.subscribeToTwinDesiredProperties()`

I receive any desired property change I make on the device from the Azure portal, but I'm unable to get the current desired properties when I first connect the device or call DeviceClient.getDeviceTwin().

**Comment by williamwilliamwilliam** [comment]
I hadn't properly implemented the callback that handles this. You should expect all device twin properties to be listed when you connect through the first callback parameter in DeviceClient.startDeviceTwin

> public void startDeviceTwin(**IotHubEventCallback deviceTwinStatusCallback**,  Object deviceTwinStatusCallbackContext, TwinPropertyCallBack genericPropertyCallBack, Object genericPropertyCallBackContext)
