### ISSUE TITLE
The method uploadToBlobAsync() doesn't work when used in Android

### ISSUE THREAD

**Issue by taroyutao** [Azure/azure-iot-sdk-java#331]
When I use the method uploadToBlobAsync() in java, it works fine. but when i use it in Android, it doesn't work.

something wrong in the following code:
`
    public CloudBlockBlob(final StorageUri blobAbsoluteUri) throws StorageException {
        super(BlobType.BLOCK_BLOB);

        **Utility.assertNotNull("blobAbsoluteUri", blobAbsoluteUri);**
        this.setStorageUri(blobAbsoluteUri);
        this.parseURIQueryStringAndVerify(blobAbsoluteUri, null,
                Utility.determinePathStyleFromUri(blobAbsoluteUri.getPrimaryUri()));
    }
`

how can we use the method in Android?

Thanks in anvance.

**Comment by timtay-microsoft** [comment]
What exception are you getting when this code executes?

**Comment by taroyutao** [comment]
can not find tostring() method

**Comment by chenrui1988** [comment]
Hi @timtay-microsoft , I met this issue too ,  file upload not work in andriod, There's no exception throw out, just return when uploadToBlobAsync   and didn't upload successful.  it looks like  the storage sdk used in Iothub SDK is not support andriod , please help us to confirm that.

**Comment by timtay-microsoft** [comment]
You are correct, @chenrui1988 It looks like the storage SDK we use does not support Android, but they have a version that does, so we will investigate using it instead.

**Comment by taroyutao** [comment]
@timtay-microsoft , Thank you for your confirmation. I want to know when this problem will be repaired.

**Comment by jasmineymlo** [comment]
@taroyutao, Adding the following addition in the build.gradle to replace the azure-storage dependency with the Android version.

dependencies {
    implementation ('com.microsoft.azure.android:azure-storage-android:2.0.0@aar')
    implementation ('com.microsoft.azure.sdk.iot:iot-device-client:1.12.0') {exclude module: 'azure-storage'}
}

**Comment by YMZ1994420** [comment]
@jasmineymlo  I add this to  build.gradle。But after connect success,throw this exception
```
 java.lang.NoClassDefFoundError: org.apache.commons.lang3.tuple.MutablePair
at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.messageArrived(Mqtt.java:361)
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.deliverMessage(CommsCallback.java:499)
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:402)
at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:206)
... 7 more
```

**Comment by jasmineymlo** [comment]
@taroyutao does replacing azure-storage works for you?  Please confirm.   Thanks.

**Comment by jasmineymlo** [comment]
Please let us know if the above doesn't fix your issue.  Feel free to reopen this issue if needed.  Thanks

**Comment by az-iot-builder-01** [comment]
@taroyutao, @chenrui1988, @YMZ1994420, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by orcame** [comment]
Met the same issue and the bellow change works for me.

`    implementation ('com.microsoft.azure.sdk.iot:iot-device-client:1.14.1'){exclude module:'azure-storage'}
    implementation 'com.microsoft.azure.android:azure-storage-android:2.0.0'
    implementation 'org.apache.commons:commons-lang3:3.6'`

**Comment by awadeyar** [comment]
@timtay-microsoft   
I am getting the x509 authentication error for file upload:
Caused by: java.lang.UnsupportedOperationException: File Upload does not support x509 authentication
        at com.microsoft.azure.sdk.iot.device.DeviceClient.uploadToBlobAsync(DeviceClient.java:429)
