### ISSUE TITLE
Cannot change device status using import in update mode via API

### ISSUE THREAD

**Issue by MCinv92** [Azure/azure-iot-sdk-java#35]
We are accessing the IoT messagehub via API using simple scrips in java. 

It is not possible to change the state of device(s) to "disabled" using import in update mode. The other parameters are changed properly.
Plus, if I disable a device manually at the portal and then run an update import for this device having the state set to "disabled", the device gets enabled anyway. 
So in fact, the device gets into enabled state always after running the update-import for it. 

Is this an intention, or a bug? 
It might be a problem if one wants to disable more devices in a bulk - in fact, there is no way how to do that.

Thanks for investigation.

**Comment by anhashia** [comment]
Investigating !

**Comment by anhashia** [comment]
Hi @MCinv92 
I used following sample for local reproduction
https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/service/sdk/DeviceManagerImportSample.java

In this sample  I set device status to disabled
https://github.com/Azure/azure-iot-sdk-java/blob/master/service/iot-service-samples/device-manager-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/service/sdk/DeviceManagerImportSample.java#L48

The device successfully got created in Hub with status as disabled.

**Comment by MCinv92** [comment]
Hi @anhashia and thanks a lot for your investigation. 
You are right, we have finally found out that there is everything going well on your site. The error was in our code. 
Sorry for a false issue report. :-)
