### ISSUE TITLE
MQTT Best practice

### ISSUE THREAD

**Issue by generosocarbone** [Azure/azure-iot-sdk-java#357]
What should be the best practice to follow in the case of disconnection?
I mean, if the client disconnects for some reason it's better to 
1. close the old client, set a new one and open the new one 
2. try to re-open the old client
3. other?

I'm asking it because apparently at a certain point (not better identified) I've got thousand copy of the same massage originated from a single incoming message. It's like that the MessageCallback it's called one time for each 'client'

**Comment by timtay-microsoft** [comment]
In general, we recommend you recycle the same client object. You should be able to re-open a client that has been disconnected/closed for any reason. 

Weird behavior will happen if you leave a DeviceClient connection open (or partially open) to your IotHub and then you try to open another connection with the same device credentials.

**Comment by generosocarbone** [comment]
ok, now, one can register a IotHubConnectionStatusChangeCallback to handle the three possible states
CONNECTED, DISCONNECTED_RETRYING and DISCONNECTED. 
Now, I'm managing my android app in this way:
 - when In DISCONNECTED_RETRYING, the app shows a message
 - when in DISCONNECTED, the app tries to re-open the client after closing the old connection 

Is this process 'right'? plus, I don't know if it's a bug or not (I'm investigating it), it may happens that after getting in a DISCONNECTED_RETRYING state, as soon the app receives a message it could be replicated thousands of times, as I wrote at the beginning

**Comment by timtay-microsoft** [comment]
Yes, that is good practice for managing the connection state. The only caveat I will point out is that your client may disconnect for non-retryable reasons, such as when your provided sas token expired. I would make sure to pay attention to the reason just as much as the connection status.

If you are seeing duplicate messages, that might be a bug. If you can provide the code you are using when you see this, I can look into it as well.

**Comment by generosocarbone** [comment]
Where I can find something to read about non-retryable situations?

**Comment by timtay-microsoft** [comment]
I recommend reading up on [this class](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/mqtt/exceptions/PahoExceptionTranslator.java) where we interpret all the different exceptions our MQTT library propagates up to us and determine whether they are retryable or not. By default, we treat exceptions as non retryable, but for most IOExceptions, timeouts, and connection loss exceptions, we make them retryable.

**Comment by timtay-microsoft** [comment]
@generosocarbone did you have any other questions about MQTT best practices? Otherwise I will go ahead and close this issue.

**Comment by generosocarbone** [comment]
the last one: 
which one, between MQTT and MQTT_WS, is more reactive on connection state changes?

**Comment by timtay-microsoft** [comment]
More reactive, as in which one would notice a connection state change the fastest? There isn't any significant difference between the two. MQTT_WS has an extra layer of logic to propagate up through, but the difference in time would be negligible.

**Comment by timtay-microsoft** [comment]
I'm going to close this thread due to inactivity, but feel free to file another issue if you have any further questions about the SDK.

**Comment by az-iot-builder-01** [comment]
@generosocarbone, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
