### ISSUE TITLE
Problem sending commands using direct method

### ISSUE THREAD

**Issue by samisarfraz** [Azure/azure-iot-sdk-java#359]
This is a bit weird and confusing issue but i'll try to explain it.I am facing a problem in sending commands using direct method (invoke method). We developed our code with azure c sdk (Arduino) and was able to send commands with Direct method (Method name + payload) when using Portal.Azure.com or windows 7 machine using device explorer. Initially we were using this feature from cloud (Direct method) then we shifted to device explorer as its easy to use. Device explorer was working fine on windows 7. We can send commands with method name and payload. But when we installed device explorer on windows 10 things got very peculiar as we only invoke a command with only method name (no payload). When we send the command with method name and payload (json string) it cause our device to restart and shows an error but these very same commands { method name and payload (json string)} execute fully when we send them from windows 7 device explorer or portal.azure.com – direct method / invoke method (no restart or errors) . We are facing the same problem when we use the sdks (java , node , C#) for sending commands.

**Comment by timtay-microsoft** [comment]
Sounds like this is an issue with the Device Explorer. I suggest you file an issue with the [C# repo](https://github.com/Azure/azure-iot-sdk-csharp/issues) that maintains that tool. Since this issue is unrelated to the Java SDK, I'm going to close this issue.

**Comment by az-iot-builder-01** [comment]
@samisarfraz, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by samisarfraz** [comment]
It is related to Java SDK as we tried to invoke method using Java SDK the error was same as iot-hub explorer showed. as i mentioned above this issue is very weird and we have done full development on hardware side cause direct method was working from  Portal.Azure.com. As we're developing a product and the latency is also a very major flaw of azure in this case we've no other choice than move to other Iot platforms.

**Comment by timtay-microsoft** [comment]
What version of the Java SDK service client are you using to invoke methods?

**Comment by timtay-microsoft** [comment]
And what do the logs look like for the Java client failures?

**Comment by samisarfraz** [comment]
Q1 - What version of the Java SDK service client are you using to invoke methods?  
A - 1.8
Q2 - And what do the logs look like for the Java client failures?
A - Malformed gson errors.
Q3 - Also could you add what timeout you are using ?
A - We are using default time-out given in java sdk given by azure

**Comment by timtay-microsoft** [comment]
> Q1 - What version of the Java SDK service client are you using to invoke methods?
> A - 1.8 
<i>This seems like the Java SDK version, not the service sdk version. Check your pom file for the dependency you declare, and tell me what version it is</i>

> Q2 - And what do the logs look like for the Java client failures?
> A - Malformed gson errors.
<i>Can you please provide the full stacktraces? It will be much easier to resolve this issue with more details</i>

**Comment by prmathur-microsoft** [comment]
Could you detail what is your callback code on device side as you mentioned device restarts. In particular - 
1. What callbacks have you registerted on device side ?
2. Sample code on both device and service(if possible) side
3. Detail java SDK version on device side
4. Protocol you are using on device side

**Comment by timtay-microsoft** [comment]
I'm going to close this issue due to inactivity. If you still see this issue, feel free to re-open this issue.
