### ISSUE TITLE
[Device Client] Devices stopped receiving method invocations using AMQP

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdk-java#367]
- **OS and version used:** Windows 10 / Raspbian

- **Java runtime used:** 1.8

- **SDK version used:** 1.14.1

# Description of the issue:
Using AMQP (WS)

We've experienced that some of our devices stop being able to receive method invocations after some time, no network drops during that time, they're able to send messages and to receive regular C2D messages, but they stop receiving C2D method invocations. The only exceptions that we can see are BAD_CREDENTIALS like the ones reported in #365 and the device seems to reconnect successfully in a very short time.

**Comment by timtay-microsoft** [comment]
What is the rough timespan that a device is waiting before you start seeing this behaviour? 1 hour? 1 day?

**Comment by Sensing-Control-DevTeam** [comment]
It usually happens between 1 to 3 days

**Comment by timtay-microsoft** [comment]
Are you seeing the same issue when using any other protocol?

**Comment by pizerg** [comment]
For several reasons we are restricted to AMQP_WS but I'll try to deploy a version using MQTT_WS to one of our affected machines only for the test and let you know the results in a couple of days

**Comment by timtay-microsoft** [comment]
While you are testing that, can you also check if you see a similar loss in the ability to receive twin updates and telemetry?

**Comment by pizerg** [comment]
Finally found the issue, one of our callback invocations was getting randomly stuck and the iothub receiver thread executes method invocations on the same thread so if a callback gets stuck the system stops receiving new method invocations

**Comment by Sensing-Control-DevTeam** [comment]
Yes and no, I do not remember reading that method invocation is performed in serie (or maybe I missed it in the docs), maybe adding a configurable timeout or an option to execute method invocations async should be considered. 
Adding a timeout could help fixing this kind of issues in the future or at least not causing the functionality (method invocations) to fully stop working (although I agree that method invocations should never get stuck).

**Comment by timtay-microsoft** [comment]
Since there doesn't appear to be an issue with the SDK here, and your suggestion to add async/timeout options to the callbacks has been noted, I'm going to close this issue. Feel free to re-open if you still see any issues around this scenario.

**Comment by az-iot-builder-01** [comment]
@Sensing-Control-DevTeam, @pizerg, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
