### ISSUE TITLE
Device provisioning goes into an infinite state waiting

### ISSUE THREAD

**Issue by RudyEvers** [Azure/azure-iot-sdk-java#368]
- **OS and version used:** 
Android 8+, CompileSDKVersion 28

- **Java runtime used:** 
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

- **SDK version used:**
api 'com.microsoft.azure.sdk.iot:iot-device-client:1.14.1'
implementation 'com.microsoft.azure.sdk.iot.provisioning:provisioning-service-client:1.3.3'
implementation 'com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.3.3'
api group: 'com.microsoft.azure.sdk.iot.provisioning.security', name: 'x509-provider', version: '1.1.1'
api group: 'com.microsoft.azure.sdk.iot.provisioning.security', name: 'security-provider', version: '1.1.1'
api group: 'com.microsoft.msr', name: 'DiceRIoTEmulator', version: '1.0'

# Description of the issue:
After implementing the sample found in the microsoft documentation

 for registering an enrolled device to the IOT Hub, the code goes into an infinite state where the "Waiting for Provisioning Service to register" keeps repeating without any progress. Please note we had to change the cryptography type from "BC" to "SC" due to a deprecation issue in the SDK caused by changes in the Android OS, for more information please see the following: https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html

# Code sample exhibiting the issue:
 
Please see the attached files, I have also added the changes to the cryptography type just in case

# Console log of the issue:
Please see the attached files

[OurRIoT.txt](https://github.com/Azure/azure-iot-sdk-java/files/2556899/OurRIoT.txt)
[OurSecurityProviderX509Cert.txt](https://github.com/Azure/azure-iot-sdk-java/files/2556900/OurSecurityProviderX509Cert.txt)
[ProvisioningX509.txt](https://github.com/Azure/azure-iot-sdk-java/files/2556901/ProvisioningX509.txt)
[Enrollment.txt](https://github.com/Azure/azure-iot-sdk-java/files/2556902/Enrollment.txt)

**Comment by prmathur-microsoft** [comment]
Thanks for logging this issue. As the blog suggest what be the result of using default provider and not using"BC" or "SC" in your setup ? Do you still see the issue?

**Comment by RudyEvers** [comment]
@prmathur-microsoft, I will discuss it with the developer. I will let you know about the outcome.
If you have any comments about the shared files please let me know. It's a blocking issue not getting a device provisioned.

**Comment by prmathur-microsoft** [comment]
thanks @RudyEvers . We will look into it on our side to give you a better solution then.

**Comment by RudyEvers** [comment]
@prmathur-microsoft Within microsoft the issue is also discussed. One of the support engineers (André Nascimento) will create internal incident tracking tickets to both Java SDK team and DPS service, in order to get some feedback in case this situation as occurred before. It's a blocking issue so urgency is needed.

**Comment by jasmineymlo** [comment]
@RudyEvers, would you try removing explicit setProvider() calls like below.  Thanks.

    private static Key getPrivateKey(Object possiblePrivateKey) throws IOException {
        if (possiblePrivateKey instanceof PEMKeyPair)
        {
            return new JcaPEMKeyConverter().getKeyPair((PEMKeyPair) possiblePrivateKey)
                    .getPrivate();
        }
        else if (possiblePrivateKey instanceof PrivateKeyInfo)
        {
            return new JcaPEMKeyConverter().getPrivateKey((PrivateKeyInfo) possiblePrivateKey);
        }
        else
        {
            throw new IOException("Unable to parse private key, type unknown");
        }
    }

**Comment by jasmineymlo** [comment]
6f3c68a4ffbf9ed7bf156bc232f653a56238c686 should fix this issue

**Comment by jasmineymlo** [comment]
Fixed in https://github.com/Azure/azure-iot-sdk-java/releases/tag/2018-12-3

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, @RudyEvers, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
