### ISSUE TITLE
[Java] Memory leak in AmqpsIotHubConnection

### ISSUE THREAD

**Issue by hiro4kuribaya4** [Azure/azure-iot-sdk-java#4]
The Delivery object created by sendMessage () is not released.

```
diff -w -u -r /r/downloads/iothub/transport/amqps/AmqpsIotHubConnection.java /r/downloads/AmqpsIotHubConnection.java 
--- /r/downloads/iothub/transport/amqps/AmqpsIotHubConnection.java	2016-12-02 13:25:22.000000000 +0900
+++ /r/downloads/AmqpsIotHubConnection.java	2016-12-21 10:56:30.000000000 +0900
@@ -339,6 +339,7 @@
             byte[] tag = String.valueOf(this. nextTag++).getBytes();
             Delivery dlv = sender.delivery(tag);
 
+	    try {
             // Codes_SRS_AMQPSIOTHUBCONNECTION_15_018: [The function shall attempt to send the message using the sender link.]
             sender.send(msgData, 0, length);
 
@@ -347,6 +348,11 @@
 
             // Codes_SRS_AMQPSIOTHUBCONNECTION_15_020: [The function shall set the delivery hash to the value returned by the sender link.]
             deliveryHash = dlv.hashCode();
+	    } catch (Exception e) {
+		sender.advance();
+		dlv.free();
+		deliveryHash = -1;
+	    }
         }
 
         // Codes_SRS_AMQPSIOTHUBCONNECTION_15_021: [The function shall return the delivery hash.]
@@ -554,6 +560,7 @@
                 {
                     listener.messageSent(d.hashCode(), state);
                 }
+		d.free();
             }
         }
     }

```

**Comment by prmathur-microsoft** [comment]
I agree with your comment and I will check in a fix soon.

**Comment by prmathur-microsoft** [comment]
After re-evaluating this situation, it turns out proton library takes care of it and does not let us free dlv when a message is successfully sent. So there is nothing client can do in that case. Closing it for that reason.

**Comment by hiro4kuribaya4** [comment]
do not free when a message is successfully sent.
it should free when received DISPOSITION from Proton in onDelivery() method.

[AmqpsIotHubConnection.zip](https://github.com/Azure/azure-iot-sdk-java/files/697993/AmqpsIotHubConnection.zip)

**Comment by prmathur-microsoft** [comment]
Hi hiro4kuribaya4 , You are right. There may be a possibility to fix this issue. We will look into it.

**Comment by SecretBytes** [comment]
Hello hiro4kuribaya4,  the code for this in the SDK has been changed a bit, we now have handler code for ondelivery in AmqpsIotHubConnectionBaseHandler.java (it was split away from AmqpsIotHubConnection. I'll incorporate your suggestion and make sure it works.  I'll keep you posted.

**Comment by tameraw** [comment]
@hiro4kuribaya4 - Can you please submit a Pull Request with your proposed fix and sign the CLA?
Thanks!

**Comment by tameraw** [comment]
Closing as this is being tracked via the pull request #34.
