### ISSUE TITLE
[Android]android sample can't receive message

### ISSUE THREAD

**Issue by BobXLiu** [Azure/azure-iot-sdk-java#40]
Hi,
I used android sample test send and receive message to and from IoT Hub. send message will feedback: IoT Hub responded to message 0 with status OK_EMPTY, is send message success ?  when i clicked receive message button, can't receive message(com.microsoft.azure.sdk.iot.device.MessageCallback nothing feedback).

**Comment by prmathur-microsoft** [comment]
Hi BobXLiu, 

Can you explain how are you trying to receive messages ? Did you use device explorer to send a C2D message and even in spite of that are you unable to receive messages ?

Thanks
Priyanka

**Comment by BobXLiu** [comment]
Sorry,
I only tested the android sample and found MessageCallback nothing feedback. 
Did i miss some step?

**Comment by prmathur-microsoft** [comment]
Our SDK supports both D2C and C2D messaging. What you are trying to do is receive messages from IotHub in which case you would have to either use a service client to send a C2D message which can be received by your device or use device explorer (in case of verifying) to send a C2D message which can be received by your client. This message when received will be notified to you in the message call back. Hope this helps. 

Also device explorer is located here (if you want to try) - https://github.com/Azure/azure-iot-sdk-csharp/releases/download/2017-2-10/SetupDeviceExplorer.msi

**Comment by BobXLiu** [comment]
I want to build two android Apps,one send and other receive message.
So, I would like to ask Android platform can support service SDK or have any others method can do it?

**Comment by prmathur-microsoft** [comment]
Currently our java device client sdk runs on Android. However our Service client SDK does not support android and it is in our backlog to address it. However you can use service client sdk on any other java platform for sending C2D messages.

**Comment by BobXLiu** [comment]
If i use C2D send message , can i use two or many apps receive the message?(I tried use C2D send message, but only one app can receive the message.)

**Comment by prmathur-microsoft** [comment]
It depends on the scenario you are trying to accomplish. Using our java service client on a single app, you can send C2D messages to different devices running device client independently. You can then have multiple devices receiving C2D messages. Similarly you should be able to send D2C message from a device and have one app running as service client receive that message. Hope that helps.

**Comment by GamalMohamed** [comment]
@prmathur-microsoft 
Is Java service client SDK still not supported in Android till now ?

**Comment by prmathur-microsoft** [comment]
We are able to run service client on Android API 25 and higher. Please give it a try and let us know if you find any issues.

**Comment by Mani0808047** [comment]
Hi,
I am using direct mqtt mechanism for publishing messages to azure IOT hub using paho. Similarly am using subscribe option to receive messages. But am unable to receive messages in my paho client and i could able to see messsges are received in Device explorer.

**Comment by timtay-microsoft** [comment]
@Mani0808047 are you using this SDK to publish and receive messages? Or are you using a custom SDK you built that uses Paho?

**Comment by Mani0808047** [comment]
Hi,
I have used below procedure for publishing messages where its not using azure IOT sdk.
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support

In the similar way,  i want to subscribe using the topic and receive messages.

Thanks

**Comment by GamalMohamed** [comment]
@prmathur-microsoft 
I tried to use this service sdk "'com.microsoft.azure.sdk.iot:iot-service-client:1.9.25'", but it immediately  crashes once I run it on API 26..

Here's my build.gradle:

`
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.example.jimmy.android_iothub"
        minSdkVersion 26
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude "META-INF/MSFTSIG.SF"
        exclude "META-INF/MSFTSIG.RSA"
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'thirdpartynotice.txt'
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.android.support:design:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}

repositories {
    mavenCentral()
}

dependencies {
    // Remote binary dependency
    compile 'com.microsoft.azure.sdk.iot:iot-device-client:1.5.37'
    compile 'com.microsoft.azure.sdk.iot:iot-service-client:1.9.25'
}

`

**Comment by GamalMohamed** [comment]
@prmathur-microsoft 

I tried to use this service sdk "'com.microsoft.azure.sdk.iot:iot-service-client:1.9.25'", but it immediately  crashes once I run it on API 26..

Here's my build.gradle:


    apply plugin: 'com.android.application'
    
    android {
         compileSdkVersion 26
         defaultConfig {
         applicationId "com.example.jimmy.android_iothub"
         minSdkVersion 26
         targetSdkVersion 26
         versionCode 1
         versionName "1.0"
         testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
     }
         buildTypes {
             release {
               minifyEnabled false
               proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude "META-INF/MSFTSIG.SF"
        exclude "META-INF/MSFTSIG.RSA"
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'thirdpartynotice.txt'
        }
    }

    dependencies {
        implementation fileTree(dir: 'libs', include: ['*.jar'])
        implementation 'com.android.support:appcompat-v7:26.1.0'
        implementation 'com.android.support.constraint:constraint-layout:1.1.0'
        implementation 'com.android.support:design:26.1.0'
        testImplementation 'junit:junit:4.12'
        androidTestImplementation 'com.android.support.test:runner:1.0.1'
        androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        // Remote binary dependency
        compile 'com.microsoft.azure.sdk.iot:iot-device-client:1.5.37'
        compile 'com.microsoft.azure.sdk.iot:iot-service-client:1.9.25'
    }
