### ISSUE TITLE
Update Planned Release Schedule

### ISSUE THREAD

**Issue by TechWatching** [Azure/azure-iot-sdk-java#400]
Could you please update the section "Long Term Support" in the readme. I can only see one LTS package for 2018 so I guess the schedule for LTS versions have changed. 

Do you know when will be the next LTS version ? Is the release of 03/12/2018 an LTS version.

**Comment by yzhong94** [comment]
Sorry about the confusion!  We try to stay on a schedule of two LTS per year (Jan and July).  Due to Edge stabilization last year, we pushed out our July LTS.  As @prmathur-microsoft  mentioned, we expect a new LTS in January and get back to the Jan/July cadence.

**Comment by yzhong94** [comment]
@TechWatching LTS was released in January as planned.  https://github.com/Azure/azure-iot-sdk-java/tree/lts_1_2019  Thanks!

**Comment by az-iot-builder-01** [comment]
@TechWatching, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
