### ISSUE TITLE
[Java] RegistryManager.getDevices method returns too few devices

### ISSUE THREAD

**Issue by meken** [Azure/azure-iot-sdk-java#41]
The RegistryManager.getDevices doesn't return the correct number of registered devices when a limit is provided. In my example the IoT Hub contains 3 registered devices. However, when I call the getDevices method with a limit that is less than 12, RegistryManager reports a single device, when limit is increased to up to and including 14, 2 devices are reported. The correct number of devices is only reported when the limit is set to >=15.

```java
String connectionString = String.format("HostName=%s;SharedAccessKeyName=%s;SharedAccessKey=%s",
                HOST_NAME, SA_KEY_NAME, SA_KEY_VALUE);
RegistryManager registryManager = RegistryManager.createFromConnectionString(connectionString);
registryManager.getDevices(10).forEach(d -> System.out.println(d.getDeviceId()));
```

The snippet above reports only a single device, whereas 3 devices are expected.

This happens using the Java SDK (com.microsoft.azure.iothub-java-client:iothub-java-device-client:1.0.16)   with Java 8.

**Comment by tameraw** [comment]
@meken - If you're able to provide us a full snippet of your code that might help with our investigation. thanks.

**Comment by prmathur-microsoft** [comment]
I'm able to reproduce the problem locally here. I'll investigate and provide you a fix soon.

**Comment by prmathur-microsoft** [comment]
This is a service side issue and is impacting all our SDK's. Service is working on a fix. We will keep you informed when it rolls out.

**Comment by prmathur-microsoft** [comment]
This issue is now resolved. Please feel free to re-open if you still see any further issues.
