### ISSUE TITLE
Does IOT SDK support long connection of mutiply actuator devices?

### ISSUE THREAD

**Issue by wuwei3** [Azure/azure-iot-sdk-java#412]
- **OS and version used:** <VERSION> ubuntu 14

- **Java runtime used:** <VERSION> java 8

- **SDK version used:** <VERSION> iot-service-client 1.15.2, iot-device-client 1.14.2

# Description of the issue:
for now, I have 5000 simulation devices in one IOT hub, they are actuator type, I want to send message from device to cloud every 5 mins with MQTT protocol, but the connection must not be closed, means every time the send message finished, the connection is still connecting for next time using, but it seems that the azure java sdk cannot support so many connection online at the same time.
My code logic is separate the 5000 devices to 50 * 100, '50' is the send count on every round, '100' is the device number for every count of  50, I used the threadpool to send the 100 thread at the same time.

but:
it was ok for begin, maybe from device number 1-100, but it was sending slower and slower after device number behind 100 and always get "Could not open the connection" exception even I retry, so that it could not finished the 5000 devices send message mission in 5 mins.

Question:

1. Does azure java sdk support the multiply connection without closing?every device has its own connection with its own primary key. I tested the sensor for 5000 devices, it's ok, the sensor and actuator execute the same code, the only different is actuator not close the connection but sensor does.

2, while I test the multiply thread send message, I always got error "Message with message id xxx-xxx-xxx-xxxx was delivered to IoTHub, but was never sent, method name is onMessageSent", this is from auzre its own log, not from me, what is this? I saw other issue describe it as azure own bug, the message actually has been sent to hub, it's true? how to make this kind of error log disappear?

# Code sample exhibiting the issue:

Sensor and actuator are the same code, only different is actuator will not execute the closeConnecton() in finally{}

DeviceClient client = getDeviceClient();
		
		try {
			if (client == null) {
				log.error(deviceId +  " DeviceClient is null, cannot do anything!!!!");
			} else {
				boolean open = reOpenConnection(); // invoke the 'client.open()' method 
				
				if (open) {
					String payload = getPayLoad();
					Message msg = new Message(payload);
					msg.setContentType("application/json");
					msg.setContentEncoding("utf-8");
					msg.setMessageType(MessageType.DEVICE_TELEMETRY);
					// msg.setExpiryTime(2000);

					Object lockobj = new Object();
					SendMsgCallback callback = new SendMsgCallback(deviceId);

					sendMsg(client, msg, callback, lockobj);
					Thread.sleep(1000);
				} 
			}
		} catch (Exception e) {
			log.error(deviceId + " unknow exception -> " + e.getMessage());
		} finally {
			latch.countDown();
			closeConnecton(client);
		}

**Comment by timtay-microsoft** [comment]
When you see the "Could not open the connection" exception, what is the typical full stacktrace you get?

**Comment by timtay-microsoft** [comment]
And see [this](https://github.com/Azure/azure-iot-sdk-java/issues/380) issue for the explanation for the "Message with message id was delivered to iothbu, but was never sent" message. In short, it is a bug on our side.

**Comment by wuwei3** [comment]
> When you see the "Could not open the connection" exception, what is the typical full stacktrace you get?

java.io.IOException: Could not open the connection
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:164)
	at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:130)
	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:317)
	at com.orangelabs.iot.azure.IotAzureTest.utils.DeviceConnUtils.isOpen(DeviceConnUtils.java:22)
	at com.orangelabs.iot.azure.IotAzureTest.testsend.pushdata.PushDataThread.reOpenConnection(PushDataThread.java:139)
	at com.orangelabs.iot.azure.IotAzureTest.testsend.pushdata.PushDataThread.run(PushDataThread.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.microsoft.azure.sdk.iot.device.exceptions.ProtocolException: Unable to subscribe to topic :devices/OLCActuator736/messages/devicebound/#
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.exceptions.PahoExceptionTranslator.convertToMqttException(PahoExceptionTranslator.java:75)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:285)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttMessaging.start(MqttMessaging.java:61)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:179)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:653)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:280)
	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:160)
	... 8 more
Caused by: Timed out waiting for a response from the server (32000)
	at org.eclipse.paho.client.mqttv3.internal.Token.waitForCompletion(Token.java:112)
	at org.eclipse.paho.client.mqttv3.MqttToken.waitForCompletion(MqttToken.java:67)
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.Mqtt.subscribe(Mqtt.java:280)
	... 13 more

if I retry to connect again, it was ok, the exception not appear

my problem is that if I don't close the connection for 5,000 actuator simulation devices, does azure support to do that?

if yes, based on my test result, it always throwing the "Could not open the connection" and cannot send message to hub.

BTW, if not close the connection, even the connection open successfully, the sdk would throw exception "Cannot add a message when the transport is closed" while I invoking the "sendEventAsync()", is this caused by not closing the connection?

Thanks.

**Comment by wuwei3** [comment]
Anybody could answer? emergency....................

**Comment by wuwei3** [comment]
from the first pic, you could see, the cost time very short and execute very fast:

![1](https://user-images.githubusercontent.com/46955295/51821118-fea32900-2312-11e9-9ec2-6989bbb4267a.jpg)


But, after seconds, the cost time is more and more, sorry, I can't give the full trace screen, based on the cost time, it cannot finish the send message mission in 5 mins, and many exception:

![2](https://user-images.githubusercontent.com/46955295/51821178-37430280-2313-11e9-9cad-834766167168.jpg)

![3](https://user-images.githubusercontent.com/46955295/51821343-cd772880-2313-11e9-9b33-6b94884d3d3b.jpg)


![4](https://user-images.githubusercontent.com/46955295/51821345-d23bdc80-2313-11e9-8f5b-b480fb50cb2e.jpg)

**Comment by timtay-microsoft** [comment]
What are the pricing details and number of iot hub units tied to your iothub? There are some defined limits to connections per second that can be established. Pulling the relevant info from [this document](https://github.com/MicrosoftDocs/azure-docs/blob/master/includes/iot-hub-limits.md) 

The IoT Hub service throttles requests when the following quotas are exceeded:

| Throttle | Per-hub value |
| --- | --- |
| Identity registry operations <br/> (create, retrieve, list, update, delete), <br/> individual or bulk import/export |83.33/sec/unit (5000/min/unit) (for S3) <br/> 1.67/sec/unit (100/min/unit) (for S1 and S2). |
| Device connections |6000/sec/unit (for S3), 120/sec/unit (for S2), 12/sec/unit (for S1). <br/>Minimum of 100/sec. |
| Device-to-cloud sends |6000/sec/unit (for S3), 120/sec/unit (for S2), 12/sec/unit (for S1). <br/>Minimum of 100/sec. |

The exceptions that you are getting suggest that you may be using too small of an iothub to connect to. I also suggest you spread out when you establish all of these connections. If you have all 5000 simulated devices attempting to connect at once, you will very likely be throttled. If you spread them out more, you will see better results.

**Comment by wuwei3** [comment]
The unit I am using is S2, I am strictly create the new connection based on the throttles, I create 100 connections/sec, it is not exceeding the throttles, correct?

I think it's enough on my side, i tested for sensor, it was ok, but for actuator, it's not ok, they were  executing the same codes, the only different is **actuator would never closed the connection once the connection opened**. for now, I just only test 1,000 simulation devices, create the new connections 100/sec, but it did only run 2 days, then the "Out of Memory Error" happened, see the "hs_err_pid97816.log"

[hs_err_pid97816.log](https://github.com/Azure/azure-iot-sdk-java/files/2863027/hs_err_pid97816.log)



 My problem is that, does azure support long connection for simulation devices? in my case, the actuator's connection should not be closed once opened, but if not closed, it will appear the "Out of Memory Error ", and only run 2 days, then the process will be forcing exited.

Other thing is that while I use the direct method with java for cloud 2 device, it also appearing "SharedAccessKeyName cannot be null or empty" or "IoT Hub not found", see the "error.log" 
[error.log](https://github.com/Azure/azure-iot-sdk-java/files/2863018/error.log)


I am quit sure I give the share key and the IOT hub exit, it only happened while I test with multiply thread, not appear while test one by one, is there any trick on that?

**Comment by timtay-microsoft** [comment]
IotHub does support long lasting connections in theory, so if you are unable to achieve that, then there is a bug to be resolved. There are a couple of things to look at here.

The Out of Memory Error that you are seeing is likely indicative of leaked threads from the device side, possibly from the device client itself. This could be a bug on our side. To help with this investigation, can you try using AMQP instead of MQTT for your devices? It would give us another data point to help narrow down where the threads are leaking.

I don't see any "SharedAccessKeyName cannot be null or empty" exceptions in the logs you provided, so I can't comment on what that may be.

As for the 100 connections/sec, that is below the throttling limit, correct. However, before an IotHub sends back the 429 (throttled) error message, it will slow down its acceptance of new connections significantly. That slow down is likely why you are seeing a lot of timeouts. Again, I encourage you to spread out how many connections you are opening per second until you see a more consistent behavior.

**Comment by wuwei3** [comment]
> IotHub does support long lasting connections in theory, so if you are unable to achieve that, then there is a bug to be resolved. There are a couple of things to look at here.

   I think there is a bug in java sdk, I tested many times, if the connection not open, there many error.

> The Out of Memory Error that you are seeing is likely indicative of leaked threads from the device side, possibly from the device client itself. This could be a bug on our side. To help with this investigation, can you try using AMQP instead of MQTT for your devices? It would give us another data point to help narrow down where the threads are leaking.
 
   Actually, I tried before, still the same result, the error message is the same with last file (hs_err_pidxx.log)


> I don't see any "SharedAccessKeyName cannot be null or empty" exceptions in the logs you provided, so I can't comment on what that may be.

sorry, my fault, I uploaded the new one, from the error log, you would see it also throws "Device not found" and "IoT Hub not found!" error, I am quiet sure they are exiting!!!

this happened while I was using "Directly method" to send message from cloud to devices.

[error.log](https://github.com/Azure/azure-iot-sdk-java/files/2867526/error.log)


> As for the 100 connections/sec, that is below the throttling limit, correct. However, before an IotHub sends back the 429 (throttled) error message, it will slow down its acceptance of new connections significantly. That slow down is likely why you are seeing a lot of timeouts. Again, I encourage you to spread out how many connections you are opening per second until you see a more consistent behavior.

I am sure there are only 100 connections/sec for device to cloud, the less than 100 connections/sec for cloud to device.

**Comment by wuwei3** [comment]
I got another issue:

 1. I used the "send message with cloud to device ", code example from  https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-java-java-c2d

 2. I send 10 times for cloud 2 device, everything is OK for the first time, but from the second time, the class implements "MessageCallback.class" always getting the same message from the same deviceId, not only one, but also for others, it was not normally, I still open the DeviceClient connection once and never closed.

3, From the "info.txt" file bottom, you select any "OLCActuatorXX", you will find there are other same message sent at the same times, **I think there is big bug in DeviceClient if the connection is not closed,**

    I cannot upload the full log file, because it it too big, so I truncated some of it.
   
[info.txt](https://github.com/Azure/azure-iot-sdk-java/files/2874498/info.txt)


4, For the hs_error_pidXX issue. I think this is the main cause for the "out of memory" issue, because it was sending the same message with the same deviceId (Also for other devices), so the print thread annex the memory, you cloud see the file size, I just only run 20 mins, but printed more 300M content, the main content is from the class which implement the "MessageCallback.class".

**Comment by timtay-microsoft** [comment]
For the "Iot Hub not found" and "Device not found" errors, those simply mean you tried to invoke a method on a device that could not be reached. This is likely just because of the other issues in this thread causing your devices to lose connectivity. I wouldn't worry much about those right now.

**Comment by wuwei3** [comment]
Ok, what about the issue I mentioned on last reply?
I found very strange issue, for the cloud 2 device, whatever I used the direct method or the example (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-java-java-c2d), they had the same errror phenomenon

1. If run the first time, everything would be ok, and didn't stop the program, just waiting the next time run, everything was OK.

2. But,  while the second time runs, send messages from cloud to device, the subscribe side would get the same message many times, I mean, I received the message and print it for every device, it printed unstopped, I am sure I just only send one message from cloud to device for every device, but the device's subscribe method (Direct method is implement DeviceMethodCallback, https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-java-java-c2d is AppMessageCallback), they got the message unstopped, or I should say the cloud was sending the same message unstopped.

 I think the cause is still the connection did't close, I didn't close the DeviceClient connection after the logic finished, I need it to keep the long connection alive.

Does java SDK have any method to keep the DeviceClient connection alive and the hub would never dropped the connection down even I don't do any operation until I terminate the program?

**Comment by timtay-microsoft** [comment]
The behavior you are seeing with C2D producing extra callbacks to the client is a separate known issue that will have a fix soon (see #362)

**Comment by wuwei3** [comment]
ok, thanks, what for the share access key null exception?

![shearkeynull](https://user-images.githubusercontent.com/46955295/53229197-93086d80-36be-11e9-9d01-97906153fe15.jpg)


this is only happened while send message with thread, if one by one, no this kind of error.

**Comment by timtay-microsoft** [comment]
The duplicate C2D/method invocation issue has been resolved as of Device Client version 1.16.0, so I highly encourage you to upgrade now, and update this thread with any new findings you have.

As for the error messages you are seeing in your above screenshot ("SharedAccessKeyName cannot be null or empty" and "The connection string has an invalid value for property"), this may be a bug on our side. Are you creating the service client instances on the separate threads?

**Comment by wuwei3** [comment]
> The duplicate C2D/method invocation issue has been resolved as of Device Client version 1.16.0, so I highly encourage you to upgrade now, and update this thread with any new findings you have.

   OK, thanks, I will try


> As for the error messages you are seeing in your above screenshot ("SharedAccessKeyName cannot be null or empty" and "The connection string has an invalid value for property"), this may be a bug on our side. Are you creating the service client instances on the separate threads?

    yes , I created the  service client instances on the separate threads

**Comment by wuwei3** [comment]
I also got another error "Cannot add a message when the transport is closed" while send message to hub, this is happened while the connection not close, if this error happened on one device, the device would fail again, again and again until I restart the program. it's not normally. 
Could you help?

**Comment by timtay-microsoft** [comment]
For the service client exceptions, I have created a [PR](https://github.com/Azure/azure-iot-sdk-java/pull/460) that I believe will fix your issue. It looks like there was a thread safety issue around parsing connection strings that is causing your exceptions.

For the "Cannot add a message when the transport is closed" message: It should only be thrown when your device client is closed. Are you sure that your device client was opened properly, and that it never reported any connection drops?

**Comment by wuwei3** [comment]
> For the service client exceptions, I have created a [PR](https://github.com/Azure/azure-iot-sdk-java/pull/460) that I believe will fix your issue. It looks like there was a thread safety issue around parsing connection strings that is causing your exceptions.

     I think so, thanks


> For the "Cannot add a message when the transport is closed" message: It should only be thrown when your device client is closed. Are you sure that your device client was opened properly, and that it never reported any connection drops?

     yes , i am sure I open the connection based on the sample codes, it never reported any connection drops, no error, no exception, everything was fine until I send the message to hub, it was appearing this error.

**Comment by wuwei3** [comment]
Any SDK upgrading on this issue? especially for the connection issue?

**Comment by timtay-microsoft** [comment]
What issues are you still seeing after upgrading to the latest SDK versions?

**Comment by wuwei3** [comment]
> What issues are you still seeing after upgrading to the latest SDK versions?

for now, I upgraded the SDK to the latest, but the main problem is still on the long connection issue (not close the connection once open it.) and has below issues:

1.  it sometimes throw the exception:
     "Cannot add a message when the transport is closed."
      
![cannot_close](https://user-images.githubusercontent.com/46955295/58142573-3a734d00-7c7a-11e9-870d-e9a2b5ff47f8.jpg)

  i don't know what is this mean and how to resolve it? any advice?

2, see the code below, 

    
![callback](https://user-images.githubusercontent.com/46955295/58142625-78707100-7c7a-11e9-86c9-180eadf027cc.jpg)

   i got one class to implement the IotHubEventCallback.class while I pushing data to IOT hub for seeing  whether the response is ok, but 

  
![error](https://user-images.githubusercontent.com/46955295/58142731-cbe2bf00-7c7a-11e9-942d-9a7f311aa0f5.jpg)

 you can see, the deviceiD "OLCActuator374"(there are many other deviceID also have the same problem) always receiving the "ERROR" response and  not only one time, it received many times, and there is no error message to receive or I could watch, I don't know whether it is Azure bug?

**Comment by timtay-microsoft** [comment]
When you see the error message "Cannot add a message when the transport is closed." that means that your device client instance has lost connectivity. In order to understand what caused your device client to lose connectivity, you need to register a connection status change callback to log connectivity events. Something like:

```java
protected static class IotHubConnectionStatusChangeCallbackLogger implements IotHubConnectionStatusChangeCallback
{
    @Override
    public void execute(IotHubConnectionStatus status, IotHubConnectionStatusChangeReason statusChangeReason, Throwable throwable, Object callbackContext)
    {
        System.out.println();
        System.out.println("CONNECTION STATUS UPDATE: " + status);
        System.out.println("CONNECTION STATUS REASON: " + statusChangeReason);
        System.out.println("CONNECTION STATUS THROWABLE: " + (throwable == null ? "null" : throwable.getMessage()));
        System.out.println();

        if (throwable != null)
        {
            throwable.printStackTrace();
        }
    }
}
...
client.registerConnectionStatusChangeCallback(new IotHubConnectionStatusChangeCallbackLogger(), null);

```

**Comment by timtay-microsoft** [comment]
This issue thread is getting very messy and includes discussions/logs on several fixed issues, so I'm closing it. If you are still seeing any issues, It would be easier for you to open a new thread rather than add to this one.

**Comment by az-iot-builder-01** [comment]
@wuwei3, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
