### ISSUE TITLE
Reference doc links return 404.

### ISSUE THREAD

**Issue by ktoraskartwilio** [Azure/azure-iot-sdk-java#417]
Provisioning service client - documentation (https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.provisioning.service._Provisioning_Service_Client)

Provisioning service client - source code (https://github.com/Azure/azure-iot-sdk-java-dps/tree/master/provisioning/provisioning-service-client)

**Comment by yzhong94** [comment]
Oops!  Thanks for letting us know.  Where did you see these links?  Is it this [document](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-sdks)?

**Comment by yzhong94** [comment]
Here's link for provisioning client API documentation: https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.provisioning.service?view=azure-java-stable

And here's link for the provisioning client source code: https://github.com/Azure/azure-iot-sdk-java/tree/master/provisioning/provisioning-service-client 

Looks like the document has the correct links, please let me know where the broken links are located and I can update them.  Thanks!

**Comment by yzhong94** [comment]
Closing this for now.  Let us know where we should update links.  Thanks!

**Comment by az-iot-builder-01** [comment]
@ktoraskartwilio, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
