### ISSUE TITLE
DeviceClient.uploadToBlobAsync fails for devices with uppercase letters in Device ID

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/azure-iot-sdk-java#419]
- **OS and version used:** Windows 10

- **Java runtime used:** 1.8.0+

- **SDK version used:** Device Client 1.15 (used for testing)

# Description of the issue:
Uploading to a blob storage fails if the Device ID contains invalid characters like uppercase letters, since the device id is used in the Blob storage URL that requires a certain naming convention. See https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata 
The http request used by the SDK method DeviceClient.uploadToBlobAsync will return a status code 403, that means TOO_MANY_DEVICES, if your using an invalid device id. This is confusing and should be changed as well. Please fix by either transforming the device id (lowercasing) or throwing an exception if it contains invalid characters.

# Code sample exhibiting the issue:
Default sample file-upload-sample of the SDK for a device with the id 'MyDevice'

# Console log of the issue:
n.a.

**Comment by jasmineymlo** [comment]
@JMayrbaeurl, thanks for letting us know the issue.  We will look into it.  Thanks.

**Comment by timtay-microsoft** [comment]
I'm not able to repro any failures around device id's having capitalization, or device id's containing multiple consecutive dashes. When using device id's such as "MyDevice", "MyDevice--", I still get 200's from the service for the file upload sample.

I'm not sure if something changed on the service side since this issue was raised, so do you still see this behavior, @JMayrbaeurl ?

**Comment by JMayrbaeurl** [comment]
If it works now with device ids like 'MyDevice' than it's OK and will close the issue now.

**Comment by az-iot-builder-01** [comment]
@JMayrbaeurl, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
