### ISSUE TITLE
Add packages version number to release notes

### ISSUE THREAD

**Issue by dluc** [Azure/azure-iot-sdk-java#42]
It would be helpful to show the package version in the [release page](https://github.com/Azure/azure-iot-sdk-java/releases). This would, for example, allow one to compare the version used in a project against the latest version listed in the release page. 
A couple of examples:
* https://github.com/Azure/azure-event-hubs-java/releases
* https://github.com/Azure/azure-storage-java/releases

**Comment by prmathur-microsoft** [comment]
Sure. We will include it in coming releases.

**Comment by prmathur-microsoft** [comment]
I believe we can close this for now. As version number was added in release.
