### ISSUE TITLE
run provisioning-x509-sample will occur error.

### ISSUE THREAD

**Issue by v-jiq** [Azure/azure-iot-sdk-java#430]
# environment 
 os: __windows 10__
 jdk version: __1.8.0__
 java sdk version: __latest__
# description 
I refer to this  link --  https://docs.microsoft.com/en-us/Azure/iot-dps/tutorial-group-enrollments to realize group enrollments , but when i through  the part of  _Simulate the device_ will occur error.

# below is error pic
<img width="978" alt="1548919412 1" src="https://user-images.githubusercontent.com/39880470/52038138-3b1d9180-256c-11e9-9808-d614cde26fdb.png">

**Comment by timtay-microsoft** [comment]
The SecurityProviderSymmetricKey class was introduced only in our latest release, so it's possible that you need to clean rebuild the jar files here.

```
mvn clean install -DskipTests
```

Also, verify that the repo that you cloned contains the SecurityProviderSymmetricKey class in the location

```
...\azure-iot-sdk-java\provisioning\security\security-provider\src\main\java\com\microsoft\azure\sdk\iot\provisioning\security\SecurityProviderSymmetricKey.java
```

**Comment by v-jiq** [comment]
I had retry according your way and still have this error . and can find SecurityProviderSymmetricKey.java file in specific Directory.

**Comment by timtay-microsoft** [comment]
Have you tried to delete your .m2 folder before you run the maven clean install? Also, try running the clean install command from the top level directory of the repo instead of at the sample level.

**Comment by v-jiq** [comment]
Thanks @timtay-microsoft   it's ok after delete .m2 folder.

**Comment by az-iot-builder-01** [comment]
@v-jiq, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by v-jiq** [comment]
@az-iot-builder-01 ok
