### ISSUE TITLE
Java Edge Module unable to connect to hub when EdgeHubConnectionString string is missing from env

### ISSUE THREAD

**Issue by logaras** [Azure/azure-iot-sdk-java#433]
- **OS and version used:** Raspbian GNU/Linux 9 (stretch)

- **Runtime used:**
moby-cli	3.0.2		
moby-engine	3.0.2
libiothsm-std	1.0.5-1
iotedge 1.0.5

edgeAgent Version - 1.0.6-rc1.19676807
edgeHub Version-1.0.6-rc1.19676807

- **SDK version used:** 1.15.0

# Description of the issue:
Invokation of `ModuleClient.createFromEnvironment(IotHubClientProtocol.MQTT)` throws the following exception: 

> com.microsoft.azure.sdk.iot.device.exceptions.ModuleClientException: java.io.IOException: Status line is not valid.
>         at com.microsoft.azure.sdk.iot.device.ModuleClient.createFromEnvironment(ModuleClient.java:252)

> Caused by: java.io.IOException: Status line is not valid.
>         at com.microsoft.azure.sdk.iot.device.hsm.HttpsRequestResponseSerializer.deserializeResponse(HttpsRequestResponseSerializer.java:144)
>         at com.microsoft.azure.sdk.iot.device.hsm.HttpsHsmClient.sendHttpRequestUsingUnixSocket(HttpsHsmClient.java:269)
>         at com.microsoft.azure.sdk.iot.device.hsm.HttpsHsmClient.sendRequestBasedOnScheme(HttpsHsmClient.java:226)
>         at com.microsoft.azure.sdk.iot.device.hsm.HttpsHsmClient.sign(HttpsHsmClient.java:112)
>         at com.microsoft.azure.sdk.iot.device.hsm.HttpHsmSignatureProvider.sign(HttpHsmSignatureProvider.java:85)
>         at com.microsoft.azure.sdk.iot.device.hsm.IotHubSasTokenHsmAuthenticationProvider.createNewSasToken(IotHubSasTokenHsmAuthenticationProvider.java:80)
>         at com.microsoft.azure.sdk.iot.device.hsm.IotHubSasTokenHsmAuthenticationProvider.create(IotHubSasTokenHsmAuthenticationProvider.java:48)
>         at com.microsoft.azure.sdk.iot.device.ModuleClient.createFromEnvironment(ModuleClient.java:235)
>         ... 2 more

Module connects and works without any issues when `EdgeHubConnectionString `and `EdgeModuleCACertificateFile `are manually inserted as environmental variables with the corresponding values.

**Comment by timtay-microsoft** [comment]
This error message suggests that the communication with the edgelet hsm is not working correctly. Are you seeing a similar error when you use any of the other protocols (MQTT_WS, AMQPS, AMQPS_WS)?

**Comment by logaras** [comment]
Hi @timtay-microsoft , I just verified that the same exception is thrown no matter which protocol I use.

**Comment by timtay-microsoft** [comment]
Can you share the edgehub logs that you are seeing? From both the edgehub container and the edge agent container?

**Comment by logaras** [comment]
Here are the logs using MQTT:

edgeHub
https://gist.github.com/logaras/7dc3897f7738a7602bde77c9705d4a71

edgeAgent
https://gist.github.com/logaras/674a39fea316d0c3d242b4563b7160d9

Java Module (Scoring)
https://gist.github.com/logaras/6d8dfbfdba36317a1d7e8e64a16adc2c

In the meantime I have updated to the following versions:
iotedge 1.0.6.1 (3fa6cbef8b7fc3c55a49a622735eb1021b8a5963)
[EdgeHub] - Version - 1.0.6.19913336 (8288bc9bd6f6e15295fea506cd3f99d7f6347a6a)
[EdgeAgent ] - Version - 1.0.6.19913336 (8288bc9bd6f6e15295fea506cd3f99d7f6347a6a)
libiothsm-std 1.0.6.1-1

**Comment by timtay-microsoft** [comment]
@varunpuranik @ancaantochi do you have any context on why the hsm http response might be formatted wrong here? The Java SDK is throwing the same exception that the C# SDK throws [here](https://github.com/Azure/azure-iot-sdk-csharp/blob/55591d5ee4359f6023074755a0a42e71c2d3e366/iothub/device/src/netstandard13/HsmAuthentication/Transport/HttpRequestResponseSerializer.cs#L135) when the hsm http response does not have the expected status line.

**Comment by varunpuranik** [comment]
Can we get the iotedged logs? That might tell us more. Check this link on how to get debug logs for iotedged - https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot#standard-diagnostic-steps

**Comment by logaras** [comment]
Thank you @varunpuranik for pointing out the right place to look. The issue was on my side.

I had multiple processes in my Dockerfile ENTRYPOINT and I was getting a "Request not authorized - expected caller pid: X, actual caller pid: Y".

Same as https://github.com/Azure/iotedge/issues/83

**Comment by az-iot-builder-01** [comment]
@logaras, @varunpuranik, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
