### ISSUE TITLE
porting java sample -- provisioning-x509-sample to android project

### ISSUE THREAD

**Issue by v-jiq** [Azure/azure-iot-sdk-java#442]
## Background
The device is android-4.4(api19) and i want run provisioning-x509-sample on it.

## Problem 
I had porting provisioning-x509-sample to android app accoding java code , and it can work on android 7.0(api 24), but when i run this app on target device(android-4.4), it will occur error

below is error log:
<img width="1324" alt="1550216922" src="https://user-images.githubusercontent.com/39880470/52842837-49a6a400-313b-11e9-9eb8-df2a80660bea.png">

**Comment by az-iot-builder-01** [comment]
@v-jiq, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
