### ISSUE TITLE
Random disconnections on a sample in the azure sdk for java

### ISSUE THREAD

**Issue by enchiladaRoja** [Azure/azure-iot-sdk-java#45]
- **OS and version used:** <VERSION> 
Raspbian 8 on a raspberry pi 3
- **Java runtime used:** <VERSION> 
jdk-8-oracle-arm32
- **SDK version used:** <VERSION> 
im using the send-receive-samples version 1.0.14 include in the sdk for java

# Description of the issue:

When i connect to the iot hub, im using the HostName=;DeviceId=;SharedAccessKey=;
It connects fine and i can receive messages, which is why im using this sample, but after a while, between 45 minutes and two hours,it disconnects. Im using the AMQPS protocol, but this behavior is the same for MQTT and amqps_ws.
This happend all the time i run the sample, and the reconnection method doesnt do anything, just stay on attempt number 1. 
![lost](https://cloud.githubusercontent.com/assets/23262644/23803324/be7b3eb4-057b-11e7-8293-caaedd18f01d.JPG)
For the enviroment im using, i need the application running all the time and if for some reason fail, that it can be able to reconnect. Is there a possible way of doing this?
# Code sample exhibiting the issue:

This is the reconnect method that the sample is using.
![reconn](https://cloud.githubusercontent.com/assets/23262644/23803909/b30a1d0a-057d-11e7-8ed1-7762fad908bb.JPG)
And this is the connectionLost which it refers.
![connlost](https://cloud.githubusercontent.com/assets/23262644/23803952/e027be96-057d-11e7-8fc4-018f112316d5.JPG)

**Comment by prmathur-microsoft** [comment]
Couple of things I would like to point out 
1. Firstly the version you are using is very old. We are currently on 1.0.20 and there has been several improvements to reconnection logic on AMQP since then. Can you please move to latest and give it a try again.
2. If even after moving to the latest you do see this issue, then it would be really helpful to get a log which we can analyze to understand what could be happening in your case. Instruction on enabling logging are located at https://github.com/Azure/azure-iot-sdk-java/tree/master/device/iot-device-samples#logging
Please setup all logging to get better insights into what could be happening. 
eg log4j.rootLogger = ALL, FILE

**Comment by enchiladaRoja** [comment]
Ok, i will try with the 1.0.20, thanks for the help. I will provide feedback as soon as i can.

**Comment by enchiladaRoja** [comment]
Hi, i try the 1.0.20 and still cant receive message. I do the logging and get a file, ill provide some lines here but theres a lot of them, if you want me i can send them to an email account.
![log](https://cloud.githubusercontent.com/assets/23262644/23911586/e7b6b284-08a2-11e7-9542-0c47bfd3b121.JPG)

LOG:

2017/03/14 07:28:00,630 [INFO] [main] DeviceClientConfig - DeviceClientConfig object is created successfully with IotHubName=ChileDelQuePica, deviceID=VasoConQueso , method name is <init> 
2017/03/14 07:28:00,657 [INFO] [main] DeviceClient - DeviceClient object is created successfully, method name is <init> 
2017/03/14 07:28:00,661 [INFO] [main] DeviceClient - Setting SASTokenExpiryTime as 2400 seconds, method name is setOption_SetSASTokenExpiryTime 
2017/03/14 07:28:00,662 [INFO] [main] AmqpsTransport - Opening the connection..., method name is open 
2017/03/14 07:28:00,735 [INFO] [main] AmqpsIotHubConnection - AmqpsIotHubConnection object is created successfully using port 5671 in <init> method 
2017/03/14 07:28:01,783 [INFO] [main] AmqpsIotHubConnection - SAS Token is created successfully, method name is openAsync 
2017/03/14 07:28:01,794 [INFO] [main] AmqpsIotHubConnection - Reactor is assigned to executor service, method name is openAsync 
2017/03/14 07:28:01,819 [DEBUG] [pool-1-thread-1] AmqpsIotHubConnection - Entered in method onReactorInit
2017/03/14 07:28:01,836 [DEBUG] [pool-1-thread-1] AmqpsIotHubConnection - Exited from method onReactorInit
2017/03/14 07:28:01,850 [DEBUG] [pool-1-thread-1] AmqpsIotHubConnection - Entered in method onConnectionInit
2017/03/14 07:28:01,870 [DEBUG] [pool-1-thread-1] AmqpsIotHubConnection - Exited from method onConnectionInit
2017/03/14 07:28:01,871 [DEBUG] [pool-1-thread-1] AmqpsIotHubConnection - Entered in method onLinkInit
2017/03/14 07:28:01,882 [DEBUG] [pool-1-thread-1] AmqpsIotHubConnection - Exited from method onLinkInit
2017/03/14 07:28:01,882 [DEBUG] [pool-1-thread-1] AmqpsIotHubConnection - Entered in method onLinkInit
2017/03/14 07:28:01,886 [DEBUG] [pool-1-thread-1] AmqpsIotHubConnection - Exited from method onLinkInit
2017/03/14 07:28:02,228 [DEBUG] [pool-1-thread-1] AmqpsIotHubConnection - Entered in method onConnectionBound
2017/03/14 07:28:02,293 [DEBUG] [pool-1-thread-1] AmqpsIotHubConnection - Exited from method onConnectionBound
2017/03/14 07:28:02,293 [INFO] [main] AmqpsTransport - Connection has been opened, method name is open 
2017/03/14 07:28:02,301 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,308 [INFO] [main] Message - Setting message property with name=messageCount and value=0, method name is setProperty 
2017/03/14 07:28:02,312 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,316 [INFO] [main] Message - Setting message property with name=key1 and value=value1, method name is setProperty 
2017/03/14 07:28:02,317 [INFO] [main] Message - Setting message property with name=key2 and value=value2, method name is setProperty 
2017/03/14 07:28:02,321 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,331 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,337 [INFO] [main] Message - The message with messageid 7ce41791-e8a9-4d03-a45b-8e65a957e93f has expiry time as 5000 milliseconds and the message will expire on Tue Mar 14 07:28:07 GMT-09:00 2017, method name is setExpiryTime 
2017/03/14 07:28:02,339 [INFO] [main] DeviceClient - Message with messageid 7ce41791-e8a9-4d03-a45b-8e65a957e93f along with callback and callbackcontext is added to the queue, method name is sendEventAsync 
2017/03/14 07:28:02,341 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,350 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,351 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,351 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,351 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,356 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,358 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,360 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,361 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,361 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,361 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,362 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,363 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,370 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,371 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,371 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,381 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,382 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,382 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,383 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,383 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,384 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,391 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,391 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,391 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,392 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,392 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,393 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,393 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,394 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,394 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,400 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,401 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,401 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,411 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,411 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,412 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,412 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,413 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,413 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,414 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,414 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,415 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,420 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,421 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,421 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,421 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,422 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,422 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,430 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,431 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,431 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,431 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,432 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,432 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,440 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,441 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,441 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,441 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,442 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,442 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,450 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,451 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,451 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,451 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,452 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,452 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,460 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,461 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,461 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,461 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,462 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,462 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,470 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,471 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,471 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,471 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,472 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,472 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,480 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,481 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,481 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,481 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,482 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,483 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,490 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,491 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,491 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,492 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,492 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,492 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,500 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,501 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,501 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,501 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,502 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,503 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,510 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,510 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,510 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,511 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,512 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,512 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,520 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,521 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,521 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,521 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,522 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,522 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,530 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,531 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,531 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,531 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,532 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,533 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,540 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,541 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,541 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,542 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,543 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,543 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,550 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,550 [INFO] [pool-2-thread-1] AmqpsTransport - Converting the IoT Hub message into AmqpsMessage, method name is sendMessages 
2017/03/14 07:28:02,550 [INFO] [pool-2-thread-2] AmqpsTransport - Get the callback function for the received message, method name is handleMessage 
2017/03/14 07:28:02,551 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,551 [INFO] [pool-2-thread-1] AmqpsTransport - Content of message is Event Message 0, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,552 [INFO] [pool-2-thread-1] AmqpsTransport - Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage 
2017/03/14 07:28:02,560 [INFO] [pool-2-thread-1] AmqpsTransport - Get the message from waiting message queue to be sent to IoT Hub, method name is sendMessages 
2017/03/14 07:28:02,560 [INFO] [pool-2-thread-1] A

**Comment by prmathur-microsoft** [comment]
Looking at the log I see the following : 
 "Started converting IoT Hub message into AmpqsMessage, method name is iotHubMessageToProtonMessage" tells me that an attempt was made to send massages by SDK. But unfortunately the link credit never became greater than zero and deliveryhash was set to -1. So if you look at code in amqpsTransport.java, if for some reason linkcredit never gets above 0, we wait and loop until it can. 
So my next question is is this complete logging ? Is it possible that you missed another log that comes after this where atleast some messages go through before attempting to reconnect. I ask this because your first case bug says so. I should atleast be able to see transport error at some place in log before I see reconnect code hitting. 

If this is complete log then we will take another route of getting detail proton library log to figure out why the link credit was never greater than zero.. So can you confirm if this is complete logging ?

**Comment by enchiladaRoja** [comment]
No, this is just a part of the log, I can´t provide all of the log because its more than 65535 charcters, and that´s the limit in the comments section, so I will upload the file. Just one update, I did a clean swipe on my raspberry and install raspbian again, also install all the enviroment necessary to run de samples in the sdk (java and maven),  and to open the connection I do this: java -jar ./send-receive-sample-1.0.14-with-deps.jar "HostName=*****;DeviceId=****;SharedAccessKey=****=" "1" "amqps" so it sends one message, but always get the message_expire confirmation.
Even so, now I can receive messages that I´m sending to my device with the Device Explorer, but still had the random disconnections every 45 minutes to 1 hour. The reconnection attemps now do work, but the fact that it still disconnects its weird. I´ve been monitoring the internet connection and its stable, so thats not the problem I guess, maybe the connection with the hub got a life span I´m not aware of. 

LOG FILE:

[iotclientjavasdklog.txt](https://github.com/Azure/azure-iot-sdk-java/files/844880/iotclientjavasdklog.txt)

**Comment by prmathur-microsoft** [comment]
Okay so this information tells me that your sastoken might be expiring. So when sas token expires we tear down the connection and generate a new sastoken and re initiate the connection. I think this is the behavior you are seeing because deafult sas token expiry time is 60 minutes. If you do not like this behavior then please use setoption and provide sas token expiry time of your choice. Our sample send-receive actually has an example usage of this for your reference.

Please let me know if this does not resolve the problem.

**Comment by enchiladaRoja** [comment]
Ok, I´ll be testing today and let you know as soon as I can.

**Comment by enchiladaRoja** [comment]
Hi, so I just let the sample run for the weekend and the reconnection attempts work fine, and the new sas token expiry time that I use work as expected. I think that this new configuration will work with the enviroment that I need.
Thank you for your help.
