### ISSUE TITLE
B3 SKU being throttled to ~750 messages / second

### ISSUE THREAD

**Issue by terrymandin** [Azure/azure-iot-sdk-java#452]
<VERSION>  Windows 10
SR # 119022421000006

My customer is sending a cap on the number of messages they can send to the IoT Hub S3 SKU via the Java SDK at ~ 80 messages / second.

To duplicate I have an IoT Hub configured with a single unit of S3. I have created a .netcore app that sends messages to a **single** device in the hub. I have removed the 'await' functionality, but ensure that no more than 5000 messages are sent every second. I created an ASA job that does a count over a 1 second tumbling window and sends the results to Power BI. I am seeing a 750 messages/second ceiling. I am expecting to see up to 6000 messages per second as per the documentation. What's up?

# Code sample exhibiting the issue:
        private async Task SendEvent()
        {
            string dataBuffer;

            Console.WriteLine("Device sending {0} messages to IoTHub...\n", MessageCount);

            DateTime monitor = DateTime.Now;
            int sent = 0;
            for (int count = 0; count < MessageCount; count++)
            {
                _temperature = s_randomGenerator.Next(20, 35);
                _humidity = s_randomGenerator.Next(60, 80);
                _timestamp = DateTime.Now.ToUniversalTime().ToString();
                dataBuffer = $"{{\"messageId\":{count},\"temperature\":{_temperature},\"humidity\":{_humidity},\"timestamp\":\"{_timestamp}\"}}";
                Message eventMessage = new Message(Encoding.UTF8.GetBytes(dataBuffer));
                if (sent >= 5000)
                {
                    var diff = DateTime.Now.Subtract(monitor);
                    Console.WriteLine("Sent 5000 messages in {0} seconds", diff.TotalSeconds.ToString());
                    int sleepTime = Convert.ToInt16(1000 - diff.TotalMilliseconds);
                    if (sleepTime > 0)
                        System.Threading.Thread.Sleep(sleepTime);
                    sent = 0;
                    monitor = DateTime.Now;
                }
                _deviceClient.SendEventAsync(eventMessage);
                sent += 1;
            }
            System.Threading.Thread.Sleep(600000);
        }

**Comment by timtay-microsoft** [comment]
This code sample looks like it was written in C#, not Java. Could you please file this issue on the [C# SDK issues page](https://github.com/Azure/azure-iot-sdk-csharp/issues) instead? And can you share if you are seeing any exceptions that suggest that the iot hub is thottling you? My first thought here is that even though your code may execute the line 

```C#
_deviceClient.SendEventAsync(eventMessage);
```

 5000+ times, the SDK itself isn't necessarily sending the messages to iot hub as fast as you are calling sendEventAsync. The bottleneck may be the SDK, not the IoT Hub.

**Comment by terrymandin** [comment]
The customer is encountering issues with the Java SDK.  I have asked the customer for permission to share their Java code in this public facing issue.  I provided some C# code that I had created.  

I met with the Microsoft Manufacturing team and they identified some issues with the client side code.  Probably the largest of which is to use AMQP instead of MQTT as MQTT limits the connections.

Ideally we would develop some sample Java gateway code that is capable of sending messages at the scale that the IoT Hub can ingest it.  In this customer's case, we need to be able to send ~5,700 messages / second through the Java SDK.

**Comment by jmbrunskill** [comment]
We are experiencing similar issues, where the Java SDK appears to be a bottle neck for sending data to Iot Edge and/or IoTHub. We maybe be able to provide some Java example code next week assuming we get clearance to share.

**Comment by prmathur-microsoft** [comment]
We are working on fixing this issue on Amqp

**Comment by prmathur-microsoft** [comment]
#314

**Comment by jasmineymlo** [comment]
[release2019-4-10](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2019-4-19) addressed the AMQP connection to basic tier issue and we were able to reach an average of ~700 messages per second on a SINGLE device on Java SDK.  The limit of 6000 messages per second from the Iothub perspective is under the assumption of having multiple devices connection sending messages simultaneously.  Feel free to reopen the issue if you have any concern on this.  Thanks.

**Comment by az-iot-builder-01** [comment]
@terrymandin, @jmbrunskill, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
