### ISSUE TITLE
com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttDeviceTwin.start() doesn't set isStarted property correctly

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/azure-iot-sdk-java#46]
- **OS and version used:** Windows 10 

- **Java runtime used:** 1.8 

- **SDK version used:** 1.0.21 

# Description of the issue:
The method MqttDeviceTwin.start() doesn't set the property isStarted to true after a successful start

# Code sample exhibiting the issue:
    public void start() throws IOException
    {
        if (!isStarted)
        {
            /*
            **Codes_SRS_MQTTDEVICETWIN_25_019: [**start method shall subscribe to twin response topic ($iothub/twin/res/#) if connected and throw IoException otherwise.**]**
             */
            this.subscribe(subscribeTopic);
        }
    }
# Console log of the issue:

**Comment by prmathur-microsoft** [comment]
Hi JMayrbaeurl ,

I have a fix for this issue coming in soon.

Thanks
Priyanka

**Comment by prmathur-microsoft** [comment]
Fix has been checked in @98737ddb9003378ebcfdbf173172f36a02cd0281. Closing this issue.
