### ISSUE TITLE
File upload to iot hub fails with status code TOO_MANY_DEVICES

### ISSUE THREAD

**Issue by dklor** [Azure/azure-iot-sdk-java#461]
- **OS and version used:** Windows 10

- **Java runtime used:** JDK 1.8

- **SDK version used:** iot-device-client:1.15.0

# Description of the issue:
When I'm uploading e. g. 30 files to the iot hub via `deviceClient.uploadToBlobAsync(...)` and the internet connection is lost during this process, after about 2 minutes the `IotHubEventCallback` gets called with the status code `ERROR`, which is not a problem so far. Then, after the internet connection is reestablished, all uploads which were affected by the connection loss and all subsequent calls fail immediately with the status code `TOO MANY DEVICES`. I assume that in this scenario, the iot hub does not free the SAS URIs, which are limited to 10/device, since they are all occupied. How can I solve this?

**Comment by timtay-microsoft** [comment]
Sorry for the delay on this issue, we are still digging into how to solve this issue.

**Comment by gohilbhagirath90** [comment]
i am getting same error on 

api 'com.microsoft.azure.sdk.iot:iot-device-client:1.17.3'

or

  implementation ('com.microsoft.azure.sdk.iot:iot-device-client:1.16.0'){exclude module:'azure-storage'}
    implementation 'com.microsoft.azure.android:azure-storage-android:2.0.0'
    implementation 'org.apache.commons:commons-lang3:3.6'

with above dependency in android

**Comment by timtay-microsoft** [comment]
Right now, there is no way for you to cancel the interrupted file uploads, nor is there a way to continue the file upload after re-establishing connection. We are looking into the possibility of having the SDK recover the file upload once network has been restored.

**Comment by marwaadihu** [comment]
Facing the same issue.

**Comment by timtay-microsoft** [comment]
From the service side, it is by design that the only way a failed file upload will stop counting against your parallel count is by allowing the created SAS uri to expire. As such, there is nothing this SDK can do to fix this issue.

**Comment by az-iot-builder-01** [comment]
@dklor, @gohilbhagirath90, @marwaadihu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by J4cku** [comment]
@timtay-microsoft 
you are saying that it is possible to complete with error status, but what if the method that is supposed to get SAS throws an error (in my case DeviceMaximumActiveFileUploadLimitExceeded, hence IOException - "Sas URI response message had no payload") and I have no correlation id to send error completion message. And even when my SAS keys have very short expiration time, after the moment I start getting the exceptions the device is unusable.
