### ISSUE TITLE
More than one file was found with OS independent path 'thirdpartynotice.txt'

### ISSUE THREAD

**Issue by paugarcia95** [Azure/azure-iot-sdk-java#465]
- **OS and version used:** <VERSION> Windows 10

- **Java runtime used:** <VERSION> 1.8.0_181

- **SDK version used:** <VERSION> 28

# Description of the issue:
This message apears when I use the library version 1.16.0:
`More than one file was found with OS independent path 'thirdpartynotice.txt'`

When I compile my code using this:
`implementation 'com.microsoft.azure.sdk.iot:iot-device-client:1.16.0'`

I've tried to add this on android options, but the error persists:

       packagingOptions {
        exclude "META-INF/MSFTSIG.SF"
        exclude "META-INF/MSFTSIG.RSA"
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'thirdpartynotice.txt'
        exclude 'META-INF/NOTICE.txt'
    }

To avoid the problem I use the version 1.12.0. My question is which is the last stable version and which one should I use?

Thank you!

**Comment by jasmineymlo** [comment]
'com.microsoft.azure.sdk.iot:iot-device-client:1.16.0' should be used and it is the latest stable version.  Take a look at the sample [build.gradle](https://github.com/Azure-Samples/azure-iot-samples-java/blob/master/iot-hub/Samples/device/AndroidSample/app/build.gradle) for your reference.  Did you put the packagingOptions block within the android{ }?  Thanks.

**Comment by paugarcia95** [comment]
I solved my problem doing the following:

I'm working in a project with the main module of the app and another module where I use Azure IoT Hub, let's call them main module and Azure module.

As I was using the Azure IoT Hub library on the Azure module, I had included the following lines on the file build.gradle of this module:

```
packagingOptions {
    exclude "META-INF/MSFTSIG.SF"
    exclude "META-INF/MSFTSIG.RSA"
    exclude 'META-INF/DEPENDENCIES'
    exclude 'META-INF/NOTICE'
    exclude 'META-INF/LICENSE'
    exclude 'META-INF/LICENSE.txt'
    exclude 'META-INF/NOTICE.txt'
    exclude 'thirdpartynotice.txt'
}

lintOptions {
    ignore 'InvalidPackage'
}
```
 
However, the solution was to include this lines on the build.gradle file of the main module, not on the module where the Azure IoT hub library is used. (note that the main module has a dependency of the Azure module)

**Comment by az-iot-builder-01** [comment]
@paugarcia95, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
