### ISSUE TITLE
com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttDeviceTwin.stop() must not be processed when not started yet

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/azure-iot-sdk-java#47]
- **OS and version used:** Windows 10 

- **Java runtime used:** 1.7 

- **SDK version used:** 1.0.21 

# Description of the issue:
When MqttDeviceTwin.stop() gets called without having called MqttDeviceTwin.start() before, the method will try to unsubscribe a topic that wasn't subscribed yet, causing an error. Can be fixed quite easily, by checking the isStarted property (when it's set correctly, see my previous  issue)

# Code sample exhibiting the issue:
    public void stop() throws IOException
    {
        /*
        **Codes_SRS_MQTTDEVICETWIN_25_020: [**stop method shall unsubscribe from twin response topic ($iothub/twin/res/#) and throw IoException otherwise.**]**
         */
        this.unsubscribe(subscribeTopic);
    }
# Console log of the issue:

**Comment by prmathur-microsoft** [comment]
Fix is work in progress . Coming in soon.

**Comment by prmathur-microsoft** [comment]
Fix has been checked in @98737ddb9003378ebcfdbf173172f36a02cd0281.
