### ISSUE TITLE
Provisioning Device pass deviceId at runtime

### ISSUE THREAD

**Issue by rockbird** [Azure/azure-iot-sdk-java#490]
- **OS and version used:** Windows 10

- **Java runtime used:** 1.8.0_202 x64

- **SDK version used:**
provisioning-device-client 1.6.0
provisioning-service-client 1.5.0
iot-device-client 1.17.0
iot-service-client 1.16.2

# Description of the issue:
I'm trying to register many devices at runtime and I want to be able to pass IoT Hub deviceId to the ProvisioningDeviceClient.registerDevice() call, but there is no way; you can only specify it in the Enrollment details:
"You can specify the IoT Hub device ID to use when assigning the device. If no IoT Hub device ID is provided, the registration ID will be used."

Can I use EnrollmentGroup to register a list of devices ?

I tried protocol ProvisioningDeviceClientTransportProtocol.AMQPS with SecurityProviderSymmetricKey

How can I register many devices (50-100k) into my hub in a reasonable time ? Using registryManager.addDevice() from iot-service-client SDK is not a solution either, it takes way too long time to create many devices due to throttling.

My subscription is S1 - Standard.

**Comment by timtay-microsoft** [comment]
When you are using EnrollmentGroups to provision a large number of devices, you will need to create a security provider to pass into the constructor for your ProvisioningDeviceClient. When you create the security provider, you pass in a registration id. That registration id can be chosen arbitrarily, and will be used as the provisioned device's deviceId.

```java
String registrationId = desiredDeviceId;
securityProvider = new SecurityProviderSymmetricKey(derivedSymmetricKey, registrationId);
```

I recommend using DPS, not registry manager for provisioning such a large number of devices. 

Let me know if you are still hitting issues with this DPS flow.

**Comment by rockbird** [comment]
It worked, I was missing the derivedSymmetricKey / desiredDeviceId in case of group enrollment.

I'll try to register many devices and I hope it will scale.

Thank you for you support.

**Comment by timtay-microsoft** [comment]
You are very welcome! Do you have any other questions, or can I go ahead and close this issue?

**Comment by rockbird** [comment]
For this question not.Still takes time to register many devices due to subscription/DPS limits, but that's another topic.

Thanks, you can close it.

**Comment by az-iot-builder-01** [comment]
@rockbird, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
