### ISSUE TITLE
 declare a parent-child relationship between the devices in IoT Hub from IOT device

### ISSUE THREAD

**Issue by haohaowasky** [Azure/azure-iot-sdk-java#494]
Is there a way to declare a parent-child relationship between the devices in IoT Hub from the IoT device ? (not in the portal). 

Now I have it work as an IoT device can auto register, can I also set parent device as well?

**Comment by yzhong94** [comment]
Hi there, are you referring to the ["assign child devices"](https://docs.microsoft.com/en-us/azure/iot-edge/offline-capabilities) for IoT Edge feature?  If so, this is currently available in the C# Service SDK ([commit ID](https://github.com/Azure/azure-iot-sdk-csharp/commit/2705938c873ad2227274dfba480f13883bf46adb#diff-41108a341698508899af777aee0096f4)).  We are in the process of adding this to the Java Service SDK.  @timtay-microsoft will provide an update when it's available.

Please note that this feature is scoped to IoT Edge only.  You can only assign child devices to IoT Edge devices.

**Comment by haohaowasky** [comment]
Yes, I'm looking for Java SDK that can be run on an Android device to assign child devices itself to an IoT edge. Is this on your road map?

**Comment by yzhong94** [comment]
@haohaowasky We envision the capability to assign child devices to live in a backend application.  Do you plan on having this capability on the Android device itself?  Or are you building a backend Java app that assigns an Android device to Edge?  It is not recommended to have your IoT Hub owner connection string on a device.

**Comment by haohaowasky** [comment]
Yes, we plan to having this capability on the Android device itself, let's say we want to assign 100 devices to become a child devices to an IoT edge, we don't wanna manually set them from the backend right? So we would like to build some script to have the devices assign themselves

**Comment by haohaowasky** [comment]
from your provisioning java SDK, we are able to have the android devices register and obtain a connection string by themselves, now just want to add one more configuration to set as an child device

**Comment by yzhong94** [comment]
@veyalla can you take a look at this scenario?

**Comment by yzhong94** [comment]
Right, the connection string you receive from Device Provisioning Service is a device connection string.  To assign child devices, you'd need an IoT Hub owner connection string.

**Comment by veyalla** [comment]
Yi is correct, you need service credentials to set a device as a child of an IoT Edge device. That is generally not something you should keep in the device.

We are looking at enabling a scenario where provisioning of a leaf devices is done by DPS and that flow can sets the device as child of an edge device. FYI: @mrohera

**Comment by yzhong94** [comment]
Thanks!  We do plan on releasing this capability on the Java Service SDK - the work is in progress and you should see the commit for it soon.  We will keep the thread open until then.

**Comment by haohaowasky** [comment]
Thanks please keep us updated!

**Comment by timtay-microsoft** [comment]
This feature has been released as of the latest release, so I'm closing this issue. See 3ba446fd43c7b8313376a90127e0f39d8f3246e4 for details

**Comment by az-iot-builder-01** [comment]
@haohaowasky, @veyalla, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by amit12cool** [comment]
Is this available on NodeJS?

**Comment by abhipsaMisra** [comment]
I would recommend opening an issue [here](https://github.com/Azure/azure-iot-sdk-node/issues), for questions related to the NodeJS client. You can add a reference to this issue for context.
