### ISSUE TITLE
Twins Support for Registry Manager (Java Lang)

### ISSUE THREAD

**Issue by raven2cz** [Azure/azure-iot-sdk-java#5]
Hello,
do you plan implementation of Twins for Registry Manager for Java?
If yes, can you provide some estimation where we can expect the implementation?
Thanks.

**Comment by prmathur-microsoft** [comment]
Yes we are work in progress for this implementation. It should be available by end of February. For tracking progress you can see here - https://github.com/Azure/azure-iot-sdk-java/projects/1

**Comment by tameraw** [comment]
Closing as this is being tracked in project:
https://github.com/Azure/azure-iot-sdk-java/projects/1
