### ISSUE TITLE
Don't use log4j directly for logging - Replace with logging facade slf4j

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/azure-iot-sdk-java#50]
- **OS and version used:** Windows 10 

- **Java runtime used:** 1.8 

- **SDK version used:** 1.0.21 

# Description of the issue:
It's best practice to not use a logging implementation like log4j directly, but use a logging facade instead. Then users of the SDK are not forced to use log4j and go with their own choice. Popular logging facade libraries are Apache Commons logging and slf4j. Since only slf4j is still maintained (new versions for actual JRE runtimes available) I would recommend to use slf4j (see https://www.slf4j.org/ )

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by JMayrbaeurl** [comment]
See last pull request #44 as an example for using this.

**Comment by prmathur-microsoft** [comment]
This issue and #51 will be addressed together once we investigate better logging options.

**Comment by jasmineymlo** [comment]
This is a low priority feature that we are not going to get to.  Please feel free to reopen and submit a PR if interested.
