### ISSUE TITLE
continuous disconnection with two modules in the edge

### ISSUE THREAD

**Issue by grex93** [Azure/azure-iot-sdk-java#506]
Hi everyone, 
I am using one Raspberry pi 3 b + with
Raspbian GNU/Linux 9 (stretch)
openjdk version "1.8.0_181"
azure iot sdk device client for modules 1.17.1 
 
I noticed that after a few minutes a continuous cycle of disconnections and reconnections versus the iothub begins.

With sdk iot-device-client   1.17.0 i have always this problems, both for two modules running on rasbperry edge.
With the new versione 1.17.1 i noticed that only one module has this problem, while the other one works without problems.
I'm Using AMQP protocol versus iothub.
Of course, after the first disconnection, i can't use module twin update form portal anymore. 

I have attached my logs with the previous sdk and the last one ( 17.01) 
[disconnection-with-version-17-0.txt](https://github.com/Azure/azure-iot-sdk-java/files/3142967/disconnection-with-version-17-0.txt)
[disconnection-with-version-17-1.txt](https://github.com/Azure/azure-iot-sdk-java/files/3142968/disconnection-with-version-17-1.txt)

**Comment by timtay-microsoft** [comment]
Can you please share some sample code that you are running that is causing this issue?

**Comment by timtay-microsoft** [comment]
And can you register the connection status callback on your module client instance so that we can see what kind of connectivity exceptions you are getting?

```java
protected static class IotHubConnectionStatusChangeCallbackLogger implements IotHubConnectionStatusChangeCallback
{
    @Override
    public void execute(IotHubConnectionStatus status, IotHubConnectionStatusChangeReason statusChangeReason, Throwable throwable, Object callbackContext)
    {
        System.out.println();
        System.out.println("CONNECTION STATUS UPDATE: " + status);
        System.out.println("CONNECTION STATUS REASON: " + statusChangeReason);
        System.out.println("CONNECTION STATUS THROWABLE: " + (throwable == null ? "null" : throwable.getMessage()));
        System.out.println();

        if (throwable != null)
        {
            throwable.printStackTrace();
        }

        if (status == IotHubConnectionStatus.DISCONNECTED)
        {
            //connection was lost, and is not being re-established. Look at provided exception for
            // how to resolve this issue. Cannot send messages until this issue is resolved, and you manually
            // re-open the device client
        }
        else if (status == IotHubConnectionStatus.DISCONNECTED_RETRYING)
        {
            //connection was lost, but is being re-established. Can still send messages, but they won't
            // be sent until the connection is re-established
        }
        else if (status == IotHubConnectionStatus.CONNECTED)
        {
            //Connection was successfully re-established. Can send messages.
        }
    }
}

...

moduleClient.registerConnectionStatusChangeCallback(new IotHubConnectionStatusChangeCallbackLogger(), new Object());
```

**Comment by timtay-microsoft** [comment]
And do you see similar behavior over any other protocol?

**Comment by grex93** [comment]
> Can you please share some sample code that you are running that is causing this issue?

If you see in my .txt files attached, there is a print for callback with the name testIotHubConnectionStatusChangeCallback, i just print the name of the exception, for example: 
2019-05-03 17:31:59 INFO  testIotHubConnectionStatusChangeCallback:35 - iot hub connection status change with :  DISCONNECTED_RETRYING for NO_NETWORK Unknown transport exception occurred
2019-05-03 17:32:01 INFO  testIotHubConnectionStatusChangeCallback:35 - iot hub connection status change with :  CONNECTED for CONNECTION_OK


Later today I will send you the entire stacktrace. No, i am currently using only AMQP. I'll try the others too, but I need to use AMQP.

Thanks a lot

**Comment by az-iot-builder-01** [comment]
@grex93, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by DeveloperBeginner** [comment]
@grex93 I am facing the same issue. Did you find a solution to this?

**Comment by grex93** [comment]
no, I have disabled  directly. i don't use iot-hub sdk anymore.. 
I am waiting too
