### ISSUE TITLE
UploadToBlobAsync for Java SDK?

### ISSUE THREAD

**Issue by milunko** [Azure/azure-iot-sdk-java#52]
# Description of the issue: File Upload not supported by current version of Java SDK 1.0.16
Hi, I saw that C# version supports UploadToBlobAsync but Java version not. Any chance we can see this feature soon in Java SDK?

Best,
Milos

**Comment by JMayrbaeurl** [comment]
It's already on the TODO list https://github.com/Azure/azure-iot-sdk-java/projects/1

**Comment by prmathur-microsoft** [comment]
Thanks for the message. We are working on it and it shall be available soon. Please follow the projects page to receive updates on progress.

**Comment by tameraw** [comment]
@milunko - I confirm it's in our backlog.
I'll close this one as it's a duplicate of issue #28
