### ISSUE TITLE
connectionState property not visible in com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwinDevice 

### ISSUE THREAD

**Issue by pawankaushal** [Azure/azure-iot-sdk-java#520]
We are building our application on Azure IOT platform and we need to get connection status for a device but unfortunately the property is not available in POJO DeviceTwinDevice.  Please see the feasibility of adding this field. 

PS: I can see the JSON document for a device coming from hub response clearly has the property connectionState.

**Comment by timtay-microsoft** [comment]
You are correct, the SDK should be propagating that field up through the deviceTwinDevice object. I'm working to fix this issue.

**Comment by pawankaushal** [comment]
Thanks for addressing this. Would be much nicer if we can have a milestone/patch release so that we can incorporate the changes quickly?

- Regards
Pawan Kaushal

**Comment by az-iot-builder-01** [comment]
@pawankaushal, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by timtay-microsoft** [comment]
This fix has been checked into master, and we are planning to do a release tomorrow (5/31)

**Comment by pawankaushal** [comment]
> This fix has been checked into master, and we are planning to do a release tomorrow (5/31)

Thanks for the update , what would the version number for the build?

**Comment by pawankaushal** [comment]
ConnectionState coming as null irrespective of state at iot hub as it was not captured in DeviceTwin class. Please see and review the fix.
https://github.com/Azure/azure-iot-sdk-java/pull/535

**Comment by pawankaushal** [comment]
@timtay-microsoft , do you see the possibility of merging my PR and adding your unit tests on top of it?

**Comment by pawankaushal** [comment]
i saw a recent release , but looks like this bug is still not fixed in the current release. We are partners with Azure (lets have a private conversation to discuss this)and out product is based on the IOT platform, would appreciate if you can send us a patch release to work with post merging either PR# 535 or PR # 536.

**Comment by pawankaushal** [comment]
Hi @timtay-microsoft , @jasmineymlo , @davilu , I believe the code is ready to be merged  https://github.com/Azure/azure-iot-sdk-java/pull/535 or https://github.com/Azure/azure-iot-sdk-java/pull/536. Can you please put this into upcoming release? Appreciate a quick reply!

**Comment by timtay-microsoft** [comment]
As of [this release](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2019-09-30_2), this bug has been fixed. As such, I am closing this thread. Thanks for providing the code needed to fix this bug, @pawankaushal!

**Comment by pawankaushal** [comment]
I don't see a mention of PR merge of #535 or #536  in the release notes for the latest release ?
