### ISSUE TITLE
[AMQP_WS] Disconnections after version upgrade

### ISSUE THREAD

**Issue by pizerg** [Azure/azure-iot-sdk-java#521]
- **OS and version used**: Windows 10, Raspbian

- **Java runtime used:** Oracle's 1.8

- **SDK version used:** 1.17.1 / 1.17.2

# Description of the issue:
We've been for a while using release 1.14.2 with AMQP_WS which seemed to be pretty stable, not long ago we decided to upgrade to 1.17.1 as it had some interesting bugfixes and since then we've experienced several daily disconnections (on different devices, different networks, different countries), most of them due to NO_NETWORK (which did not actually happen as we've been monitoring network connectivity on all the devices and rolling back to 1.14.2 prevents the issue).

After that we decided to try the newest 1.17.2 as it was released a couple of days ago and the results are even worse, with 1.17.1 the devices were able to reconnect after few minutes, with 1.17.2 they never reconnect.

In all cases connection was opened using a connection string, operation timeout was set to Long.MAX_VALUE and callbacks were registered for ConnectionStatusChange, MessageReceived and MethodInvoked.

# Console log of the issue:

`2019-05-12 16:09:15,515 AzureIoTHub [azure-iot-sdk-ReconnectionTask] DEBUG: IoTHub connection state callback, status: DISCONNECTED_RETRYING reason: NO_NETWORK`

and for 1.17.2 this shows afterwards:

```
com.microsoft.azure.sdk.iot.device.exceptions.TransportException: Unknown transport exception occurred
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.getTransportExceptionFromEvent(AmqpsIotHubConnection.java:1226)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection.onTransportError(AmqpsIotHubConnection.java:883)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:191)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.IotHubReactor.run(IotHubReactor.java:28)
	at com.microsoft.azure.sdk.iot.device.transport.amqps.AmqpsIotHubConnection$ReactorRunner.call(AmqpsIotHubConnection.java:944)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by timtay-microsoft** [comment]
Are you seeing similar behavior from AMQPS rather than AMQPS_WS? And how often do these errors occur (minutes/hours after first open)? Do you see the same connection failures when your device is just sitting idle (not sending telemetry, not receiving twin/method/C2D messages)?

And, if it isn't private info, can you provide a hub name and device id so that I can look at the server side logs to understand this disconnection better?

I'm mostly interested in the 1.17.2 version right now, for any tests that you run to help debug this issue.

**Comment by pizerg** [comment]
I've set 2 deployments one with AMQPS and the other with AMQPS_WS, both started around 9:45-9:55 UTC.

Will monitor both and let you know, unfortunately I cannot perform the idle test as our deployments are continuously sending data, at least at a rate of 1 message every 4 minutes.

If you need the details for the hub name and device ids I can send them to you via PM or email, let me know which option you prefer.

**Comment by timtay-microsoft** [comment]
Actually, nevermind about the device ids/hub names. I'm seeing some repro's of this issue locally now over AMQPS_WS. I'm checking on AMQPS now, too

**Comment by hellfenix** [comment]
AMQPS_WS -> Disconnected (an never reconnected) at around 3:00 UTC May 23rd
AMQPS -> still running

**Comment by pizerg** [comment]
AMQPS_WS -> Disconnected (an never reconnected) at around 3:00 UTC May 23rd
AMQPS -> still running

**Comment by timtay-microsoft** [comment]
As of device client version 1.17.3, the exception encountered here is now retried, and the connection is recovered. We are still investigating why this exception is occurring in the first place, though.

**Comment by pizerg** [comment]
Performed one overnight test yesterday with client version 1.17.5, the disconnection issue is still happening and it never reconnected, I had to restart the system to recover the connection.

**Comment by timtay-microsoft** [comment]
The amqp layer has changed a lot in recent versions, do you still see any issues after upgrading to the latest library?

**Comment by timtay-microsoft** [comment]
Closing this thread due to lack of activity

**Comment by az-iot-builder-01** [comment]
@pizerg, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
