### ISSUE TITLE
Help wanted - receiving C2D messages from queue

### ISSUE THREAD

**Issue by slgal** [Azure/azure-iot-sdk-java#53]
- **OS and version used:** Windows 10 

- **Java runtime used:** 1.8 

- **SDK version used:** 1.0.20 

# Description of the issue:

Hi everyone, can you help me understand this case.
I created the Android app that receive messages from the cloud and .net console app that send messages to the cloud. When Android device is online I get the messages right after I send it it from console app. Which is perfect. Than I close my app on the Android and send several messages. After that Android app back online I get only latest message I sent from console app. I was not able to find any explanation about it in documentation so asked here.  I add few pictures to better understand my case.

![1](https://cloud.githubusercontent.com/assets/1153279/23955110/ab61fc12-09a1-11e7-957d-ef639805de0d.png)

![2](https://cloud.githubusercontent.com/assets/1153279/23955114/af1dd6fa-09a1-11e7-9731-2f56023716f7.png)

Thanks in advance

**Comment by mamokarz** [comment]
@slgal each protocol are you using (mqtt, http, or amqp)?

**Comment by slgal** [comment]
Mqtt


Надіслано з мого смартфону Samsung Galaxy.
-------- Оригінальне повідомлення --------Від: Marcos Mokarzel <notifications@github.com> Дата: 16.03.17  01:18  (GMT+02:00) Кому: Azure/azure-iot-sdk-java <azure-iot-sdk-java@noreply.github.com> Копія: slgal <slavagalanov@gmail.com>, Mention <mention@noreply.github.com> Тема: Re: [Azure/azure-iot-sdk-java] Help wanted - receiving C2D messages from queue (#53) 
@slgal each protocol are you using (mqtt, http, or amqp)?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Azure/azure-iot-sdk-java","title":"Azure/azure-iot-sdk-java","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Azure/azure-iot-sdk-java"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mamokarz in #53: @slgal each protocol are you using (mqtt, http, or amqp)?"}],"action":{"name":"View Issue","url":"https://github.com/Azure/azure-iot-sdk-java/issues/53#issuecomment-286909865"}}}

**Comment by mamokarz** [comment]
I'll try to reproduce it.

**Comment by prmathur-microsoft** [comment]
As of 1.1.25, I'm able to both send and receive messages on android over MQTT. Can you please check our sample located at https://github.com/Azure/azure-iot-sdk-java/tree/master/device/iot-device-samples/android-sample/app/src/main/java/com/iothub/azure/microsoft/com/androidsample in the current master branch ?

**Comment by prmathur-microsoft** [comment]
We will close it for now. Please let us know if you have any further issues with this and feel free to reopen it.
