### ISSUE TITLE
Unable to send devicemethod command to edge-module

### ISSUE THREAD

**Issue by v-jiq** [Azure/azure-iot-sdk-java#537]
### Scene:
I want to send a devicemethod message to an edge-module listening for devicemethod methods

### platform:
1.Edge-module(listening for devicemethod messages) runs on arm32 platform(Run on iotedge)
2.The APP(sending devicemethod messages) runs on ubuntu16.04-amd64(Run directly on the host machine)

### the module is ok:
A devicemthod message has been sent through vscode to the specified module, which can receive the message normally

### app-sample(send devicemethod message):
The sender uses this sample -- https://github.com/Azure/azure-iot-sdk-java/tree/master/device/iot-device-samples/module-invoke-method-sample

#### Method of use:
I am running it directly to the host machine (ubuntu16.04), replace field ModuleClient client = ModuleClient. CreateFromEnvironment (protocol); with field ModuleClient client = new ModuleClient(connectString,protocol);The connection string is the connection string for the target module(Listen for devicemethod messages).

#### error:
when I run this sample the following error will occurs:
![image](https://user-images.githubusercontent.com/39880470/58944271-0e94b300-87b4-11e9-8eeb-b2eaf5f4e47c.png)

I would like to ask how to solve this problem. In addition, is my method of sending devicemethod to edge-module correct? If not, can provide the correct method

Thanks~

**Comment by timtay-microsoft** [comment]
Can you provide the format of the connection string that you are using?

**Comment by timtay-microsoft** [comment]
And which protocol are you using? And do you see the same behavior from each protocol?

**Comment by v-jiq** [comment]
Sorry for the late reply, I have used MQTT and amqp protocol to have the same problem. When I sent devicemethod message with this sample, edgehub did not print anything. Here is connectString:
<img width="1094" alt="1560223491(1)" src="https://user-images.githubusercontent.com/39880470/59241871-00271b00-8c3c-11e9-8b88-90eef7176ee5.png">

**Comment by v-jiq** [comment]
Hi @timtay-microsoft  Or which Java SDK sample I can use to send messages to the edge module.

I tried another java sample that sent device method -- https://github.com/Azure/azure-iot-sdk-java/tree/master/service/iot-service-samples/device-method-sample ,But still cannot send data to edgemodule. Here is the format of deviceid:
<img width="1210" alt="1560405516(1)" src="https://user-images.githubusercontent.com/39880470/59407338-7ca82e00-8de3-11e9-9d1f-c62d3bf0dcf2.png">

Thanks~

**Comment by timtay-microsoft** [comment]
I don't see anything in your connection strings to indicate that you are connecting your modules to an edgehub. Typically, there is a key pair within it that looks like "GatewayHostName=<ip address of edgehub>". Without it, you are telling the SDK to connect directly to the IotHub.

Are you trying to invoke a method of a module from another module through an edgehub, or through an IotHub? I believe you can only do so through an edgehub.

**Comment by timtay-microsoft** [comment]
Are you still seeing any issues here, @v-jiq ?

**Comment by v-jiq** [comment]
I looked the NOTE of sample code(https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/samples/iothub_client_sample_module_method_invoke/iothub_client_sample_module_method_invoke.c), that "NOTE: This will only work when both modules are running on an IoT Edge device.", so , I just can invoke a mthod from a module to another module belong same edgedev. So,  i want to consult the sdk weather support that iot-device send to a method to a edgemodule .

**Comment by timtay-microsoft** [comment]
There is currently no way for a device to invoke a method on any device/module regardless of if that device/module is tied to an edgehub. The only supported flows are module to module, and module to device. We don't have any plans to add support for invoking methods from device to module

**Comment by v-jiq** [comment]
ok,got it ~

**Comment by az-iot-builder-01** [comment]
@v-jiq, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
