### ISSUE TITLE
Gradle support(native Android) for provisioning

### ISSUE THREAD

**Issue by DeveloperBeginner** [Azure/azure-iot-sdk-java#538]
If one needs to do group provisioning/enrollment in an Android application there is no gradle dependency. There is a gradle dependency available for iot-device-client only. Please add gradle dependency support for provisioning. Also please let me know from which version of Android will the provisioning be supported.

**Comment by DeveloperBeginner** [comment]
As an alternative,  I have built a jar file for provisioning and added it to the libs folder of my Android project. But while I build the code I receive the following RuntimeException: transformClassesWithDexBuilderForDebug
I have enabled multidex, yet I get the same error. Please help me resolve this issue.

Note: I do not have any other library added in my Android application

**Comment by timtay-microsoft** [comment]
> If one needs to do group provisioning/enrollment in an Android application there is no gradle dependency.

We publish packages for provisioning that you should be able to use with the below gradle definitions:

```gradle
dependencies {
...
    implementation ('com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.7.1')
    implementation ('com.microsoft.azure.sdk.iot.provisioning:provisioning-service-client:1.5.2')
...
}

repositories {
    mavenLocal()
    mavenCentral()
}
```

What does your full build.gradle file look like, if the above isn't working for you?

**Comment by DeveloperBeginner** [comment]
@timtay-microsoft Thanks for the reply. When I try to use the above mentioned published package and try to build, I receive the following error:
Build failed.
Caused by: java.lang.RuntimeException

There is no clear information as to why we get RuntimeException.

My full build.gradle files looks like this

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.provisioning"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        checkReleaseBuilds true
        abortOnError false
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    implementation 'com.android.support:multidex:1.0.3'
    implementation ('com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.7.1')

}

**Comment by timtay-microsoft** [comment]
Do you get any sort of stacktrace for that runtimeexception? Does provisioning device client version 1.7.0 work for you?

**Comment by DeveloperBeginner** [comment]
I was able to resolve the issue after updating the Android Studio to the latest version(3.4.1) and the gradle to the latest version(5.1.1). Thanks for your time!

**Comment by az-iot-builder-01** [comment]
@DeveloperBeginner, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
