### ISSUE TITLE
[Service Client] FileUploadNotificationReceiver consumes unbounded file handles during a network outage

### ISSUE THREAD

**Issue by tmb-twx** [Azure/azure-iot-sdk-java#549]
- **OS and version used:** Host OS: Windows 10 , Virtualbox guest: Ubuntu 18.04.2 LTS 

- **Java runtime used:** Tested with Oracle 1.80_201 and amazon corretto 8.202.08.2

- **SDK version used:** iot-service-client 1.17.1

# Description of the issue:
File handles consumed by the application grow unbounded while the network is disconnected.  These steps reproduced the issue every time for me:

1. Start the attached reproducer and wait for the receiver to start
1. Disconnect the network.  I did this by setting the network of my vm to 'Not attached'
1. Wait for the receiver to detect it has been disconnected.  This will take a couple of minutes.  You will see the text _Receive file upload notifications_ scrolling by very fast once this happens

I can now verify that file handles are growing using lsof 
 
>date; lsof -p 9217 | grep TCPv6 | wc -l
Thu Jun 27 12:37:38 EDT 2019
0
date; lsof -p 9217 | grep TCPv6 | wc -l
Thu Jun 27 12:38:12 EDT 2019
1470
date; lsof -p 9217 | grep TCPv6 | wc -l
Thu Jun 27 12:38:13 EDT 2019
1976

If the process hits max file handles (about 10 seconds on my machine)  then the FileUploadNotificationReceiver is dead, along with the rest of our application.  Reconnecting the network does not clean up the TCPv6 socket handles.

# Code sample exhibiting the issue:
A reproducer project is attached as read-file-upload-notification.zip.  It was stolen from the file upload article here:  https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/iot-hub/iot-hub-java-java-file-upload.md

I added some output statements and the ability to slow down the receive loop for my testing.

_The reproducer does not simulate or cause the network outage - this will need to be done some other way._

# Console log of the issue:
>Jun 27, 2019 12:51:32 PM -- 1 --  Receive file upload notifications...
Jun 27, 2019 12:51:43 PM -- 2 --  Receive file upload notifications...
Jun 27, 2019 12:51:53 PM -- 3 --  Receive file upload notifications...
Jun 27, 2019 12:52:05 PM -- 4 --  Receive file upload notifications...
Jun 27, 2019 12:52:08 PM -- 5 --  Receive file upload notifications...
Jun 27, 2019 12:52:08 PM -- 6 --  Receive file upload notifications...
Jun 27, 2019 12:52:08 PM -- 7 --  Receive file upload notifications...
Jun 27, 2019 12:52:08 PM -- 8 --  Receive file upload notifications...
Jun 27, 2019 12:52:08 PM -- 9 --  Receive file upload notifications...
Jun 27, 2019 12:52:08 PM -- 10 --  Receive file upload notifications...
Jun 27, 2019 12:52:08 PM -- 11 --  Receive file upload notifications...
Jun 27, 2019 12:52:08 PM -- 12 --  Receive file upload notifications...
Jun 27, 2019 12:52:08 PM -- 13 --  Receive file upload notifications...
Jun 27, 2019 12:52:08 PM -- 14 --  Receive file upload notifications...
Jun 27, 2019 12:52:08 PM -- 15 --  Receive file upload notifications...
Jun 27, 2019 12:52:08 PM -- 16 --  Receive file upload notifications...
...
Jun 27, 2019 12:52:08 PM -- 80 --  Receive file upload notifications...
Jun 27, 2019 12:52:09 PM -- 81 --  Receive file upload notifications...
...

[read-file-upload-notification.zip](https://github.com/Azure/azure-iot-sdk-java/files/3335896/read-file-upload-notification.zip)

**Comment by timtay-microsoft** [comment]
Thanks for providing steps to repro, we'll try to fix this soon

**Comment by tmb-twx** [comment]
Thanks timtay.  Has there been any progress,  or do you need more information to reproduce/fix?  This is a blocker for us.

**Comment by tmb-twx** [comment]
Is there any update that you can share with me?  We're eagerly awaiting a status.   Thanks!

**Comment by timtay-microsoft** [comment]
Do you see the file handles growing even when connectivity isn't lost? Or do you only see file handles grow when connection is lost for a long time?

**Comment by timtay-microsoft** [comment]
Any extra context helps, and if you'd like to provide a PR, I'd be happy to merge it in for you. 

I suspect the fileuploadnotificationreciever stack isn't properly closing the proton-j connection/session/receiver objects, but I haven't had time to confirm yet

**Comment by tmb-twx** [comment]
Only when connectivity is lost for more than about two minutes.   In the attached reproducer, everything is stable and OK until the "Receive file upload notifications..." message starts happening multiple times per second (at 12:52:08 in the log snip in the ticket above".

**Comment by timtay-microsoft** [comment]
The fix for this issue was released as of service client version 1.20.1, so I'm closing this issue. The amqp layer now always releases the reactor resources once the reactor finishes, regardless of if the reactor threw an exception or finished gracefully

**Comment by az-iot-builder-01** [comment]
@tmb-twx, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
