### ISSUE TITLE
C2D message get the message "java.time.format.DateTimeParseException: Text '2019-07-08T08:52:36.4643757+00:00' could not be parsed at index 27"

### ISSUE THREAD

**Issue by wuwei3** [Azure/azure-iot-sdk-java#551]
- **OS and version used:** <VERSION> Ubuntu 14... 

- **Java runtime used:** <VERSION>  JDK 1.8 

- **SDK version used:** <VERSION> iot-device-client 1.17.1, iot-service-client 1.16.3

# Description of the issue:
   the C2D send message, sometimes get the error "java.time.format.DateTimeParseException: Text '2019-07-08T08:52:36.4643757+00:00' could not be parsed at index 27"

  But I am quiet sure, I don't use any java.time.* in my code

# Code sample exhibiting the issue:
String connectionStringPrimaryKey = factory.getConnectionStringPrimaryKey();

		ServiceClient serviceClient = ServiceClient.createFromConnectionString(connectionStringPrimaryKey, IotHubServiceClientProtocol.AMQPS);
		
		if (serviceClient != null) {
		    serviceClient.open();
		    FeedbackReceiver feedbackReceiver = serviceClient.getFeedbackReceiver();
		    if (feedbackReceiver != null) {
		    	feedbackReceiver.open();
		    }

		    Message messageToSend = new Message(payload);
		    //messageToSend.setDeliveryAcknowledgement(DeliveryAcknowledgement.Full);
		    messageToSend.setDeliveryAcknowledgementFinal(DeliveryAcknowledgement.Full);

		    serviceClient.send(deviceId, messageToSend);
		    log.info("send commands message sent to device, deviceid " + deviceId);

		    FeedbackBatch feedbackBatch = feedbackReceiver.receive(4000);

		    if (feedbackReceiver != null) {
		    	feedbackReceiver.close();
		    }
		    serviceClient.close();
		  }

# Console log of the issue:
    
![1](https://user-images.githubusercontent.com/46955295/60798229-5045be80-a1a3-11e9-9a77-e1ab0adfab53.jpg)

**Comment by timtay-microsoft** [comment]
Can you please provide the full stacktrace associated with that exception?

**Comment by wuwei3** [comment]
> Can you please provide the full stacktrace associated with that exception?

Sorry, I couldn't because I catch up the exception and only print the message

#Code
try {
} catch (Exception e) {
			log.error("send commands failed for deviceId " + deviceId + ", failed message is " + e.getMessage());

		}

i didn't expect this kind of error would throw.

**Comment by timtay-microsoft** [comment]
Can you please alter your code to better capture the full stacktrace? I don't have enough information to investigate this exception.

**Comment by wuwei3** [comment]
Sorry, the code is running on pro env, if no special reason, I can't to change the code and then re-run, it seems that there is no this kind of error in recent days, you could close first.

**Comment by timtay-microsoft** [comment]
Okay, since I can't repro this issue, and you aren't seeing it anymore, I'll go ahead and close this issue

**Comment by az-iot-builder-01** [comment]
@wuwei3, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
