### ISSUE TITLE
Invoking closeNow and open again on DeviceClient over an LTE connection leaves a socket partially closed

### ISSUE THREAD

**Issue by hurtmil** [Azure/azure-iot-sdk-java#552]
- **OS and version used:** <VERSION> 
Android 8.0.1 (Oreo)

- **SDK version used:** <VERSION> 
    implementation 'com.microsoft.azure.sdk.iot:iot-device-client:1.17.3'
    implementation 'com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.7.1'
    implementation 'com.microsoft.azure.sdk.iot.provisioning.security:x509-provider:1.1.3'

# Description of the issue:
In  our use of the DeviceClient and the Azure SDK, we invoke closeNow on DeviceClient if we detect we have lost connectivity over a given adapter (i.e. WIFI or LTE), and we have another transport available, we do this to stop any retries we could have incurred over one transport, to instead start trying a new connection over a different (available transport).

For instance, if we were connected over LTE to the cloud, and we detect the adapter over LTE has gone down (i.e. lost ip address), we check if we have another adapter available (i.e. WIFI), then we call closeNow on DeviceClient, to then call open again to establish a new cloud connection over WIFI now. For our device running Android 8.0.1 (Oreo), when we run through this sequence we detect that socket's are left open which causes new connections to be created leaving the old socket half closed, when we do this a few times we start to leave behind these open sockets consuming software resources.

It appears from our analysis that azure sdk sometimes calls socket.close + sock.shutdowninput  when cleaning a connection after a client invokes closeNow, but in other cases it only calls sock.shutdowninput, leaving the socket still open.

**Comment by hurtmil** [comment]
Adding additional information based on questions we received from Anil Hashia who is helping us from Microsoft tech support.

**QUESTION:** Does the same issue happen on WLAN if your cellular data connection is disabled all time and vice versa ? Any chance you were able to reproduce it on Windows or Linux ?

**ANSWER:** We only see the issue happening over LTE, meaning if we go through closeNow/Open sequence on the LTE adapter repeatedly, we'll see the socket not properly closed, if we do the same sequence over WIFI then we see that the socket is properly closed. One theory we have is the timing on how the adapter down is detected leading our application to call closeNow on the DeviceClient, here is the difference we see between the two adapters:
- WIFI OFF: Azure SDK detects disconnect and reports DISCONNECTED_RETRYING, about 100ms later we detect wifi went down and call closeNow.
- LTE OFF: Our app detects lte went down and calls closeNow, so we never see Azure SDK reporting DISCONNECTED_RETRYING, it will simply be closed because of the app calling closeNow on DeviceClient.

**QUESTION:** How are you determining the there is a socket leak ? Do you run any tool ?

**ANSWER:** We use our own proprietary security provider instead of default Android/Java security providers, in that component we can see whether a socket was fully closed on partially closed.

**QUESTION:** Do you have step by step reproduction steps here ?

**ANSWER:**
1.- On an Android device connect app with azure sdk to the cloud using DeviceClient.
2.- Then turn mobile data off on the device to bring the LTE network adapter down, have the app call closeNow before the SDK reports DISCONNECTED_RETRYING (need the app listening to LTE connectivity events from android (i.e. onLost implementation from Android's connectivity manager).
3.- Verify through Azure SDK debugging/logs that the SDK is not fully closing the socket associated with the connection (i.e. socket.close is not invoked but socket.shutdowninput is called).

**Comment by timtay-microsoft** [comment]
Which protocol is your device client instance using?

**Comment by timtay-microsoft** [comment]
If you are using Mqtt, this bug may be related to [this bug](https://github.com/eclipse/paho.mqtt.java/issues/467) in our mqtt client. That issue is resolved by upgrading to version 1.2.1, but as discussed in other issues threads, this SDK cannot upgrade to 1.2.1. 

For testing purposes, is there any way that you can try forcing your application to use Mqtt paho version 1.2.1 rather than our current dependency 1.2.0?

**Comment by timtay-microsoft** [comment]
A member of the MQTT Paho team is actively looking into the bug in Paho 1.2.1 that was preventing us from upgrading our dependency. We plan on updating and releasing our SDK as soon as that new Paho version becomes available. That new version of Paho should resolve this issue.

**Comment by timtay-microsoft** [comment]
As of [this release](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2019-09-30_2), the SDK now uses the latest version of Paho 1.2.2 which fixes this bug. As such, I am closing this thread

**Comment by az-iot-builder-01** [comment]
@hurtmil, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
