### ISSUE TITLE
Azure JSON standard key prefix for read only properties/tags does not serialize properly using Jackson  

### ISSUE THREAD

**Issue by coltonf93** [Azure/azure-iot-sdk-java#554]
I am attempting to serialize the DeviceTwinDevice object using Jackson and ran into an issue with default readonly keys prefixed with a `$` [as defined here ](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#device-twin-metadata). This caused the [Pair object's constructor](https://github.com/Azure/azure-iot-sdk-java/blob/39d14a0e7c065f2ed81a9d05199c1f1a6993374e/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/Pair.java#L14) to throw [an exception](https://github.com/Azure/azure-iot-sdk-java/blob/39d14a0e7c065f2ed81a9d05199c1f1a6993374e/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/Pair.java#L29). I am a little confused as to why the Pair constructor and the [documented standards](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#device-twin-metadata) conflict with each other in regards to the readonly prefix. 

- **OS:** Windows 10 <VERSION> 

- **Java:** JDK 1.8.0 <VERSION> 

-  **Azure IOT SDK:** 1.15.1 <VERSION> 
 
- **Jackson Databind:** 2.8.10

# Description of the issue:
As stated above, the default readonly properties don't serialize properly using Jackson due to an exception thrown in the [constructor of the Pair object](https://github.com/Azure/azure-iot-sdk-java/blob/39d14a0e7c065f2ed81a9d05199c1f1a6993374e/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/Pair.java#L24).

That being said this does not occur when the java object is created or when it is [serialized](https://github.com/Azure/azure-iot-sdk-java/blob/39d14a0e7c065f2ed81a9d05199c1f1a6993374e/service/iot-service-client/src/main/java/com/microsoft/azure/sdk/iot/service/devicetwin/DeviceTwinDevice.java#L519) in a print statement . `System.out.println(deviceTwin);`

![image](https://user-images.githubusercontent.com/2908733/61152820-07e21580-a4af-11e9-89cb-b6e0035e267f.png)

# Console log of the issue:
`ERROR Error: Uncaught (in promise): Could not write JSON: Key cannot contain illegal unicode control characters '.', '$', ' '; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Key cannot contain illegal unicode control characters '.', '$', ' ' (through reference chain: com.....SomeDevice["deviceTwinDevice"]->com.microsoft.azure.sdk.iot.service.devicetwin.DeviceTwinDevice["tags"])
    at resolvePromise (VM7311 polyfills.js:3728)
    at resolvePromise (VM7311 polyfills.js:3685)
    at VM7311 polyfills.js:3789
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (VM7311 polyfills.js:3320)
    at Object.onInvokeTask (VM7313 vendor.js:62829)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (VM7311 polyfills.js:3319)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (VM7311 polyfills.js:3092)
    at drainMicroTaskQueue (VM7311 polyfills.js:3498)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (VM7311 polyfills.js:3399)
    at invokeTask (VM7311 polyfills.js:4641)`

**Comment by datoga** [comment]
Is maybe the same as https://github.com/Azure/azure-iot-sdk-java/issues/522?

**Comment by coltonf93** [comment]
Yeah that appears to be the same issue. Furthermore the tags that were causing the problem are no longer being passed to the application. I didn't change anything so they most likely updated the cloud service. This issue seems to be resolved.

**Comment by az-iot-builder-01** [comment]
@datoga, @coltonf93, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
