### ISSUE TITLE
Is Module0 bound to lose? What exactly does this mean?

### ISSUE THREAD

**Issue by locedubo** [Azure/azure-iot-sdk-java#556]
is moduleId0，moduleId1，configurationId bound to lose? What exactly does this mean?

**Comment by az-iot-builder-01** [comment]
@locedubo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
