### ISSUE TITLE
mqtt-dup property handling

### ISSUE THREAD

**Issue by ewertons** [Azure/azure-iot-sdk-java#557]
Filing this issue on behalf of @Draczeck, which was incorrectly filed under the C# SDK repo.
Please refer to https://github.com/Azure/azure-iot-sdk-csharp/issues/329 for details in previous conversation.

-------

# Setup Description
In my company's setup we use set of services (written in Java + Spring) running as Docker swarm containers. One of these services takes care of processing messages from IoT Hub, augmenting them and dispatching them to their respective destinations (mostly Service Bus queues).

When an event is read from IoT Hub, it is read by [Event Processor Host](https://github.com/Azure/azure-event-hubs-java/tree/dev/azure-eventhubs-eph) and all of its application properties are copied while system properties are ignored apart from sender device ID.

When a message is sent to the receiver's queue, the [Spring's JmsTemplate](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jms/core/JmsTemplate.html) is used and BytesMessage is created with the payload and properties read from the initial event's application properties as well as properties collected during message augmentation are assigned to it as String properties.

# Problem Description
Sometimes when trying to send the message via JMS tools to the Service Bus queue we get following JMSException:
> Identifier contains invalid JMS identifier character '-': 'mqtt-dup'

After escallation of the topic today with MS support technician **Enes Uysal** we found there is problem in the [Util class](https://github.com/Azure/azure-iot-sdk-csharp/blob/d7a5ddd734c635479e63a2732ac5bec3dc7543c1/device/Microsoft.Azure.Devices.Client/Transport/Mqtt/Util.cs) on line 156. The _DupProperty_ cannot be treated as a applicationproperty, but has to be treated as one of the system properties instead.

If any application property slips from the IoT Hub and is later processed by different technology it may cause serious trouble. In this case the solution of reading IoT Hub messages as Event Hub events and later dispatching them through JMS compatible technology is rendered invalid.

Please consider making any internal message property a system property to prevent similar problems from hapenning in the future.
Thanks

**Comment by timtay-microsoft** [comment]
Closing this due to unclear relevancy and lack of interest
