### ISSUE TITLE
Follow package name guidelines - only lowercase characters

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/azure-iot-sdk-java#56]
- **OS and version used:** Windows 10 

- **Java runtime used:** 1.8 

- **SDK version used:** 1.0.21 

# Description of the issue:
Please follow common best practices and guidelines for package naming (http://www.oracle.com/technetwork/java/codeconventions-135099.html ). E.g. Package 'com.microsoft.azure.sdk.iot.device.DeviceTwin' should be renamed to 'com.microsoft.azure.sdk.iot.device.devicetwin'.

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by tameraw** [comment]
@JMayrbaeurl - This will be a breaking change at this point.
We could consider once we have a LTS for this branch.

**Comment by timtay-microsoft** [comment]
We have opted to not introduce this breaking change to out existing pacakges, so I'm closing this issue. We will keep this guideline in mind for any new packages we create.

**Comment by az-iot-builder-01** [comment]
@JMayrbaeurl, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
