### ISSUE TITLE
Messages from C2D keeps repeating at Device client side while using mqtt_ws

### ISSUE THREAD

**Issue by Kbhargav04** [Azure/azure-iot-sdk-java#565]
Using Ubuntu 16.04.3

Java runtime used: 1.8.0_181 OpenJDK

SDK version used: 1.17.2

# Description of the issue:
DeviceClient callback is blocked by repated messages and throws below exception.
ERROR IotHubReceiveTask:76 - com.microsoft.azure.sdk.iot.device.exceptions.TransportException: java.lang.IllegalArgumentException: Provided message cannot be acknowledged because it was already acknowledged or was never received from service: java.lang.IllegalArgumentException: Provided message cannot be acknowledged because it was already acknowledged or was never received from service
DEBUG IotHubReceiveTask:39 - Exception on receiving queued messages to IoT Hub
com.microsoft.azure.sdk.iot.device.exceptions.TransportException: java.lang.IllegalArgumentException: Provided message cannot be acknowledged because it was already acknowledged or was never received from service
	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.sendMessageResult(MqttIotHubConnection.java:436)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.acknowledgeReceivedMessage(IotHubTransport.java:551)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.handleMessage(IotHubTransport.java:438)
	at com.microsoft.azure.sdk.iot.device.transport.IotHubReceiveTask.run(IotHubReceiveTask.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Provided message cannot be acknowledged because it was already acknowledged or was never received from service
	... 11 more

# Code sample exhibiting the issue:
public class AzureDeviceClientCallBack implements MessageCallback {
	final static Logger LOGGER = Logger.getLogger(AzureDeviceClientCallBack.class);
	private static AzureDeviceClientCallBack instance = null; 
	private AzureDeviceClientCallBack() {
		super();
	}
	
	public static synchronized AzureDeviceClientCallBack getAzureDeviceClientCallBack() {
		if (instance == null) {
			instance = new AzureDeviceClientCallBack();
		}
		
		return instance;
	}

	public IotHubMessageResult execute(Message message, Object arg1) {
		LOGGER.info("Received message with content: " + new String(message.getBytes(), Message.DEFAULT_IOTHUB_MESSAGE_CHARSET));

		String msg = new String(message.getBytes(), Message.DEFAULT_IOTHUB_MESSAGE_CHARSET);
		LOGGER.info("In AzureDeviceClientCallBack execute(), message: " + msg);
		//Before Sending to execute...
		
		try {
                                     system.out.println(msg);
		}
		catch (Exception e) {
			LOGGER.error("Error in AzureDeviceClientCallBack message", e);
		}

		return IotHubMessageResult.COMPLETE;
	}

}

**Comment by timtay-microsoft** [comment]
Can you try upgrading to the latest version of the SDK?

```
<dependency>
  <groupId>com.microsoft.azure.sdk.iot</groupId>
  <artifactId>iot-device-client</artifactId>
  <version>1.17.5</version>
</dependency>
```

**Comment by Kbhargav04** [comment]
@timtay-microsoft 
upgraded Device client version to 1.17.5.
Able to reproduce the same issue.

**Comment by timtay-microsoft** [comment]
Is your device seeing any disconnection events prior to you seeing this error?

**Comment by Kbhargav04** [comment]
@timtay-microsoft  if any disconnections are happening, we are checking the status in  AzureDeviceClientConnectionStatusChangeCallBack  and reinitiating the Device client.
there can be many disconnections and reconnections. At one point of time we encounter this error.

**Comment by davilu** [comment]
@Kbhargav04  Could you please share the sample code? It will help us how to repro this issue. Thanks.

**Comment by Kbhargav04** [comment]
[Microsoft.zip](https://github.com/Azure/azure-iot-sdk-java/files/3477275/Microsoft.zip)

**Comment by anhashia** [comment]
@Kbhargav04  : Avoid recreating **new**  DeviceClient object on connection loss scenario in the callback related to connection status change . Use the same DeviceClient object and let underlying transport layer take care of retry using the **existing** DeviceClient object.

**Comment by timtay-microsoft** [comment]
It is okay to recreate a new Device Client instance after a previous one has disconnected, but it is not safe to create that device client instance on the same thread that is given in the connection status update callback. Doing so will not allow the old device client to clean up properly, and may cause the state management issues that you are seeing. 

The callback should only be used for logging, or for spawning off new threads to handle creating a new device client, or opening the old device client again. To minimize state issues, I recommend re-opening the existing device client rather than creating a new one.

**Comment by Kbhargav04** [comment]
Hi @anhashia @timtay-microsoft your suggestion is not working in real time. we cannot wait for IotHub to reconnect , the issue repeats if we use closenow() and open new device client. need your help in resolving this.

**Comment by abhipsaMisra** [comment]
As Tim has mentioned above, the device client instance should not be created in the same thread on which the callback returns. The following call in your sample should be triggered from a new thread:
```
AzureDeviceClientManager.getInstance().createDeviceClient();
```
I have a sample here that demonstrates the device reconnection behaviour:
https://github.com/abhipsaMisra/azure-iot-sdk-java/tree/reconnectSample/device/iot-device-samples/device-reconnection-sample

**Comment by Kbhargav04** [comment]
@abhipsaMisra  i will try this out , but it should not make much of a difference running it in different thread.

**Comment by anhashia** [comment]
@Kbhargav04  : I assume your testing went well.. Closing this. If you see issue again please feel free to reopen
