### ISSUE TITLE
device twin callback not getting triggered/notified to device client

### ISSUE THREAD

**Issue by THANOJKUMAR** [Azure/azure-iot-sdk-java#572]
Description of the issue:

Device twin behavior is awkward and callback function is not getting triggered when device twin  desired properties are updated.  
Azure device client SDK version used :1.17.5.

**Issue Description:** we are currently working one sensor project where we need to updated our gateway device firmware .we have used startDeviceTwin(azureclient.startDeviceTwin(deviceTwinStatusCallback, deviceTwinStatusCallbackContext, genericPropertyCallBack, genericPropertyCallBackContext) function to get device twin update but this call back function is getting called for very first where connection is established later any changes in device twin desired properties is not getting reflected in device client.

**Comment by timtay-microsoft** [comment]
After you call startDeviceTwin, are you also calling subscribeToDesiredProperties? There is a sample that you can take reference from that shows how to use it [here](https://github.com/Azure/azure-iot-sdk-java/blob/5383561eeebd6191f6251163d62421d097938828/device/iot-device-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java#L216)

Simply calling startDeviceTwin is not enough for you to received desired property updates

**Comment by THANOJKUMAR** [comment]
Hi timtay

Thanks for update it's worked for me .

IAM in interested to know the difference between start device and subscribetwindesiredproperties.

Is it like start device twin will called when there is new device client connected /after any connection loss/reconnection and subscribetwindesiredproperies will get called when there is change in desired properties.

**Comment by timtay-microsoft** [comment]
Glad to hear it!

StartTwin opens the data flow between your client and iothub, and subscribe to desired properties tells the SDK which properties you are interested in getting callbacks for. It is mandatory for you to call StartTwin before doing any twin operations, but you don't need to subscribe to desired properties if you only want to send reported properties.

The callbacks you provide in SubscribeToDesiredProperties should only be called when the SDK receives an update to your property. It should not fire due to connection loss/recovery.

**Comment by timtay-microsoft** [comment]
I'm going to close this issue since you have twin working now. Feel free to open another issue if you still have any further questions.

**Comment by az-iot-builder-01** [comment]
@THANOJKUMAR, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by Vishwas-75** [comment]
s
