### ISSUE TITLE
401002 CA certificate not found - SDK - Microsoft.Azure.Devices.Provisioning.Client

### ISSUE THREAD

**Issue by BhupalPatil** [Azure/azure-iot-sdk-java#573]
OS - Windows 10
.net Environment - .net core 2.1
SDK - Microsoft.Azure.Devices.Client - 1.21.0
Microsoft.Azure.Devices.Provisioning.Client - 1.4.0
Microsoft.Azure.Devices.Provisioning.Transport.Amqp - 1.1.9
Microsoft.Azure.Devices.Provisioning.Transport.Http - 1.1.6
Microsoft.Azure.Devices.Provisioning.Transport.Mqtt - 1.1.8

# Description of the issue:
I'm trying to conect simulated device (.net core console app) to IOT hub via azure Device Provisioning Service. this is based on x.509 cetificates (root+ interimidiate certificate).

I created the enrollment group ok, then uploaded the root certificate and completed verification.

After that generated the device certificate from root certificate and tried to connect to IOT hub using sample code from below link:

https://github.com/Azure-Samples/azure-iot-samples-csharp/tree/master/provisioning/Samples/device/X509Sample

After having all setup when I tried to connect to IOT bub I'm getting below error, tried all protocol - Amqp,Http,Mqtt...

Microsoft.Azure.Devices.Provisioning.Client.ProvisioningTransportException
  HResult=0x80131500
  Message={"errorCode":401002,"trackingId":"408d5ad7-aa7c-45a1-b19a-e4af41ccf54b","message":"CA certificate not found.","timestampUtc":"2019-08-23T09:17:53.762099Z"}
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

private static string s_idScope = "0ne00074417";
private const string GlobalDeviceEndpoint = "global.azure-devices-provisioning.net";
private static string s_certificateFileName = "simulateddevicecert.pfx";

anything missing in the setup that is causing this error?
also I there any rest api exposed by azure DPS to register device (instead of using Azure Devices/Client SDK)

**Comment by timtay-microsoft** [comment]
You seem to be using the C# SDK, not the Java SDK. Since this is the issues page for the Java SDK, I'm closing this issue as off-topic. I recommend filing this issue on [this](https://github.com/Azure/azure-iot-sdk-csharp/issues) page instead.

**Comment by az-iot-builder-01** [comment]
@BhupalPatil, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by timtay-microsoft** [comment]
I recommend making sure that you have uploaded the root certificate to your DPS instance via the Azure portal, first. This walkthrough should help you out: https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509-csharp

**Comment by BhupalPatil** [comment]
@Timtay-microsoft, Thanks for pointing to right page. I tried to trace this issue further and created new issue with latest finding : https://github.com/Azure/azure-iot-sdk-csharp/issues/1040

Thanks.
Bhupal
