### ISSUE TITLE
Service client apparently can send an invalid eTag and it still updates the twin.

### ISSUE THREAD

**Issue by anthonyvercolano** [Azure/azure-iot-sdk-java#574]
I tried running a java service client with an invalid eTag and it worked.

Do a patch with an eTag of 'abc' (which can never be correct).

**Comment by timtay-microsoft** [comment]
The SDK needs to surround the etag values with quotes for the iot hub to interpret them correctly

**Comment by barustum** [comment]
Synced up with a couple of team members. We decided to hold off on this fix as it might introduce some complexity for our developers, not to mention it might introduce breaking changes. We gave this issue a lower priority, hence we will address this fix as an enhancement once it's at a higher priority.

**Comment by timtay-microsoft** [comment]
Just a quick status update: We plan on doing a complete revamp of the iothub service client in the coming months. During that process, we will fix this issue

**Comment by timtay-microsoft** [comment]
As per the above, this issue will not be fixed in this codebase. We will have a separate codebase for this revamp of our service client.

**Comment by az-iot-builder-01** [comment]
@anthonyvercolano, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
