### ISSUE TITLE
Wrong CALLING_METHOD_NAME_DEPTH of com.microsoft.azure.sdk.iot.device.CustomLogger

### ISSUE THREAD

**Issue by slgal** [Azure/azure-iot-sdk-java#58]
- **OS and version used:** Android 4.4.2 KitKat API 19  

- **Java runtime used:** 1.8 

- **SDK version used:** 1.0.20 

```
//CustomLogger usage
logger.LogInfo("SAS Token is created successfully, method name is %s ", logger.getMethodName());

//com.microsoft.azure.sdk.iot.device.CustomLogger.java
//Implementation of CustomLogger.getMethodName
 private static final int CALLING_METHOD_NAME_DEPTH = 2;

public String getMethodName()
    {
        return Thread.currentThread().getStackTrace()[CALLING_METHOD_NAME_DEPTH].getMethodName();
    }

```
While correct name is in depth 3. See picture

![c2d41e19676d16b5f7d8736804f046a4](https://cloud.githubusercontent.com/assets/1153279/24097541/f23ba68a-0d6e-11e7-8792-e2418b0e9790.png)

![631370fa62840c105b241bd77c9a2918](https://cloud.githubusercontent.com/assets/1153279/24097772/07159042-0d70-11e7-87e2-f43a4f09b232.png)

**Comment by JMayrbaeurl** [comment]
Yes. You are right. I just worked on the logging approach of the SDK and figured out the same problem. But I'm really not sure if we should do it this way, because log4j can do this directly with its %I log4j conversion pattern. I personally prefer to add in the name of the method manually, because both ways of getting the method name (via stacktrace or conversion pattern) are known to be very slow!

**Comment by tameraw** [comment]
@slgal - Thanks for reporting this issue. Can you please submit a quick PR for this change?

**Comment by JMayrbaeurl** [comment]
Did some testing with the provided unit test and it works as expected. Obvisouly there are cases where the method name is at position 2 in the stack trace array and others with a position of 3. Therefore please remove the getMethodName method of CustomLogger and have it entered manually in each log string message.

**Comment by timtay-microsoft** [comment]
We are actively working on enhancing our logging within the device client right now, and should have the fix out soon.

**Comment by timtay-microsoft** [comment]
As of [this release](https://github.com/Azure/azure-iot-sdk-java/releases/tag/2019-09-30_2) we no longer explicitly log the method name in this way, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@slgal, @JMayrbaeurl, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
