### ISSUE TITLE
Javadoc Improvements

### ISSUE THREAD

**Issue by IvanBoychevMarinov** [Azure/azure-iot-sdk-java#588]
**Setup (please complete the following information if applicable):**
 - OS: Windows - not relevant
 - IDE : Java 8 - not relevant
- iot-service-client 1.17.1, iot-device-client 1.17.5
 

# Description of the issue:
Javadoc improvement. This specific query concerns the RegistryManager and its method **getDevice(String deviceId)**. In the javadoc it states that _...IotHubException - This exception is thrown if the response verification failed..._. I had to look through the log files and deeper inside the code and assume that  if the exception is of type IoTHubNotFoundException this should mean that the device is missing. 

Besides of this, I think a deep review and refinement of the javadoc would not hurt. There are several mehtods for which the JavaDoc just restates the method name like DeviceClient.startDeviceTwin whose java doc states _Starts the device twin._ Well there is some meaningful information - it states that two of the four parameters can not be null, so I got this going for me, which is nice.

I can not remember all of the java docs that were not clear enough.

# Code sample exhibiting the issue:
 /**
     * Starts the device twin.
     *
     * @param deviceTwinStatusCallback the IotHubEventCallback callback for providing the status of Device Twin operations. Cannot be {@code null}.
     * @param deviceTwinStatusCallbackContext the context to be passed to the status callback. Can be {@code null}.
     * @param genericPropertyCallBack the PropertyCallBack callback for providing any changes in desired properties. Cannot be {@code null}.
     * @param genericPropertyCallBackContext the context to be passed to the property callback. Can be {@code null}.     *
     *
     * @throws IllegalArgumentException if the callback is {@code null}
     * @throws UnsupportedOperationException if called more than once on the same device
     * @throws IOException if called when client is not opened
     */
    public void startDeviceTwin

**Comment by timtay-microsoft** [comment]
This is a fair ask. We will try to do a scrub through our Javadocs and make them more useful and informative.

**Comment by timtay-microsoft** [comment]
The javadocs in our SDK have improved substantially since this issue was filed. Considering there is no "final" state of the SDK's javadocs, I'm going to close this issue.

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
