### ISSUE TITLE
azure-iot-sdk-java/tree/master/device POM wrong target and source version 

### ISSUE THREAD

**Issue by jimbouki** [Azure/azure-iot-sdk-java#59]
Look at lines 26 and 27. This needs to be 1.8 and not 1.7
https://github.com/Azure/azure-iot-sdk-java/blob/master/device/pom.xml

I need to have both 1.7 and 1.8 on my machine with JAVA being set to 1.7 by default. Because of the POM being setup as it is I would need to change my java path I build this project and then change it back every single time. This is terrible and unusable.

**Comment by JMayrbaeurl** [comment]
Why should it be 1.8? It's quite important to have it as 1.7 otherwise we would force anyone to use Java 8 on SDKs without support for 7. I'm using Eclipse and Maven and it works without problems!

**Comment by jimbouki** [comment]
I have both JDKs on my machine which is a PC. The JAVA_HOME on my machine needs to be pointed to 1.7. Also, it should be 1.8 because I am being forced to change my JAVA_HOME to get it to work.

**Comment by jimbouki** [comment]
I understand. You wish to keep build the project as Java 7 to make it more compatible. Nevertheless, the surefire plugin causes the user to have to use Java 8 to build.
