### ISSUE TITLE
Documentation has dead links

### ISSUE THREAD

**Issue by owen2** [Azure/azure-iot-sdk-java#590]
# Description of the issue:
The links on the page https://github.com/Azure/azure-iot-sdk-java/tree/master/provisioning/provisioning-samples/service-enrollment-sample are pointing to github repos that are either gone or private.

**Comment by timtay-microsoft** [comment]
Good catch, we'll try to update those links soon

**Comment by timtay-microsoft** [comment]
Closing this issue as we have fixed those links as of [this](https://github.com/Azure/azure-iot-sdk-java/commit/33c5c69c7b60000141d58f7be84c57e592af62bf) commit

**Comment by az-iot-builder-01** [comment]
@owen2, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
