### ISSUE TITLE
Documentation links broken

### ISSUE THREAD

**Issue by hegate** [Azure/azure-iot-sdk-java#6]
I’m trying to follow the Java SDK sample. I’m on this page https://github.com/azure/azure-iot-sdk-java , then I click on Simple send sample and I don’t get any instructions. Just another folder to finally find the code.

https://github.com/Azure/azure-iot-sdk-java/tree/master/device/samples/send-event 

Is this supposed to work this way?

Also, the Run Java Sample link seems like it suffered some trouble on the migration, cause I get a 404. https://github.com/Azure/azure-iot-sdk-java/blob/doc/get_started/java-run-sample.md

**Comment by olivierbloch** [comment]
Hi @hegate 
I have just pushed updates to the readmes that address this issue.
Let us know if you are still seeing things out of place in here.
thanks
