### ISSUE TITLE
azure-iot-sdk-java/tree/master/device package names to not match folder hierarchy

### ISSUE THREAD

**Issue by jimbouki** [Azure/azure-iot-sdk-java#60]
Take a look at line 4 of https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/device-twin-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/DeviceTwinSample.java. This name does not match with the folder structure as a result the project is broken in my ide. Please fix ASAP. We cannot use like this. Moreover the problem is covered up my the POM file on line 31 https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/device-twin-sample/pom.xml where the package name is changed during the packaging phase.

**Comment by JMayrbaeurl** [comment]
I've reported the same in issue #55 . But it was classified as enhancement and not as bug. Therefore I'm having big troubles using my favorite IDE (Eclipse)

**Comment by jimbouki** [comment]
Cool

**Comment by jimbouki** [comment]
The problem came back with tests.unit.com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTest. It is not a deal breaker but I often find myself having to hack the code so it is not all red in eclipse and then stash and unstash when needed. Nevertheless, an IDE that does not scream at you, which is what I suspect even though I can likely find out from your gitignore file, is not a good IDE. I am sorry for my sharpness but this should not be the norm. If the IDE is screaming red I blame the code. The code should be in pristine condition when presented to any IDE industry standard IDE such as Eclipse.

**Comment by prmathur-microsoft** [comment]
I agree with the problem you are having. Currently we use IntelliJi where we don't see any trouble with IDE and also moven doesnot complain either and hence the code is that way. As most of the community users use eclipse, we will make sure in future to make it compatible with eclipse as well. For now you can leave this open until we fix this issue.

**Comment by prmathur-microsoft** [comment]
#55

**Comment by prmathur-microsoft** [comment]
This issue is now fixed as of check in 4c5ce0979f108a58370006b1d1b3d5f94fa0b40d.

**Comment by prmathur-microsoft** [comment]
Maven package containing the fix is released now. Please give it a try and feel free to reopen if you see further issues.
