### ISSUE TITLE
uploadToBlobAsync hangs with log message "Automatic Reconnect Successful"

### ISSUE THREAD

**Issue by tianhai-liu** [Azure/azure-iot-sdk-java#601]
**Describe the bug**
When uploading a zip file (<=3 MB) using the `DeviceClient.uploadToBlobAsync` method, the uploading process hangs (at least no invoke of `IotHubEventCallback.execute` in 2 hours after starting the uploading process) and the Azure internal logger keeps printing following messages periodically:

> FINE: null: Check schedule at 1,564,727,590,274
> FINE: Dev01: checkForActivity entered
> FINE: Dev01: ping needed. keepAlive=230,000 lastOutboundActivity=1,564,727,360,306 lastInboundActivity=1,564,727,361,053
> FINE: Dev01: key=Ping message=PINGREQ
> FINE: Dev01: key=Ping token=org.eclipse.paho.client.mqttv3.MqttToken@6f8439c4
> FINE: Dev01: notifying queueLock holders
> FINE: Dev01: Schedule next ping at 230,000
> FINE: Dev01: new work or ping arrived
> FINE: Dev01: network send key=Ping msg=PINGREQ
> FINE: Dev01: sent bytes count=2
> FINE: null: Sent PINGREQ
> FINE: Dev01: key=Ping
> FINE: Dev01: > key=Ping
> FINE: Dev01: ping sent. pingOutstanding: 1
> FINE: Dev01: wait for new work or for space in the inflight window
> FINE: Dev01: received bytes count=1
> FINE: null: Automatic Reconnect Successful: PINGRESP msgId 0
> FINE: Dev01: received key=0 message=PINGRESP msgId 0
> FINE: Dev01: >key=Ping response=PINGRESP msgId 0 excep=null
> FINE: Dev01: >key=Ping response=PINGRESP msgId 0 excep=null
> FINE: Dev01: keyPing, msg=PINGRESP msgId 0, excep=null
> FINE: Dev01: new workAvailable. key=Ping
> FINE: Dev01: key=Ping
> FINE: Dev01: ping response received. pingOutstanding: 0
> FINE: Dev01: network read message
> FINE: Dev01: callback and notify for key=Ping
> FINE: Dev01: received key=0 token=org.eclipse.paho.client.mqttv3.MqttToken@6f8439c4 message=PINGRESP msgId 0
> FINE: Dev01: >key=Ping response=PINGRESP msgId 0 excep=null
> FINE: Dev01: notify spaceAvailable
> FINE: Dev01: wait for workAvailable
>
> FINE: null: Check schedule at 1,564,727,820,471
> FINE: Dev01: checkForActivity entered
> FINE: Dev01: ping needed. keepAlive=230,000 lastOutboundActivity=1,564,727,590,361 lastInboundActivity=1,564,727,591,115
> FINE: Dev01: key=Ping message=PINGREQ
> FINE: Dev01: key=Ping token=org.eclipse.paho.client.mqttv3.MqttToken@1ebdbab
> FINE: Dev01: notifying queueLock holders
> FINE: Dev01: Schedule next ping at 230,000
> FINE: Dev01: new work or ping arrived
> FINE: Dev01: network send key=Ping msg=PINGREQ
> FINE: Dev01: sent bytes count=2
> FINE: null: Sent PINGREQ
> FINE: Dev01: key=Ping
> FINE: Dev01: > key=Ping
> FINE: Dev01: ping sent. pingOutstanding: 1
> FINE: Dev01: wait for new work or for space in the inflight window
> FINE: Dev01: received bytes count=1
> FINE: null: Automatic Reconnect Successful: PINGRESP msgId 0
> FINE: Dev01: received key=0 message=PINGRESP msgId 0
> FINE: Dev01: >key=Ping response=PINGRESP msgId 0 excep=null
> FINE: Dev01: >key=Ping response=PINGRESP msgId 0 excep=null
> FINE: Dev01: keyPing, msg=PINGRESP msgId 0, excep=null
> FINE: Dev01: new workAvailable. key=Ping
> FINE: Dev01: key=Ping
> FINE: Dev01: ping response received. pingOutstanding: 0
> FINE: Dev01: network read message
> FINE: Dev01: callback and notify for key=Ping
> FINE: Dev01: received key=0 token=org.eclipse.paho.client.mqttv3.MqttToken@1ebdbab message=PINGRESP msgId 0
> FINE: Dev01: >key=Ping response=PINGRESP msgId 0 excep=null
> FINE: Dev01: notify spaceAvailable
> FINE: Dev01: wait for workAvailable

***Exception or Stack Trace***
No exception or stack trace

**To Reproduce**
Hard to reproduce, the file uploading works well in 2~4 days, and suddenly does not work. It happened several times, but I have no clue how to reproduce it with a simple problem.

***Code Snippet***
```
while (true) {
    if (FileUploadStatusCallback is not invoked) 
        wait;

    File file = fetchNextFileToUpload();
    if (client == null) client = new DeviceClient(connectString, MQTT);
    client.open();
    client.setOperationTimeout(300000);
    client.uploadToBlobAsync(..., new IotHubEventCallback(...), file);
}
```

**Expected behavior**
`BlobEventCallBack.execute` shall be invoked if timeouts.

**Setup (please complete the following information):**
 - OS: linux
 - Version of the Library used: 1.17.5

**Comment by timtay-microsoft** [comment]
Just to clarify, you are capable of uploading similar sized files with no issue for 2~4 days, but occasionally you see this behavior?

**Comment by tianhai-liu** [comment]
Sorry for the late reply. 

To your question: Yes.

**Comment by timtay-microsoft** [comment]
The logs above about "Automatic Reconnect Successful" and similar are related to the mqtt connection that the device client uses, but that exists for sending telemetry, receiving twin/methods/etc. The file upload code always uses http.

Similarly, the device operation timeout has no bearing on file upload right now.

In your logs, do you see any instances of this error log?
"File upload failed to upload the stream to the blob"

Some other factors here are the http read and connect timeouts. By default, the read timeout is 4 minutes, and the connect timeout is infinite. If you file uploads are failing, it is possible that you are unable to connect over http infinitely.

Try upgrading to the latest sdk version (1.21.0) and set the read timeout and connect timeouts to lower values:

```
long connectTimeout = 1000 * 10; //10 seconds
long readTimeout= 1000 * 10; //10 seconds
deviceClient.setOption("SetHttpsConnectTimeout", connectTimeout);
deviceClient.setOption("SetHttpsReadTimeout", readTimeout);

**Comment by timtay-microsoft** [comment]
@tianhai-liu are you still seeing issues here? Can you try my above suggestions?

**Comment by tianhai-liu** [comment]
@timtay-microsoft, sorry for the delay. I don't see the issues any more after using latest SDK. Thanks for your help.

**Comment by timtay-microsoft** [comment]
Okay, I will go ahead and close this issue, then

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @tianhai-liu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
