### ISSUE TITLE
Device Client cannot be re-opened after retry policy has been exhausted

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#603]
If a device client or module client instance gets disconnected due to network issues, and the retry policy runs to completion, the client reports the connection status as DISCONNECTED. However, within the deviceIO layer, it still reports as CONNECTED. This is a bug due to the transport layer not communicating to the deviceIO layer when a disconnection/reconnection event occurs

**Comment by timtay-microsoft** [comment]
Calling closeNow() on the client before re-opening it should work as a workaround, but we are working to fix this issue anyways

**Comment by prmathur-microsoft** [comment]
Wont fix it as our recommendation now is call closeNow and recreate the instance.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
