### ISSUE TITLE
Connection Status Callback reports DISCONNECTED_RETRYING even on non-retryable errors

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#606]
If a client sets the retry policy to no retry, or if the client encounters a non-retryable exception, the connection status callback still reports DISCONNECTED_RETRYING and then immediately reports DISCONNECTED. This is misleading; the client should only report DISCONNECTED in these cases

**Comment by timtay-microsoft** [comment]
To clarify, the SDK isn't retrying anything in scenarios like this. It is just reporting that it is, and that is why it is misleading

**Comment by prmathur-microsoft** [comment]
Not planning to fix it now as it a behavior breaking change.

**Comment by az-iot-builder-01** [comment]
@prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
