### ISSUE TITLE
Nested Desired Properties with Pairs

### ISSUE THREAD

**Issue by hasanalpzengin** [Azure/azure-iot-sdk-java#613]
- **OS and version used:** 18.1.1 Manjaro Linux

- **Java runtime used:** 1.8 OpenJDK

- **SDK version used:** 1.18.0

# Description of the issue:
I'm working on nested desired properties. I tried nested pairs but it's not looking nested in iot hub:
After I update twindevice with nested pairs result is:
```
"properties": {
    "desired": {
      "app": {
        "key": "windows_test",
        "value": "2.3.4.txt"
      }
    }
}
```

But I'm expecting to see this:
```
"properties": {
    "desired": {
      "app": {
        "windows_test": "2.3.4.txt"
      }
  }
}
```

# Code sample exhibiting the issue:
```
Set<Pair> result = new HashSet<>();
        keyValues.forEach((keyValue)->{
            String[] splittedKey = keyValue.getKey().split("\\.");
            int i = splittedKey.length-1;
            //create first pair
            Pair pair = new Pair(splittedKey[i], keyValue.getValue());
            while (i > 0) {
                i--;
                pair = new Pair(splittedKey[i], pair);
            }
            result.add(pair);
        });
        return result;
```
As you can see I'm nesting pair's with that algoirthm.

# Console log of the issue:
Unnecessary
verbose output that will help debugging -->
Unnecessary

How I can get my expected result ?

**Comment by hasanalpzengin** [comment]
I used nested hashmap to fix that problem.

**Comment by az-iot-builder-01** [comment]
@hasanalpzengin, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
