### ISSUE TITLE
Device closes itself after 5 minutes of no network

### ISSUE THREAD

**Issue by mmacagno** [Azure/azure-iot-sdk-java#620]
# Description of the issue:
Our app is configured to send IoT hub messages every minute.
Everything works normally when network is present.

If I disable the network and re-enable it within 5 minutes, the pending/queued messages are properly sent to IoTHub when network is available.

If I leave the network disabled for more than 5 minutes, I receive MESSAGE_CANCELLED_ONCLOSE for all the pending messages, and from that point on I receive "Cannot add a message when the transport is closed" for each subsequent message.

# Code sample exhibiting the issue:
`
private void initIoTClient(String connectionString) {
        try {
            client = new DeviceClient(connectionString, IotHubClientProtocol.MQTT);
            client.open();
            if (protocol == IotHubClientProtocol.MQTT) {
                MessageCallbackMqtt callback = new MessageCallbackMqtt();
                Counter counter = new Counter(0);
                client.setMessageCallback(callback, counter);
            } else {
                MessageCallback callback = new MessageCallback();
                Counter counter = new Counter(0);
                client.setMessageCallback(callback, counter);
            }
            client.subscribeToDeviceMethod(new SampleDeviceMethodCallback(), null, new DeviceMethodStatusCallBack(), null);
            Succeed.set(false);
            client.startDeviceTwin(new DeviceTwinStatusCallBack(), null, new onProperty(), null);

            do {
                Thread.sleep(ONESECOND);
            }
            while (!Succeed.get());

        } catch (Exception e2) {
            showLog(Log.E, "Exception while opening IoTHub connection: " + e2.getMessage(), MainActivity.class);
            client = null;
            showLog(Log.E, "Shutting down...", MainActivity.class);
        }
    }

    private void sendToCloud(JSONObject jsonData, Date date) {
        String msgStr = jsonData.toString();
        try {
            com.microsoft.azure.sdk.iot.device.Message msg = new com.microsoft.azure.sdk.iot.device.Message(msgStr);
            msg.setMessageId(java.util.UUID.randomUUID().toString());
            msg.setCreationTimeUTC(date == null ? new Date() : date);
            showLog(Log.W, "IoT Hub post: " + msgStr, MainActivity.class);
            EventCallback eventCallback = new EventCallback();
            client.sendEventAsync(msg, eventCallback, 1);
        } catch (Exception e) {
            showLog(Log.E, "IoT Hub post: " + "exception while sending message: " + e.getMessage(), MainActivity.class);
        }
    }

    static class EventCallback implements IotHubEventCallback {
        public void execute(IotHubStatusCode status, Object context) {
            Integer i = (Integer) context;
            showLog(Log.I, "IoT Hub responded to message " + i.toString() + " with status " + status.name(), MainActivity.class);
        }
    }

`

# Console log of the issue:

![image](https://user-images.githubusercontent.com/2315384/68633382-8fb04e80-04a6-11ea-91cb-32a13d0a17e6.png)

**Comment by mmacagno** [comment]
It looks like there is a default timeout at 4 minutes.
I tried to change to 5 minutes and effectively the behavior above now happens just after 5 minutes.

The problem is that I need a resilience to no-network of several hours. I tried to set 24 hours but the connection won't open.

How do we make the queue resilient to network unavailable for several hours?

**Comment by mmacagno** [comment]
I found the issue as the default timeout for operations is 4 minutes.

Is it ok to set this value to a really long time, like 24 hours? Our scenario could have client devices that are disconnected for several hours at a time.

**Comment by timtay-microsoft** [comment]
Yeah, the client will stop retrying to open the connection after ~4 minutes by default. You can configure this value to be whatever you want. You can also override the default retry policy if the default exponential backoff algorithm doesn't meet your needs

**Comment by timtay-microsoft** [comment]
@mmacagno Is there anything else you need help with on this issue?

**Comment by mmacagno** [comment]
Please let's keep this open a little longer - I have tested with 24 hours but got problems delivery messages after ~1 hour disconnection from network - I was not wired to the logcat and don't know what happened. Will investigate tomorrow

**Comment by timtay-microsoft** [comment]
@mmacagno do you still want to leave this issue open? I'd rather close it now that the question has been answered. If you have any further issues, you can open a new issue instead of adding to this thread

**Comment by az-iot-builder-01** [comment]
@mmacagno, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by mmacagno** [comment]
Reopening this.
Even if I set a long limit for retry (24 hours), I get the transport closed exception after 1 hour without network.

This is how I set my client (a singleton), and reuse it "forever" in the app.

```
    public boolean init(String connectionString) {
        try {
            showLog(Log.D, "IoTClient::init()", IoTClient.class);

            initialized = false;
            client = null;

            client = new DeviceClient(connectionString, protocol);
            client.setOperationTimeout(24 * 60 * 1000); // 1 day timeout
            client.open();
...


```

**Comment by mmacagno** [comment]
Ooops, I guess it was 24 minutes timeout, not hours... missed a * 60...
