### ISSUE TITLE
Twin desired property updates not received on AMQP when using Preview API version

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#631]
Preview branch tests revealed that preview sevice api version has issues around desired properties over AMQP. Disabled the amqp twin tests while service fixes this issue

AB#7425686

**Comment by timtay-microsoft** [comment]
Service side bug has been opened

**Comment by timtay-microsoft** [comment]
It turns out this was due to an intentional decision by the service team. For higher API versions, they started requiring the SDK to send an explicit subscribe to desired properties after opening the twin receiving link.

**Comment by timtay-microsoft** [comment]
PR #792 will bring in the fix for this issue, and we will do a release for it soon after

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released as of iot-device-client-preview:1.1.0, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
