### ISSUE TITLE
kotlin

### ISSUE THREAD

**Issue by Alberto-Vega-MSFT** [Azure/azure-iot-sdk-java#637]
Please delete this was created by mistake.

**Comment by az-iot-builder-01** [comment]
@Alberto-Vega-MSFT, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
