### ISSUE TITLE
Direct Method response: Timed out waiting for the response from device

### ISSUE THREAD

**Issue by lexguy20** [Azure/azure-iot-sdk-java#640]
Hi,
I am having problem getting response for Direct Method call.
I am using DeviceClient version 1.16.0, release date February 28, 2019. I am using Java to create DeviceClient. It is running fine to send and receive any message to IoT hub.
When I call a Direct method from Azure IoT hub then after ~10 sec it displayed a response message as:

**{"message":"{\"Message\":\"{\\\"errorCode\\\":504101,\\\"trackingId\\\":\\\"40a7dd98fc2d4836b1c045996665b23d-G:9-TimeStamp:12/03/2019 15:00:09-G:11-TimeStamp:12/03/2019 15:00:09\\\",\\\"message\\\":\\\"Timed out waiting for the response from device.\\\",\\\"info\\\":{},\\\"timestampUtc\\\":\\\"2019-12-03T15:00:09.0082523Z\\\"}\",\"ExceptionMessage\":\"\"}"}
Failed to invoke device method: {"message":"{\"Message\":\"{\\\"errorCode\\\":504101,\\\"trackingId\\\":\\\"40a7dd98fc2d4836b1c045996665b23d-G:9-TimeStamp:12/03/2019 15:00:09-G:11-TimeStamp:12/03/2019 15:00:09\\\",\\\"message\\\":\\\"Timed out waiting for the response from device.\\\",\\\"info\\\":{},\\\"timestampUtc\\\":\\\"2019-12-03T15:00:09.0082523Z\\\"}\",\"ExceptionMessage\":\"\"}"}**

I tried: **setOption("SetSASTokenExpiryTime" , new Long(300))** as mentioned in other thread but no help.

Interestingly, if I check logs on my app(IoT-Application), I can see the the method is successfully called from IoT hub, its looks like IoT hub has failed to received the response from my App. Am I missing something here?
Any help will be greatly appreciated, thanks

Following is my simple App's code:
` 
     public class IoT-Application
     {
     private static DeviceClient client = null;
     private static DeviceMethodStatusCallBack deviceMethodStatusCallBack = null;

     public IoT-Application()
     {
        deviceMethodStatusCallBack = new DeviceMethodStatusCallBack();
     }

    /**
     * Send message to iot hub
     */
    private static void sendMessage(JSONObject content, String type)
    {
       content.put("iotDeviceId", client.getConfig().getDeviceId());
       Message message = new Message(content.toString());
       message.setProperty("type", type);
       client.sendEventAsync(message, deviceMethodStatusCallBack, null);
    }

    /**
     * Hub event callback that just echos status.
     */
    protected static class DeviceMethodStatusCallBack implements IotHubEventCallback
    {
       @Override
       public void execute(IotHubStatusCode status, Object context)
       {
          Activator.getLog().debug(" IotHubEventCallback execute method called with status::" +
          status.name());
       }
    }

    /**
     * Message callback that just echos the message received.
     */
    private static MessageCallback messageCallback = (message, context) -> {
       Activator.getLog().debug(" MessageCallback received message: " + 
       new String(message.getBytes(), StandardCharsets.UTF_8));
       return IotHubMessageResult.COMPLETE;
    };

    /**
     * Direct method callback handler.
     */
    private static class DirectMethodCallback implements DeviceMethodCallback
    {
      /**
       * Executes the specified direct method.
       *
       * @param methodName	The name of the method.
       *           
       * @param methodData	The method body (JSON).
       *           
       * @param context	The context in which the method was called.       
       *           
       * @return The status of the method result.
       */
      @Override
      public DeviceMethodData call(String methodName, 
                               Object methodData, Object context)
      {
         Activator.getLog().debug(" Incoming method: " + methodName);
         return new DeviceMethodData(200, "StringData");
      }
    }

    @Override
    public void init()
    {

       Thread t = new Thread(() -> {
        try
         {
        	 
		client = new DeviceClient("<My-Connection-String>", 
                IotHubClientProtocol.MQTT_WS);
		client.open();
		client.setMessageCallback(messageCallback, new HashMap<>());
		client.subscribeToDeviceMethod(new DirectMethodCallback(), null, 
                deviceMethodStatusCallBack, null);
		Long sasTime = new Long(300);
		client.setOption("SetSASTokenExpiryTime", sasTime);
         }
         catch (URISyntaxException syntaxException)
         {
            Activator.getLog().info("Invalid URI syntax");
         }
         catch (Throwable tr)
         {
            tr.printStackTrace();
         }
      });
      t.setName("IoT-device-thread");
      t.start();
    }
   }
`

**Comment by timtay-microsoft** [comment]
Are you consistently seeing this kind of failure? Can you try upgrading your device client dependency to the latest version (1.18.0)? And do you see this behavior when using other protocols like AMQPS/AMQPS_WS/MQTT?

**Comment by lexguy20** [comment]
Hi, thanks for reply, I am seeing this error consistently. I upgraded device client to 1.18.0 with all its dependencies and now I am getting following IllegalArgumentException:

**java.lang.IllegalArgumentException: no NetworkModule installed for scheme "wss" of URI "wss://dev-lram-iot.azure-devices.net/$iothub/websocket?iothub-no-client-cert=true"java.lang.IllegalArgumentException: no NetworkModule installed for scheme "wss" of URI "wss://dev-lram-iot.azure-devices.net/$iothub/websocket?iothub-no-client-cert=true"
at org.eclipse.paho.client.mqttv3.internal.NetworkModuleService.validateURI(NetworkModuleService.java:72)	at org.eclipse.paho.client.mqttv3.internal.NetworkModuleService.validateURI(NetworkModuleService.java:72)
at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:454)	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:454)
at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:320)	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:320)
at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:315)	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.<init>(MqttAsyncClient.java:315)
at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttConnection.<init>(MqttConnection.java:65)	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttConnection.<init>(MqttConnection.java:65)
at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:171)	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:171)
at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:707)	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.openConnection(IotHubTransport.java:707)
at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:273)	at com.microsoft.azure.sdk.iot.device.transport.IotHubTransport.open(IotHubTransport.java:273)
at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:158)	at com.microsoft.azure.sdk.iot.device.DeviceIO.open(DeviceIO.java:158)
at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:123)	at com.microsoft.azure.sdk.iot.device.InternalClient.open(InternalClient.java:123)
at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:316)	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:316)**

Any idea?
Thanks

**Comment by timtay-microsoft** [comment]
That error suggests that the underlying mqtt client (paho) isn't capable of doing websocket communication, which isn't right. That client does have websocket support in the latest version, and that is the version that this SDK uses. Are you using an older version of mqtt paho? 

If not, then it may be a limitation of the machine. What kind of device are you running this code on? And are you capable of connecting over MQTT rather than MQTT_WS?

**Comment by lexguy20** [comment]
Ok thanks for the reply.
I fixed the "no NetworkModule installed" error
I upgraded the DeviceClient to the latest version (1.18.0) and still getting the first error in method response: "Timed out waiting for the response from device."
I tried to change Method and Connection timeout values but no luck.
when a Direct method is called from IoT hub, I can see the method is been called on the device and my device is returning the response but Azure IoT hub is showing the above response: "Timed out waiting for the response from device."
Any help will be greatly appreciated, thanks

**Comment by lexguy20** [comment]
Update:
I was missing the package: com.google.gson that is been used by com.microsoft.azure.sdk.iot.deps.serializer.MethodParser and sdk.iot package was throwing NoClassDefFoundError but my app was not showing/logging that error and I had no way knowing whats going on. Adding the package: com.google.gson in my App run path fixes the problem.
I would like to thank to all and close this issue.

**Comment by az-iot-builder-01** [comment]
@lexguy20, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
