### ISSUE TITLE
Provisioning Device Client Documentation link is not  working in readme

### ISSUE THREAD

**Issue by ajmeraaxesh** [Azure/azure-iot-sdk-java#649]
In the following link
https://github.com/Azure/azure-iot-sdk-java/tree/master/provisioning/provisioning-samples/provisioning-X509-sample

The "Provisioning Device Client Documentation" link is leading to a 404
It should point to the following link:
https://docs.microsoft.com/en-us/azure/iot-dps/

**Comment by timtay-microsoft** [comment]
Good catch. I believe the link should be [this one](https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.sdk.iot.provisioning.device.provisioningdeviceclient?view=azure-java-stable) instead. I'll get this fixed in the repo soon

**Comment by timtay-microsoft** [comment]
The fix for this has been checked in, so I'm closing this issue now

**Comment by az-iot-builder-01** [comment]
@ajmeraaxesh, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
