### ISSUE TITLE
run digitaltwin.sample.IoTCentralSample build error 

### ISSUE THREAD

**Issue by mxxmusic** [Azure/azure-iot-sdk-java#659]
Could not resolve dependencies for project com.microsoft.azure.sdk.iot.device.samples:iot-central-sample:jar:1.0.0: Failed to collect dependencies at com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client-preview:jar:1.0.0

**Comment by davilu** [comment]
@mxxmusic  `digitaltwin.sample` is deprecated and will be removed from this repo. `IoTCentralSample` is not ready for public review. For java digital samples, please refer to java sample repo: https://github.com/Azure-Samples/azure-iot-samples-java/tree/master/digital-twin/Samples

**Comment by timtay-microsoft** [comment]
Closing this issue since it is unrelated to this repo

**Comment by az-iot-builder-01** [comment]
@mxxmusic, @davilu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
