### ISSUE TITLE
Use runtime scope for transportation implementation libraries like eclipse paho

### ISSUE THREAD

**Issue by JMayrbaeurl** [Azure/azure-iot-sdk-java#66]
- **OS and version used:** Windows 10 

- **Java runtime used:** 1.7 

- **SDK version used:** 1.0.21 

# Description of the issue:
The SDKs are using third party transport implementation libraries like Eclipse Paho and Apache Qpid Proton. Currently they are used with Maven scope of compile that builds up a static dependency on them. So users of the SDK that just want to use the MQTT protocol get the Qpid Proton library with all its direct dependencies on the classpath, too. Therefore please set the scope of these libraries to runtime in the Maven pom.xml files.

# Code sample exhibiting the issue:
Current:
```
        <dependency>
            <groupId>org.apache.qpid</groupId>
            <artifactId>proton-j</artifactId>
            <version>0.15.0</version>
            <type>jar</type>
        </dependency>
```
Should be
```
        <dependency>
            <groupId>org.apache.qpid</groupId>
            <artifactId>proton-j</artifactId>
            <version>0.15.0</version>
            <type>jar</type>
            <scope>runtime</scope>
        </dependency>
```

# Console log of the issue:

**Comment by tameraw** [comment]
@JMayrbaeurl - Thanks for the feedback on this. We will put this in our backlog and evaluate it in the future.

**Comment by JMayrbaeurl** [comment]
BTW. This is no breaking change and could be applied immediately. The effect would be to reduce the coupling of third party libraries drastically. 'Enhancement' sounds like 'will be done in two or more years'.

**Comment by prmathur-microsoft** [comment]
Just changing the scope to runtime would not resolve the problem. Problem lies in having runtime dependency on the code from external libraries. We have been working on refactoring our SDK to support this. However we are still not there yet where can simply change the scope to runtime and it works. We will keep you updated about progress.

**Comment by jasmineymlo** [comment]
Progress has been made towards resolving this issue but we are still not there yet.  More work is needed to be in place.  We will keep you posted.

**Comment by timtay-microsoft** [comment]
Closing this issue because the current design of the SDK prohibits us from making this a reality without significant changes. If we ever redesign the SDK from the bottom up, we'll keep this suggestion in mind

**Comment by az-iot-builder-01** [comment]
@JMayrbaeurl, @prmathur-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
