### ISSUE TITLE
Pipeline jobs are coming as failed. So just confused whether to use this repo or not.

### ISSUE THREAD

**Issue by ashishc** [Azure/azure-iot-sdk-java#663]
On git readme file pipeline jobs are failed. Please fix them before anyone takes wrong jars.

**Comment by timtay-microsoft** [comment]
We are working to cut down on some flakey e2e tests that have been causing the nightly builds some issues. This is still the correct repo to take jars from.

**Comment by timtay-microsoft** [comment]
Closing this issue because it isn't about a particular issue with the SDK itself

**Comment by az-iot-builder-01** [comment]
@ashishc, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
