### ISSUE TITLE
Missing DPS Service client APIs for getting enrollment attestation mechanism

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#674]
Currently, the GetIndividualEnrollment and GetEnrollmentGroup APIs don't return the symmetric key values if the enrollment uses symmetric keys for attestation. This is by design from the service side, but there are service APIs that allow you to get these values:

https://docs.microsoft.com/en-us/rest/api/iot-dps/getindividualenrollmentattestationmechanism/getindividualenrollmentattestationmechanism

https://docs.microsoft.com/en-us/rest/api/iot-dps/getenrollmentgroupattestationmechanism/getenrollmentgroupattestationmechanism

The provisioning service client should create new APIs that use the above APIs so that customers can get the symmetric key values

AB#8102333

**Comment by timtay-microsoft** [comment]
Make sure to document the existing getIndividualEnrollment APIs to say that it is by design that symmetric key values won't be retrieved through those APIs, and to use the new API if you want those values

**Comment by timtay-microsoft** [comment]
This issue has been fixed as of provisioning service client version 1.7.0, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by Bozhidariv** [comment]
Hello @timtay-microsoft, Is this feature only for the individual enrolments. Because in the code I see that only it is affected.
I would like to use the sdk to get the enrolment group attestation, and in specific the primary/secondary symmetric key of the group. Could you please give an update on this ?

Thanks in advance.

**Comment by timtay-microsoft** [comment]
@Bozhidariv the SDK also has a method for getting the attestation mechanism for group enrollments here: https://github.com/Azure/azure-iot-sdk-java/blob/283b0098949015413fcfa84fbf0096b183476042/provisioning/provisioning-service-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/service/ProvisioningServiceClient.java#L690
