### ISSUE TITLE
AMQPS or AMQP_Websocket not working with Android Sample 

### ISSUE THREAD

**Issue by jkriba** [Azure/azure-iot-sdk-java#69]
Hi Support,
  We are using Android Version 7.1 for developing a Cloud connector for our business application in the mobile device. It is working well with HTTPS and MQTT but when we try to use AMQPS and AMQPS_Websocket its getting hung.

- **OS and version used:** <VERSION>Android 7.1 

- **Java runtime used:** <VERSION> JDK "1.8.0_45" 

- **SDK version used:** <VERSION>  IoT Device Client 1.1.22 for Java

# Description of the issue:
When we try to send sample messages to the IoT Hub using Device client with AMQPS or AMQPS_Websocket, the trasport is getting hung. And application is getting into un responsive state.

# Code sample exhibiting the issue:
        IotHubClientProtocol protocol = IotHubClientProtocol.AMQPS;
        DeviceClient client = new DeviceClient(connString, protocol);
       try 
        {
            //Here it is getting out of the scope and never returns back 
            client.open();
        }
        catch(IOException e1)
        {
            System.out.println("Exception while opening IoTHub connection: " + e1.toString());
        }

# Console log of the issue:
03-28 14:11:52.961 32750-32750/? I/art: Late-enabling -Xcheck:jni
03-28 14:11:53.005 32750-32750/com.iothub.azure.microsoft.com.androidsample W/System: ClassLoader referenced unknown path: /data/app/com.iothub.azure.microsoft.com.androidsample-1/lib/arm
03-28 14:11:53.117 32750-32750/com.iothub.azure.microsoft.com.androidsample W/System.err: log4j:WARN No appenders could be found for logger (com.microsoft.azure.sdk.iot.device.DeviceClientConfig).
03-28 14:11:53.117 32750-32750/com.iothub.azure.microsoft.com.androidsample W/System.err: log4j:WARN Please initialize the log4j system properly.
03-28 14:11:53.117 32750-32750/com.iothub.azure.microsoft.com.androidsample W/System.err: log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by prmathur-microsoft** [comment]
Thank you for raising this issue. This issue is primarily because we use proton library for AMQP and it is not yet completely compatible with Android. We have already raised an issue with proton for the same. We will keep you updated as we get any information on the progress with android compatibility. This is a priority for us too.

As a work around we suggest using MQTT.

**Comment by jkriba** [comment]
Hi prmathur,
  Thanks for the rapid response, we have a business delivery depends upon this. 
Please consider qualifying AMQPS_Websocks also in the scope, thanks in advance

Regards
JK

**Comment by jkriba** [comment]
Hi prmathur,
  Did you have any update on the same, kindly let us know. thanks

Regards
JK

**Comment by prmathur-microsoft** [comment]
Our latest release and master branch currently supports Mqtt and AMQPS, if you want to give it a try - https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-4-21

**Comment by jkriba** [comment]
Thanks a lot buddy, this will really help us. 

Regards
JK

**Comment by AnnapoorniS** [comment]
Hi,
      We tried using the latest java SDK 1.1.26 and it works fine for AMQPS. But, when we try send messages to the IotHub using AMQPS_WS protocol, we are facing some issues (ie. we are not able to get the response back from the cloud). Kindly let us know your comments on this?

Thanks
Annapoorni S

**Comment by prmathur-microsoft** [comment]
We are aware of this issue. Currently our android support only works on MQTT and AMQP. We have it in our backlog to add support for AMQPS_WS as well.

**Comment by mamokarz** [comment]
I'll take a look.

**Comment by prmathur-microsoft** [comment]
A fix has been checked in @87d2c65c67ae7e1c3e5e2e6efce497853aa20b47. AMQPS_WS now works on Android. Please give it a try from our master branch and lets us know if you see any further issues.

**Comment by mamokarz** [comment]
There is another issue, I'm investigating.

**Comment by AnnapoorniS** [comment]
Hi, we validated with AMQPS_WS protocol and we are unable to send packets with Android. Kindly check once if the protocol supports for Android.
Thanks
Annapoorni S

**Comment by prmathur-microsoft** [comment]
AMQP_WS now works with Android. Please give it a try and let us know if you see any further issues.

**Comment by prmathur-microsoft** [comment]
Maven package for the same is also released. Closing this issue now. Please feel free to reopen if you see any further issues.
