### ISSUE TITLE
IoT Hub resets the connection

### ISSUE THREAD

**Issue by vslepakov** [Azure/azure-iot-sdk-java#7]
Hi,

we use Java SDK version 1.0.15 on debian and have the problem that we sporadically get into an endless reconnect loop (Lost connection to the server. Reconnection attempt 1368 etc.). 
I captured the network traffic using Wireshark. Please take a look at the screenshot:

![image](https://cloud.githubusercontent.com/assets/1545509/21810042/8110c620-d74a-11e6-8948-5a16e390e892.png)

As you can see the connection is first closed by the client (FIN). The SDK seems to do this on its own because we have no code in place that would close the connection (only on app exit).
After this the SDK tries to reconnect and from that point on the connection is reset (RST) by the IoT Hub.
If we kill the process and restart it, it works again for a while until the issue reappears.
We were able to reproduce it on OSX and Windows as well.

Thanks for your support
Best Regards
Vitaliy

**Comment by anhashia** [comment]
Investigating !

**Comment by vslepakov** [comment]
Thanks for your help.

1. we use amqp 
2. about an hour or so till the issue manifests itself 
3. Actually we did not try it with other protocols but we'll do so 

Regards
Vitaliy

**Comment by vslepakov** [comment]
Hi all,

after update to 1.0.16 there no more issues.
The issue is resolved for me but might still be present in the previous version.

Regards
Vitaliy

**Comment by anhashia** [comment]
Hi @vslepakov 
Thanks for the update ! Please re-activate if you have any further questions on this. Thanks !
