### ISSUE TITLE
Problems in ProvisioningDeviceClient and DeviceClient when running with SpongyCastle and SecurityProviderX509Cert

### ISSUE THREAD

**Issue by devzeze** [Azure/azure-iot-sdk-java#701]
I ran in issues when running app with [SpongyCastle](https://rtyley.github.io/spongycastle/)  and using SecurityProviderX509Cert as auth mechanism in Android

In Provisioning I get this exception:
**W/System.err: Exception while opening IoTHub connection: java.lang.IllegalArgumentException: private key algorithm does not match algorithm of public key in end entity certificate (at index 0)**

In DeviceClient:
No reaction at all, no registration.

Everything works properly when I remove the SpongyCastle.

Libraries used:

    //  IoT
    implementation 'com.microsoft.azure.sdk.iot:iot-device-client:1.19.1'
    implementation 'com.microsoft.azure.sdk.iot.provisioning:provisioning-device-client:1.7.1'
    implementation 'com.microsoft.azure.sdk.iot.provisioning.security:x509-provider:1.1.3'

    //  Spongy Castle
    implementation 'com.madgag.spongycastle:core:1.58.0.0'
    implementation 'com.madgag.spongycastle:prov:1.58.0.0'
    implementation 'com.madgag.spongycastle:bcpkix-jdk15on:1.58.0.0'
    implementation 'com.madgag.spongycastle:bcpg-jdk15on:1.58.0.0'

**Comment by timtay-microsoft** [comment]
Are you able to capture the full stacktrace of the exception in question?

**Comment by devzeze** [comment]
Unfortunately I cannot get the same sample as before. 

Anyway I rerun today the same test with your's Android Sample app:
https://github.com/Azure-Samples/azure-iot-samples-java/tree/master/digital-twin/Samples/device/AndroidSample

And got same result in Provisioning (added by me) and DeviceClient (in available sample). Both silent, no logs and not working.
Once I remove SpongyCastle it works as expected.

**Comment by timtay-microsoft** [comment]
Can you provide a complete project zip that demonstrates this issue? Without any secrets, but with the gradle and application code?

**Comment by devzeze** [comment]
Hi, here you have the demo.

//  Comment to test with and without Spongycastle
            Security.insertProviderAt(new org.spongycastle.jce.provider.BouncyCastleProvider(), 1);

Let me know if you need anything else.

[azureiot_demo.zip](https://github.com/Azure/azure-iot-sdk-java/files/4557732/azureiot_demo.zip)

**Comment by devzeze** [comment]
SpongyCastle seems to not be maintained anymore.

Lower priority now.

**Comment by timtay-microsoft** [comment]
Closing this issue as SpongyCastle isn't being maintained, which is important for a security library

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @devzeze, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
