### ISSUE TITLE
MethodParser does not serialize null-values anymore

### ISSUE THREAD

**Issue by cepxy** [Azure/azure-iot-sdk-java#711]
I am using the "iot-service-client" (1.17.1) to invoke direct methods on a device.

When invoking a direct method, a payload can be provided which will be serialized as JSON and sent to the device.

Between 1.16.0 and 1.17.x the MethodParser class which is responsible for serializing and deserializing of methods which also includes the payload, stopped serializing null values.
That means if the payload-object contains fields that have a null value, these fields will not be present in the serialized JSON string and therefore missing when the method is received by the device.

I took a closer look on the implementation. The MethodParser is actually contained in the "iot-deps" artifact.

Using iot-service-client 1.16.0 which relys on iot-deps 0.8.0 we can see in the method "toJsonElement" (line 295) which instantiates a Gson-object and explicitly setting "serializeNull" so fields with null-values will be included in the json:
```
    public JsonElement toJsonElement() throws IllegalArgumentException
    {
        Gson gson = new GsonBuilder().enableComplexMapKeySerialization().serializeNulls().create();
```

In iot-service-client 1.17.1 (last one that I used) which relys on iot-deps 0.8.1 the json-serializing changed a bit and now uses a private method jsonizePayload (line 327). In this method eventually a Gson-object is instantiated as well but does not get the configuration to include null-values. Default configuration does not serialize null-values.
```
    private JsonElement jsonizePayload(Object payload)
    {
	//...
                return new Gson().toJsonTree(payload);
```

This is not the expected behavior. My guess is that it is a bug and was just forgotten during refactoring.
If fields of the payload with null values are not contained in the JSON, then the object set as payload differs from the object transferred to the device. Therefore, null-values should always be kept.

The issue could be easily fixed by using GsonBuilder.serializeNulls() for instantiation.

Issue still exists in the last version iot-service-client 1.20.0

Thanks and regards,
Christian

Had another look, the change must have happened between 0.8.0 and 0.8.1 of the iot-deps artifact.

**Comment by timtay-microsoft** [comment]
Thanks for the detailed write up. Can you please also provide some sample code that demonstrates this bug?

**Comment by cepxy** [comment]
Sure I can.
I started using the azure-iot-samples project which has a quickstart for invoking devicemethods: https://github.com/Azure-Samples/azure-iot-samples-java/blob/master/iot-hub/Quickstarts/back-end-application/src/main/java/com/microsoft/docs/iothub/samples/BackEndApplication.java

However, the easiest way is to just write a quick junittest for the MethodParser. (I will leave out some boilerplate code...)

Suppose we have a simple testclass used as payload with two fields, one we will assign a value to and one we will leave with null.
```
public class PayloadExample {
    private String fieldA;
    private String fieldB;
}
```

Then a unit test could look like this:
```
    @Test
    public void testSerializingWithNullValues() {
        PayloadExample payload = new PayloadExample("test", null);

        MethodParser methodParser = new MethodParser(payload);

        String expected = "{\"fieldA\":\"test\",\"fieldB\":null}";
        String actual = methodParser.toJson();

        Assert.assertEquals(expected, actual);
    }
```

Since iot-deps-0.8.1 (--> used by iot-service-client-1.17.0) this test fails:
```
org.junit.ComparisonFailure: 
Expected :{"fieldA":"test","fieldB":null}
Actual   :{"fieldA":"test"}
```

If you try the IoT-Hub-Example BackendApplication to send direct methods you just extend the example with our new PayloadExample-Object and invoke the method.
You have to debug into the code though if you dont have an actual device which will receive the method call...

```
// Call the direct method.
PayloadExample payload = new PayloadExample("test", null);
MethodResult result = methodClient.invoke(deviceId, methodName, responseTimeout, connectTimeout, payload);
```

**Comment by timtay-microsoft** [comment]
Perfect, thanks for all the info! I'll try to get the fix for this checked in and released soon.

**Comment by timtay-microsoft** [comment]
So I'm trying to repro this issue, and I'm getting different results than you reported. Here is my code, with no code removed for simplification:
```
public static void main(String[] args)
{
    PayloadExample payload = new PayloadExample("test", null);

    MethodParser methodParser = new MethodParser(payload);

    String expected = "{\"fieldA\":\"test\",\"fieldB\":null}";
    String actual = methodParser.toJson();

    Assert.assertEquals(expected, actual);
}

public static class PayloadExample {
    private String fieldA;
    private String fieldB;

    public PayloadExample(String fieldA, String fieldB)
    {
        this.fieldA = fieldA;
        this.fieldB = fieldB;
    }
}
```

With deps version 8.0, you are correct, the assertion passes because the null value is serialized.
With deps version 8.1+, I don't even get a properly serialized object at all:
```
Exception in thread "main" org.junit.ComparisonFailure: expected:<[{"fieldA":"test","fieldB":null}]> but was:<["samples.com.microsoft.azure.sdk.iot.SendEvent$PayloadExample@4617c264"]>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.junit.Assert.assertEquals(Assert.java:146)
```

The code path that deps 8.1+ uses to serialize an object that isn't a map, JsonElement, or null object looks like this:
```
private JsonElement jsonizePayload(Object payload)
{
    if (payload == null) { ... }
    else if (payload instanceof JsonElement)  { ... }
    else if (payload instanceof Map)  { ... }
    else
    {
        JsonParser parser = new JsonParser();
        try
        {
            // NOTE: This toString() operation just returns the class name and hashcode, not fieldA and fieldB
            String json = payload.toString(); 
            JsonElement jsonElement = parser.parse(json);
            if (jsonElement.isJsonNull())
            {
                return new JsonPrimitive(json);
            }
            else
            {
                return jsonElement;
            }
        }
        catch (JsonSyntaxException e)
        {
            return new Gson().toJsonTree(payload);
        }
    }
}
```

In the above sample, the PayloadExample object falls under the else block, gets its toString() called, and that useless info is turned into a JsonElement.

Now, by overriding the toString() of the PayloadExample like below:

```
public static class PayloadExample {
    ...
    @Override
    public String toString()
    {
        return "{\"fieldA\":\"test\",\"fieldB\":null}";
    }
}
```

Then suddenly, the assertion passes because the null value does get serialized.

I'm having trouble finding how to hit the code path within MethodParser (in deps 8.1+) with the line
```
return new Gson().toJsonTree(payload);
```

Where you suggested to use a Gson object that serializes nulls.

Can you please clarify how you hit the codepath that even builds a gson object?

**Comment by cepxy** [comment]
Interesting. I guess leaving out even small details is never a good idea ;-)
So here is some clarification:

Youre right, we are in the last else-block where the JsonParser gets initialized.
If we use the java-standard toString() that creates the class/hash info (om.microsoft.docs.iothub.samples.PayloadExample@7637f22) it can't get parsed, or lets say it shouldnt get parsed.
I do not understand, why `JsonElement jsonElement = parser.parse(json);` works for that, even though the result is useless.

Anyway, I left out that I in fact did override toString to generate a meaningful toString-Method that reflects the content of the fields. I used Lombok which generates this:
```
public String toString() { return "PayloadExample(fieldA=" + this.fieldA + ", fieldB=" + this.fieldB + ")"; }
```

This fortunately is not getting parsed by the JsonParser, the JsonSyntaxException is thrown and we eventually end up in the line with `return new Gson().toJsonTree(payload);`

I would not recommend overriding the toString-method and return a selfcreated json-string. Getting a json out of the object is imho the purpose of the MethodParser.

Thanks for help :)
