### ISSUE TITLE
com.microsoft.azure.sdk.iot.digitaltwin.SdkInformationComponent does not resolve in the DigitalTwin device sample

### ISSUE THREAD

**Issue by apulliam** [Azure/azure-iot-sdk-java#712]
Tried building the digital-twin-device-samples.  The pom.xml references "LATEST" version of the digital-twin-device-client-preview.  Please update code and/or provide version which will build.

**Comment by timtay-microsoft** [comment]
This sample is tied to the pre-summer refresh PnP work that we did, so we consider it deprecated. We have new PnP libraries and samples in this repo that should be used instead. Closing this issue as "won't fix"
