### ISSUE TITLE
IoT Service Client does not expose functionality for replacing a device twin

### ISSUE THREAD

**Issue by mattixtech** [Azure/azure-iot-sdk-java#719]
Using iot-service-client version 1.2.0

# Description of the issue:
The iot-service-client currently does not support replacing a device twin. It only has a method for updating the device twin. According to the HTTP API (https://docs.microsoft.com/en-us/rest/api/iothub/service/replacetwin) it appears a replace is done the same as an update but sending HTTP method PUT instead of PATCH.

The Java SDK can be updated easily to add support for this and I have tested it in a fork here: https://github.com/mattixtech/azure-iot-sdk-java/commit/7ad66f1f948946642c24b0403540b02edbb3b162. The replace call is made exactly the same as the existing call to update aside from substituting the HTTP method to PUT.

With thew new method I was able to replace the desired properties of my IoT device entirely overwriting the existing contents which is the expected behaviour.

Adding this functionality to the SDK would make replacing device twins much more convenient since the alternative seems to be to explicitly set all the existing keys that are no longer required to null which requires you know all the keys at the time of replacing the twin.

I'm assuming the intent of the SDK is to have feature parity with the other language SDKs and HTTP API. If that is the case I don't see any reason to not update the Java SDK to support this.

Thanks!!

**Comment by mattixtech** [comment]
This feature will be very handy for our use case. Can I please get some feedback on whether or not we could get this updated in the SDK. I'm hesitant to open a PR because I'm not sure about the documentation requirements/testing needed.

Thanks

**Comment by prmathur-microsoft** [comment]
At the moment we dont have an ETA for this feature. We will add it to backlog.

**Comment by timtay-microsoft** [comment]
I'm looking to finally get this feature in soon. I'm aiming to release it alongside the other issue that you filed.

**Comment by timtay-microsoft** [comment]
Closing this issue as this feature has been released as of Service Client version 1.28.0
