### ISSUE TITLE
usesValidChars method of MessageProperty does not work, always returning true

### ISSUE THREAD

**Issue by morphvale** [Azure/azure-iot-sdk-java#724]
- **OS and version used:** Custom build Linux, not relevant
- **Java runtime used:** 1.8.0, not relevant
- **SDK version used:** 1.20.0

# Description of the issue:
The MessageProperty documentation https://azure.github.io/azure-iot-sdk-java/device/com/microsoft/azure/iothub/MessageProperty.html states that usesValidChars method should return true only if the string contains US-ASCII printable chars, and does not contain ()<>@,;:\"/[]?={} (space) (horizontal tab). The regex used for this validation does not seem to work, and the method always returns true, however messages are never sent to Azure.

Also, if the string contains invalid characters (in our case, this was a space) there is no exception or information logged when attempting to send the invalid message, and the callback of sendEventAsync is not entered. However, when we close our application and the resources are disposed, all previously sent messages will be logged with MESSAGE_CANCELLED_ONCLOSE status.

![2020-03-05](https://user-images.githubusercontent.com/10355724/76056909-76b13900-5f80-11ea-9722-429e1dab4463.png)

**Comment by timtay-microsoft** [comment]
This does look like a bug on our side. Interestingly, only clients using MQTT or MQTT_WS seem to break when an invalid character is provided in an application property. AMQP and HTTP seem to allow it. The official [IoTHub documentation](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-construct) says nothing about this protocol level distinction, so it's safer for the SDK to prevent any protocol from using these invalid characters.

I'll have the fix up soon

**Comment by az-iot-builder-01** [comment]
@morphvale, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by timtay-microsoft** [comment]
The fix for this issue has been check in, and will be released within the next few days
