### ISSUE TITLE
NotImplementedException while updating twin and desired properties 

### ISSUE THREAD

**Issue by Sunil123K** [Azure/azure-iot-sdk-java#73]
- **OS and version used:** <VERSION> Ubuntu 15.04.

- **Java runtime used:** <VERSION> jdk1.8

- **SDK version used:** <VERSION> 

# Description of the issue:
Getting NotImplementedException while updating twin and desired properties. I am able to get twin using getTwin method in DeviceTwin class but when i try to call DeviceTwin.updateTwin() and DeviceTwin.updateDesiredProperties() method with required argument (after setting desired propeeties), it throws NotImplementedException.

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by prmathur-microsoft** [comment]
We have an issue on the service side that is preventing us from using this feature. So we have not yet rolled out complete implementation of twin on service side. IotHub service is working on fixing this issue and should have this enabled soon. In the mean time only get twin is available on service.

**Comment by prmathur-microsoft** [comment]
Fix is checked in @67e00470f525e4026a04dd88923af1905c8293f3. Packages should be released to maven soon.

**Comment by prmathur-microsoft** [comment]
Packages for the same are also released. Please check - https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-4-21.

**Comment by prmathur-microsoft** [comment]
Closing this for now. Please reopen if you see further issues.
