### ISSUE TITLE
[Module Client] Throughput Issues When Receiving Messages From OPC Publisher 2.6.x

### ISSUE THREAD

**Issue by jerickcolendres** [Azure/azure-iot-sdk-java#739]
- **OS and version used:** <VERSION> 
Host: Ubuntu 18.04.2 LTS

- **Java runtime used:** <VERSION> 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)

- **SDK version used:** <VERSION> 
1.20.2

- **IOT Edge runtime**
iotedge 1.0.8 (208b2204fd30e856d00b280112422130c104b9f0)

# Description of the issue:

Hi,

We currently have a custom IOT edge module consuming messages from  **OPC Publisher 2.6.x** module using **MQTT** protocol. Since the new version of OPC Publisher 2.6.x no longer support message batching like the previous 2.5.x version, messages are sent one by one and we are experiencing throughput problems. I look at the code and the current implementation uses a scheduler that runs a **IotHubReceiveTask** which takes a message from the **receivedMessagesQueue** every **receivedPeriodInMillis**. For MQTT, the RECEIVE_PERIOD_MILLIS_MQTT value is set to 10 so it can only process 100 message per second. We need to process over 1000 OPC UA values per second and on our largest sites we might have around 80,000+ telemetry tags configured with an average of 15 seconds between updates.

We already contacted the OPC Publisher team about the urgent need to support batched messages but is there any other way to increase the message throughput? Would it be possible to modify the code to poll and process messages in realtime by having a long running thread consuming from a blocking queue? If possible, could you apply that to the "sending" code as well? We have another custom IOT Edge module that had the same message throughput problem when sending messages  using the Java IOT SDK and we worked around the problem by not using the SDK and directly send the messages to IOT Hub via REST API.

# Code sample exhibiting the issue:

ModuleClient.java
```java
public class ModuleClient extends InternalClient
{
    ...
    private static long RECEIVE_PERIOD_MILLIS_MQTT = 10;
    ...
}
```

DeviceIO.java
```java
public final class DeviceIO
{
    ...
    private void commonOpenSetup()
    {
        this.sendTask = new IotHubSendTask(this.transport);
        this.receiveTask = new IotHubReceiveTask(this.transport);

        this.taskScheduler = Executors.newScheduledThreadPool(2);
    
        this.taskScheduler.scheduleAtFixedRate(this.sendTask, 0, sendPeriodInMilliseconds, TimeUnit.MILLISECONDS);
        this.taskScheduler.scheduleAtFixedRate(this.receiveTask, 0, receivePeriodInMilliseconds, TimeUnit.MILLISECONDS);

        this.state = IotHubClientState.OPEN;
    }
    ...
}
```

IotHubReceiveTask.java
```java
public final class IotHubReceiveTask implements Runnable
{
    private static final String THREAD_NAME = "azure-iot-sdk-IotHubReceiveTask";
    private final IotHubTransport transport;

    ...
    public void run()
    {
        try
        {
        
            this.transport.handleMessage();
        }
        catch (Throwable e)
        {
            log.warn("Receive task thread encountered exception while processing received messages", e);
        }
    }
    ...
}
```
IotHubTransport.java
```java
public class IotHubTransport implements IotHubListener
{
    ...
    public void handleMessage() throws DeviceClientException
    {
        //Codes_SRS_IOTHUBTRANSPORT_34_046: [If this object's connection status is not CONNECTED, this function shall do nothing.]
        if (this.connectionStatus == IotHubConnectionStatus.CONNECTED)
        {
           ...
            IotHubTransportMessage receivedMessage = this.receivedMessagesQueue.poll();
            if (receivedMessage != null)
            {
                //Codes_SRS_IOTHUBTRANSPORT_34_048: [If this object's connection status is CONNECTED and there is a
                // received message in the queue, this function shall acknowledge the received message
                this.acknowledgeReceivedMessage(receivedMessage);
            }
        }
    }
    ...
}
```
# Console log of the issue:

The following logs is from our custom IOT Edge module and you can see a single message from OPC Publisher are read every 10ms:
```
2020-03-20 01:56:44.314 [azure-iot-sdk-IotHubReceiveTask] DEBUG c.f.a.e.m.m.IotEdgeHubMessageBus - Received message 5198: {"ContentMask":1493,"NodeId":"nsu=ThingWorx Industrial Connectivity;s=Sim.CH1.NZ010_SIM_CH1_TAG15337\\2347805-c63-0d603","ServerTimestamp":"2020-03-20T00:05:05.6693509Z","SourceTimestamp":"2020-03-20T00:05:05.6693509Z","StatusCode":null,"Status":"Good","ApplicationUri":"urn:SERVER001:PTC.ThingWorxIC.1:UA%20Server","Timestamp":"2020-03-20T00:05:33.8367789Z","Value":{"Type":11,"Body":5540.0}}
2020-03-20 01:56:44.324 [azure-iot-sdk-IotHubReceiveTask] DEBUG c.f.a.e.m.m.IotEdgeHubMessageBus - Received message 5199: {"ContentMask":1493,"NodeId":"nsu=ThingWorx Industrial Connectivity;s=Sim.CH1.NZ010_SIM_CH1_TAG15328\\2347805-c63-0e105","ServerTimestamp":"2020-03-20T00:05:05.6693509Z","SourceTimestamp":"2020-03-20T00:05:05.6693509Z","StatusCode":null,"Status":"Good","ApplicationUri":"urn:SERVER001:PTC.ThingWorxIC.1:UA%20Server","Timestamp":"2020-03-20T00:05:33.8368218Z","Value":{"Type":11,"Body":6541.0}}
2020-03-20 01:56:44.334 [azure-iot-sdk-IotHubReceiveTask] DEBUG c.f.a.e.m.m.IotEdgeHubMessageBus - Received message 5200: {"ContentMask":1493,"NodeId":"nsu=ThingWorx Industrial Connectivity;s=Sim.CH1.NZ010_SIM_CH1_TAG15395\\2347805-c63-0f305","ServerTimestamp":"2020-03-20T00:05:05.6693509Z","SourceTimestamp":"2020-03-20T00:05:05.6693509Z","StatusCode":null,"Status":"Good","ApplicationUri":"urn:SERVER001:PTC.ThingWorxIC.1:UA%20Server","Timestamp":"2020-03-20T00:05:33.836861Z","Value":{"Type":11,"Body":1166.0}}
2020-03-20 01:56:44.344 [azure-iot-sdk-IotHubReceiveTask] DEBUG c.f.a.e.m.m.IotEdgeHubMessageBus - Received message 5201: {"ContentMask":1493,"NodeId":"nsu=ThingWorx Industrial Connectivity;s=Sim.CH1.NZ010_SIM_CH1_TAG15386\\2347805-c63-12705","ServerTimestamp":"2020-03-20T00:05:05.6693509Z","SourceTimestamp":"2020-03-20T00:05:05.6693509Z","StatusCode":null,"Status":"Good","ApplicationUri":"urn:SERVER001:PTC.ThingWorxIC.1:UA%20Server","Timestamp":"2020-03-20T00:05:33.8369014Z","Value":{"Type":11,"Body":8015.0}}
```

**Comment by azabbasi** [comment]
You can override these intervals by using the ModuleClient super class (InternalClient) method called setOption. 
The method signature looks like this:
`public void setOption(String optionName, Object value)` 

So to change the receiver interval you will override the `SetMinimumPollingInterval` and to change the sender interval you override the `SetSendInterval`. You can refer to the [InternalClient implementation](https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/InternalClient.java) for more details

So once you created the ModuleClient object, you can immediately override the sending and polling interval to 1 milliseconds as follows:
```
ModuleClient module = new ModuleClient(connectionString, protocol);
module.setOption("SetMinimumPollingInterval", 1);
module.setOption("SetSendInterval", 1);
```

Please let us know if this help addressing the issue you are coming across.

**Comment by jerickcolendres** [comment]
Hi,

Thanks for the reply. I'm getting the error "**optionName is unknown = SetMinimumPollingInterval for MQTT**":

```
2020-03-27 01:17:21.543 [main] INFO  c.f.a.e.messageprocessor.App - Started App in 21.701 seconds (JVM running for 23.197)
2020-03-27 01:17:21.553 [main] INFO  c.f.a.e.m.s.MessageProcessorService - Starting message consumer
2020-03-27 01:17:21.555 [main] INFO  c.f.a.e.m.s.MessageProcessorService - Message processor initialised
2020-03-27 01:17:22.459 [main] ERROR c.f.a.e.m.m.IotEdgeHubMessageBus - Error starting IotEdge Message Bus: optionName is unknown = SetMinimumPollingInterval for MQTT
java.lang.IllegalArgumentException: optionName is unknown = SetMinimumPollingInterval for MQTT
        at com.microsoft.azure.sdk.iot.device.InternalClient.setOption(InternalClient.java:403)
```
Checked the code and it looks like that option is only available for HTTPS protocol:

InternalClient.java
```java
     switch (optionName)
            {
                case SET_MINIMUM_POLLING_INTERVAL:
                {
                    if (this.deviceIO.isOpen())
                    {
                        throw new IllegalStateException("setOption " + SET_MINIMUM_POLLING_INTERVAL +
                                "only works when the transport is closed");
                    }
                    else
                    {
                        if (this.deviceIO.getProtocol() == IotHubClientProtocol.HTTPS)
                        {
                            setOption_SetMinimumPollingInterval(value);
                        }
                        else
                        {
                            throw new IllegalArgumentException("optionName is unknown = " + optionName + " for " + this.deviceIO.getProtocol().toString());
                        }
                    }

                    break;
                }
```

**Comment by timtay-microsoft** [comment]
Hi @jerickcolendres you are correct. Currently, only clients using HTTP can configure that. We are internally discussing the best way to extend that option to AMQP and MQTT users as well. We'll update this thread when we have updates

**Comment by timtay-microsoft** [comment]
We have released a new version of the device client SDK with a new feature that allows you to set the receive interval with the following:

```
// milliseconds between spawning a thread to check for received messages
long receiveInterval = 1l;
deviceClient.setOption("SetReceiveInterval", receiveInterval);
```

With this feature, you can receive messages from the SDK more frequently. The SDK still only extends one thread at a time to give you these messages, so we recommend not doing much logic within each message callback. That way, the SDK can give you messages more frequently.

Let us know if you still see performance issues here

**Comment by jmbrunskill** [comment]
Thanks @timtay-microsoft 
The release seems to mention both com.microsoft.azure.sdk.iot:iot-device-client:1.20.3 and https://search.maven.org/artifact/com.microsoft.azure.sdk.iot/iot-device-client/1.21.0/jar

Is this a typo? From downloading the source it looks like 1.21.0 is the correct release version?

**Comment by azabbasi** [comment]
Yes, The title 1.21.0 is the new released version. We have updated the releases typo.

**Comment by timtay-microsoft** [comment]
@jmbrunskill @jerickcolendres Is this new feature enough for your purposes? Are you happy with the SDK's performance now?

**Comment by jmbrunskill** [comment]
@timtay-microsoft Sorry for not getting back to you early. Yes, I'm happy for you to close off this issue. We've tested this update and it appears to be working well, for our situation we really need batched messages to get the required throughput. That part is being worked on by the IIOT team so we have a good path forward.

**Comment by az-iot-builder-01** [comment]
@azabbasi, @jerickcolendres, @timtay-microsoft, @jmbrunskill, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
