### ISSUE TITLE
Update to latest proton-j to fix SecurityProvider issue

### ISSUE THREAD

**Issue by sirpodgio** [Azure/azure-iot-sdk-java#74]
Update POM to use at least version Apache Proton-J 0.18.0.

**Comment by prmathur-microsoft** [comment]
Thanks for reporting this. We will work on upgrading to latest proton-j.

**Comment by prmathur-microsoft** [comment]
Fix checked in @591b3625a2ca7449de9deff81aa8510573b0acea
Please re-open if you see any further issues.
