### ISSUE TITLE
Minimum Android API version?

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#747]
I recently checked on the Android sample that we maintain, and it wouldn't compile unless we set the minimum API version as 26, which is higher than the minimum we claim to support. We need to investigate if ever correctly supported these lower API versions

**Comment by timtay-microsoft** [comment]
So there's a lot at play here. Over the course of device client versions 1.17.1 to now, we have added/upgraded dependencies that stopped supporting java 7, and by extension, Android API 17. In turn, our SDK stopped compiling correctly after 1.17.1

Here's a list of my findings so far:

- BouncyCastle dependencies upgraded from 1.53 to 1.64 starting in device client version 1.17.2
    - Max BouncyCastle dependency that still compiles with Java 7/ Android 17: 1.60
    - SDK made this upgrade for security purposes, and this library is used for almost all device client use cases
    - One way to circumvent this issue is to exclude this library from your device client dependency, and to only use the device/module client constructor that takes an SSLContext directly. That constructor will build a device/module client without needing bouncycastle at all

- Qpid Proton-j dependency upgraded from 0.25.0 to 0.30.0 starting in device client version 1.17.2
    - Max Proton-j dependency version that still compiles for Java 7/Android 17: 0.28.1
    - SDK made this upgrade for security purposes, but this is only relevant for applications using amqps and/or amqps_ws.

- JNR-Unixsocket dependency upgraded from 0.19 to 0.23 starting in device client version 1.17.5
    - Max JNR-Unixsocket dependency version that still compiles for Java 7/Android 17: 0.22
    - SDK made this upgrade to fix a raspberry pi support issue, but that support isn't needed for android devices. This library is only used at runtime for module clients who authenticate through edgelet. Other applications can ignore this dependency and just use 0.22

- Added Qpid proton-j extensions dependency (version 1.2.2) starting in device client version 1.18.0
    - This library is partially under our control, and we are working to make a new version still works with Java 7/Android 17.

 
I'm working to update our android sample to show what a gradle file would look like with these limitations in mind

**Comment by timtay-microsoft** [comment]
As an example, here is a snippet of a gradle file that would theoretically allow you to use the device SDK over MQTT:

```
api ('com.microsoft.azure.sdk.iot:iot-device-client:1.21.1') {
        exclude module: 'slf4j-api'
        exclude module:'azure-storage'
        exclude module: 'bcmail-jdk15on' //fixes 1.17.1 -> 1.17.2 jump
        exclude module: 'bcprov-jdk15on' //fixes 1.17.1 -> 1.17.2 jump
        exclude module: 'proton-j' //fixes 1.17.1 -> 1.17.2 jump, but removes support for AMQPS and AMQPS_WS
        exclude module: 'jnr-unixsocket' // fixes 1.17.4 -> 1.17.5 jump (issue #434 caused us to upgrade unixsocket dependency, but that was for supporting raspberry pis. Android should be unaffected)
        exclude module: 'qpid-proton-j-extensions'
        exclude module: 'org.eclipse.paho.client.mqttv3'
        //need to exclude current paho version here, as well, with a note about losing proxy support
    }
    implementation 'com.microsoft.azure.android:azure-storage-android:2.0.0'
    implementation 'org.apache.commons:commons-lang3:3.6'
    implementation 'org.bouncycastle:bcmail-jdk15on:1.60' //fixes 1.17.1 -> 1.17.2 jump
    implementation 'org.bouncycastle:bcprov-jdk15on:1.60' //fixes 1.17.1 -> 1.17.2 jump
    implementation 'org.apache.qpid:proton-j:0.28.1' //fixes 1.17.1 -> 1.17.2 jump. From 0.28.1 to 0.29.0, proton started targeting java 8 instead of java 7
    implementation 'com.github.jnr:jnr-unixsocket:0.22' // Main library uses 0.23, but only because it had a fix for raspberry pi support. No need to use 0.23 here, too
    implementation 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.0' //Main library uses 1.2.2, but that is incompatible with Android 17 to 24. Only missing feature from 1.2.0 i
```

This would remove support for AMQPS, AMQPS_WS, and would remove proxy support for MQTT, but would compile on Android API level 17

**Comment by timtay-microsoft** [comment]
Closing this issue as "won't fix" seeing as the device client no longer supports Android API versions 23 or below

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
