### ISSUE TITLE
Don't declare 'throws Exception' from RegistryManager.createConnectionFromString

### ISSUE THREAD

**Issue by nielsvn92** [Azure/azure-iot-sdk-java#76]
- **SDK version used:** 1.2.17

# Description of the issue:
Currently the RegistryManager declares that it can throw Exception from the method createConnectionFromString. This causes the caller to catch Exception, which is a bad practice. Our SonarQube also doesn't accept this, and causes quality issues in our project.

# Desired solution
It would be great if you could change the throws declaration to something more specific than Exception. This shouldn't give any problems with other implementors, since you're throwing a more specific Exception which doesn't break the code.

Thank you in advance.

**Comment by prmathur-microsoft** [comment]
Sounds reasonable. I'll work on fixing this.

**Comment by nielsvn92** [comment]
Great! Thank you very much!

**Comment by prmathur-microsoft** [comment]
Fix checked in @8599e3b67e77c2092b3a62bcf41897cce363383a
Please re-open if you see any issues.

**Comment by nielsvn92** [comment]
Thank you for the quick solution.

Can it be that the new version is published under com.microsoft.azure : iot-service-client : 1.2.18 on Maven, instead of com.microsoft.azure.**sdk.iot** : iot-service-client : 1.2.18?

See http://search.maven.org/#artifactdetails%7Ccom.microsoft.azure%7Ciot-service-client%7C1.2.18%7Cjar for why I think this. My Maven client also can't find the group/artifact that's written in the POM file.

**Comment by prmathur-microsoft** [comment]
Sorry about that. Looks like there was a problem when we published packages even though POM had correct group id i.e com.microsoft.azure.sdk.iot, it landed up under com.microsoft.azure . I'm investigating it.

**Comment by prmathur-microsoft** [comment]
This issue is now resolved. You should be able to see correct packages under original group id  com.microsoft.azure.sdk.iot : iot-service-client : 1.2.18 where we usually publish.
