### ISSUE TITLE
Corporate proxy for iot-service-client

### ISSUE THREAD

**Issue by alam-R** [Azure/azure-iot-sdk-java#766]
- **OS and version used:** Centos 7

- **Java runtime used:** 1.8

- **SDK version used:** 1.21

Hey there,

I couldn't find an answer so my question is:
Is it possible to define an unauthenticated internal proxy for iot-service-client? If so, is there a sample or a reference?

Thanks!

**Comment by timtay-microsoft** [comment]
What features do you need proxy support for on the service client? Is this for registry manager (device identity management) or service client (messaging, file upload notification)?

**Comment by alam-R** [comment]
This is for the registry manager. I was wondering if I could specify my company's internal network when I am trying to connect to my IoT Hub.

**Comment by timtay-microsoft** [comment]
Currently the registry manager does not have proxy support, but I can look into adding it

**Comment by alam-R** [comment]
It would be most helpful for our application which runs behind a corporate proxy, thanks!

**Comment by alam-R** [comment]
Thank you very much @timtay-microsoft for your effort. 
But we will need also proxy support for the service client for messaging. Is this also possible?

**Comment by timtay-microsoft** [comment]
That depends, what kind of proxy do you use, and which protocol do you use for messaging (amqps or amqps_ws)?

**Comment by timtay-microsoft** [comment]
I could feasibly add proxy support for typical HTTP proxies if you are using amqps_ws, similar to how we have it on the device client side.

**Comment by alam-R** [comment]
Yes we are using the websocket version of the AMQPS, so again we would be grateful if you could add support for HTTP proxies.
Thank you!

**Comment by timtay-microsoft** [comment]
Yeah, that's feasible. I'll try to get that feature in soon. Do you need authentication for these proxies?

**Comment by alam-R** [comment]
No, not at the moment at least!

**Comment by alam-R** [comment]
Thank you @timtay-microsoft, I've used the updates and works like a charm!
Do you know when it will be released?

**Comment by timtay-microsoft** [comment]
Glad to hear it! We're hoping to get the release out within the next week

**Comment by timtay-microsoft** [comment]
Proxy support has now been released as of service client version 1.22.0, so I'm closing this issue.

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @alam-R, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
