### ISSUE TITLE
RegistryStatistics class needs accessor methods for protected fields

### ISSUE THREAD

**Issue by mrb-twx** [Azure/azure-iot-sdk-java#77]
The RegistryStatistics object returned from the RegistryManaged.getStatistics() method has protected fields for the enabled device count, disabled device count, and total device count but lacks public accessors for the fields.

A user is unable to read the field values without using reflection.

**Comment by prmathur-microsoft** [comment]
You are right. We will need to implement getters and setters for RegistryStatistics protected members. I will work on a fix.

**Comment by prmathur-microsoft** [comment]
Fixed checked in @a772ef773744101b5b479fffb4cc9824f2d80d27
Please reopen if you see any issues.
