### ISSUE TITLE
DeviceClient using MQTT receives twin updates even when not subscribed to twin topics

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#777]
(Latest SDK, Windows OS)

When a device client using mqtt opens a connection to IoT Hub, the service will always send desired property updates regardless of what subscriptions the device client has made. I can repro this behavior by only connecting, and not subscribing to any mqtt topics. 

Note that these messages are delivered to the device over the mqtt protocol, bu the SDK doesn't bubble them up to the user. This bug is more about wasted network traffic than SDK behavior.

This looks like a service bug, but I'm opening this issue here for customer awareness purposes

**Comment by timtay-microsoft** [comment]
Same behavior can be seen for cloud to device messages. Network exercised, but SDK doesn't bubble it up. Method invocations seem to work as expected, though

**Comment by timtay-microsoft** [comment]
AMQPS seems to work as expected, so this is just an MQTT issue

**Comment by timtay-microsoft** [comment]
Actually, closing this issue as it is related to a known Iot hub feature where mqtt subscriptions are held onto at the hub level across multiple connections if those connections happen within a certain timeframe of eachother

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
