### ISSUE TITLE
Service error code changes between DF, Canary, Prod

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#789]
Opening this issue here more as a reminder to follow up with the service folks on something. This repo recently introduced tests that verify that service client operations get a 6 digit status code on certain scenarios (such as invoking a method on a device that is offline gives a 404XXX).

I noticed some nightly builds in dogfood failing these tests because the returned status code was only a 404, not a 404XXX. This may be a breaking change incoming from the service deployments.

**Comment by timtay-microsoft** [comment]
The SDK feature for retrieving this substatus code has not been released yet, so it may be smart to hold off on releasing it until we understand if the service will change something underneath us here first.

**Comment by timtay-microsoft** [comment]
My suspicion is that the error message returned by the service differs from DF to Prod, and that the SDK parsing of that message is broken by that

**Comment by timtay-microsoft** [comment]
After investigating, the error message given by DF hubs is indeed different than the error message in canary and prod hubs. It looks like the service exposes the stacktrace from the hub side which breaks our error message parsing logic. This isn't behavior that will exist in canary or production hubs, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
