### ISSUE TITLE
Sending data with IOT Hub OK_EMPTY?

### ISSUE THREAD

**Issue by aindriu** [Azure/azure-iot-sdk-java#79]
Hi, I am trying to write and read messages and make them store in the IOT hub.
12:06:56.167 [main] ERROR com.microsoft.azure.sdk.iot.device.transport.IotHubSendTask - IotHubSendTask constructor called with null value for parameter transport
12:06:56.170 [main] ERROR com.microsoft.azure.sdk.iot.device.transport.IotHubReceiveTask - IotHubReceiveTask constructor called with null value for parameter transport
Here is my code. I get OK_EMPTY when I run the one that sends messages. Then when I run the retrieve messages nothing comes up
Sending: {"deviceId":"testdevice","windSpeed":11.683053189186499}
IoT Hub responded to message with status: OK_EMPTY
Sending: {"deviceId":"testdevice","windSpeed":11.03230312796512}
IoT Hub responded to message with status: OK_EMPTY
Sending: {"deviceId":"testdevice","windSpeed":10.03760821881059}
IoT Hub responded to message with status: OK_EMPTY
Sending: {"deviceId":"testdevice","windSpeed":8.705940582911076}
IoT Hub responded to message with status: OK_EMPTY

Thanks,
package testreceiver;

import java.io.IOException;
import java.net.URISyntaxException;

import com.google.gson.Gson;
import com.microsoft.azure.eventhubs.*;
import com.microsoft.azure.sdk.iot.device.DeviceClient;
import com.microsoft.azure.sdk.iot.device.IotHubClientProtocol;
import com.microsoft.azure.sdk.iot.device.IotHubEventCallback;
import com.microsoft.azure.sdk.iot.device.IotHubStatusCode;
import com.microsoft.azure.sdk.iot.device.Message;
import com.microsoft.azure.servicebus.*;

import java.nio.charset.Charset;
import java.time.*;
import java.util.Random;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.function.*;

public class TestReceiver {

	private static IotHubClientProtocol protocol = IotHubClientProtocol.HTTPS;
	private static String deviceId = "testdevice";
	private static DeviceClient client;
	private static String connString = "HostName=riv.azure-devices.net;DeviceId=testdevice;SharedAccessKey=/Y2zbtKt2NQ36DIDi/JNRU2KhXraH91QY3z5MNmQNgI=";

	private static class TelemetryDataPoint {
		 public String deviceId;
		   public double windSpeed;

		   public String serialize() {
		     Gson gson = new Gson();
		     return gson.toJson(this);
		   }
		 }
	
	
	 private static class EventCallback implements IotHubEventCallback
	 {
	   public void execute(IotHubStatusCode status, Object context) {
	     System.out.println("IoT Hub responded to message with status: " + status.name());

	     if (context != null) {
	       synchronized (context) {
	         context.notify();
	       }
	     }
	   }
	 }
	 
	 private static class MessageSender implements Runnable {

		 public void run()  {
			    try {
			      double avgWindSpeed = 10; // m/s
			      Random rand = new Random();

			      while (true) {
			        double currentWindSpeed = avgWindSpeed + rand.nextDouble() * 4 - 2;
			        TelemetryDataPoint telemetryDataPoint = new TelemetryDataPoint();
			        telemetryDataPoint.deviceId = deviceId;
			        telemetryDataPoint.windSpeed = currentWindSpeed;

			        String msgStr = telemetryDataPoint.serialize();
			        Message msg = new Message(msgStr);
			        System.out.println("Sending: " + msgStr);

			        Object lockobj = new Object();
			        EventCallback callback = new EventCallback();
			        client.sendEventAsync(msg, callback, lockobj);

			        synchronized (lockobj) {
			          lockobj.wait();
			        }
			        Thread.sleep(1000);
			      }
			    } catch (InterruptedException e) {
			      System.out.println("Finished.");
			    }
			  }
	 }
	 
	private static String connStr = "Endpoint=sb://iothub-ns-riv-142216-3cd5298da6.servicebus.windows.net/;EntityPath=riv;SharedAccessKeyName=iothubowner;SharedAccessKey=a3nFHxz3GDigj96JCTui03VMftQn5Q8JozETaUq2IKU=";
	
	private static EventHubClient receiveMessages(final String partitionId)
	 {
	   EventHubClient client = null;
	   try {
	     client = EventHubClient.createFromConnectionStringSync(connStr);
	   }
	   catch(Exception e) {
	     System.out.println("Failed to create client: " + e.getMessage());
	     System.exit(1);
	   }
	   try {
		   
	     client.createReceiver( 
	       EventHubClient.DEFAULT_CONSUMER_GROUP_NAME,  
	       partitionId,  
	       Instant.now()).thenAccept(new Consumer<PartitionReceiver>()
	     {
	       public void accept(PartitionReceiver receiver)
	       {
	         System.out.println("** Created receiver on partition " + partitionId);
	         try {
	           while (true) {
	             Iterable<EventData> receivedEvents = receiver.receive(100).get();
	             int batchSize = 0;
	             if (receivedEvents != null)
	             {
	               for(EventData receivedEvent: receivedEvents)
	               {
	                 System.out.println(String.format("Offset: %s, SeqNo: %s, EnqueueTime: %s", 
	                   receivedEvent.getSystemProperties().getOffset(), 
	                   receivedEvent.getSystemProperties().getSequenceNumber(), 
	                   receivedEvent.getSystemProperties().getEnqueuedTime()));
	                 System.out.println(String.format("| Device ID: %s", receivedEvent.getSystemProperties().get("iothub-connection-device-id")));
	                 System.out.println(String.format("| Message Payload: %s", new String(receivedEvent.getBody(),
	                   Charset.defaultCharset())));
	                 batchSize++;
	               }
	             }
	             System.out.println(String.format("Partition: %s, ReceivedBatch Size: %s", partitionId,batchSize));
	           }
	         }
	         catch (Exception e)
	         {
	           System.out.println("Failed to receive messages: " + e.getMessage());
	         }
	       }
	     });
	   }
	   catch (Exception e)
	   {
	     System.out.println("Failed to create receiver: " + e.getMessage());
	   }
	   return client;
	 }
	
	public static void main2(String[] args) throws IOException {
		
		EventHubClient client0 = receiveMessages("0");
		EventHubClient client1 = receiveMessages("1");
		System.out.println("Press ENTER to exit.");
		System.in.read();
		try
		{
		  client0.closeSync();
		  client1.closeSync();
		  System.exit(0);
		}
		catch (ServiceBusException sbe)
		{
		  System.exit(1);
		}
	}

	//private static String connString = "HostName=riv.azure-devices.net;DeviceId=testDevice;SharedAccessKey=a3nFHxz3GDigj96JCTui03VMftQn5Q8JozETaUq2IKU=";  
	public static void main( String[] args ) throws IOException, URISyntaxException {

		
		client = new DeviceClient(connString, protocol);
		  client.open();

		  MessageSender sender = new MessageSender();

		  ExecutorService executor = Executors.newFixedThreadPool(1);
		  executor.execute(sender);

		  System.out.println("Press ENTER to exit.");
		  System.in.read();
		  executor.shutdownNow();
		  client.close();
		}
	
}

**Comment by prmathur-microsoft** [comment]
Is there any specific reason for you to use EventHub to check for receive messages ? Our service client does the same and is verified to work.

**Comment by aindriu** [comment]
Hi, this code works fine. It's the tutorial code on the website I was using. Actually what wasn't working was the messages applet on the portal hub. The messages applet is meant to display devices and messages received but it doesn't work. That is why I was thinking it wasn't receiving the messages. Also I changed the create receiver function to a date in the past rather than 'now' and got all the messages in the system. 

Thanks for responding

**Comment by prmathur-microsoft** [comment]
Good to know! So as you claim this is working now, I will close it and you can reopen if you see any further issues.
