### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by hegate** [Azure/azure-iot-sdk-java#8]
Link to Get Started documents on Readme shows a 404. Right now, there's no way to look for instructions to run the simplesamples, as far as I could find.

**Comment by tameraw** [comment]
@hegate - Got it. I see the link with 404 is  that one:
https://github.com/Azure/azure-iot-sdk-java/blob/master/doc/get_started
Thanks for filing this issue.

**Comment by olivierbloch** [comment]
Hi @hegate , I have just pushed bunch of updates to the readmes in the repo.
Let us know if that looks better. I'll go ahead and close the issue as the link itself is fixed as part of this readmes overhaul.
