### ISSUE TITLE
Feature request: JobClient

### ISSUE THREAD

**Issue by ChThelen** [Azure/azure-iot-sdk-java#80]
- **Java runtime used:** 1.8

- **SDK version used:** com.microsoft.azure.sdk.iot:iot-service-client:1.2.18

# Description of the issue:
At the moment this SDK has no client implementation to start batch jobs, e.g. to send messages to devices having a certain tag assigned. The .NET SDK has a "JobClient" for this purpose, it would be great to have something similar for the Java SDK.
Are you planning to implement this feature?

**Comment by tameraw** [comment]
@ChThelen - Yes we currently plan to implement this feature as well. No ETA as of yet.

**Comment by ChThelen** [comment]
@tameraw Thanks for the information, please keep us posted.

**Comment by prmathur-microsoft** [comment]
#32

**Comment by prmathur-microsoft** [comment]
JobClient is now available for you in the master. Please give it a try. Maven packages shall be released soon as well.

**Comment by prmathur-microsoft** [comment]
Maven package for the same is also released. Follow our release from https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-7-14
