### ISSUE TITLE
[DeviceClient] Multiplexed connections don't renew sas tokens on per client schedule 

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#804]
When multiplexing over AMQPS or AMQPS_WS, the current device client implementation schedules token renewal on the schedule of the first device's sas token timespan. If a user configures different sas token time to live values per device client, they will see unexpected disconnections.

This issue will be fixed by #793 

AB#7422371

**Comment by timtay-microsoft** [comment]
If the first client associated with the transport client has the shortest time to live, then this isn't a big deal.

**Comment by timtay-microsoft** [comment]
Closing this issue as the fix is now released as of device client 1.24.0

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
