### ISSUE TITLE
Only receive 1 message a time with the Handle-Messages sample

### ISSUE THREAD

**Issue by remcoploeg** [Azure/azure-iot-sdk-java#82]
- **OS and version used:** Windows 10 

- **Java runtime used:** 1.8.0_121 

- **SDK version used:** 1.8.0_121 

# Description of the issue:
I have tried the handle-messages example and I can receive only one message a time. I have to restart the handle-message example to receive one new message. Is this normal? 

# Code sample exhibiting the issue:
java -jar ./handle-messages-1.1.24-with-deps.jar "CONNECTIONSTRING" "https"

# Console log of the issue:
Starting...
Beginning setup.
Successfully read input parameters.
Using communication protocol HTTPS.
log4j:WARN No appenders could be found for logger (com.microsoft.azure.sdk.iot.device.DeviceClientConfig).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Successfully created an IoT Hub client.
Successfully set message callback.
Opened connection to IoT Hub.
Beginning to receive messages...
Press any key to exit...
Received message 0 with content: test23
Responding to message 0 with COMPLETE

When I send a message again with the device explorer it don't receive anything. When I try to restart, it works again (for 1 message)

**Comment by remcoploeg** [comment]
After some more testing; When I use AMQPS it's working perfect. Issue with the HTTPS?

**Comment by prmathur-microsoft** [comment]
I'll investigate and get back to you soon.

**Comment by prmathur-microsoft** [comment]
Our SDK polls by default (only on HTTPS) for once in 25 minutes. And that is the reason you don't receive messages. You can modify this polling time as per your need using setoption for "SetMinimumPollingInterval" to  a value of your choice. And you would be able to receive messages that your chosen Poll.

**Comment by prmathur-microsoft** [comment]
I'm going to close this for now. If you see any further problems with this please feel free to reopen.
