### ISSUE TITLE
[feature request] Configure read/connect timeouts on service client twin operations

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#824]
The service client twin APIs all use HTTP, but none of them expose a way to configure the http read/connect timeouts. Lately, our e2e tests have been hitting read timeout exceptions in twin tests, and it would be worthwhile to make these configurable not only for our tests, but for users who may hit the same issue.

AB#7543972

**Comment by timtay-microsoft** [comment]
Once we have this code checked in, definitely bump up the read timeout in our e2e tests. We've been seeing a lot of read timeouts lately

**Comment by timtay-microsoft** [comment]
#878 for tracking purposes

**Comment by timtay-microsoft** [comment]
This issue has been fixed as of service client version 1.26.0, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
