### ISSUE TITLE
[Bug Report] DeviceClient spawns send/receive threads even during reconnection

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#827]
The send/receive threads spawn to handling sending queued messages and to handle received messages, but when a client is reconnecting, these threads are just costly busywork. Ideally, when the client goes into a reconnection state, the send/receive threads should stop spawning. Once the client gets back into a connected state, then the threads should resume

AB#7556322

**Comment by timtay-microsoft** [comment]
PR #826 should fix this issue

**Comment by timtay-microsoft** [comment]
Closing this issue as the fix is now released as of device client 1.24.0

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
