### ISSUE TITLE
Message Properties with mqtt and default messageId

### ISSUE THREAD

**Issue by tcazabat** [Azure/azure-iot-sdk-java#83]
- **OS and version used:** Linux

- **Java runtime used:** 1.7

- **SDK version used:** iot-device-client 1.1.23

# Description of the issue:
When you add some properties to a message and try to send it using MQTT, an error is received.
It seems that the generated MessageId contains some not supported characters (+ and #) in MQTT topics.
If we use a custom MessageId there is no problem the message is sent. (an UID for example)
There is no problem using others protocols such as https or AMQP.

# Code sample exhibiting the issue:
In Message.java:

String validCharacters = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-:.+%_#*?!(),=@;$'";

**Comment by prmathur-microsoft** [comment]
We will provide a fix for this.

**Comment by prmathur-microsoft** [comment]
Fix has been checked in @04ec700a9632c9dd5a2dd3d54dbee3a02404358e.

**Comment by prmathur-microsoft** [comment]
Packages for the same are also released. Please check - https://github.com/Azure/azure-iot-sdk-java/releases/tag/2017-4-21. You can reopen this if you see any issue.
