### ISSUE TITLE
[Bug Report] Provisioning Clients occasionally throw 411 error

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#837]
Our nightly builds have been occasionally throwing 411 errors when using http to create enrollments or during registration for our DPS tests. Our SDK hasn't sent the content length header in these contexts historically, but sending them now seems to cause these errors to stop.

AB#7621439

**Comment by timtay-microsoft** [comment]
Fixed by #833

**Comment by timtay-microsoft** [comment]
Closing this issue as the fix is now released as of provisioning device client 1.8.3 and provisioning service client 1.6.2

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
