### ISSUE TITLE
Unable to connect to serviceMqttException 

### ISSUE THREAD

**Issue by xiaolingcong** [Azure/azure-iot-sdk-java#86]
Hi Support,
We are using Android Version 4.4 for developing a Cloud connector for our business application in the mobile device.when I opened the connection,it always throw the exception。

    OS and version used: Android 4.4

    Java runtime used: JDK "1.8.0_102"

    SDK version used: iot-device-client:1.1.24 for Java

## # Here is the exception logs:
openConnectToIOT:java.io.IOException: Unable to connect to serviceMqttException
01-01 08:18:00.418: D/DemoTest(8571): 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttIotHubConnection.open(MqttIotHubConnection.java:138)
01-01 08:18:00.418: D/DemoTest(8571): 	at com.microsoft.azure.sdk.iot.device.transport.mqtt.MqttTransport.open(MqttTransport.java:83)
01-01 08:18:00.418: D/DemoTest(8571): 	at com.microsoft.azure.sdk.iot.device.DeviceClient.open(DeviceClient.java:184)
01-01 08:18:00.418: D/DemoTest(8571): 	at com.iothub.azure.microsoft.com.androidsamplegolo.MainActivity$3.run(MainActivity.java:155)
01-01 08:18:00.418: D/DemoTest(8571): 	at java.lang.Thread.run(Thread.java:848)

## Here is the connection code:
       sendText.setText(" init the DeviceClient");
        Log.d(TAG," init the DeviceClient ");
        try {
            isOpen=false;
            client = new DeviceClient(connString, protocol);
            client.setMessageCallback(this, new Counter(0));
            sendText.setText(" open the DeviceClient");
            Log.d(TAG," open the DeviceClient ");
        } catch (URISyntaxException e) {
            StringWriter sw = new StringWriter();
            PrintWriter pw = new PrintWriter(sw);
            e.printStackTrace(pw);
            String error = sw.toString();
            Log.d(TAG, "initService:" + error);
            handler.sendEmptyMessage(OPEN_FAIL);
            disconnect();
        }

**Comment by prmathur-microsoft** [comment]
Can you confirm that you do have network connectivity when you tried this ?

**Comment by xiaolingcong** [comment]
I have confirmed that the network is available.

**Comment by xiaolingcong** [comment]
I have confirmed that the network is available.

**Comment by anhashia** [comment]
Hi @xiaolingcong 

Can you please test with Android **sample** located at following location for **comparison**
https://github.com/Azure/azure-iot-sdk-java/tree/master/device/iot-device-samples/android-sample

Set **connection string** of the device
https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/android-sample/app/src/main/java/com/iothub/azure/microsoft/com/androidsample/MainActivity.java#L22

Set following location to use IoT client SDK version 24 or latest available 25
https://github.com/Azure/azure-iot-sdk-java/blob/master/device/iot-device-samples/android-sample/app/build.gradle#L50

I just tried with following SDK versions on Android Emulator **API 19** (Android 4.4.2) locally and it worked fine
```
compile 'com.microsoft.azure.sdk.iot:iot-device-client:1.1.24'
compile 'com.microsoft.azure.sdk.iot:iot-device-client:1.1.25'
```

**Comment by xiaolingcong** [comment]
@anhashia  Hi，thanks for your response，I have found the root cause，if the device does not synchronize the time,It will throw the exception.

**Comment by anhashia** [comment]
Hi @xiaolingcong 
Yeah, connection to Azure IoT Hub via MQTT is secured via **TLS** connection on port **8883**. TLS handshake has to succeed first. If you fail to validate server side certificate because your device clock in not correct or fail certificate **validation** for some other reason then you won't be able to connect to IoT Hub.
