### ISSUE TITLE
send device-to-cloud messages into batches 

### ISSUE THREAD

**Issue by venkatpalnati** [Azure/azure-iot-sdk-java#863]
In the documentation it says **HttpsBatchMessage** class is used to build a batched IoT Hub request body as a JSON array. The batched message has a maximum size of 256 kb but i didn't find any method or class using this request to send it over to IoT hub. any help here is very appreciated. In Node and C# sdk's i see an option to send data into batches. let me know if i am missing something here.

AB#7743470

**Comment by timtay-microsoft** [comment]
We currently don't support using that class. We have it in our backlog to make sending batch messages over HTTP supported

**Comment by timtay-microsoft** [comment]
@azabbasi has checked in the feature for sending a batch message over HTTP, and we have released that feature in device client version 1.25.0. Since this feature has been released for HTTP, I'm going to close this issue

**Comment by az-iot-builder-01** [comment]
@venkatpalnati, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
