### ISSUE TITLE
Could not find artifact com.microsoft.azure.sdk. iot:iot-device-client-parent:pom:1.1.24 in central (https://repo.maven.apache.or g/maven2) and 'parent.relativePath' points at wrong local POM

### ISSUE THREAD

**Issue by v-limliu** [Azure/azure-iot-sdk-java#87]
# **I have follow the instruction in doc with branch "2017-4-6",  but the  "mvn install"  show  many errors:**

ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for com.microsoft.azure.sdk.iot.samples:iot-de
vice-samples:[unknown-version]: Could not find artifact com.microsoft.azure.sdk.
iot:iot-device-client-parent:pom:1.1.24 in central (https://repo.maven.apache.or
g/maven2) and 'parent.relativePath' points at wrong local POM @ line 14, column
13
[FATAL] Non-resolvable parent POM for com.microsoft.azure.sdk.iot:iot-device-tes
ts:[unknown-version]: Failure to find com.microsoft.azure.sdk.iot:iot-device-cli
ent-parent:pom:1.1.24 in https://repo.maven.apache.org/maven2 was cached in the
local repository, resolution will not be reattempted until the update interval o
f central has elapsed or updates are forced and 'parent.relativePath' points at
wrong local POM @ line 13, column 13
 @
[ERROR] The build could not read 2 projects -> [Help 1]
[ERROR]
[ERROR]   The project com.microsoft.azure.sdk.iot.samples:iot-device-samples:[un
known-version] (E:\certify\azure-iot-sdk-java\device\iot-device-samples\pom.xml)
 has 1 error
[ERROR]     Non-resolvable parent POM for com.microsoft.azure.sdk.iot.samples:io
t-device-samples:[unknown-version]: Could not find artifact com.microsoft.azure.
sdk.iot:iot-device-client-parent:pom:1.1.24 in central (https://repo.maven.apach
e.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 14, col
umn 13 -> [Help 2]
[ERROR]
[ERROR]   The project com.microsoft.azure.sdk.iot:iot-device-tests:[unknown-vers
ion] (E:\certify\azure-iot-sdk-java\device\iot-device-tests\pom.xml) has 1 error

[ERROR]     Non-resolvable parent POM for com.microsoft.azure.sdk.iot:iot-device
-tests:[unknown-version]: Failure to find com.microsoft.azure.sdk.iot:iot-device
-client-parent:pom:1.1.24 in https://repo.maven.apache.org/maven2 was cached in
the local repository, resolution will not be reattempted until the update interv
al of central has elapsed or updates are forced and 'parent.relativePath' points
 at wrong local POM @ line 13, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
gException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableMo
delException.

# **I find "om.microsoft.azure.sdk.iot:iot-device-client-parent" is not there  in in central (https://repo.maven.apache.org/maven2)**

**Comment by prmathur-microsoft** [comment]
Can you please delete your .m2 and try mvn install again ?

**Comment by v-limliu** [comment]
which  file should  be deleted?,i just "cd azure-iot-sdk-java/device" and then  "mvn install"

**Comment by v-limliu** [comment]
Hi,

I just "cd azure-iot-sdk-java/device" and then "mvn install", Can you show me  which file should be deleted?

**Comment by prmathur-microsoft** [comment]
Can you try the following instead ?
cd azure-iot-sdk-java
mvn install 

If this does not work then can you please delete C:\Users\<username>\.m2 and try mvn install from the root ?

**Comment by v-limliu** [comment]
I tried as you recommend ,but  The same error occurs, so why it will find the not existed urls?
[cid:image001.png@01D2BCE1.98C0C780]

**Comment by prmathur-microsoft** [comment]
I did not receive your screen shot. Could you try sending list of commands you tried and their result here ?

**Comment by prmathur-microsoft** [comment]
Also I would like to point out that we have recently seen another issue around this (not sure if it is similar to what you see) but we checked in a fix @d2356e854631bc282ebe8a4bbc99fd95f1e6e3ba. So could you give it a try on the latest ?

**Comment by v-limliu** [comment]
YES, it solves my problem . thanks very much.

**Comment by prmathur-microsoft** [comment]
Awesome! Closing this for now. Feel free to reopen if you see further issues.
