### ISSUE TITLE
[Bug Report] DeviceClient does not send user agent string with proxy connect requests

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#870]
When sending a proxy tunnel request, the SDK should send the same user agent string that the SDK sends to iothub for consistency. Right now, the SDK doesn't send a user agent header in the tunnel request, so the user agent string ends up only describing the JVM version that the tunnel request was sent from

AB#7822159

**Comment by timtay-microsoft** [comment]
Fixed by #871

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released as of Device Client 1.25.0, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
