### ISSUE TITLE
[Bug Report] Device Client Amqp layer doesn't check delivery state for sent messages

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#887]
When the amqp library notifies our SDK of a delivery on a sender link (aka when iothub acknowledges a message sent on that link), our code currently does not look at whether the message was actually accepted by the hub or not. There aren't many cases where the sent message is rejected/released, but the SDK should still log when the message is unexpected rejected/released and should propagate this info up to the user.

https://github.com/Azure/azure-iot-sdk-java/blob/40f93c895e0ef1ab3e762bd3fc5458afe96c422a/device/iot-device-client/src/main/java/com/microsoft/azure/sdk/iot/device/transport/amqps/AmqpsSenderLinkHandler.java#L73

AB#7923246

**Comment by timtay-microsoft** [comment]
Fixed by #888

**Comment by timtay-microsoft** [comment]
The fix for this issue has been released as of Device Client 1.25.0, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
