### ISSUE TITLE
AMQP C2D message properties

### ISSUE THREAD

**Issue by PanzerHabba** [Azure/azure-iot-sdk-java#89]
Hi,

# ENVIROMENT (JAVA):
Windows 10 Pro
JRE: jdk.1.8.0_73
SDK: 1.1.24

# ENVIROMENT (NODE.JS):
Windows 10 Pro
node runtime: 6.3.1
"azure-event-hubs": "0.0.7",
"azure-iot-common": "1.1.6",
"azure-iot-device": "1.1.9",
"azure-iot-device-amqp": "1.1.9",
"azure-iot-device-mqtt": "1.1.9",

# Description of the issue:
We have an node.js eventhubClient, which is fetching amqp messages to a device-client running on java.
In our eventhubClient we generate a message and add custom properties to it in the following manner:

`var message = new Message(JSON.stringify(messageBody));`
`message.properties.add("some_key", "some_value");`
`message.ack = "full";`
`message.to = <MY_DEVICE>;`
`message.messageId = <MY_MESSAGE_ID>;`

When I send this message from eventhubClient, my Java device-client claim that propertyList is empty ([]).
When I generate the same message using device-explorer, my java device-client can read the propertyList just fine.

From  debug-log org.apache.qpid.proton.engine.impl.FrameParser input: IN: CH[0] I can clearly see my properties, but it is not parsed properly.

Is ther any major differenses in how devlice-explorer and azure-node.js-api generate the properties ?

Earlier I can remember that the properties might appear in "transportObject" as well..

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by PanzerHabba** [comment]
Update:

When i retrieve the messageBody like:
`messageBody = new String(message.getBytes(), Message.DEFAULT_IOTHUB_MESSAGE_CHARSET);`

The properties from node.js-eventhub-client is part of the messagebody.

**Comment by prmathur-microsoft** [comment]
Which protocol are you seeinf problems with? Is it amqp or mqtt or both ?

**Comment by prmathur-microsoft** [comment]
So I ran this on java SDK with amqp on device client and I'm able to see all the properties sent from device explorer. I see that you mention azure-node.js-api, could you please point me to the code that you are using so that I can see what the difference is between device explorer and azure-node.js-api

**Comment by PanzerHabba** [comment]
Hi,

Sorry for late response.
Actually this issue was related to node.js implementation and format of the message.
So I think you can close this issue now=)

**Comment by prmathur-microsoft** [comment]
Thank you. Closing it.
