### ISSUE TITLE
iothub sdk write access

### ISSUE THREAD

**Issue by edyrli** [Azure/azure-iot-sdk-java#90]
Hi, i am running iothub on an ARM platform. This is a write protected filesystem based on busybox. 

- **OS and version used:** <VERSION> 
Busybox 1.22.0
- **Java runtime used:** <VERSION> 
Java 8SE Embedded 1.8.0_65 Compact 2.
- **SDK version used:** <VERSION> 
iot-device-client 1.1.24

# Description of the issue:

It seems like iothub library need os write access to be able to start up.
As long as the filesystem is wite protected iothub simply wont start. I dont even get any debug from org.apache.qpid.proton.engine.
As soon as i remove the writeprotect everything runs as i should.

Which parts of os does iohub sdk require write access to? Is it possible to change this location?

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by prmathur-microsoft** [comment]
As far as I can see in the code, 1.1.24 was using a file to store certificate for peer validation. From 1.1.25, we have gotten rid of that from the SDK and currently from 1.1.25, you shouldn't be needing to use that anymore as we changed the design. Could you please try 1.1.25 and even with that if you would need write access then we will start investigating this further.

**Comment by edyrli** [comment]
I can confirm 1.1.25 has corrected the issue with running on write protected filesystem.
