### ISSUE TITLE
Batch messaging support over AMQP

### ISSUE THREAD

**Issue by venkatpalnati** [Azure/azure-iot-sdk-java#905]
In recent release batch messaging is enabled for HTTPS and we tried and its working well and we are kind of looking this feature to be available over AMQP also, can you guys please add this feature over AMQP seems to be this feature is missing in it.

AB#8100755

**Comment by timtay-microsoft** [comment]
We are looking into adding this enhancement now

**Comment by timtay-microsoft** [comment]
This feature hasn't gotten any meaningful traction or priority since being filed, so I'm closing this issue for now. We may revisit this feature at a later time

**Comment by abhipsaMisra** [comment]
Re-opening and closing to work around dashboard issue.

**Comment by abhipsaMisra** [comment]
Closing the issue.
