### ISSUE TITLE
[feature request] Add a constructor for initializing a device client using a shared access token directly

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-iot-sdk-java#907]
**Is your feature request related to a problem? Please describe.**
One key requirement of the IoMT proxy is the following: 
“It shall not store any device symmetric keys on it, but rather compute Sas tokens on the fly based on a customer key (DPS group enrollment key) handed out to each customer.
With that Sas Token, a DeviceClient shall be instantiated to interact with the device’s device twin. “

**Describe the solution you'd like**
Provide a way to initialize a device client using pre-computed sas tokens.

**Describe alternatives you've considered**
An alternative right now is to use the sas token to format a sas-token based connection string and use that for initialization. 
`HostName=<iothub_host_name>;CredentialType=SharedAccessSignature;DeviceId=<device_id>;SharedAccessSignature=SharedAccessSignature sr=<iot_host>/devices/<device_id>&sig=<token>&se=<expiry_time>`

However, this is not user-friendly.

**Additional context**

Thank you for helping make this project even better!

**Comment by timtay-microsoft** [comment]
#1002 for reference

**Comment by timtay-microsoft** [comment]
Device client version 1.28.0 has this feature and has now been released, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@abhipsaMisra, @timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
