### ISSUE TITLE
[Bug Report] Device Client API completeFileUploadAsync is not an async function

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#910]
Need to deprecate that API and add a new one called "completeFileUpload" to make this less confusing

AB#8214907

**Comment by timtay-microsoft** [comment]
#911

**Comment by timtay-microsoft** [comment]
This issue has been fixed as of device client version 1.26.0, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
