### ISSUE TITLE
[Bug Report] Iot Hub Service client send throws null pointer if message payload is null

### ISSUE THREAD

**Issue by timtay-microsoft** [Azure/azure-iot-sdk-java#919]
Not sure if the hub allows for messages without payload, but we should at least be throwing an illegal argument exception about this, not a null pointer.

AB#8312697

**Comment by timtay-microsoft** [comment]
This will be released within the next few days

**Comment by timtay-microsoft** [comment]
This issue has been fixed as of service client version 1.26.0, so I'm closing this issue

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
