### ISSUE TITLE
[Bug Report] IotHubEventCallback not invoked in response to a device-to-cloud message

### ISSUE THREAD

**Issue by soumdev** [Azure/azure-iot-sdk-java#953]
# Context

- **OS and version used:** Windows 10
- **Java runtime used:** Amazon Coretto 1.8.222
- **SDK version used:** IoT Hub Java Device Client 1.25.0

## Description of the issue
After upgrading iot-device-client jar to latest version, the execute method of the callback class implementing IotHubEventCallback is not invoked when the device receives an acknowledgement from the IoT hub in response to a device-to-cloud message. This issue happens with iot-device-client jar versions 1.17.2 and above. There has been no change in the code, just upgrade of iot-device-client jar to latest version. I couldn't find any changes in the way to call/ define IotHubEventCallback in the documentation. Has there been any change? Why is the callback not getting invoked with v1.17.2 and above?

AB#8449281

**Comment by timtay-microsoft** [comment]
Can you provide some logs from the device SDK for this? We have some instructions [here](https://github.com/Azure/azure-iot-sdk-java/blob/master/logging.md) to help you capture these logs

**Comment by timtay-microsoft** [comment]
And which protocol are you using?

**Comment by soumdev** [comment]
We're using IotHubClientProtocol AMQPS_WS. I'll add logs from the SDK.

**Comment by timtay-microsoft** [comment]
@soumdev any updates on the logs? Are you still having issues?

**Comment by soumdev** [comment]
Sorry for the delay. Here is the log generated by the SDK. Please let me know if there's anything more I need to provide.
[logging.log](https://github.com/Azure/azure-iot-sdk-java/files/5351801/logging.log)

**Comment by timtay-microsoft** [comment]
These logs couldn't have come from a recent device client library version. Can you double check that you using the latest SDK version?

**Comment by soumdev** [comment]
Yes, the logs were from client version 1.17.2, which was the earliest version with the problem. I had tried a few versions counting down from 1.25, which was the latest version with the issue. 

The other day I saw that there's a new version v1.26. I tried that and I don't see the issue so far with that version. I think we can close this bug, as it seems resolved with 1.26. Thanks!

**Comment by timtay-microsoft** [comment]
Good to hear! I'll go ahead and close this issue then

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @soumdev, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
