### ISSUE TITLE
[Bug Report] Incorrect signature generation for Symmetric Key Device Provisioning

### ISSUE THREAD

**Issue by daawnee** [Azure/azure-iot-sdk-java#989]
# Context

- **OS and version used:** N/A
- **Java runtime used:** N/A
- **SDK version used:** N/A

## Description of the issue
When constructing the SAS token, the token URL is URL encoded *before* it is signed.
Thus, the resulting signature included in the SharedAccessSignature is incorrect.

See this line: [RegisterTask.java#L154](https://github.com/Azure/azure-iot-sdk-java/blob/283b0098949015413fcfa84fbf0096b183476042/provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/RegisterTask.java#L154)

Expected: `0neXXXXXXXX/registrations/DEVICE_ID`
Actual: `0neXXXXXXXX%2Fregistrations%2FDEVICE_ID`

The actual message to be signed is compiled at [line 162](https://github.com/Azure/azure-iot-sdk-java/blob/283b0098949015413fcfa84fbf0096b183476042/provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/RegisterTask.java#L162), where you can observe that it takes the _actual_ URL-encoded version as a basis (`0neXXXXXXXX%2Fregistrations%2FDEVICE_KEY`) instead of the expected, non-URL-encoded version (`0neXXXXXXXX/registrations/DEVICE_KEY`), which then gets HMAC signed in [line 172](https://github.com/Azure/azure-iot-sdk-java/blob/283b0098949015413fcfa84fbf0096b183476042/provisioning/provisioning-device-client/src/main/java/com/microsoft/azure/sdk/iot/provisioning/device/internal/task/RegisterTask.java#L172), resulting in an incorrect signature.

## Code sample exhibiting the issue
N/A

## Console log of the issue
N/A

AB#8770376

**Comment by timtay-microsoft** [comment]
That does seem incorrect. How does this fix look to you? https://github.com/Azure/azure-iot-sdk-java/pull/990

**Comment by timtay-microsoft** [comment]
Out of curiosity, were there characters in your registrationId got messed up from this? I'd be interested in adding an e2e test around this.

**Comment by daawnee** [comment]
> #990

Seems all right.

**Comment by daawnee** [comment]
> Out of curiosity, were there characters in your registrationId got messed up from this? I'd be interested in adding an e2e test around this.

I haven't observed anything like that. Especially, because of the sas token issue the whole registration process failed right from the start.

**Comment by timtay-microsoft** [comment]
We have now released device client version 1.27.0 which contains the fix for this issue. Marking this issue as closed

https://github.com/Azure/azure-iot-sdk-java/releases/tag/2020-11-16

**Comment by az-iot-builder-01** [comment]
@timtay-microsoft, @daawnee, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by timtay-microsoft** [comment]
#1001 for reference on our updated samples/documentation around this flow
