### ISSUE TITLE
NullPointerException when closing connection - ClientState.quiesce

### ISSUE THREAD

**Issue by devzeze** [Azure/azure-iot-sdk-java#991]
Several crash reports on Crashlytics, I think you have all information needed here.

# Context

Android (several versions)
com.microsoft.azure.sdk.iot:iot-device-client:1.25.0

## Description of the issue
We are getting some crash reports in Crashlytics.

## Code sample exhibiting the issue
In some scenarios, or closing the app we close conection:

    public void destroy() {
        removeCallbacksAndMessages(null);
        try {
            deviceClientRegistration.closeNow();
        } catch (Exception e) {
            Log.e(TAG, "Exception closing Device Client", e);
        }

    }

## Console log of the issue
Crash Stack Trace

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Vector.clear()' on a null object reference
       at org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce(ClientState.java:1356)
       at org.eclipse.paho.client.mqttv3.internal.ClientComms$DisconnectBG.run(ClientComms.java:775)
       at java.lang.Thread.run(Thread.java:784)

AB#8799730

**Comment by timtay-microsoft** [comment]
Can you provide more context on the android devices in question? We have some known compatibility issues with android API versions below 24 that may be relevant here. How consistently do you see this error?

**Comment by devzeze** [comment]
For a relatively small amount of apps, few hundreds, in last 90 days I had this 6 times, it shows up like every 15 days.

in Crashlytics stats:

67% Samsung.
67% Android 10.
33% Background.

Also, some of those occurred during automated tests with Appium, not sure if it might have influence also.

To sum up its not critical, happen not very often.

**Comment by devzeze** [comment]
Hi,

I made a sum up of the NullPointerException we had in last weeks on our Android app. Info obtained in Crashlytics.


1. ClientState.java line 1356

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void java.util.Vector.clear()' on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Vector.clear()' on a null object reference
       at org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce(ClientState.java:1356)
       at org.eclipse.paho.client.mqttv3.internal.ClientComms$DisconnectBG.run(ClientComms.java:775)
       at java.lang.Thread.run(Thread.java:919)


2. ClientComms.java line 775

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce(long)' on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.eclipse.paho.client.mqttv3.internal.ClientState.quiesce(long)' on a null object reference
       at org.eclipse.paho.client.mqttv3.internal.ClientComms$DisconnectBG.run(ClientComms.java:775)
       at java.lang.Thread.run(Thread.java:919)


3. ClientComms.java line 161

Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void org.eclipse.paho.client.mqttv3.internal.ClientState.send(org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage, org.eclipse.paho.client.mqttv3.MqttToken)' on a null object reference

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.eclipse.paho.client.mqttv3.internal.ClientState.send(org.eclipse.paho.client.mqttv3.internal.wire.MqttWireMessage, org.eclipse.paho.client.mqttv3.MqttToken)' on a null object reference
       at org.eclipse.paho.client.mqttv3.internal.ClientComms.internalSend(ClientComms.java:161)
       at org.eclipse.paho.client.mqttv3.internal.ClientComms$DisconnectBG.run(ClientComms.java:777)
       at java.lang.Thread.run(Thread.java:929)
       

I believe those occur while app is being closed.

Can you give us some feedback if this will be fixed? In similar places on those classes I see comments like:

		catch (InterruptedException ex) {
			// Don't care, as we're shutting down anyway
		}

Maybe this could be included?

**Comment by timtay-microsoft** [comment]
We're taking a lot at this issue now, so I'll keep you posted.

**Comment by timtay-microsoft** [comment]
Device client version 1.29.2 has fixed this issue, so I'm closing this issue. If you still see any unusual exceptions from the MQTT layer, feel free to open a new issue.

**Comment by abhriyaroy** [comment]
Hello, we are facing the same issue in 1.34.2 and in samsung devices.
